// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Geography exclusions for FareHarbor migrations. Do not edit by hand.
export type FareHarborGeographyReviewEntry = {
  itemId: string;
  title: string;
  reason: string;
  city: string;
  state: string;
  expectedPath: string;
};

export const fareHarborGeographyReviewEntries: FareHarborGeographyReviewEntry[] = [
  {
    "itemId": "73240",
    "title": "Wheels in the Woods",
    "reason": "Hardwick, Vermont from meeting_point does not belong to Boston, and no matching public destination exists",
    "city": "Hardwick",
    "state": "Vermont",
    "expectedPath": "/destinations/massachusetts/boston/tours/wheels-in-the-woods-73240"
  }
];

export const FAREHARBOR_GEOGRAPHY_REVIEW_IDS = new Set(
  fareHarborGeographyReviewEntries.map(entry => entry.itemId)
);
