// This file is auto-generated by scripts/generate-sedona-pages.ts. Do not edit manually.
import type { ComponentType } from "react";
import CityIndex from "./index";
import CityTourPage0 from "./the-flavors-of-historic-jerome-214355";
import CityBookingPage0 from "./book/the-flavors-of-historic-jerome-214355";
import CityTourPage1 from "./the-terroir-of-the-verde-valley-wine-trail-214370";
import CityBookingPage1 from "./book/the-terroir-of-the-verde-valley-wine-trail-214370";
import CityTourPage2 from "./the-historic-downtown-flagstaff-microbrewery-tour-214389";
import CityBookingPage2 from "./book/the-historic-downtown-flagstaff-microbrewery-tour-214389";
import CityTourPage3 from "./alcantara-estate-vineyard-tasting-experience-214307";
import CityBookingPage3 from "./book/alcantara-estate-vineyard-tasting-experience-214307";
import CityTourPage4 from "./sedona-scenic-adventure-tour-214429";
import CityBookingPage4 from "./book/sedona-scenic-adventure-tour-214429";
import CityTourPage5 from "./scenic-sedona-sunset-experience-214430";
import CityBookingPage5 from "./book/scenic-sedona-sunset-experience-214430";
import CityTourPage6 from "./red-rock-state-park---scenic-sedona-hiking-adventure-214438";
import CityBookingPage6 from "./book/red-rock-state-park---scenic-sedona-hiking-adventure-214438";
import CityTourPage7 from "./sedona-hiking-and-yoga-experience-214442";
import CityBookingPage7 from "./book/sedona-hiking-and-yoga-experience-214442";
import CityTourPage8 from "./sedona-red-rocks-highlights-tours-307177";
import CityBookingPage8 from "./book/sedona-red-rocks-highlights-tours-307177";
import CityTourPage9 from "./scenic-sedona-ancient-indian-ruins-and-historic-jerome-214428";
import CityBookingPage9 from "./book/scenic-sedona-ancient-indian-ruins-and-historic-jerome-214428";
import CityTourPage10 from "./scenic-sedona-and-ancient-indian-ruins-combo-adventure-214434";
import CityBookingPage10 from "./book/scenic-sedona-and-ancient-indian-ruins-combo-adventure-214434";
import CityTourPage11 from "./lil-rattler-111869";
import CityBookingPage11 from "./book/lil-rattler-111869";
import CityTourPage12 from "./diamondback-gulch-111868";
import CityBookingPage12 from "./book/diamondback-gulch-111868";
import CityTourPage13 from "./lil-outlaw-119028";
import CityBookingPage13 from "./book/lil-outlaw-119028";
import CityTourPage14 from "./cliff-hanger-trail---hummer-247889";
import CityBookingPage14 from "./book/cliff-hanger-trail---hummer-247889";
import CityTourPage15 from "./gambler-trail-247891";
import CityBookingPage15 from "./book/gambler-trail-247891";
import CityTourPage16 from "./private-yoga-and-hiking-sessions-600765";
import CityBookingPage16 from "./book/private-yoga-and-hiking-sessions-600765";
import CityTourPage17 from "./colorado-plateau-111872";
import CityBookingPage17 from "./book/colorado-plateau-111872";
import CityTourPage18 from "./red-rock-west-hummer-247892";
import CityBookingPage18 from "./book/red-rock-west-hummer-247892";
import CityTourPage19 from "./red-rock-west-510638";
import CityBookingPage19 from "./book/red-rock-west-510638";
import CityTourPage20 from "./red-rock-panoramic-510640";
import CityBookingPage20 from "./book/red-rock-panoramic-510640";
import CityTourPage21 from "./sedona-vortex-tour-75978";
import CityBookingPage21 from "./book/sedona-vortex-tour-75978";
import CityTourPage22 from "./magical-hour-hikes-354423";
import CityBookingPage22 from "./book/magical-hour-hikes-354423";
import CityTourPage23 from "./the-rubicon-rock-crawler---automatic-transmission-385858";
import CityBookingPage23 from "./book/the-rubicon-rock-crawler---automatic-transmission-385858";
import CityTourPage24 from "./the-badass-jeep-rental---automatic-transmission-368975";
import CityBookingPage24 from "./book/the-badass-jeep-rental---automatic-transmission-368975";
import CityTourPage25 from "./private-northern-arizona-day-trips-571812";
import CityBookingPage25 from "./book/private-northern-arizona-day-trips-571812";
import CityTourPage26 from "./easy-walk-351561";
import CityBookingPage26 from "./book/easy-walk-351561";
import CityTourPage27 from "./moderate-to-advanced-hike-354426";
import CityBookingPage27 from "./book/moderate-to-advanced-hike-354426";
import CityTourPage28 from "./the-rubicon-xl-jeep-rental---manual-transmission-336398";
import CityBookingPage28 from "./book/the-rubicon-xl-jeep-rental---manual-transmission-336398";
import CityTourPage29 from "./rim-to-rim-backpacking-571816";
import CityBookingPage29 from "./book/rim-to-rim-backpacking-571816";
import CityTourPage30 from "./backpacking-adventure-571818";
import CityBookingPage30 from "./book/backpacking-adventure-571818";

type CityRoute = {
  path: string;
  component: ComponentType;
};

export const cityTourRoutes: CityRoute[] = [
  { path: "/arizona/sedona", component: CityIndex },
  { path: "/arizona/sedona/the-flavors-of-historic-jerome-214355", component: CityTourPage0 },
  { path: "/arizona/sedona/book/the-flavors-of-historic-jerome-214355", component: CityBookingPage0 },
  { path: "/arizona/sedona/the-terroir-of-the-verde-valley-wine-trail-214370", component: CityTourPage1 },
  { path: "/arizona/sedona/book/the-terroir-of-the-verde-valley-wine-trail-214370", component: CityBookingPage1 },
  { path: "/arizona/sedona/the-historic-downtown-flagstaff-microbrewery-tour-214389", component: CityTourPage2 },
  { path: "/arizona/sedona/book/the-historic-downtown-flagstaff-microbrewery-tour-214389", component: CityBookingPage2 },
  { path: "/arizona/sedona/alcantara-estate-vineyard-tasting-experience-214307", component: CityTourPage3 },
  { path: "/arizona/sedona/book/alcantara-estate-vineyard-tasting-experience-214307", component: CityBookingPage3 },
  { path: "/arizona/sedona/sedona-scenic-adventure-tour-214429", component: CityTourPage4 },
  { path: "/arizona/sedona/book/sedona-scenic-adventure-tour-214429", component: CityBookingPage4 },
  { path: "/arizona/sedona/scenic-sedona-sunset-experience-214430", component: CityTourPage5 },
  { path: "/arizona/sedona/book/scenic-sedona-sunset-experience-214430", component: CityBookingPage5 },
  { path: "/arizona/sedona/red-rock-state-park---scenic-sedona-hiking-adventure-214438", component: CityTourPage6 },
  { path: "/arizona/sedona/book/red-rock-state-park---scenic-sedona-hiking-adventure-214438", component: CityBookingPage6 },
  { path: "/arizona/sedona/sedona-hiking-and-yoga-experience-214442", component: CityTourPage7 },
  { path: "/arizona/sedona/book/sedona-hiking-and-yoga-experience-214442", component: CityBookingPage7 },
  { path: "/arizona/sedona/sedona-red-rocks-highlights-tours-307177", component: CityTourPage8 },
  { path: "/arizona/sedona/book/sedona-red-rocks-highlights-tours-307177", component: CityBookingPage8 },
  { path: "/arizona/sedona/scenic-sedona-ancient-indian-ruins-and-historic-jerome-214428", component: CityTourPage9 },
  { path: "/arizona/sedona/book/scenic-sedona-ancient-indian-ruins-and-historic-jerome-214428", component: CityBookingPage9 },
  { path: "/arizona/sedona/scenic-sedona-and-ancient-indian-ruins-combo-adventure-214434", component: CityTourPage10 },
  { path: "/arizona/sedona/book/scenic-sedona-and-ancient-indian-ruins-combo-adventure-214434", component: CityBookingPage10 },
  { path: "/arizona/sedona/lil-rattler-111869", component: CityTourPage11 },
  { path: "/arizona/sedona/book/lil-rattler-111869", component: CityBookingPage11 },
  { path: "/arizona/sedona/diamondback-gulch-111868", component: CityTourPage12 },
  { path: "/arizona/sedona/book/diamondback-gulch-111868", component: CityBookingPage12 },
  { path: "/arizona/sedona/lil-outlaw-119028", component: CityTourPage13 },
  { path: "/arizona/sedona/book/lil-outlaw-119028", component: CityBookingPage13 },
  { path: "/arizona/sedona/cliff-hanger-trail---hummer-247889", component: CityTourPage14 },
  { path: "/arizona/sedona/book/cliff-hanger-trail---hummer-247889", component: CityBookingPage14 },
  { path: "/arizona/sedona/gambler-trail-247891", component: CityTourPage15 },
  { path: "/arizona/sedona/book/gambler-trail-247891", component: CityBookingPage15 },
  { path: "/arizona/sedona/private-yoga-and-hiking-sessions-600765", component: CityTourPage16 },
  { path: "/arizona/sedona/book/private-yoga-and-hiking-sessions-600765", component: CityBookingPage16 },
  { path: "/arizona/sedona/colorado-plateau-111872", component: CityTourPage17 },
  { path: "/arizona/sedona/book/colorado-plateau-111872", component: CityBookingPage17 },
  { path: "/arizona/sedona/red-rock-west-hummer-247892", component: CityTourPage18 },
  { path: "/arizona/sedona/book/red-rock-west-hummer-247892", component: CityBookingPage18 },
  { path: "/arizona/sedona/red-rock-west-510638", component: CityTourPage19 },
  { path: "/arizona/sedona/book/red-rock-west-510638", component: CityBookingPage19 },
  { path: "/arizona/sedona/red-rock-panoramic-510640", component: CityTourPage20 },
  { path: "/arizona/sedona/book/red-rock-panoramic-510640", component: CityBookingPage20 },
  { path: "/arizona/sedona/sedona-vortex-tour-75978", component: CityTourPage21 },
  { path: "/arizona/sedona/book/sedona-vortex-tour-75978", component: CityBookingPage21 },
  { path: "/arizona/sedona/magical-hour-hikes-354423", component: CityTourPage22 },
  { path: "/arizona/sedona/book/magical-hour-hikes-354423", component: CityBookingPage22 },
  { path: "/arizona/sedona/the-rubicon-rock-crawler---automatic-transmission-385858", component: CityTourPage23 },
  { path: "/arizona/sedona/book/the-rubicon-rock-crawler---automatic-transmission-385858", component: CityBookingPage23 },
  { path: "/arizona/sedona/the-badass-jeep-rental---automatic-transmission-368975", component: CityTourPage24 },
  { path: "/arizona/sedona/book/the-badass-jeep-rental---automatic-transmission-368975", component: CityBookingPage24 },
  { path: "/arizona/sedona/private-northern-arizona-day-trips-571812", component: CityTourPage25 },
  { path: "/arizona/sedona/book/private-northern-arizona-day-trips-571812", component: CityBookingPage25 },
  { path: "/arizona/sedona/easy-walk-351561", component: CityTourPage26 },
  { path: "/arizona/sedona/book/easy-walk-351561", component: CityBookingPage26 },
  { path: "/arizona/sedona/moderate-to-advanced-hike-354426", component: CityTourPage27 },
  { path: "/arizona/sedona/book/moderate-to-advanced-hike-354426", component: CityBookingPage27 },
  { path: "/arizona/sedona/the-rubicon-xl-jeep-rental---manual-transmission-336398", component: CityTourPage28 },
  { path: "/arizona/sedona/book/the-rubicon-xl-jeep-rental---manual-transmission-336398", component: CityBookingPage28 },
  { path: "/arizona/sedona/rim-to-rim-backpacking-571816", component: CityTourPage29 },
  { path: "/arizona/sedona/book/rim-to-rim-backpacking-571816", component: CityBookingPage29 },
  { path: "/arizona/sedona/backpacking-adventure-571818", component: CityTourPage30 },
  { path: "/arizona/sedona/book/backpacking-adventure-571818", component: CityBookingPage30 },
];
