// This file is auto-generated by scripts/generate-sedona-pages.ts. Do not edit manually.
import CityTourPage from "./CityTourPage";
import { getCityTourBySlug } from "./cityTourData";

const tour = getCityTourBySlug("red-rock-west-510638");

export default function CityTourDetailRoute() {
  return <CityTourPage tour={tour} />;
}
