// This file is auto-generated by scripts/generate-sedona-pages.ts. Do not edit manually.
import CityTourPage from "./CityTourPage";
import { getCityTourBySlug } from "./cityTourData";

const tour = getCityTourBySlug("rim-to-rim-backpacking-571816");

export default function CityTourDetailRoute() {
  return <CityTourPage tour={tour} />;
}
