// This file is auto-generated by scripts/generate-sedona-pages.ts. Do not edit manually.
import CityTourPage from "./CityTourPage";
import { getCityTourBySlug } from "./cityTourData";

const tour = getCityTourBySlug("scenic-sedona-sunset-experience-214430");

export default function CityTourDetailRoute() {
  return <CityTourPage tour={tour} />;
}
