export const AUSTIN_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "5513806P1",
  "406074P3",
  "421026P1",
  "327690P1",
  "10428P19",
  "10428P6",
  "87115P27",
  "5494432P1",
  "5494432P3",
  "153655P2",
  "10428P1",
  "244340P2",
  "121998P6",
  "406074P1",
  "291969P2",
  "57338P1",
  "42365P4",
  "42365P1",
  "350454P2",
  "134057P1",
] as const;

export type AustinTargetedNarrativeDescriptionProductCode =
  (typeof AUSTIN_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const AUSTIN_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  AustinTargetedNarrativeDescriptionProductCode,
  string
> = {
  "5513806P1": "Explore Austin's most iconic landmarks and hidden gems in a modern open-top Ford Bronco on this private small-group tour. Visit Mount Bonnell for panoramic views, South Congress Avenue murals and shops, the historic Texas State Capitol, and East Austin street art with Lady Bird Lake scenery along the way. Stops include Texas State Capitol, Mount Bonnell, South Congress Avenue, East Austin Murals, Lady Bird Lake. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "406074P3": "In Austin, paddle a giant board with your private group of up to six on Lady Bird Lake at sunset. Watch the Austin skyline glow, then position for the Congress Avenue Bridge bat emergence before returning to shore with life jackets, paddles, and a dry cooler provided. Stops include Lady Bird Lake Launch, Austin Skyline, Congress Avenue Bridge, Bat Colony Viewing. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "421026P1": "Host a private wine tasting with a certified sommelier at your Austin home or lodging. Walk through three guided tastings for your group of up to 15 while learning how to evaluate aroma, structure, and finish without fighting crowded tasting rooms. Stops include Private Austin Location, Guided Wine Tasting Flight, Sommelier Q&A. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "327690P1": "Visit three Texas Hill Country wineries from Austin in a luxury vehicle with tastings included. Stops typically include Duchman Family Winery, Bell Springs Winery, and Wimberley Valley Winery, with round-trip transport so your group can focus on the tasting rooms. Stops include Hilton Austin Pickup, Duchman Family Winery, Bell Springs Winery, Wimberley Valley Winery. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "10428P19": "Travel southwest of Austin into the Driftwood and Wimberley Hill Country in a Mercedes Sprinter with a local guide. Sample wines at three award-winning wineries across a 4.5-hour afternoon shuttle limited to about 10 guests. Stops include Austin Departure, Duchman Family Winery, Wimberley Valley Winery, Limestone Terrace Vineyard. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "10428P6": "Leave downtown Austin for a half-day Hill Country shuttle that pairs Texas barbecue at Salt Lick with two winery stops. Ride in an air-conditioned van with a maximum of about 10 guests and a local driver who knows the Driftwood routes. Stops include Austin Visitor Center, Hill Country Winery, Salt Lick BBQ, Second Winery Stop. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "87115P27": "See Austin's signature landmarks on a premium small-group driving tour with hotel pickup. Stops and viewpoints commonly include the Texas State Capitol, Mt. Bonnell overlooks, and mural photo stops with a local guide narrating city history. Stops include Hotel Pickup, Texas State Capitol, Mt. Bonnell, Austin Murals, Lady Bird Lake Viewpoint. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "5494432P1": "Fly over downtown Austin and Lake Austin on a compact helicopter sightseeing flight. Aerial viewpoints typically include the Texas State Capitol area, UT Stadium, Frost Bank Tower, and the lake corridor during about 20 minutes of flight time. Stops include Heliport Check-in, Downtown Austin Aerial, Lake Austin Aerial, Landing. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "5494432P3": "In Austin, circle Circuit of the Americas by helicopter on a private flight built for race fans and thrill-seekers. The roughly 30-minute flight time includes aerial laps of the Formula 1 track and surrounding venue complex when conditions allow. Stops include Heliport Check-in, Circuit of the Americas Aerial, Track Overview Passes, Landing. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "153655P2": "Cruise Lake Austin on a fully shaded pontoon for a two-hour scenic history tour. Guides cover lakeside estates, cliffside homes, and landmarks such as Pennybacker Bridge while you stay cool under canopy cover on morning, afternoon, or sunset departures. Stops include Lake Austin Dock, Pennybacker Bridge, Lake Austin Shoreline, Scenic Return. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "10428P1": "Cover Austin landmarks and offbeat gems on a two-hour small-group driving tour with a local guide. Your guide covers Austin landmarks such as the Texas State Capitol, South Congress murals, Lady Bird Lake, Mt. Bonnell, or nearby Hill Country scenery depending on the itinerary. Stops include Greetings from Austin Mural, Texas State Capitol, Neighborhood Highlights. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "244340P2": "In Austin, watch sunset over Lake Travis on a public BYOB boat cruise lasting about 90 minutes. Bring your own drinks and enjoy open-water views of the Hill Country shoreline as the sky changes colors. Stops include Lake Travis Marina, Open Water Cruise, Sunset Viewpoint, Return Dock. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "121998P6": "Join a one-hour BYOB scenic cruise on Lake Austin timed for sunset light. The shared boat format is an easy way to see lakeside cliffs, homes, and skyline reflections without chartering a private vessel. Stops include Lake Austin Dock, Scenic Lake Cruise, Sunset Viewing, Return Dock. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "406074P1": "Paddle the Austin skyline at golden hour, then stage under Congress Avenue Bridge for the Mexican free-tailed bat emergence. This guided kayak outing lasts about 2.5 hours and includes equipment with an interpretive bat briefing. Stops include Kayak Launch, Austin Skyline Paddle, Congress Avenue Bridge, Bat Emergence Viewing. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "291969P2": "Kayak Lady Bird Lake at sunset with a guide and watch Austin's famous bat colony leave Congress Avenue Bridge. Gear is included on this approximately two-hour outing suited to beginners and visitors seeking a water-level skyline view. Stops include Lady Bird Lake Launch, Downtown Skyline, Congress Avenue Bridge, Bat Viewing. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "57338P1": "Ride electric minibikes with a guide past Austin murals, bridges, and skyline viewpoints. The roughly 90-minute Biker Gang format mixes photo stops at landmarks such as the Greetings from Austin mural with easy throttle-assisted cruising. Stops include Greetings from Austin Mural, Bridge Skyline Stop, Neighborhood Cruise. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "42365P4": "In Austin, a local guide leads the two-to-three-hour route with safety briefing and bike fitting included. Your guide covers Austin landmarks such as the Texas State Capitol, South Congress murals, Lady Bird Lake, Mt. Bonnell, or nearby Hill Country scenery depending on the itinerary. Stops include Barton Springs Bike Shop, Barton Springs Pool, Zilker Park, Greetings from Austin Mural, I Love You So Much Mural, Congress Avenue Bridge. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "42365P1": "See Austin's greatest hits on a guided hybrid bike tour covering about 10 miles. Ride through Zilker Park and around Lady Bird Lake, cross Congress Avenue Bridge, and roll past the Texas State Capitol with a local guide. Stops include Zilker Park, Lady Bird Lake Trail, Congress Avenue Bridge, Texas State Capitol. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "350454P2": "Cruise Austin on fat-tire e-bikes with skyline photo stops and a high-energy local guide. The about two-hour Good Vibes route emphasizes mural culture, lake paths, and downtown viewpoints. Stops include Lady Bird Lake Path, Austin Skyline Viewpoint, Mural Photo Stops. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "134057P1": "Follow Austin bike trails on a guided e-bike tour with mural and landmark stops. Expect about 2.5 hours covering spots such as the Greetings from Austin mural, park corridors, and skyline overlooks with equipment included. Stops include Greetings from Austin Mural, Park Path, Austin Skyline Overlook. Local commentary and route logistics are handled so you can focus on Austin skyline views, lake corridors, and Hill Country highlights. Ideal for visitors basing in Austin who want a guided Capital City experience without coordinating meeting points, trailheads, or photo locations on their own.",
};

export const getAustinTargetedNarrativeDescription = (productCode: string) =>
  AUSTIN_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as AustinTargetedNarrativeDescriptionProductCode
  ];
