export const BOULDER_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "87324P1",
  "326597P1",
  "134767P1",
  "326597P4",
  "326597P3",
  "283446P3",
  "411989P1",
  "205114P1",
  "5653780P1",
  "210815P2",
  "438442P1",
  "404160P1",
  "87324P2",
  "5554564P5",
  "397161P1",
] as const;

export type BoulderTargetedNarrativeDescriptionProductCode =
  (typeof BOULDER_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const BOULDER_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  BoulderTargetedNarrativeDescriptionProductCode,
  string
> = {
  "87324P1": "Visit the places that make Boulder the “Happiest City in America” on a guided e-bike tour. The electric motor allows you to cover a huge range of attractions in the great outdoors, without getting winded. Stops include Pedego Boulder- Electric Bike Tours & Rentals, Settler's Park, Flatirons, Colorado Chautauqua: Park, University of Colorado at Boulder, National Center for Atmospheric Research - NCAR. Get comfortable with your e-bike during a short training session before the tour begins. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "326597P1": "Enjoy Boulder's natural beauty, iconic landmarks and major attractions all from a pedal-assist electric bike. After a short tutorial, we'll head out on the trails to cover the historic Pearl Street pedestrian mall, the CU Boulder campus, Wonderland Lake, Boulder Creek and more! Stops include University of Colorado at Boulder, The Hill, The Boulder Dushanbe Teahouse, Hotel Boulderado, Flatirons, Folsom Field. This is a great activity for solo visitors, groups and families to see town in an active, fun and memorable way. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "134767P1": "Get a comprehensive tour of Boulder on this excursion astride an electric bike. Riding an e-bike means you can work as hard as you like, using the pedal assist to get you up the hills. Stops include Hotel Boulderado, Pearl Street Mall, The Boulder Dushanbe Teahouse, Boulder Creek Path, University of Colorado at Boulder, Folsom Field. Pedal through the charming neighborhoods, NCAR, University of Colorado, Chautauqua, the historic downtown areas, and along Boulder Creek. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "326597P4": "This is our All-In-One \"Best Family\" Boulder tour designed for families, couples, or solo guests to see the top destinations of the city. After a safety orientation session, head out to the trails to see Wonderland Lake, Pearl Street, CU Boulder's campus, Boulder Creek, the Flatiron Mountains, and more. Stops include Folsom Field, Fiske Planetarium, Hotel Boulderado, Boulder County Farmers Market, University of Colorado at Boulder, The Hill. Local commentary and route logistics are handled so you can focus on Boulder's foothills scenery, open-space trails, and downtown highlights. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "326597P3": "Enjoy an active introduction to Boulder, Colorado—and discover many of the city’s top attractions—on this small-group e-bike tour. Pick from multiple convenient, daily start times; meet your guide in central Boulder; and get acquainted with your e-bike. Stops include Folsom Field, Fiske Planetarium, Hotel Boulderado, Boulder County Farmers Market, University of Colorado at Boulder, The Hill. Then, follow your guide to local landmarks like Wonderland Lake Park, the University of Colorado at Boulder, the Flatirons, and much more. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "283446P3": "Ride Boulder on a guided e-bike route that mixes creek paths, neighborhood streets, and canyon-edge byways for a local's view of the city. Stops include Boulder Creek Path, Scott Carpenter Park, The Boulder Dushanbe Teahouse, Eben G. Fine Park, Boulder Canyon Trail. The outing covers eclectic neighborhoods, popular gathering spots, and open foothills views while your guide handles pacing and route choices. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "411989P1": "Explore the world renowned Boulder Flatirons up close and personal. Preston, a Boulder local, will help you escape into the foothills of the Rockies and help you connect to the natural landscape through storytelling and conversations about the local flora fauna and history of the Flatirons. Stops include Chautauqua Trailhead, Flatirons Trails. Local commentary and route logistics are handled so you can focus on Boulder's foothills scenery, open-space trails, and downtown highlights. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "205114P1": "In Boulder, in the presence of horses, you can tell a lot about humans. With this experience, not only will you discover how these magnificent creatures interact with us and each other, but you’ll get a keen eye on your own unique gifts and traits. Stops include Equine Interaction Arena. No experience or riding required—just a willingness to experience the world from another perspective. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "5653780P1": "Experience Rocky Mountain National Park on this personalized small-group tour departing from Boulder. A guide handles mountain-road logistics while you take in alpine peaks, park overlooks, and nearby gateway towns without arranging park reservations yourself. Stops include Lyons, Estes Park, Beaver Meadows Visitor Center, Trail Ridge Road, Alpine Visitor Center, Sprague Lake. Local commentary and route logistics are handled so you can focus on Boulder's foothills scenery, open-space trails, and downtown highlights. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "210815P2": "Capture professional portraits against Boulder's foothills scenery on this private mountain photoshoot. A local photographer guides you to scenic Flatirons-area settings sized for couples, families, and solo visitors, then delivers polished images from the session. Stops include Flatirons, Rocky Mountains. Local commentary and route logistics are handled so you can focus on Boulder's foothills scenery, open-space trails, and downtown highlights. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "438442P1": "Hike Boulder's Flatirons foothills on a private wilderness tour that starts at the NCAR trailhead. Local guides lead you through pine forest, rocky outcrops, and scenic overlooks near Mallory Cave Trail with photo stops and naturalist commentary along the way. Stops include National Center for Atmospheric Research - NCAR, Mallory Cave Trail, Flatirons. Local commentary and route logistics are handled so you can focus on Boulder's foothills scenery, open-space trails, and downtown highlights. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "404160P1": "Photograph Boulder's Flatirons with a local guide and photographer on a private outing that pairs foothills scenery with high-end portrait sessions. Stops include Flatirons, National Center for Atmospheric Research - NCAR. Routes move between open Flatirons viewpoints and nearby NCAR-area overlooks sized for couples, families, and solo visitors. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "87324P2": "If you've always wanted to try an e-bike, experience the power of Pedego’s Elevate Mountain Bike on this private Boulder mountain biking tour that’s open to all skill levels. Get oriented to the bike’s high-tech features, then set off along the scenic Boulder Creek Trail before ascending up Sugarloaf Mountain using the bike’s battery power. Stops include Pearl Street Mall, Boulder Creek Path, Sugarloaf Mountain, Switzerland Trail Trailhead, Switzerland Trail. Stop for photos while cruising the spectacular Switzerland Trail on this curated Rocky Mountain adventure. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "5554564P5": "Explore the stunning landscapes of Boulder and Eldorado Canyon on a thrilling half-day e-bike tour. This 29-mile journey takes you along peaceful bike paths and scenic roads, showcasing the majestic Flatirons and the natural beauty that Colorado is famous for. Stops include Harlow Platts Community Park, Eldorado Canyon State Park, The Boulder Dushanbe Teahouse, Boulder Canyon Scenic Drive, Chautauqua Park. Enjoy a refreshing artisanal ice cream break at the Dushanbe Teahouse, and learn about local history at the Eldorado Canyon park visitor center. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
  "397161P1": "If you’re visiting Boulder, this is one of those experiences you’ll be glad you didn’t miss—and very likely the one you’ll end up telling people about when you get home. It’s not just a hike, and not just a yoga class—it’s a feel-good, memorable way to experience the Flatirons that blends movement, nature, and time to actually slow down and take it all in. Stops include Boulder Yoga Hike Trailhead, Flatirons Open Space. Instead of rushing through a checklist of sights, this is about being in it—the views, the fresh air, the energy of the mountains, and those unexpected “wow, I needed this” moments along the way. Ideal for visitors basing in Boulder who want a guided Front Range experience without coordinating meeting points, trailheads, or photo locations on their own.",
};

export const getBoulderTargetedNarrativeDescription = (productCode: string) =>
  BOULDER_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as BoulderTargetedNarrativeDescriptionProductCode
  ];
