export const CABO_SAN_LUCAS_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "3714LUXSUNSET",
  "3714P32",
  "18372P1",
  "8056P2",
  "3714P39",
  "220975P1",
  "7054P7",
  "13221P9",
  "177104P1",
  "303247P1",
  "34186P2",
  "16451P2",
  "190377P1",
  "30877P4",
] as const;

export type CaboSanLucasTargetedNarrativeDescriptionProductCode =
  (typeof CABO_SAN_LUCAS_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const CABO_SAN_LUCAS_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  CaboSanLucasTargetedNarrativeDescriptionProductCode,
  string
> = {
  "3714LUXSUNSET": "In Cabo San Lucas, this small-group sunset sail leaves the marina on a 50-foot boat for Land's End, Lover's Beach, and the Arch of Cabo San Lucas. An open bar of sparkling wine, cocktails, beer, and soft drinks is served with light appetizers so the evening stays on the water rather than a separate restaurant stop. The crew handles docking and pacing while the published route stays on the bay and rock formations that mark where the Sea of Cortez meets the Pacific. Hotel pickup is listed for many Los Cabos properties. The format suits visitors who want a guided scenic evening without chartering a boat independently. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the marina, Lover's Beach, and Arch that define this sunset outing.",
  "3714P32": "In Cabo San Lucas, this luxury catamaran looks for humpback whales from a double-deck boat with a guide and a hydrophone for whale song when animals are present. Snacks plus alcoholic and soft drinks are included so the morning stays on the water rather than a separate cafe stop. The published route covers the Cabo San Lucas coastline and the Arch, with an optional hotel transfer fee and a small cash dock fee at check-in. Seasonal whale presence still depends on winter migration, and the crew keeps a respectful distance from the animals. The format suits visitors who want a guided wildlife window without booking a private charter. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the marina, Arch, and Sea of Cortez water that shape this catamaran outing.",
  "18372P1": "In Cabo San Lucas, this small-group boat looks for humpback whales with a marine biologist on board and a cap of about 12 passengers. The published 2.5-hour route passes the Arch of Cabo San Lucas and the sea lion colony before spending time on open water where whales may splash or travel with calves. Marine park fees and bottled water are included; souvenir photos are offered for purchase rather than required. The meeting point is the CaboTrek office inside Hotel Tesoro on the marina, near dock M-O and the lighthouse. The format suits visitors who want expert commentary without a large party boat. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the marina, Arch, and Sea of Cortez that define this wildlife morning.",
  "8056P2": "In Cabo San Lucas, this two-hour shared sunset sail boards a yacht for Land's End and the Arch while the crew talks through local coastline history. Unlimited beer, wine, and soft drinks are served with snacks so the evening stays on deck rather than a separate bar stop. Departure time tracks the sunset, and the boat often powers down to sail once it clears the rocks. Hotel pickup is not included; the published meeting point is the marina dock listed at booking. The format suits visitors who want a guided scenic sail without chartering independently. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the marina, Arch, and Land's End that shape this evening cruise.",
  "3714P39": "In Cabo San Lucas, this half-day snorkel covers two corridor bays with lunch and an open bar on board. Crew members handle snorkel gear, in-water timing, and a Land's End pass for the Arch so the group can stay with Santa Maria Bay and Chileno Bay rather than assembling boat and lunch tickets separately. Hotel pickup is listed for many Los Cabos properties. The outing is aimed at visitors who want a guided reef window with food service included. Seasonal whale sightings on the return are possible in winter but are not guaranteed. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the published bays and Arch rather than adding extra downtown shopping or a self-guided kayak hop.",
  "220975P1": "In Cabo San Lucas, this sightseeing cruise heads to Santa Maria Bay for a guided snorkel with gear on the boat. The published route keeps the group on marina departure and corridor reef time rather than a multi-bay add-on. A small port tax may be collected in destination. The format suits visitors who want a compact guided swim without booking a private skiff. Commentary covers the bay and fish typical of the corridor reefs. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the marina and Santa Maria Bay that define this snorkel cruise rather than adding Chileno Bay, a kayak crossing, or a downtown shopping loop.",
  "7054P7": "In Cabo San Lucas, this outing pairs a glass-bottom kayak with snorkel time at Santa María Bay and Chileno Bay. Hotel pickup arrives by air-conditioned van, then a bilingual guide issues life jackets, snorkel gear, and a wetsuit when needed. The kayak crossing between the two bays is the published movement rather than a motorboat hop, so the day stays on the reefs and rock formations of the corridor. Dry bags are listed for phones and wallets. The format suits visitors who want a guided paddle-and-swim without renting kayaks independently. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on Santa María Bay and Chileno Bay that shape this two-bay outing rather than a Land's End yacht add-on.",
  "13221P9": "In Cabo San Lucas, this small-group day follows the Pacific coast to Todos Santos for galleries, a blanket workshop, a pearl demonstration, and lunch at the Hotel California. A tequila tasting and a stop at the old Jesuit mission are on the published list, with hotel pickup and drop-off included so the group can stay with the town rather than self-driving the highway. Numbers are limited for a more personal pace. The format suits visitors who want a guided pueblo day without coordinating restaurant, tasting-room, and artisan timing independently. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on Todos Santos, the Hotel California, and the mission that define this Baja town outing rather than a La Paz beach add-on.",
  "177104P1": "In Cabo San Lucas, this guided ATV outing follows Migrino Desert tracks and Migrino Beach on a single or shared machine. Helmets, goggles, and a bandana are issued after a safety briefing, and a tequila tasting closes the published route. Round-trip transfers cover listed hotels, villas, and the cruise port. A Migrino Park entrance fee and optional collision insurance are collected separately from the listed From price. Drivers need a valid license. The format suits visitors who want a guided off-road window without renting ATVs independently. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on Migrino Desert and Migrino Beach that shape this Pacific-side ride rather than a canyon jeep or camel-safari add-on.",
  "303247P1": "In Cabo San Lucas, this private yacht keeps the boat for one group, with snorkeling or paddleboarding at Pelican Rock and Chileno Bay plus a pass at the Arch of Cabo San Lucas. Drinks and snacks are included so the outing stays on the water rather than a marina restaurant stop. The meeting point is Local A at Tesoro Hotel on Blvd. Paseo de la Marina. The private format is aimed at visitors who want a guided scenic charter without sharing the deck with another party. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on Pelican Rock, the Arch, and Chileno Bay that define this yacht day rather than a shared sunset sail or glass-bottom city loop.",
  "34186P2": "In Cabo San Lucas, the Tropicat jazz-and-wine sunset cruise boards an elegant catamaran for Lover's Beach, Land's End, and the Arch with an open international bar. Gourmet meats, cheeses, and crudités are served with premium wines so the evening stays on deck. Hotel transfers from most Los Cabos properties must be reserved at least 48 hours ahead. In season the crew also watches for whales while the published route stays on the rock formations at Land's End. The format suits visitors who want a guided wine-focused sail without booking a private charter. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the marina, Lover's Beach, and Arch that shape this jazz cruise rather than a tequila-ranch add-on.",
  "16451P2": "In Cabo San Lucas, this small-group Beach Hopper uses a zodiac for half-hour snorkel windows at Chileno Bay and Santa Maria Bay, then continues to Lover's Beach and the Arch of Cabo San Lucas with sea lions on the rocks. A light lunch is included after the swims. The captain adjusts bay order to water conditions rather than a fixed self-guided hop. The format suits visitors who want a guided two-bay snorkel without assembling separate boat tickets. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on Chileno Bay, Santa Maria Bay, Lover's Beach, and the Arch that define this hopper rather than a glass-bottom kayak crossing or a shared sunset sail.",
  "190377P1": "In Cabo San Lucas, this guided hike follows a Pericu route in the Sierra de la Laguna reserve, then sits down to a California rancho meal of handmade tortillas and rancho cheese. The published walk covers about four miles through semitropical desert, with a swim hole when water is present and a later stargazing window on the return when the group finishes after dark. Hotel transfers and the reserve entrance fee are included; the group is capped at eight. The meeting point is the McDonald's lot on Blvd. Lázaro Cárdenas. The format suits visitors who want an Indigenous-history trail day without finding the canyon independently. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the Sierra de la Laguna, Pericu trail, and rancho that shape this outing.",
  "30877P4": "In Cabo San Lucas, this guided day pairs a glass-bottom boat to the Arch with a narrated city circuit, a blown-glass workshop, and a sit-down lunch window. Hotel pickup keeps the group on the published marina and downtown stops rather than a self-drive shopping loop. The boat segment is the scenic core; the land stops cover artisan and plaza time listed on the product page. The format suits visitors who want a longer guided sightseeing day without booking the Arch boat and a city van separately. Meeting points are confirmed at booking in Cabo San Lucas, and the itinerary stays on the Arch, downtown Cabo San Lucas, and the glass workshop that define this combination outing rather than a Todos Santos highway day.",
};

export const getCaboSanLucasTargetedNarrativeDescription = (
  productCode: string
) =>
  CABO_SAN_LUCAS_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as CaboSanLucasTargetedNarrativeDescriptionProductCode
  ];
