export const CANCUN_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "5885P231",
  "110186P7",
  "308891P15",
  "252732P1",
  "70244P1",
  "117119P3",
  "118403P17",
  "7041P7",
  "12861P5",
  "6200P5",
  "308891P25",
  "42786P2",
  "368094P1",
] as const;

export type CancunTargetedNarrativeDescriptionProductCode =
  (typeof CANCUN_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const CANCUN_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  CancunTargetedNarrativeDescriptionProductCode,
  string
> = {
  "5885P231": "In Cancun, journey to Mexico's Yucatán Peninsula to visit the Mayan ruins of Chichen Itza on this full-day tour and experience this incredible archeological site with a local guide. Walk along El Castillo and the Pyramid of Kukulcan and learn how this pre-Columbian city played an important role in the Mayan Civilization. Stops include Chichen Itza, Cenote Chichikan, Valladolid. Midway through the day, enjoy a typical buffet lunch and a refreshing dip at a cenote. Ideal for visitors basing in Cancun who want a guided city or Yucatan experience without coordinating tickets or landmark timing on their own. Routes stay oriented to Chichen Itza, Cenote Chichikan, Valladolid that define this Cancun experience, with a guide handling ticket windows, coach or boat connections, and neighborhood pacing so the day stays focused on the outing rather than logistics.",
  "110186P7": "In Cancun, say goodbye to the Riviera Maya beaches and see a different side of the Yucatan. This guided tour explores Chichen Itza’s pyramid temples and colonial Valladolid, with a swim in an underground cenote. Stops include Chichen Itza, Cenote, Valladolid. Upgrade to add transfers from Cancun or Riviera Maya hotels—or book a private tour with flexible pickup times. Ideal for visitors basing in Cancun who want a guided city or Yucatan experience without coordinating tickets or landmark timing on their own. Routes stay oriented to Chichen Itza, Cenote, Valladolid that define this Cancun experience, with a guide handling ticket windows, coach or boat connections, and neighborhood pacing so the day stays focused on the outing rather than logistics. Meeting points are confirmed at booking in Cancun, and the itinerary keeps visitors close to Caribbean coastline, Mayan ruins, and cenote swimming holes that shape this Cancun tour.",
  "308891P15": "In Cancun, ideal for visitors looking for a full day of outdoor adventure, this tour combines an all-terrain vehicle (ATV) off-road session with ziplining, swimming, and tequila tasting. Following pickup from your hotel, head to an adventure eco-park, where you’ll ride an ATV over jungle trails, try three zipline flights, and swim in a cenote—a natural limestone sinkhole with clear emerald waters. Stops include Yucatan jungle ATV trails, Zipline circuit, Cenote. Wrap up the day’s activities with a tequila tasting. Ideal for visitors basing in Cancun who want a guided off-road day without renting ATVs independently. Routes stay oriented to Yucatan jungle ATV trails, Zipline circuit, Cenote that define this Cancun experience, with a guide handling ATV briefing, jungle routing, and return to Cancun so the day stays focused on the outing rather than logistics.",
  "252732P1": "In Cancun, enjoy a more intimate adventure than the big box tours when you book this small-group adrenaline package that's suitable for most everyone, even non-swimmers. Visit two cenotes—one lagoon and one cave cenote; roar through the jungle on a 2021 all-terrain vehicle (ATV); brave an upside-down zipline circuit and hanging bridge; and enjoy lunch and water. Stops include ATV jungle trail, Five zip lines, Lagoon cenote, Cave cenote. Your package includes photos and video, but a charge is payable to cover admission fees. Ideal for visitors basing in Cancun who want a guided off-road day without renting ATVs independently. Routes stay oriented to ATV jungle trail, Five zip lines, Lagoon cenote, Cave cenote that define this Cancun experience, with a guide handling ATV briefing, jungle routing, and return to Cancun so the day stays focused on the outing rather than logistics.",
  "70244P1": "Embark on a once-in-a-lifetime adventure swimming with whale sharks in Cancun. After a hotel pickup, enjoy a light breakfast and head to a protected area for 2-3 dives, guided by certified experts. Stops include Whale shark swim, Isla Mujeres. Visit Isla Mujeres' Playa Norte for relaxation and ceviche before returning. Ideal for visitors basing in Cancun who want a guided city or Yucatan experience without coordinating tickets or landmark timing on their own. Routes stay oriented to Whale shark swim, Isla Mujeres that define this Cancun experience, with a guide handling ticket windows, coach or boat connections, and neighborhood pacing so the day stays focused on the outing rather than logistics. Meeting points are confirmed at booking in Cancun, and the itinerary keeps visitors close to Caribbean coastline, Mayan ruins, and cenote swimming holes that shape this Cancun tour.",
  "117119P3": "Discover the story behind Chichen Itza with a private tour from Cancun. Get picked up at your hotel or the address of your choice in Cancun and set out on a full-day sightseeing tour to the Mayan ruins at Chichen Itza. Stops include Chichen Itza, Cenote, Valladolid. Learn about Mexican history in the Yucatan Peninsula and explore this archaeological site including its iconic pyramid. Ideal for visitors basing in Cancun who want a guided city or Yucatan experience without coordinating tickets or landmark timing on their own. Routes stay oriented to Chichen Itza, Cenote, Valladolid that define this Cancun experience, with a guide handling ticket windows, coach or boat connections, and neighborhood pacing so the day stays focused on the outing rather than logistics.",
  "118403P17": "In Cancun, this Xenotes day follows the Ruta de los Cenotes into jungle sinkholes of four types: semi-open, open, ancient, and cavern. Round-trip hotel transport is included, and the circuit mixes rappelling, zip lining, kayaking, and swimming before a picnic lunch with water, coffee, wine, and beer. Stops include Ruta de los Cenotes, Semi-open cenote, Open cenote, Ancient cenote, Cavern cenote. Life jackets and activity gear are provided so visitors can stay with the water rather than packing their own kit. The format suits visitors basing in Cancun who want a full cenote circuit without coordinating four separate park tickets. Departures are confirmed at booking in Cancun, and the itinerary stays on the published Xenotes route rather than adding extra ruins or beach clubs.",
  "7041P7": "Get your adrenaline fix while in Cancun with this five-in-one adventure combo. Fly through the trees on a thrilling zipline circuit, including an Aquazip; ride the Tarzania zipline coaster, and take a daring parachute drop. Stops include Selvatica Adventure Park, ATV jungle trail, Zipline circuit, Cenote. Then, challenge yourself to a treetop rope course and venture off-road on an exhilarating ATV or Polaris RZR buggy excursion. Ideal for visitors basing in Cancun who want a guided off-road day without renting ATVs independently. Routes stay oriented to Selvatica Adventure Park, ATV jungle trail, Zipline circuit, Cenote that define this Cancun experience, with a guide handling ATV briefing, jungle routing, and return to Cancun so the day stays focused on the outing rather than logistics.",
  "12861P5": "In Cancun, explore coral reefs, ancient history, and nature in the Riviera Maya in just a day on this combination tour. Visit the Tulum archaeological site, snorkel coral reef in the Caribbean Sea, and swim in the crystal waters of a cenote sinkhole. Stops include Tulum Archaeological Site, Playa Maya, Parque De Cenotes Yax-Muul. Your package includes entrance fees, lunch, and door-to-door transport from hotels in Cancun, Tulum, and the Riviera Maya, but excludes a marine park tax. Ideal for visitors basing in Cancun who want a guided city or Yucatan experience without coordinating tickets or landmark timing on their own. Routes stay oriented to Tulum Archaeological Site, Playa Maya, Parque De Cenotes Yax-Muul that define this Cancun experience, with a guide handling ticket windows, coach or boat connections, and neighborhood pacing so the day stays focused on the outing rather than logistics.",
  "6200P5": "In Cancun, this luxury catamaran sails the Caribbean coastline toward Isla Mujeres with snorkeling gear, a gourmet lunch, and an open bar on board. The crew handles hotel-zone pickup, reef timing, and the island stop so visitors can stay with the water rather than ferry tickets. Stops include Cancun Caribbean coastline, Snorkel stop, Isla Mujeres. Free time on Isla Mujeres is included after the snorkel break, then the return sail continues with complimentary drinks. The half-day format is aimed at visitors eight years and older, with round-trip transport from most Cancun and Riviera Maya hotels. Departures are confirmed at booking in Cancun, and the itinerary stays on the catamaran, the reef stop, and Isla Mujeres rather than adding extra mainland beach clubs.",
  "308891P25": "In Cancun, this Puerto Morelos food walk leaves the hotel zone for a quieter fishing town south of the resort strip. A local guide leads a walking circuit of the plaza and waterfront, then stops for handmade tacos and an artesanal tequila tasting instead of a generic resort buffet. Fish, shrimp, smoked-meat, chicken, and vegetable taco options keep the food stop flexible, with a Mayan-style pork taco and a small ice-cream tasting rounding out the flavors. Hotel pickup and drop-off are included from most Cancun and Riviera Maya properties, so the afternoon stays on tasting and town walking rather than taxi logistics. The format suits visitors who want a native cultural food walk without coordinating restaurant reservations or tequila-room timing on their own. Departures are confirmed at booking in Cancun, and the itinerary stays on Puerto Morelos streets, taco counters, and tasting rooms that define this half-day from the hotel zone.",
  "42786P2": "In Cancun, snorkel the Great Maya Reef on a half-day snorkeling tour of the coral reef near Puerto Morelos. Spot fish, marine wildlife, and vibrant corals as you swim alongside the snorkel guides, then enjoy some free time to explore the fishing village of Puerto Morelos. Stops include Puerto Morelos National Reef Park, Puerto Morelos. This snorkel tour includes all equipment, lunch at a beach club, and round-trip transport from centrally-located hotels in Cancun and the Riviera Maya. Ideal for visitors basing in Cancun who want a guided city or Yucatan experience without coordinating tickets or landmark timing on their own. Routes stay oriented to Puerto Morelos National Reef Park, Puerto Morelos that define this Cancun experience, with a guide handling ticket windows, coach or boat connections, and neighborhood pacing so the day stays focused on the outing rather than logistics.",
  "368094P1": "In Cancun, this all-inclusive catamaran day sails from Playa Tortugas toward Isla Mujeres with snorkeling gear, lunch, snacks, and an open bar on board. The crew handles boarding, reef timing, and the island stop so visitors can stay with Caribbean water and beach time rather than ferry tickets. A snorkel stop is included when conditions allow, then the boat continues to Isla Mujeres for free time before the return sail. Restrooms on board and unlimited non-alcoholic and alcoholic drinks keep the full-day format straightforward for hotel-zone visitors. The outing is a scenic sailing day rather than a private charter, with a dock tax collected for Tortugas Beach as listed on the live product. Departures are confirmed at booking in Cancun, and the itinerary stays on the catamaran, the snorkel stop, and Isla Mujeres rather than adding extra ruins or mainland beach clubs.",
};

export const getCancunTargetedNarrativeDescription = (
  productCode: string
) =>
  CANCUN_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as CancunTargetedNarrativeDescriptionProductCode
  ];
