export const DENVER_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "41410P10",
  "8950P6",
  "72188P15",
  "41410P15",
  "41410P14",
  "8950P37",
  "59646P2",
  "8950P29",
  "8950P9",
  "59646P5",
  "323041P1",
  "128737P1",
  "128737P2",
  "41410P1",
  "72188P1",
  "59646P3",
] as const;

export type DenverTargetedNarrativeDescriptionProductCode =
  (typeof DENVER_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const DENVER_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  DenverTargetedNarrativeDescriptionProductCode,
  string
> = {
  "41410P10": "Head south from Denver on a small group tour to two of Colorado's most majestic places. First, visit Garden of the Gods, a unique geological area with colossal red rock formations. Stops include Garden of the Gods, Balanced Rock, Pikes Peak, Manitou Springs. Then take a drive up Pikes Peak, which inspired the song \"America the Beautiful.\" Have lunch and enjoy a bit of free time or shopping in the charming town of Manitou Springs, then take a scenic drive through the foothills back to Denver. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "8950P6": "In Denver, climb from the streets of the \"Mile High City\" to Rocky Mountain National Park, on a day trip that showcases the rugged beauty of Colorado's mountains. Weave through small, historic towns and drive over alpine passes, as you scan the horizon for mountain wildlife such as elk, black bears, or moose. Stops include Denver Union Station, Boulder, Lyons, Lily Lake, Rocky Mountain National Park, Stanley Hotel. Transportation and local commentary are handled so you can focus on Denver's foothills scenery, red-rock amphitheater views, and Rocky Mountain day-trip landmarks. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "72188P15": "Discover some of Colorado's wildest Rocky Mountain Scenery on this full-day, small-group tour from Denver. In the morning, meet near Union Station, hop aboard your vehicle, and head first to the Garden of the Gods—a nature park known for its staggering sandstone rock formations. Stops include Pikes Peak, Manitou Springs, Garden of the Gods, Colorado Springs. Next, drive all the way to the summit of Pikes Peak for extraordinary views over the landscape. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "41410P15": "Venture beyond Denver, and discover what Colorado has to offer: on this small-group tour, visit Red Rocks Amphitheatre, the Continental Divide, and the ski resort town of Breckenridge, all in one day. Depart in the morning via comfortable vehicle: you'll explore Red Rocks before taking Loveland Pass along the Continental Divide, and stopping for photos along the way. Stops include Red Rocks Park and Amphitheatre, Continental Divide, Loveland Pass, Breckenridge. At Breckenridge, enjoy free time to wander, shop, and eat lunch (own expense). Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "41410P14": "Escape Denver and immerse yourself in the nature of Mt. Blue Sky (formerly Mt. Evans) and the Rocky Mountains during this small-group day trip. Reach the summit via tour vehicle, get out to explore, and get epic views over the surrounding Rockies. Stops include Red Rocks Park and Amphitheatre, Echo Lake, Mount Blue Sky, Clear Creek Canyon, Idaho Springs. Along the way, stop at Red Rocks Park and Amphitheatre, Clear Creek Canyon, Idaho Springs, Summit Lake, and Echo Lake. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "8950P37": "In Denver, immerse yourself in the natural beauty of the Colorado Rockies on a full-day tour to Breckenridge. All-inclusive transportation from downtown Denver enables you to skip the hassle of navigating mountain roads and enjoy the stunning natural scenery. Stops include Red Rocks Park and Amphitheatre, Continental Divide, Breckenridge. After a visit to Red Rocks Amphitheater and a trip over the Continental Divide, enjoy several hours of free time to explore Breckenridge independently. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "59646P2": "In Denver, this full-day, small-group tour takes you out of the city and into the rugged Rocky Mountains. Visit Red Rocks Amphitheatre, an acoustic masterpiece crafted by Mother Nature; travel through rugged Clear Creek Canyon to the Continental Divide; and visit an old mining town. Stops include Red Rocks Park and Amphitheatre, Clear Creek Canyon, Continental Divide, Breckenridge, Eisenhower Tunnel. Enjoy free time for lunch and shopping in the iconic ski town of Breckenridge, then head back to Denver, passing through the Eisenhower Tunnel—the longest, highest, passenger car tunnel in the world. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "8950P29": "In Denver, if you're seeking a quick adventure, take a four hour tour that treats you to a few of the best things of Colorado. Your tour guide Gem gives you locals only insight into the front range before you set off from gorgeous Red Rocks Park for a hike at the base of Red Rocks and Morrison Slide Trail. Stops include Red Rocks Park and Amphitheatre, Morrison Slide Trail, Golden. Following the moderate two-three mile hike, relax and unwind at a local coffee shop downtown Golden, Colorado. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "8950P9": "The Denver foothills are packed with some of Colorado's best sights, from Red Rocks Amphitheater to Lookout Mountain and scenic Lariat Loop. Throughout this half-day tour from Denver explore the scenic foothills, get panoramic views of the mountain surroundings, and stroll through small, historic towns before stopping in Golden for a coffee or craft beer. Stops include Red Rocks Park and Amphitheatre, Lookout Mountain, Lariat Loop, Golden. It's a quick escape from the big city buzz and a taste of life in the mountains just outside of \"Mile High\" City. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "59646P5": "Explore Colorado’s natural playgrounds, just a short drive from downtown Denver. Escape the city and head for the Rockies with a guide to handle the road, so you can focus on the stunning scenery of Mt. Evans, Bear Creek Canyon, and beyond. Stops include Red Rocks Park and Amphitheatre, Evergreen, Echo Lake, Mount Blue Sky, Bear Creek Canyon. Get a taste of mountain culture in the charming town of Evergreen, check out the dramatic formations of Red Rocks Amphitheatre, and hike around serene Echo Lake on this half-day mountain sampler. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "323041P1": "There are so many great hikes in the Denver area, how can you choose? Let a local do the work—on this guided tour, you’ll get whisked off to the mountains, where you’ll hike at your comfort level (snacks and breaks as needed), learn about the flora and fauna of the Rockies, and get incredible bird’s-eye photos of Colorado. Stops include Rocky Mountain Foothills, Mount Blue Sky Viewpoint. Simply put, you'll get more out of your time spent in the mountains. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "128737P1": "In Denver, enjoy the beauty of a hike in the Rockies without the worry of getting lost or picking an unsuitable trail during this full-day excursion. Plus, save your strength for the hike thanks to round-trip transportation and learn about the wildflowers and wildlife from your guide, something that would be harder to do alone. Stops include Rocky Mountain Trailhead, Scenic Mountain Overlook. Transportation and local commentary are handled so you can focus on Denver's foothills scenery, red-rock amphitheater views, and Rocky Mountain day-trip landmarks. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "128737P2": "In Denver, do you want to go for a hike but don't know which trail to pick, and don't want to get lost in the forest? We make things easy for you by taking you to a beautiful trail that wouldn't be easy to find on your own, and we'll make sure you have a stress-free time, enjoying the natural beauty of the Rocky Mountains. Stops include Rocky Mountain Trailhead, Sunset Overlook. We'll hike for 1.5-2 hours in the Rocky Mountains while the sun sets. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "41410P1": "Explore the grand scenery of the Rocky Mountains and Colorado’s Wild West history on a small-group bus tour from Denver. Visit the famous Red Rocks Amphitheatre, and encounter descendants of America’s last wild buffalo herd grazing in the foothills. Stops include Red Rocks Park and Amphitheatre, Lookout Mountain, Lariat Loop, Golden. Get panoramic views of Denver and the Front Range from atop Lookout Mountain, drive the Lariat Loop National Scenic Byway, visit the town of Golden, and more. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "72188P1": "Enjoy an introductory visit to the Rocky Mountains—and still leave enough time to continue your Denver sightseeing—on this half-day, small-group tour. Meet your guide in the morning, and head out to the foothills to enjoy views of the Great Plains and Lookout Mountain. Stops include Lookout Mountain, Lariat Loop, Golden. Drive historic Lariat Loop, and get a glimpse of historic Golden, home to Coors Brewery. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
  "59646P3": "First-time visitors to Denver appreciate this opportunity to escape the city for a few hours to see key attractions in the foothills. Let a professional do the driving on mountain byways, while you sit back and take in the sights. Stops include Red Rocks Park and Amphitheatre, Lariat Loop. You'll visit the iconic Red Rocks Amphitheatre, will stop by the Buffalo Bill Museum and Grave, will drive the Lariat Loop, and more. Ideal for visitors basing in Denver who want a guided Front Range experience without coordinating transport, trailheads, or mountain logistics on their own.",
};

export const getDenverTargetedNarrativeDescription = (productCode: string) =>
  DENVER_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as DenverTargetedNarrativeDescriptionProductCode
  ];
