export const HONOLULU_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "28456P8",
  "12446P4",
  "70444P6",
  "28456P1",
  "117916P9",
  "179218P23",
  "368856P1",
  "6981P1",
  "189546P8",
  "12446SNORKEL",
  "452226P3",
  "23607",
  "390101P5",
  "64146P1",
  "33188P2",
  "166842P1",
  "375182P1",
  "469693P1",
  "3961P32",
  "5563928P2",
] as const;

export type HonoluluTargetedNarrativeDescriptionProductCode =
  (typeof HONOLULU_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const HONOLULU_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  HonoluluTargetedNarrativeDescriptionProductCode,
  string
> = {
  "28456P8": "A private helicopter flight over Oahu passes lush valleys, Diamond Head crater, and the South Shore. The flight lands at a private oasis away from crowds, where leis, chocolates, and champagne are waiting. The helicopter is reserved for the booking, and several departure times are offered from Honolulu. Leis, chocolates, and champagne are set out at that private Oahu landing after the pass over the crater, the valleys, and the South Shore. Several departure times are offered so the private Honolulu flight can be scheduled for the party.",
  "12446P4": "A private circle-island tour of Oahu is reserved for one party, with stops and timing set by that party. There is no shared bus and no waiting on other groups. Pickup and drop-off are from the party's accommodations, and the guide covers Hawaiian history during the day. The places on this Honolulu booking are the ones the party chooses, and the party decides how long to remain at each one. The guide's comments on Hawaiian history accompany the party from the accommodation pickup to the drop-off back at those accommodations.",
  "70444P6": "This volcano day leaves Honolulu on a flight to Kona International Airport, where a driver meets the group. More than eight hours on the ground include historic Kona, the Kilauea Iki Overlook, black sand, and Hawaii Volcanoes National Park. Ground transport is included with the inter-island flight. The park is an active volcanic landscape that is still forming the Big Island. Black sand and the Kilauea Iki Overlook share that ground day with historic Kona. The driver meets the group in Kona after the flight from Honolulu.",
  "28456P1": "This helicopter tour flies over Oahu past Diamond Head, Sacred Falls, the Dole Plantation, and Pearl Harbor. The flight lasts about an hour, with a choice of doors on or doors off. Several departure times are offered from Honolulu. Passengers pick the time and whether the doors stay on or come off for the aerial pass over Diamond Head, Sacred Falls, the Dole Plantation, and Pearl Harbor. Doors-on and doors-off choices are both offered, along with more than one Honolulu departure time for the hour in the air.",
  "117916P9": "This Pearl Harbor visit from Honolulu includes memorials, museums, historic vessels, and a USS Arizona boat ride. Admissions and transportation are included, so the December 7, 1941 sites on this booking are handled together. The boat ride to the USS Arizona Memorial is part of that included access. Transportation, the admissions, and the USS Arizona Memorial boat ride all sit on this one Honolulu booking. The USS Arizona Memorial boat ride, the admissions, and the transportation are bundled for this Pearl Harbor visit from Honolulu.",
  "179218P23": "A small-group day from Waikiki visits Pearl Harbor, the Dole Plantation, and the Polynesian Cultural Center. Pearl Harbor covers World War II history in the United States, the Dole Plantation covers Hawaii's pineapple industry, and the Polynesian Cultural Center covers traditions in Hawaii and across the Pacific. Round-trip transportation from Waikiki hotels is included, and admission is included in the tour price. All three stops are on Oahu, and the day returns to the hotel. Waikiki hotel transfers are round trip.",
  "368856P1": "Private surf lessons in Honolulu are taught one-to-one by an instructor with 18 years on the world circuit. Sessions are matched to skill, from first-timers learning the basics to experienced riders working on technique. A surfboard and waterproof gear are provided. The lessons suit most ages and fitness levels, including younger children. The instructor stays with one student, and the surfboard and waterproof gear are part of the Honolulu lesson. Younger children can join when the lesson fits their age and fitness.",
  "6981P1": "Chief's Luau includes pickup at the hotel, a lei and cocktail greeting, Hawaiian food, and a live Polynesian show. The meal is an all-you-can-eat buffet, and headband weaving is one of the activities during the evening. Round-trip transfers from the hotel are provided, and more than one package is offered. Headband weaving sits with the buffet and the Polynesian show after the hotel transfer on Oahu. Packages differ, but the hotel transfer, lei, cocktail, buffet, and live Polynesian show are the evening's core on Oahu.",
  "189546P8": "This North Shore day from Honolulu stops at the old Sugar Mill and then walks to a waterfall in Waimea Valley. The drive over includes a history lesson. At the Sugar Mill there is coffee and chocolate, then a souvenir shop. About seven miles later, a three-quarter-mile walk through rainforest and a Hawaiian village reaches a 45-foot waterfall and a pool about 110 feet across, with lifeguards on duty. Swimming is part of the stop before the walk back. Lifeguards are present for the swim at the waterfall pool.",
  "12446SNORKEL": "A small-group minibus circles Oahu with snorkeling among Hawaiian green sea turtles on the North Shore. A local guide travels with a group of about 24 to 28 people or fewer. Stops include the Dole Plantation, a macadamia nut farm, the Halona Blowhole, Diamond Head, and Makapu'u Beach, plus Kualoa Point on Kaneohe Bay for a view of Mokoliʻi. Round-trip transportation from Waikiki hotels is included. The North Shore snorkel is with Hawaiian green sea turtles. Waikiki hotels are the pickup and return point for the minibus.",
  "452226P3": "Pickup at a Waikiki hotel goes to Pearl Harbor for the USS Arizona Memorial and the Battleship Missouri. The ride goes to the Pearl Harbor National Museum, and included tickets cover the Pearl Harbor National Memorial and the Battleship Missouri Memorial, including time aboard the battleship. Drop-off returns to Waikiki hotels. This Honolulu visit covers the attack on Pearl Harbor and World War II, with those tickets included. Boarding the battleship is included with the Missouri ticket on this Honolulu booking.",
  "23607": "A coach circles Oahu from Honolulu, with Diamond Head, the North Shore, the Dole Plantation, and Byodo-In Temple. The day also includes Nu'uanu Pali Lookout, the Halona Blowhole, and Waimea Valley. On the North Shore, Waimea Bay is noted for big-wave surfing since the 1960s. Byodo-In Temple admission and round-trip hotel transport are included. Ocean views, rugged mountains, and history come along on the full-day coach circuit. The temple stop includes admission, and the coach handles the hotel transport both ways.",
  "390101P5": "A small group leaves a Waikiki hotel for Pearl Harbor, the USS Arizona Memorial, and the Battleship Missouri. The transfer uses an air-conditioned vehicle, and tickets for the USS Arizona Memorial and the USS Missouri, also called the Mighty MO, are included. The day includes a short ride through downtown Honolulu. Time aboard the battleship follows pickup at the Waikiki hotel on this Oahu tour. Downtown Honolulu is a short ride on the same air-conditioned day as the Arizona Memorial and the Mighty MO.",
  "64146P1": "Ka Moana Luau is an oceanfront show at Aloha Tower, with cultural activities, a Hawaiian buffet, and fire dance. Activities include making a coconut headband, stringing a flower lei, and hula. The buffet includes kalua pork, huli huli chicken, and lomi lomi salmon. The performance includes Polynesian fire dance. The headband, lei, and hula come before that fire dance and buffet at Aloha Tower in Honolulu. Lomi lomi salmon joins kalua pork and huli huli chicken on the Aloha Tower buffet before the fire dance.",
  "33188P2": "Germaine's Luau is a dinner show in Kapolei, with a lei greeting, a Hawaiian-American meal, and live dance. The meal includes roasted pig, sauteed island fish, and Hawaiian chicken. Performances include Polynesian fire-knife, hula, and slap dancing. The Makai Luau Package lists a shell lei, a Hawaiian buffet, soft drinks, hot coffee, and one alcoholic drink ticket for each adult age 21 or older. This Oahu luau is held in Kapolei. Soft drinks, hot coffee, and the adult drink ticket are listed on the Makai package with the shell lei.",
  "166842P1": "A small-group coach of no more than 14 passengers circles Oahu after pickup at a Waikiki hotel. The day includes Diamond Head, the Halona Blowhole, Nu'uanu Pali Lookout, and Haleiwa Town. A stop at the Dole Plantation includes a whole Dole pineapple. The guide covers Oahu history during the ride. Pickup at the Waikiki hotel is part of that 14-passenger circle. Diamond Head, the Halona Blowhole, Nu'uanu Pali Lookout, Haleiwa Town, and the Dole pineapple stop are the named pieces of this small-group circle from Waikiki.",
  "375182P1": "This Oahu day includes snorkeling plus Diamond Head State Monument, the Halona Blowhole, and the Dole Plantation. Other named stops are Makapu'u Beach, Kahuku Farms, and Waimea Bay. Snacks and snorkeling gear are provided, and pickup at the hotel is part of the day. Those named stops and the snorkeling share the same day, with the snacks and gear provided. Diamond Head State Monument, the Halona Blowhole, the Dole Plantation, Makapu'u Beach, Kahuku Farms, and Waimea Bay are the places named alongside the snorkeling on this Oahu day.",
  "469693P1": "'Auana is a Cirque du Soleil show at the OUTRIGGER Waikiki Beachcomber Hotel in Honolulu. The Hawaii-inspired production uses acrobats, comedians, musicians, singers, and hula dancers. The company mixes international performers with local performers and draws on Hawaiian tradition. The show is presented only at the OUTRIGGER Waikiki Beachcomber Hotel. International and local performers share the acrobatics, comedy, music, singing, and hula in this Hawaii-inspired production at the Waikiki Beachcomber Hotel in Honolulu.",
  "3961P32": "The Waikiki Luau pairs a buffet of suckling pig and roast beef with the onsite Rock-a-Hula show. The evening starts with a Hawaiian welcome and a mai tai. Rock-a-Hula includes hula, fire-knife dancing, and rock and roll, and admission to that show comes with select packages. Whole suckling pig and roast beef are on the buffet at this luau in Waikiki, on Oahu. Select packages add Rock-a-Hula admission, with hula, fire-knife dancing, and rock and roll after the welcome mai tai and the Waikiki buffet.",
  "5563928P2": "This small-group circle-island tour picks up early from Waikiki hotels and includes Byodo-In Temple. Named lookouts include Diamond Head Lookout and the Halona Blowhole. Breakfast is a burrito, temple admission is included, and a local guide comments on the culture. Drop-off returns to Waikiki. The burrito, the temple admission, and those two lookouts are part of the early small-group ride on Oahu. A local guide, the breakfast burrito, and Byodo-In admission accompany the early Waikiki pickup on this small-group Oahu ride.",
};

export const getHonoluluTargetedNarrativeDescription = (productCode: string) =>
  HONOLULU_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as HonoluluTargetedNarrativeDescriptionProductCode
  ];
