export const HONOLULU_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "28456P8",
  "12446P4",
  "70444P6",
  "28456P1",
  "117916P9",
  "179218P23",
  "368856P1",
  "6981P1",
  "189546P8",
  "12446SNORKEL",
  "452226P3",
  "23607",
  "390101P5",
  "64146P1",
  "33188P2",
  "166842P1",
  "375182P1",
  "469693P1",
  "3961P32",
  "5563928P2"
] as const;

export type HonoluluTargetedNarrativeDescriptionProductCode =
  (typeof HONOLULU_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const HONOLULU_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  HonoluluTargetedNarrativeDescriptionProductCode,
  string
> = {
  "28456P8": "If you're looking to add to the romance of your Hawaii trip then this romantic helicopter ride is right up your alley. Enjoy a scenic flight over Oahu and take in the lush valleys, Diamond Head crater, and the South Shore. Transportation, equipment, and local commentary are handled so you can focus on Oahu's coastlines, valleys, and cultural landmarks. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "12446P4": "Swap the big, crowded tour buses for a private and personalized experience of Oahu. This private tour is exclusively for your party so there's no rushing or waiting around for others. Your tour is fully customizable so you can choose which places you want to visit and how long you want to spend therePrivate tour of Oahu: Avoid crowds and enjoy a personalized experience Flexibility to customize your tour to your own preferences Hassle-free pickup and drop-off from your accommodations See the sights and learn about Hawaiian history from your guide Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "70444P6": "Get away from the Oahu buzz with this whirlwind volcano-chasing tour. After your short flight from Honolulu, arrive in Kona to meet your driver for a serious adventure: You’ll visit the historic town of Kona, set your eyes on the Mars-like Kilauea Iki Overlook, run your toes along black sand, and explore Hawaii Volcanoes National Park, an active volcanic landscape that’s creating the Big Island to this day.Inter-island flight to Kona International Airport and transport included See wild spots like Hawaii Volcanoes National Park Spend 8+ hours on the ground, for a full day chasing wild landscap Transportation, equipment, and local commentary are handled so you can focus on Oahu's coastlines, valleys, and cultural landmarks. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "28456P1": "Explore Hawaii’s island of Oahu by air on this helicopter tour. Fly above the island and many of its most well-known landmarks, such as Diamond Head, Sacred Falls, the Dole Plantation, and Pearl Harbor. On this ride, choose your departure time and whether or not you’d like the helicopter doors on or off.Oahu helicopter tour with doors on or off Pass by Diamond Head, Sacred Falls, Pearl Harbor, and more Multiple departure times make it easy to fit into your schedule Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "117916P9": "Visit Pearl Harbor’s most important sites without the hassle of securing separate tickets or coordinating multiple admissions. This tour combines access to key memorials, museums, and historic vessels in one streamlined experience, helping you gain a broader understanding of the events of December 7, 1941. Included admissions and transportation make exploring this historic landmark more convenient and efficient.Pearl Harbor's top memorials and museums explored with one convenient booking Included admission tickets save time and simplify your visit USS Arizona Memorial boat ride included at no Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "179218P23": "See three of Oahu's most important cultural attractions in just one day with his small-group tour. You'll visit historic Pearl Harbor where you'll learn about WWII history in the US, continuing to the Dole Plantation to learn about the history of the state's pineapple industry. Transportation, equipment, and local commentary are handled so you can focus on Oahu's coastlines, valleys, and cultural landmarks. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "368856P1": "Hawaii is the perfect to learn to surf, and the perfect *way* is with a pro who's chased waves for 18 years on the world circuit. Unlike crowded tourist lessons, these private sessions match your skill level, from first-timers mastering the basics to experienced riders fine-tuning technique. With all gear provided, you’re guaranteed to improve your skills with 1-1 instruction—and hopefully have a great time in the waves.Surfboard and waterproof gear provided Get 1-1 access to a local surfing pro who can address your needs Suitable for most all ages and fitness levels, including younger kids Li Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "6981P1": "Immerse yourself in Hawaiian culture with a visit to a traditional luau. Your driver will pick you up at your hotel and take you to the luau, where you'll be greeted with a lei and a cocktail. During the course of the evening, you'll have your fill of Hawaiian food while watching a live Polynesian show. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "189546P8": "Depart from Honolulu on a guided Oahu North Shore day trip that pairs island history with Waimea Valley's rainforest waterfall swim. After a North Shore coffee and chocolate tasting, hike through Waimea Valley to a 45-foot waterfall pool with lifeguards on duty. You'll pause at Waimea Valley, the North Shore tasting stop, and the waterfall pool. Transportation, equipment, and local commentary are handled so you can focus on Oahu's North Shore coastlines, valleys, and cultural landmarks. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "12446SNORKEL": "Explore Oahu on this full-day minibus tour with a small group and a local guide. See the Dole Plantation, the Halona Blowhole, Diamond Head, and Makapu’u Beach during this day-long outing. Round-trip transportation from Waikiki hotels is included.Stop by Kualoa Point on Kane’ohe Bay for a look at Mokoliʻi Visit a macadamia nut farm and the Dole pineapple plantation Snorkel amongst Hawaiian green sea turtles Travel by minibus with a max Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "452226P3": "Deepen your understanding of World War II and the attack on Pearl Harbor with this seamless and convenient tour. Enjoy stress-free travel with direct pickup and transportation to the Pearl Harbor National Museum. Then, skip the hassle of ticket lines as admission to key sites—including the Pearl Harbor National Memorial and Battleship Missouri Memorial—is included, giving you more time to immerse yourself in the exhibits.Avoid long lines at the Pearl Harbor National Memorial with included tickets Rare opportunity to step aboard a battleship Hassle-free pickup and drop-off from Waikiki hotels L Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "23607": "Circle the Island of Oahu by coach, enjoying ocean views, rugged mountains, and fascinating history during this full-day tour. Check out Diamond Head, Nu’uanu Pali lookout, the Halona Blowhole, Waimea Valley and Oahu’s beautiful North Shore. Soak up Hawaiian history and culture with a stop at the Dole Plantation and the serene, Japanese-style Byodo-In Temple. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "390101P5": "Visit Pearl Harbor, the USS Arizona Memorial, and the Battleship Missouri Memorial (aka the “Mighty MO”) on this small-group tour. After a pickup from your Waikiki hotel, travel to the harbor in a comfortable, air-conditioned vehicle. This full-day tour gives you time to reflect on what you see and learn at Pearl Harbor.Ideal for World War II and American history buffs Round-trip hotel transfers mean you don't risk getting lost Includes tickets for USS Arizona Memorial and USS Missouri Battleship Enjoy a short ride through the historical Honolulu downtown Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "64146P1": "Experience a traditional Hawaiian Luau in a scenic location. The evening begins with a variety of cultural activities ideal for all ages. Learn how to make a coconut headband, string flower lei, or dance hula, and then sit down for a buffet dinner with a large selection of Hawaiian specialties like Kalua pork and Huli Huli chicken. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "33188P2": "Enjoy a taste of Hawaiian culture when you book this luau dinner experience in Kapolei. Head to the venue and be greeted with a traditional lei before you are seated for dinner. Enjoy a delicious Hawaiian-American meal with dishes that include a succulent roasted pig, sauteed island fish, Hawaiian chicken, and much more. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "166842P1": "This small-group circle-island tour of Oahu is ideal for those who want to see a lot in a short time. In a cozy vehicle with no more than 14 passengers, you'll see landmarks like Diamond Head, the Halona Blowhole, Nu'uanu Pali Lookout, and historic Haleiwa Town. You'll also visit the famed Dole Plantation where you'll get a whole delicious Dole pineapple. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "375182P1": "With just one day, you can see 16 of Oahu’s greatest sights and still have time for snorkeling—if you hop on this tour. Across one whirlwind day, you’ll witness Diamond Head State Monument, the Halona Blowhole, the Dole Plantation, and so much more. You’ll capture fantastic photos, learn all about the island’s history, and go snorkeling, topping off the day surrounded by Oahu’s colorful marine life.Make the most of your time on the island, hitting all the best spots with a guide See Makapu'u Beach, Kahuku Farms, Waimea Bay, and beyond Snacks and snorkeling gear provided Hassle-free hotel picku Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "469693P1": "A new dawn of live entertainment rises in ʻAuana by Cirque du Soleil – a Hawai‘i-inspired production featuring a cast of powerful acrobats, hilarious comedians, talented musicians and singers, and profound hula dancers. The unparalleled ensemble brings together international and local talents to shine a fresh light on the spirit of Hawai‘i. Blending Cirque du Soleil’s world-renowned artistry with the rich traditions of the islands, this one-of-a-kind spectacle transports audiences on a breathtaking journey through Hawaiian culture. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "3961P32": "Come experience a celebration of Hawaiian cuisine, live music, and festive hula at the Waikiki Luau. Relax with a Hawaiian welcome and tropical mai tai before dining on a lavish Luau-themed buffet dinner with island-roasted whole suckling pig and roast beef. Then, find your premier seats for the onsite \"Rock-a-Hula\" show, which features everything from hula and fire-knife dancing to rock n' roll.Experience an authentic Hawaiian luau, right in Waikiki Includes admission into Rock-a-Hula with select packages Witness Hawaiian's ancient dance, fire-knife work, and more Prebooking your spot guarant Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
  "5563928P2": "There are many Circle Island tours on offer in Oahu but this one delivers a small-group, crowd- and traffic-free experience. With an early-morning pickup from Waikiki hotels, you're on the road before the rest, which means no lines at the island's top attractions, including the Diamond Head Lookout and Halona Blowhole.Benefit from your local Hawaiian guide's insights into local culture Start your day off right with an included breakfast burrito Enjoy hassle-free hotel pickup and drop-off in Waikiki Includes admission to Byodo-In Temple and an unrushed experience Transportation, equipment, and local commentary are handled so you can focus on Oahu's coastlines, valleys, and cultural landmarks. Ideal for travelers basing in Honolulu who want a guided Oahu experience without coordinating transport, gear, or admission tickets on their own.",
};

export const getHonoluluTargetedNarrativeDescription = (productCode: string) =>
  HONOLULU_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as HonoluluTargetedNarrativeDescriptionProductCode
  ];
