export const KAUAI_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "106191P10",
  "441243P1",
  "277445P2",
  "23786P2",
  "36364P11",
  "132411P3",
  "132411P2",
  "132411P1",
  "7062WCWFT1",
  "2064P6",
  "445157P2",
  "24198P1",
  "2360KAUAI",
  "5655PLANTATION",
  "6654P2",
] as const;

export type KauaiTargetedNarrativeDescriptionProductCode =
  (typeof KAUAI_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const KAUAI_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  KauaiTargetedNarrativeDescriptionProductCode,
  string
> = {
  "106191P10": "On Kauai, the excitement of a helicopter tour can quickly turn to disappointment when you are seated in the middle. Not on this private tour where every seat is a window seat. Stops include Manawaiopuna Falls, Olokele Canyon, Waimea Canyon, Na Pali Coast, Wai'ale'ale Crater. You'll get excellent views of Kauai as you soar through the sky over Manawaiopuna Falls, the Olokele Canyon, Waimea Canyon, Na Pali coast, and Wai'ale'ale crater. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "441243P1": "On Kauai, get those drone views of Hawaii’s “Garden Isle”—but get them yourself, in an open-door helicopter. With no rear middle seats, you and your crew will take to the skies for nearly an hour, flying above lush canyons, wild cliffs, and the wettest spot on Earth. Stops include Manawaiopuna Falls, Na Pali Coast, Waimea Canyon, Mount Waialeale. Led by a trained firefighting pilot, you’ll get a fast-paced-yet-awe-inducing adventure, and you’ll nab some of the most gorgeous views on the planet. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "277445P2": "On Kauai, get those drone views of Hawaii’s “Garden Isle”—but get them yourself, in an open-door helicopter. With no rear middle seats, you and your crew will take to the skies for nearly an hour, flying above lush canyons, wild cliffs, and the wettest spot on Earth. Stops include Manawaiopuna Falls, Waimea Canyon State Park, Na Pali Coast State Wilderness Park, Hanalei, Mount Waialeale. Led by a trained firefighting pilot, you’ll get a fast-paced-yet-awe-inducing adventure, and you’ll nab some of the most gorgeous views on the planet. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "23786P2": "To fully appreciate the beauty of Hawaii’s ‘Garden Isle,’ take to the skies above Kauai on a helicopter tour in a new Eurocopter Eco-Star. Soar over the island’s diverse terrain, from rain-soaked Mount Waialeale and the waterfalls of Waiapuna to the dry red ravine of Waimea Canyon and the breathtaking emerald spires of the Na Pali Coast. Stops include Na Pali Coast, Waimea Canyon, Manawaiopuna Falls, Mount Waialeale. A two-way radio to communicate with the pilot and expansive viewing glass add to the unforgettable flight. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "36364P11": "This private tour gets you closer to some of the most stunning waterfalls on Kauai than would be possible alone or in a big group. The exact location depends upon your party's preferences and abilities but the tour can be as challenging as you wish. Stops include Secret Waterfall, Kauai Rainforest Trail, Rainforest Lookout. Your guide is a professional photographer and videographer so you will have someone with you to capture memories to cherish. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "132411P3": "This full-day guided excursion takes you to 8 of Kauai’s gorgeous spots by air-conditioned vehicle, ideal for a shore excursion. Drive through the south and west sides of the island, taking in a mix of scenic views and an opportunity to try and buy local products. Stops include Waimea Canyon, Spouting Horn, Kauai Coffee Company, South Shore Lookouts. Your guide will share the legends and stories of the places you stop by, including the renowned Waimea Canyon, the powerful Spouting Horn, Kauai Coffee Company, and more. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "132411P2": "Nicknamed the “Garden Isle,” Kauai is the oldest of Hawaii’s main islands, giving it time to become the lush oasis it is today. On this tour, you’ll experience its western wonders, from colorful Waimea Canyon and the 800-foot Waipoo Falls to the largest coffee orchard in the country. Stops include Waimea Canyon, Waipo'o Falls, Koke'e State Park, Kauai Coffee Company. You’ll feed chickens, cross historic swinging bridges, taste local foods, and walk away understanding Hawaii’s greatest legends. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "132411P1": "The Kauai legends, waterfalls, and geysers tour mixes stunning natural sites with storytelling across the island's south and east sides. Take the day off from driving and relax while a local guide shares Hawaiian legends at waterfalls, river lookouts, and the Spouting Horn blowhole. Stops include Wailua River, Opaekaa Falls, Wailua Falls, Tree Tunnel, Spouting Horn. Small-group routing keeps the experience intimate as you travel by air-conditioned vehicle with live narration. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "7062WCWFT1": "On your private tour of Kauai, you'll see the magnificent Waimea Canyon and places the big bus tours can't take you to. You'll enjoy great photo ops of Waipo'o Falls, admire a beautiful vista at Kalalau Lookout and visit the Poipu Beach resort area to see the Spouting Horn, sea turtles and perhaps a Hawaiian Monk seal! Stops include Waimea Canyon, Waipo'o Falls, Kalalau Lookout, Spouting Horn, Kauai Coffee Company. With a knowledgeable guide, you'll also visit attractions like the Kauai Coffee Company and the Captain Cook monument. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "2064P6": "On Kauai, the Na Pali coast may be 17 miles of pure “Garden Isle” splendor, but there’s even more to explore beyond its 4,000-foot cliffs. On this tour, you’ll go for 60 miles of discovery, from the coast to Kaulakahi Channel to Lehua Crater, the “Forbidden Island” of Ni’ihau, and beyond. Stops include Na Pali Coast State Wilderness Park, Ni'ihau, Lehua Crater, Kaulakahi Channel. Along the way, you’ll spot dolphins, snorkel amongst reefs, and, of course, sip and sit back, relishing in the adventure. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "445157P2": "On Kauai, fly across the ocean on an exhilarating guided Zodiac raft ride along the gorgeous Na Pali coast. The raft’s small size allows you to get into hard-to-reach sea caves, plus you’ll ogle pristine beaches, gushing waterfalls, and sheer cliffs. Stops include Na Pali Coast, Sea Caves, Coastal Waterfalls. This ocean adventure isn’t for the light-hearted, but the Zodiac rafts provide a thrilling and memorable way to explore this magnificent coastline from the water, as your captain and crew ensure your safety. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "24198P1": "Explore the natural beauty of Kauai on a 5-hour tour that combines a lovely kayaking trip with an moderately easy hike to Uluwehi Falls, also known as Secret Falls. Your experienced guide provides a paddling lesson and guided kayak tour in the Wailua River Valley, following gorgeous waterways through the lush Kauai landscape. Stops include Wailua River, Secret Falls (Uluwehi Falls), Wailua Marina. Then hop out of your kayaks and take a 45-minute hike to Secret Falls where you can cool off in the clear waters before returning to the Wailua marina the way you came. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "2360KAUAI": "Experience the natural wonders of Kauai on this full-day guided tour, featuring a scenic Wailua River cruise to the lush Fern Grotto and breathtaking views of Waimea Canyon. Visit iconic spots like Opaekaa Falls and the Kauai Coffee Estate, where you can sample locally grown coffee. Stops include Wailua River, Fern Grotto, Waimea Canyon, Opaekaa Falls, Kauai Coffee Estate. With a knowledgeable guide, air-conditioned transport, and plenty of photo stops, this tour offers a perfect blend of relaxation, history, and stunning landscapes. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "5655PLANTATION": "Enjoy an enchanted evening in Kauai with a gourmet dinner followed by one of the top-rated luaus on the island! Kick off the night with a Champagne reception and lei greeting at the historic Kilohana Plantation, then settle into a four-course meal of island favorites. Stops include Kilohana Plantation, The Plantation House by Gaylords, Luau Kalamaku Stage. After dinner, take in the mesmerizing Luau Kalamaku as dancers, fire-twirlers and musicians enact the story of the first Tahitian voyage to Hawaii. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "6654P2": "Get a new perspective on Kauai as you soar through lush forests and over the Waita Reservoir on the island's longest ziplines. While cruising across the 8-track course near Koloa, hang on to the handlebars or try some more daring acrobatic stunts with the hands-free 'Flyin' Kauai'an' harness. Stops include Koloa Zipline, Waita Reservoir, Koloa Sugar Mill. Transportation, equipment, and local commentary are handled so you can focus on Kauai's canyons, coastlines, waterfalls, and cultural landmarks. Ideal for visitors basing on Kauai who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
};

export const getKauaiTargetedNarrativeDescription = (productCode: string) =>
  KAUAI_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as KauaiTargetedNarrativeDescriptionProductCode
  ];
