export const KEY_WEST_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "331502P3",
  "362955P2",
  "119664P1",
  "288166P2",
  "328038P9",
  "102533P9",
  "2642P5",
  "418765P2",
  "2642P21",
  "2642P34",
  "2642P30",
  "7506P2",
  "7506P1",
  "5395SUNSET",
  "5264HDRS",
  "3800P30",
  "6426SHARKECO",
  "2642P6",
  "44502P1",
  "7812P77",
  "328038P8",
  "18235P1",
  "5264DC",
  "2642P16"
] as const;

export type KeyWestTargetedNarrativeDescriptionProductCode =
  (typeof KEY_WEST_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const KEY_WEST_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  KeyWestTargetedNarrativeDescriptionProductCode,
  string
> = {
  "331502P3": "Set sail for a full-day escape to the hidden gems off Key West’s coast—where pristine beaches and secluded islands await. Whether you're soaking up the sun, taking in the coastal views, or just unwinding with your group, this experience blends the excitement of the open water with the comfort of premium onboard amenities. Perfect for history lovers and adventure seekers alike, this guided journey offers something for everyone. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "362955P2": "Escape the crowds and discover hidden sandbars on a private eco tour through Key West’s backcountry waters. Swim, snorkel, or simply relax on pristine beaches only accessible by boat, with a flexible itinerary customized just for you.• Watch wild dolphins in their natural habitat• Private eco-friendly tour, just for your group• Cruise Key West’s beautiful backcountry waters• Flexible departure times to fit your schedule• Learn about marine life from a local guide Equipment, beverages, and local commentary are handled so you can focus on the water and island scenery. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "119664P1": "Discover the Great Florida Reef while visiting the Florida Keys on this private snorkel excursion. Board a private boat and depart from Big Pine Key towards Looe Key, where you can jump in the water and explore the extensive coral reef system. Snorkel alongside your captain and learn about the various species you encounter such as barracuda, parrotfish, and rays.Discover marine species on a snorkel tour to Looe Key Avoid crowded tourist boats on this private excursion All snorkel gear is provided for your convenience A private boat and captain means a personalized experience Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "288166P2": "Getting out on the water is one of the best ways to explore Key West, but many big tours cram their boats with passengers. This private tour promises an un-crowded experience. Head out onto turquoise water aboard a unique tiki bar boat and look out for marine life such as turtles and dolphins as you cruise to a sandbar where you can swim or just soak up the sun.Private boat tour of Key West: Avoid the big boats Set sail aboard a distinctive tiki bar boat: Unique experience Learn all about the local area and marine life from your captain Includes time for swimming or chilling on the sandbar Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "328038P9": "Get ready for an unforgettable journey that takes you through the natural beauty of Key West’s surrounding waters. Our Craigcat boat tour will take you on an exhilarating, up-close adventure across crystal-clear waters, winding through lush mangroves, stopping at pristine sandbars, and exploring hidden islands that are off the beaten path. This is your chance to experience Key West like never before — in a fun, fast, and eco-friendly CraigCat boat!Perfect for All Levels: Whether you're an experienced boater or a first-time adventurer, the Craigcat is easy to handle and designed for fun and com Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "102533P9": "Cruise from Key West into deeper waters where you can fish for tuna, mahi-mahi, and kingfish—species you won’t see in coastal areas. The small group size allows for plenty of one-on-one coaching from the captain and mate, with tips on how to make the most of provided gear. That means the experience will be tailored to you, whether you’re a lifelong angler or fishing for the first time.Visit offshore areas frequented by deep-water fish Use provided gear and bait suited to local conditions and season Fishing permit included—no need to apply for one Improve your fishing skills with tips from loca Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "2642P5": "Cool off in Key West on a half-day water sports tour that features 10 different water activities for you to try, from jet skiing to parasailing to banana boat rides to snorkeling, and much more. Enjoy lunch and draft beer on the way back to the marina for those over the age of 21.A great Key West experience for locals and tourists alike Take a boat out to sea for a day of water activities Ideal for adventure-seekers and water-lovers Lunch, drinks, and all equipment is included in the cost of booking Equipment, beverages, and local commentary are handled so you can focus on the water and island scenery. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "418765P2": "One of the only Adult Only experiences offered in Key West, our excursions are top-notch, with the vessel, all equipment, food and beverage service being set to premium standards! We offer a more intimate experience with less crowded excursions for the comfort of all of our guests. Equipment, beverages, and local commentary are handled so you can focus on the water and island scenery. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "2642P21": "Discover 28 miles (45 kms) of the Floridian coast on a 1.5-hour Jet Ski tour. With several daily tours, you can easily find a time that fits with your schedule. The tour is priced per Jet Ski, so you can ride tandem with a friend at no additional cost. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "2642P34": "Spend a stunning afternoon soaking up the sights of the Gulf of Mexico, chilling out at a sandbar, and watching dolphins at the Florida Marine Sanctuary. With the help of a fun and informative crew, you’ll explore the Floridian sea while your guides tell you all about the area’s history and wildlife. Enjoy lunch as well as unlimited beer, wine, and mimosas on your trip—just remember to drink responsibly.Half-day boat tour with dolphin spotting and sandbar chilling Guides to share facts about the area Fun for families and friends alike Unlimited draft beer, wine, and mimosas Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "2642P30": "Get ready to spend a half-day soaking up the sun and enjoying Key West’s diverse ecology during this fun sandbar and mangrove tour. Discover the backcountry waters and secluded sandbars around the busy island, all while sipping on cold drinks. This guided kayak ecotour takes you into the mangrove isles to spot dazzling marine life before heading to a sandy beach to knock back a few alcoholic or nonalcoholic beverages.Ditch the crowds and enjoy time spent on a secluded sandbar All snorkeling and kayaling equipment is included Wade into the mangroves where more than 500 species live Savor unlimi Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "7506P2": "Soak up sunset views from the water's edge, and admire a perspective many visitors miss, on this Key West sailing tour. Sample up to eight different wines and/or five different beers as you sail, and indulge in a selection of gourmet hors d'oeuvres to accompany them. As you go, learn more from your crew, and enjoy a festive and celebratory way to toast to your trip.Enjoy an experience many Key West visitors miss on this sunset cruise All snacks and beverages are included in the cost for your ease This tour is a great choice for romantic trips or special occasions Crew members are on hand to as Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "7506P1": "Get ready for fun in the sun—and leave all the planning to someone else—on this half-day sailing, kayaking, and snorkeling adventure off the coast of Key West. Kayak through a maze of mangrove-canopied canals and streams, home to a tropical array of birds, rays, sharks, sport fish and more. Then jump into the water for a snorkeling session above a coral reef teeming with marine life. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "5395SUNSET": "Set sail on a replica of the 1851 Schooner America on a cruise from Key West. See the top sights of the city, including Fort Zachary, Mallory Square, and Sand Key Lighthouse from a unique perspective. Your cruise is accompanied by complimentary hors d’oeuvres along with alcoholic and non-alcoholic beverages. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "5264HDRS": "Enjoy an amazing day out on the water in Florida’s Key West with this ultimate adventure tour aboard a catamaran. Spend the day partaking in water sports such as parasailing, jet skiing, snorkeling, and riding on a Banana Boat. Sunbathe on the boat’s spacious deck, or just take in the sights of the Key West area. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "3800P30": "Picture yourself aboard our unique tiki boat, the Lazy Lady, cruising through the crystal-clear waters toward a secluded sandbar. The sun is shining bright, and the air is filled with the scent of salt and sunshine. As you approach the sandbar, the boat glides over shallow waters, revealing stretches of soft, white sand inviting you to explore.Once you anchor, the fun begins! Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "6426SHARKECO": "The whole family can learn more about sharks and other marine wildlife on this boat tour from Key West. Travel on board an eco-friendly, 34-foot catamaran just a few miles off the coast to try your luck spotting dolphins, stingrays, turtles, and birds while you learn more about Key West’s waters than you ever would sailing along. Then watch as the pilot drops bait to draw a variety of sharks right to the edge of the boat.Cold drinks, snacks, and polarized sunglasses are included View lemon, nurse and other shark species from the safety of your catamaran An ideal experience for nature-lovers, b Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "2642P6": "Watch Key West's sunset — a main island attraction — on an evening dinner cruise. Feast on a tropical-themed buffet dinner and sip provided cocktails, beer, wine, and soft drinks as you take in views of the sea, the waterfront, and the sky's warm glow. Live music provides a festive atmosphere, and a cash bar is also available for premium drinks.Key West sunset dinner cruise Enjoy a tropical-themed buffet with several dishes Sip on provided margaritas, rum runners, wine, or beer Watch the sunset from the water — the best vantage point Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "44502P1": "Eat your way around Key West on a food tour of “mom and pop” eateries in the Old Town historic district. Taste seafood, Cuban cuisine, and delicious key lime pie. The walking tour route takes you off typical touristy streets so you can see Key West like a local, listening to insights about the city's food, architecture, and history along the way. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "7812P77": "From local shrimp to the perfect Key lime pie, Key West dining is a food-lover’s dream, but finding authentic flavors can be a challenge in a town packed with touristy restaurants. Discover the very best bites on a gourmet tour that samples a little bit of everything, exploring Key West’s charming neighborhoods, colorful characters, and history along the way.Included tastings feature a wide range of flavors Discover eateries off the tourist trail Visit lesser-known areas for a glimpse of local life Convenient departure point in central Key West Equipment, beverages, and local commentary are handled so you can focus on the water and island scenery. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "328038P8": "See the Key West lagoons in a whole new way. Go on a nocturnal adventure with clear kayaks and LED lights that illuminate the surroundings so you can see underwater. A local guide takes you and a small group to the best spots for a unique and memorable marine life experience lasting about 90 minutes.Experience a memorable nighttime adventure Embark on clear kayaks with LED illumination for a unique adventure Spot wildlife and nature that’s otherwise hard to see Enjoy a more personal experience with a local tour guide Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "18235P1": "Paddle a kayak through mangrove creeks and shallow water on a Key West kayaking tour that offers an up-close look that this unique coastal environment. This guided tour is the perfect way to spot Florida wildlife in a natural habitat.Kayak tour of Key West mangroves Learn about local geology and nature Suited to all ages and skill levels Choice of morning or afternoon departure Dog Friendly Equipment, beverages, and local commentary are handled so you can focus on the water and island scenery. Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "5264DC": "Get ready for fun in the sun—and check off two top experiences in just one trip—on this dolphin-watching and snorkeling tour off the coast of Key West. Departing Key West, look out for dolphins swimming alongside the boat, then jump in for a shallow-water snorkel at the Key West National Wildlife Refuge with many different species of marine life. Relax, feel the warm sea breezes, and select from a variety of refreshing beverages on board the boat.Admire views of the scenery that many Key West visitors don't get Go dolphin-watching and snorkeling on this two-in-one boat tour Complimentary beer, Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
  "2642P16": "Take in rare birds–eye views of Key West on a parasailing adventure over Smathers Beach. With a range of departure times offered throughout the day, this tour is a popular, flexible choice for families. Your guide, who ensures that the small group has a personalized experience, takes photos and videos available for purchase after the trip.Soar over the coastal landscapes of Key West, Florida Keep your eyes peeled for wildlife while in the air Photos and videos of your flight are available to purchase A small group means less time to wait before your flight Ideal for travelers basing in Key West who want a guided Florida Keys experience without coordinating boats, gear, or launch times on their own.",
};

export const getKeyWestTargetedNarrativeDescription = (productCode: string) =>
  KEY_WEST_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as KeyWestTargetedNarrativeDescriptionProductCode
  ];
