export const KONA_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "28456P13",
  "110657P1",
  "190952P1",
  "190952P2",
  "287816P1",
  "2804MKS",
  "8945P14",
  "88002P3",
  "358276P1",
  "26811P1",
  "26811P4",
  "2804PINZHH",
  "5527LUAU",
  "418633P1",
  "207802P1",
] as const;

export type KonaTargetedNarrativeDescriptionProductCode =
  (typeof KONA_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const KONA_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  KonaTargetedNarrativeDescriptionProductCode,
  string
> = {
  "28456P13": "Marvel at the Kona coastline's splendor and the beauty of the Hualalai volcano on this awe-inspiring 60-minute helicopter tour. Begin over ancient Hawaiian Kaloko Fish Ponds and Kailua Bay, then follow Ali'i Drive past Magic Sands Beach and the Captain Cook Monument at Kealakekua Bay before turning inland toward Hualalai's volcanic slopes and Makalawena Beach. Stops include Kaloko Fishpond, Kailua Bay, Ali'i Drive, La'aloa Beach Park, Kealakekua Bay Marine Preserve, Captain Cook Monument. Transportation, equipment, and local commentary are handled so you can focus on Kona's coastline, volcanic highlands, coffee country, and island landmarks. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "110657P1": "Explore the ancient volcanoes and cascading waterfalls of the Kohala Mountains on a thrilling private helicopter tour from Kona. With up to 1 hour 15 minutes in the air, this flight covers all seven windward valleys of Kohala in one itinerary. Stops include Kohala Mountains, Waipio Valley, Waimanu Valley, Honokane Nui, Kohala Coast. Enjoy spectacular aerial views as you fly over Waipio Valley and Waimanu Valley, swoop over Honokane Nui and Kohala volcano, then circle back along the coast. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "190952P1": "From the Kona side of the Big Island, the soaring sea cliffs, cascading waterfalls, and rainforest-clad headlands of the Kohala Coast are even more impressive when viewed from above. Admire the scenery as you fly overhead in a luxury helicopter, swoop over the Kohala Mountains, spot ancient Hawaiian settlements from the air, and enjoy magnificent ocean views. Stops include Kohala Coast, Kohala Mountains, Kohala Waterfalls, Waikoloa Heliport. Transportation, equipment, and local commentary are handled so you can focus on Kona's coastline, volcanic highlands, coffee country, and island landmarks. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "190952P2": "The natural wonders of the Kohala Mountains and Laupahoehoe Nui Waterfall are only reachable on foot—or by helicopter from the Kona side of the Big Island. Fly over the ever-changing landscapes of the Kohala Coast, admiring volcanic mountains, lush rainforest, and lava fields from above. Stops include Kohala Coast, Kohala Mountains, Laupahoehoe Nui Waterfall, Exclusive Waterfall Landing. Fly between 1,200-foot cliffs and land at a magnificent spot by a waterfall where you can get out to enjoy the views. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "287816P1": "In Kona, touring the Big Island of Hawaii loses a little magic when you are crowded onto a bus with lots of strangers. This private tour ensures a personalized and uncrowded experience by taking you around the island in the company of just your group and a guide. Stops include Kailua-Kona, Kona Coffee Country, Scenic Coastal Lookouts, Big Island Highlight Stops. You'll see the island's best attractions at a pace that fits your interests, with pickup included for a full-day private sightseeing route. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "2804MKS": "Experience big skies and incredible nighttime views on this Mauna Kea stargazing trip with a small group departing from the Kona area. Enjoy a warm pre-trip picnic, then ride in a 4x4 luxury van to the summit of the Big Island's tallest peak. Stops include Courtyard King Kamehameha's Kona Beach Hotel, Maunakea Visitor Information Station, Mauna Kea Summit, Stargazing Session. After admiring a sunset view, continue down to 9,000 feet for guided telescope stargazing under some of the clearest night skies on Earth. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "8945P14": "From Kona-accessible Big Island heights, join one of the world's premier stargazing locations with an astronomer and professional astrophotographer. See the night sky like never before through a Unistellar EV2 Telescope, and leave with stunning photos of your group with galaxies, stars, and constellations as the backdrop. Stops include Mauna Kea Access Road, Stargazing Site, Astrophotography Session. Transportation, equipment, and local commentary are handled so you can focus on Kona's coastline, volcanic highlands, coffee country, and island landmarks. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "88002P3": "From Kona-side departures, travel to the 13,803-foot peak of Mauna Kea—Hawaii's highest point and a popular spot for star-gazing. Stop for dinner at the Onizuka Astronomy Complex, then arrive at the summit in time to watch the sunset. Stops include Kailua-Kona, Onizuka Astronomy Complex, Mauna Kea Summit, Night Star Photo Session. As dark sets in, enjoy a stargazing session and receive a complimentary night star photo to take home. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "358276P1": "Get off the tourist track and experience the wildest side of the Big Island on this small-group ATV tour from the Kona south side. Don goggles and a helmet and drive your ATV over rugged ranch lands, craggy lava flows, and ancient forests, stopping along the way at lookout points to take photos and listen to commentary from your guide. Stops include South Kona Ranch Lands, Lava Flow Trails, Ancient Forest Track, Scenic Lookout Points. Transportation, equipment, and local commentary are handled so you can focus on Kona's coastline, volcanic highlands, coffee country, and island landmarks. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "26811P1": "See the Big Island from a different angle on this 9-line zipline adventure near Kona that takes you over tree tops, waterfalls, and rivers. Four dual lines let travelers zip side by side across the course. Stops include Umauma Experience Check-In, Waterfall Zipline Course, Dual Racing Lines, Pacific Ocean Viewpoint Platforms. Platforms open toward Pacific Ocean views as the route moves through the Umauma landscape. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "26811P4": "Spend time exploring the Big Island’s Hamakua Coast on this off-road excursion accessible from Kona-side itineraries. Enjoy complimentary lessons on a practice track if needed, then cruise along picturesque coastal trails on 4x4 Honda ATVs or UTVs. Stops include Practice Track, Hamakua Coast Trails, Mauna Kea Viewpoint, Waterfall Swim Stop. Enjoy magnificent views of Mauna Kea and the Pacific Ocean, stop at scenic spots for memorable photos, and cool off with a waterfall swim when conditions allow. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "2804PINZHH": "Join the Hidden Craters Hike for a Big Island off-road climb and hike up the cool and misty slopes of Hualalai volcano above Kona. 4 Wheel Drive vans carry you up most of the way to 6,000 feet elevation before you begin your on-foot ascent through lava flows and a forest full of native birdsong. Stops include Hawaii Forest & Trail Headquarters, Hualalai Volcano Slopes, Native Cloud Forest Trail, Volcanic Craters and Fissures, Lava Tube. This adventure tour teaches you all about the best of Kona's volcanic highlands. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "5527LUAU": "Sort out your entertainment and dinner plans for the night with this popular Kona luau featuring shows from around Polynesia, with performances ranging from Fijian war dances to traditional Hawaiian hula. You and the whole family feast on a delicious Hawaiian buffet that pairs beautifully with the event’s open bar. Stops include Island Breeze Luau Grounds, Hawaiian Buffet Dinner, Polynesian Cultural Show, Samoan Fire Knife Dance. The night is capped off by the thrilling action of a Samoan fire and knife dance. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "418633P1": "Explore Waipio on horseback from a Kona-area Big Island itinerary with this small-group guided ride through a working cattle ranch and farm. Follow your guide through a traditional land division that stretches from the mountain to the ocean, while enjoying the views, looking for wildlife, and learning about the ranch's history and Hawaiian land stewardship. Stops include Waipio Ranch Check-In, Working Cattle Ranch Trails, Mountain Ocean Viewpoint, Traditional Land Division Ride. Transportation, equipment, and local commentary are handled so you can focus on Kona's coastline, volcanic highlands, coffee country, and island landmarks. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "207802P1": "Hawaii is renowned for its coffee and chocolate, and this Kona farm tour takes you behind the scenes of a traditional plantation. Learn how coffee is grown and produced, discover the chocolate-making journey from bean to bar, and have a chance to sample both delicacies. Stops include Kona Coffee Orchard, Coffee Processing Area, Chocolate Making Demonstration, Farm Gift Shop. At the end of the tour, spend as much time as you like browsing unique gifts made from farm ingredients. Ideal for visitors basing in Kona who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
};

export const getKonaTargetedNarrativeDescription = (productCode: string) =>
  KONA_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as KonaTargetedNarrativeDescriptionProductCode
  ];
