export const KYOTO_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "92136P55",
  "92136P37",
  "92136P49",
  "21490P11",
  "285124P1",
  "5924KYOCUSTOM_FULL",
  "407697P2",
  "374249P4",
  "103013P3",
  "38922P3",
  "63670P28",
  "92281P2",
  "293458P17",
  "5522662P20",
] as const;

export type KyotoTargetedNarrativeDescriptionProductCode =
  (typeof KYOTO_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const KYOTO_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  KyotoTargetedNarrativeDescriptionProductCode,
  string
> = {
  "92136P55": "In Kyoto, this private six-hour circuit pairs a government-licensed guide with a published list of neighborhood stops rather than a fixed coach loop. The group chooses three or four sights such as Nijo Castle, Higashiyama, Gion, Kiyomizu-dera Temple, or Fushimi Inari-taisha Shrine, then moves between them on foot and public transport. Guide entry fees apply only to the listed What to Expect sights; meals and most tickets stay separate. The meeting is on foot inside the designated Kyoto area, not in Osaka. The format suits visitors who want licensed commentary without assembling bus and train transfers independently. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Nijo Castle, Higashiyama, Gion, and Kiyomizu-dera that define this private city window rather than a Nara add-on.",
  "92136P37": "In Kyoto, this private four-hour circuit pairs a government-licensed guide with a published half-day stop list rather than a full coach loop. The group chooses two or three sights such as Nishiki Market, Kiyomizu-dera Temple, Gion, Nijo Castle, or Fushimi Inari-taisha Shrine, then moves between them on foot and public transport. Hotel-front pickup on foot is listed; a private car is an optional upgrade booked in advance. Guide entry fees apply only to the listed What to Expect sights. The format suits visitors who want a compact licensed window without assembling a full-day temple circuit. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Nishiki Market, Kiyomizu-dera, and Gion that define this half-day rather than an Arashiyama transfer.",
  "92136P49": "In Kyoto, this private six-hour charter pairs a licensed guide with a vehicle and door-to-door hotel transfers instead of public-transport walking. The group chooses three or four published sights such as Fushimi Inari-taisha Shrine, Nijo Castle, Kiyomizu-dera Temple, Nishiki Market, Gion, the Kyoto Imperial Palace, or Kinkaku-ji. Pickup is listed for Kyoto-area hotels or Kyoto Station, not Osaka, Kobe, or Nara. Entrance fees, lunch, and personal expenses stay separate. The format suits visitors who want licensed commentary and a private van without navigating the city bus network. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Fushimi Inari, Nijo Castle, and Kiyomizu-dera that define this vehicle window rather than a Nara park add-on.",
  "21490P11": "In Kyoto, this private walking outing lets the group pick a four-hour or eight-hour window and two to four published stops instead of a scripted coach loop. The listed options include Kinkaku-ji, Fushimi Inari-taisha Shrine, Nijo Castle, Gion, Kiyomizu-dera Temple, Nishiki Market, Tenryu-ji Temple, and the Kyoto Imperial Palace, with Philosopher's Walk and Pontocho as pass-bys. Hotel meetup is included; entrance fees and transport fares stay separate. Public transportation or taxis may be used between sites. The format suits first-time visitors who want a licensed walk without booking three district tours separately. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Kinkaku-ji, Fushimi Inari, and Nijo Castle that shape this outing rather than a Nara day.",
  "285124P1": "In Kyoto, this private eight-hour circuit starts at Kitaoji Station and covers ten published sights with a guide handling district transfers for one group of up to seven. The listed route includes Kinkaku-ji, Arashiyama Bamboo Forest Street, Tenryu-ji Temple, Togetsukyo Bridge, Arashiyama Kimono Forest, Fushimi Inari-taisha Shrine, Kiyomizu-dera Temple, Sannenzaka and Ninenzaka, Yasakanoto, and Gion. Navigation stays with the guide so the day can hold both the north-city pavilion and the east-side temple lanes. The format suits visitors with a short stay who want a single guided sweep rather than assembling ten tickets independently. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Kinkaku-ji, Arashiyama, Fushimi Inari, and Kiyomizu-dera that define this outing rather than an Osaka transfer.",
  "5924KYOCUSTOM_FULL": "In Kyoto, this private custom day builds a half-day or full-day route from a published UNESCO stop list rather than a fixed coach loop. The listed options include Kinkaku-ji, Nijo Castle, Fushimi Inari-taisha Shrine, Tenryu-ji Temple, and Kiyomizu-dera, with hotel pickup inside Kyoto city. A professional English-speaking guide travels by public transport or a private vehicle depending on the selected option, and lunch is listed on the full-day window. Pickup outside Kyoto city is not offered. The format suits first-time visitors who want a tailored temple day without assembling shrine and castle timing independently. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Kinkaku-ji, Nijo Castle, Fushimi Inari, and Kiyomizu-dera that shape this outing rather than a Nara park add-on.",
  "407697P2": "In Kyoto, this private six-to-ten-hour charter leaves a hotel lobby for a combined Kyoto and Nara day with an English-speaking driver-host and an air-conditioned vehicle. The published Nara window can include Todai-ji Temple, Nara Park, and Kasuga-Taisha Shrine, with Kinkaku-ji available on the Kyoto side of the same booking. Parking fees are listed; lunch and some admissions stay separate. Hotel pickup and drop-off are published from Kyoto so the group can stay with the two-city route rather than assembling express-train transfers. The format suits visitors who want a guided Kyoto-to-Nara day without self-driving. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Kinkaku-ji, Todai-ji, and Nara Park that define this outing rather than an Osaka castle add-on.",
  "374249P4": "In Kyoto, this private van day can hold Osaka, Nara, or both, with flexible pickup listed from Kyoto as well as Osaka or Nara hotels. An English-speaking guide and an air-conditioned Nissan van keep one group on published stops such as Todai-ji Temple, Nara Park, Kasuga-Taisha Shrine, and Osaka Castle. Fuel and highway fees are included; Todai-ji entry and meals stay separate. The published window is about six hours, with pickup and drop-off allowed at different cities. The format suits visitors basing in Kyoto who want a guided Nara or Osaka day without renting a highway car. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Todai-ji, Nara Park, and Osaka Castle that shape this outing rather than a Fushimi Inari walking loop.",
  "103013P3": "In Kyoto, this small-group bike or e-bike day leaves JR Saga-Arashiyama Station for five published highlights: Kinkaku-ji, Kiyomizu-dera Temple, Fushimi Inari-taisha Shrine, Arashiyama Bamboo Forest, and Gion. A cycling guide, bike, helmet, lunch, snacks, and listed admission fees are included for the seven-to-eight-hour loop covering up to 44 kilometers. The ride ends back at Saga-Arashiyama Station. Hotel pickup is not listed. The format suits visitors who want a guided bike window across shrine forest and downtown districts without renting independently. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Kinkaku-ji, Kiyomizu-dera, Fushimi Inari, and Arashiyama that define this ride rather than a Nara park add-on.",
  "38922P3": "In Kyoto, this small-group e-bike outing leaves NORU Kyoto Bike Tours in Kamigyo for Arashiyama Bamboo Forest and nearby temple lanes such as Adashino Nenbutsu-ji. An electric-assist bike, helmet, temple fees, water, and snacks are included for the published 4-hour-15-minute loop of about 25 kilometers. The group is capped at eight and returns to the Cycle Village meeting point. The route stays on bamboo groves and quieter temple approaches rather than a five-highlight city cram. The format suits visitors who want a guided Arashiyama ride without renting independently. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Arashiyama Bamboo Forest and Adashino Nenbutsu-ji that shape this outing rather than a Fushimi Inari hike.",
  "63670P28": "In Kyoto, this guided three-hour hike leaves the paved Fushimi Inari-taisha corridor for forest trails, a bamboo stand, a small shrine off the usual tourist path, and a viewpoint toward Fushimi-Momoyama Castle. A guide handles routing so the group can stay on unpaved approaches rather than only the lowest torii tunnel. The published window is about three hours on mixed forest and shrine paths. The format suits visitors who want a guided hike at the shrine without assembling a self-guided mountain loop. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Fushimi Inari-taisha, the bamboo-forest trail, and the Fushimi-Momoyama Castle viewpoint that define this outing rather than an Arashiyama bike add-on.",
  "92281P2": "In Kyoto, this private one-hour photography session pairs a professional photographer with a chosen neighborhood window such as Yasaka Shrine, Gion, or Higashiyama. About 50 edited images are listed after the shoot, with photographer commentary on Kyoto history and culture during the walk. Kimono rental and transport fees are not treated as inclusions. The meeting point is confirmed when booking. The format suits visitors who want guided location shooting without assembling a self-directed photo walk. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Yasaka Shrine, Gion, and Higashiyama that shape this session rather than a full temple-hopping day.",
  "293458P17": "In Kyoto, this two-hour cultural session at Nishiki Orizuruya pairs kimono dressing and simple hairstyling with a matcha ceremony and seasonal wagashi. A licensed guide covers tea-room etiquette and matcha preparation, with an optional calligraphy window in the same tea house near Nishiki Market. The group is capped at ten. Hotel pickup is not listed; the meeting point is a short walk from Hankyu Karasuma or subway Shijo. The format suits visitors who want a guided tea-and-kimono window without booking a full temple circuit. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Nishiki Orizuruya and Nishiki Market that define this session rather than a Fushimi Inari hike.",
  "5522662P20": "In Kyoto, this guided coach day leaves Hotel Keihan Kyoto Grande for a published ten-hour circuit of Arashiyama Bamboo Forest, Kinkaku-ji, Nijo Castle, Kiyomizu-dera Temple, and Fushimi Inari-taisha Shrine. Ticket-inclusive or ticket-excluded packages are listed so admission at the Golden Pavilion, Kiyomizu-dera, and Nijo Castle can be added or left separate. The tour ends at Fushimi Inari-taisha, with directions back to Kyoto Station given on site. Arrive at least ten minutes before departure. The format suits visitors who want a coordinated five-stop day without assembling coach and ticket timing independently. Meeting points are confirmed at booking in Kyoto, and the itinerary stays on Arashiyama, Kinkaku-ji, Nijo Castle, Kiyomizu-dera, and Fushimi Inari that define this outing rather than a private walking custom day.",
};

export const getKyotoTargetedNarrativeDescription = (
  productCode: string
) =>
  KYOTO_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as KyotoTargetedNarrativeDescriptionProductCode
  ];
