export const LIMA_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "20336P1",
  "155286P1",
  "148831P28",
  "85155P2",
  "89775P1",
  "226342P3",
  "141439P1",
  "17020P17",
  "5207LIMBIKE",
] as const;

export type LimaTargetedNarrativeDescriptionProductCode =
  (typeof LIMA_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const LIMA_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  LimaTargetedNarrativeDescriptionProductCode,
  string
> = {
  "20336P1": "In Lima, this private half-day circuit covers Miraflores, a San Isidro pass, and Centro Historico de Lima with a dedicated guide and vehicle for one group. The published route walks the Malecon, Love Park, and Kennedy Park before the historic-center squares, then offers a guided visit to the San Francisco Convent and catacombs or Huaca Pucllana. Snacks, a drink, and the San Francisco admission ticket are listed on the product page. Morning, afternoon, or early evening departures are offered from the confirmed Lima accommodations. The format suits visitors who want a guided city window without assembling taxi, ticket, and neighborhood timing independently. Meeting points are confirmed at booking in Lima, and the itinerary stays on Miraflores, San Isidro, and Centro Historico de Lima that define this private outing rather than a Barranco night add-on.",
  "155286P1": "In Lima, this private half-day city tour keeps one group in an air-conditioned vehicle for Barranco, Miraflores, and the historic center. A dedicated guide handles neighborhood pacing so stops can run longer at a plaza or shorter at a pass-by rather than a fixed coach loop. Hotel pickup is listed for Miraflores, Barranco, and San Isidro; transfers from outside that axis are listed as a USD 20 add-on. Museum and attraction tickets are not treated as a guaranteed inclusion on the published page. The format suits visitors who want a flexible guided overview without booking three district walks separately. Meeting points are confirmed at booking in Lima, and the itinerary stays on Miraflores, Barranco, and the Historic Center of Lima that shape this private circuit rather than a Palomino Islands or desert add-on.",
  "148831P28": "In Lima, this small-group evening starts at the San Francisco Monastery catacombs, continues through the historic center around Plaza de Armas, and ends at the Magic Water Circuit. Air-conditioned hotel pickup plus tickets to the catacombs and the water show are included, with a published 4:00 p.m. start from Barranco, Miraflores, San Isidro, or downtown Lima. The group is listed with a maximum of 15. Commentary stays on the monastery crypts and the illuminated colonial squares rather than a daytime museum hop. The format suits visitors who want a guided night window without buying catacomb and fountain tickets independently. Meeting points are confirmed at booking in Lima, and the itinerary stays on San Francisco Monastery, Plaza de Armas, and the Magic Water Circuit that define this evening.",
  "85155P2": "In Lima, this private full-day outing leaves the coastal districts for San Pedro de Casta and the Marcahuasi Stone Forest. A guide covers the off-road approach and the high plateau walk among the stone formations, with breakfast listed on the product page. Pickup is published for Lima Metropolitana so the group can stay with the plateau rather than self-driving mountain roads. The day is aimed at visitors who want a guided jeep-and-hike window without renting a 4x4 independently. Altitude and walking time still depend on conditions on the plateau. Meeting points are confirmed at booking in Lima, and the itinerary stays on San Pedro de Casta and the Marcahuasi Stone Forest that shape this inland day rather than a city-plaza or island add-on.",
  "89775P1": "In Lima, this private 4x4 outing heads north to Lomas de Ancón for guided dune driving and sandboarding. Hotel pickup, sandboarding equipment, a certified instructor, and snacks are included after a safety briefing, and no prior sandboard experience is required. The published route stays on the Ancón reserve dunes rather than a long southbound Huacachina transfer. Airbnb pickups are asked to stay within a 20-mile radius of Lima. The format suits visitors who want a guided off-road window close to the capital without booking a 17-hour desert coach. A local dessert stop on the return is mentioned on the product page. Meeting points are confirmed at booking in Lima, and the itinerary stays on Lomas de Ancón and Ancón that define this sandboard day rather than a Paracas boat or vineyard add-on.",
  "226342P3": "In Lima, this long guided day runs south to Islas Ballestas, an Ica wine and pisco tasting, and Huacachina for a two-hour dune-buggy and sandboarding window. Hotel or hostel pickup is listed for Barranco, Miraflores, and San Isidro, with bilingual guiding and a published 22-person cap. Boat time at Ballestas and the desert activity are included; meals and some rentals are listed separately on the product page. The route is aimed at visitors who want a single guided coastal-and-desert day without booking the boat, tasting room, and dunes independently. Sunset timing at Huacachina is listed with the dune-buggy window. Meeting points are confirmed at booking in Lima, and the itinerary stays on Islas Ballestas, Ica, and Huacachina that define this outing rather than a Nazca overflight add-on.",
  "141439P1": "In Lima, this small-group day follows the Supe Valley to the Caral Archaeological Zone, then continues to Barranca for the published beach-town stop. Round-trip transport, site admission, a bilingual guide, and lunch are listed so the group can stay with the pyramids rather than assembling highway and ticket logistics independently. The guide covers unmarked ruins at what the product page calls the oldest center of civilization in the Americas. Pickup is published from multiple Lima locations. The format suits visitors who want a guided Indigenous-history day without self-driving the north coast. Meeting points are confirmed at booking in Lima, and the itinerary stays on the Caral Archaeological Zone and Barranca that shape this outing rather than a Pachacamac half-day add-on.",
  "17020P17": "In Lima, this small-group half-day heads south to Pachacamac for the site museum and the Temple of the Sun. Air-conditioned private transport, a professional guide, bottled water, and entry tickets are included, with the group capped at 10. The published route stays on the adobe sanctuary and museum rather than adding Barranco or a historic-center walk. Round-trip pickup from Lima is listed when booking. The format suits visitors who want a guided Indigenous sanctuary window without buying tickets and arranging the desert-coast transfer independently. Shade is limited on the adobe terraces, so sun protection is useful on the published walk. Meeting points are confirmed at booking in Lima, and the itinerary stays on the Pachacamac Site Museum and Temple of the Sun that define this outing rather than a Caral valley day.",
  "5207LIMBIKE": "In Lima, this small-group coast ride starts in Miraflores, drops toward Chorrillos, then follows Barranco and Love Park on protected bike paths. Bicycles, helmets, and a cycling guide are included. The published meeting point is Calle Alcanfores 425 in Miraflores, with the end at Church Virgen Milagrosa. Commentary covers coastal neighborhoods and street art rather than a historic-center walking loop. The format suits visitors who want a guided bike outing without renting independently or navigating Lima traffic alone. The published duration is about three hours and fifteen minutes on mixed coastal path and neighborhood streets. Meeting points are confirmed at booking in Lima, and the itinerary stays on Chorrillos, Barranco, Love Park, and Miraflores that shape this coastal ride rather than a Huaca Pucllana or downtown plaza add-on.",
};

export const getLimaTargetedNarrativeDescription = (
  productCode: string
) =>
  LIMA_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as LimaTargetedNarrativeDescriptionProductCode
  ];
