export const LONDON_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "8607P1",
  "106826P1",
  "60273P32",
  "349592P2",
  "103194P1",
  "12389P8",
  "306564P1",
  "110975P32",
  "13106P1",
  "62043P1",
  "2452L02",
  "75760P71",
  "6295LOBLEGFD",
  "75760P69",
  "24338P83",
  "3862BICYCLE",
  "40046P15",
  "5936WHOWALK",
] as const;

export type LondonTargetedNarrativeDescriptionProductCode =
  (typeof LONDON_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const LONDON_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  LondonTargetedNarrativeDescriptionProductCode,
  string
> = {
  "8607P1": "Marvel over royal monuments, architectural masterpieces and iconic landmarks on this 3-hour walking tour of London. Enjoy the undivided attention of your private guide as you stroll around Covent Garden, Leicester Square and Piccadilly Circus; snap photos of Trafalgar Square, Westminster Abbey, and Big Ben; and stand in awe before the magnificent Buckingham Palace. Stops include Westminster Abbey, Big Ben, Buckingham Palace, Trafalgar Square, Covent Garden, Piccadilly Circus. For the full experience, upgrade to include a visit to St Paul’s Cathedral, Tower Bridge, and the Tower of London. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "106826P1": "Optimize your time in the British capital on a private day tour, popping between landmarks by traditional black cab for an authentic London experience. Benefit from your guide’s personalized recommendations to add additional stops according to your interests. Stops include Buckingham Palace, Westminster Abbey, London Eye, Tower of London. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "60273P32": "In London, this private walking tour traces Winston Churchill's life through his childhood homes, favorite tailors, and cigar shops. Cross essential London sights such as 10 Downing Street and the Houses of Parliament, then use skip-the-line entry to the Churchill War Rooms for a focused visit without waiting. Stops include Churchill War Rooms, 10 Downing Street, Houses of Parliament. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "349592P2": "With 1,000 years of history, there’s only one way to explore the Tower of London: with a guide demystifying it all. On this private tour, you’ll explore this castle-turned-prison, discovering its dark, inner workings and, of course, its Crown Jewels. Stops include Tower of London, Crown Jewels, Tower Bridge. With your private guide, you’ll walk in the footsteps of royalty—and like royalty, you’ll get to skip the ticket lines, enjoying this iconic landmark in style. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "103194P1": "Discover London landmarks linked to the Beatles, Rolling Stones, Queen, and other rock legends on a private black cab music tour. Choose the tour start time and duration and meet your music industry expert cabbie at your hotel. Stops include Abbey Road, Trident Studios, Central London. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "12389P8": "In London, Thanks to growing conditions similar to those in northern France, southern England’s burgeoning wine scene has never been more promising or accomplished—and this private tour makes it easy to sample and discover more. After pickup from a location of your choosing, you’ll travel in a comfortable minibus to at least three of Kent’s top wineries, where you’ll tour the vineyards and cellars and do plenty of tasting. Stops include Tonbridge Station, Kent Vineyards, English Wine Country. The tour also includes a pub or picnic lunch, per your preference. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "306564P1": "In London, Pick from a range of itineraries, including an East End tour, a Soho and Chinatown tour, and more. Whichever you choose, you can look forward to rubbing shoulders with locals and indulging in a range of top-tier eats. Stops include Borough Market, Soho, East End, Chinatown. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "110975P32": "In London, Start at SoHo, Chinatown, and Westminster before taking the tube to the lively Notting Hill neighborhood. Stroll through Portobello Road Market, savor a classic English tea and pastry, and see filming locations from the Hugh Grant and Julia Roberts movie, Notting Hill. Stops include Soho, Chinatown, Westminster, Notting Hill, Portobello Road Market. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "13106P1": "In London, Discover the cultural hub and maritime center of Greenwich on a full-day small-group walking tour including lunch. Step aboard the legendary Cutty Sark, visit the home of Greenwich Mean Time at the Greenwich Royal Observatory, visit the recently-renovated Queen's House, and tour the National Maritime Museum and the Old Royal Naval College. Stops include Cutty Sark, Royal Observatory Greenwich, Queen's House, National Maritime Museum, Old Royal Naval College, Greenwich Market. Browse for bargains at the lively Greenwich market, then tuck into a traditional pub lunch overlooking the River Thames. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "62043P1": "A short stay in London can still cover the capital’s key landmarks. Soak up the key sights in just one action-packed day on this guided small-group walking tour. Stops include Westminster Abbey, Buckingham Palace, Thames River, Tower of London. Then, cruise the Thames River on a comfortable riverboat to the Tower of London where you can delve into British history. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "2452L02": "Tick off the British capital’s most recognizable landmarks on this attraction-packed London tour. Explore St. Paul’s Cathedral, then make a photo stop at Westminster Abbey. Stops include St. Paul's Cathedral, Westminster Abbey, Buckingham Palace, Tower of London, Thames River. Watch the Changing of the Guard at Buckingham Palace and visit the Tower of London, where you'll have free time for lunch (own expense). Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "75760P71": "With such a high concentration of world-famous attractions, Westminster is an essential stop on any London sightseeing itinerary. After a walking tour of the borough’s major attractions, descend into the Churchill War Rooms to learn the secrets of the famous leader as he strategized during World War II. Stops include Westminster Abbey, Big Ben, Buckingham Palace, Churchill War Rooms. This landmark-packed tour is perfect for history buffs looking for a manageable but extensive tour to fit into a busy schedule. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "6295LOBLEGFD": "See the iconic royal sights of London on a full-day tour that showcases the best of the capital—a combination of two popular sightseeing experiences. Witness the Changing of the Guard ceremony outside Buckingham Palace, cruise along the Thames River to central London, an then meet an iconic Beefeater during a visit to the Tower of London. Stops include Buckingham Palace, Thames River, Tower of London. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "75760P69": "See London's most famous landmarks on a half-day tour that combines a Westminster walking tour with a Thames River sightseeing cruise. Skip the hassle of navigating as you follow your guide past attractions such as Buckingham Palace, Trafalgar Square, Big Ben, and Westminster Abbey. Stops include Buckingham Palace, Trafalgar Square, Big Ben, Westminster Abbey, Thames River. The walking tour ends with drop-off at the Thames River cruise for another perspective on London from the water. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "24338P83": "Combine a guide-led visit to the Tower of London with a sighseeing cruise along the River Thames on this two-in-one tour. Meet your guide at Parliament Square before hopping on a riverboat along the Thames for a new view on the London skyline. Stops include Parliament Square, Thames River, Tower of London, Crown Jewels. Then, hop off at the Tower of London, where you’ll explore the famous monument, which dates to 1066, and houses the Crown Jewels. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "3862BICYCLE": "Explore London's rich heritage and fabulous architecture in the open air—on a bicycle. With an experienced guide leading the way, you'll cycle from Covent Garden's vibrant atmosphere to the royal splendor of Buckingham Palace, from Westminster, to the architectural grandeur of St. Paul's Cathedral and beyond. Stops include Big Ben, Houses of Parliament, Westminster Abbey, Buckingham Palace, Covent Garden, St. Paul's Cathedral. Throughout your ride, your guide will share fascinating narratives about the city, covering everything from its moments of triumph to its notorious chapters and all its intrigue in between. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "40046P15": "London’s East End is the epicenter of the city’s vibrant street art scene, and the stomping ground of legendary street artists such as Shepard Fairey, Eine, and Banksy. This small-group walking tour will take you through East London’s coolest neighborhoods, where you’ll discover colorful street art, learn about the notorious Jack the Ripper, stroll down Brick Lane, and visit the famous Spitalfields Market. Stops include Shoreditch, Brick Lane, Spitalfields Market. Local commentary and route logistics are handled so you can focus on royal landmarks, river views, and neighborhood walking or cycling highlights. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
  "5936WHOWALK": "Step into the universe of Doctor Who on this walking tour of London’s famous filming locations. Wander through areas like Borough Market and Southwark with an expert guide, stopping at iconic sites such as Shakespeare’s Globe Theatre. Stops include Borough Market, Southwark, Shakespeare's Globe Theatre. Hear fascinating behind-the-scenes stories about the making of the beloved series and its many Doctors, from classic episodes to modern adventures. Ideal for visitors basing in London who want a guided city experience without coordinating Tube routes, attraction tickets, or landmark timing on their own.",
};

export const getLondonTargetedNarrativeDescription = (
  productCode: string
) =>
  LONDON_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as LondonTargetedNarrativeDescriptionProductCode
  ];
