export const MAUI_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "5501HASKY",
  "5069WEST60",
  "5069COMP60",
  "7029OGGHAN",
  "5069DOM",
  "7029OGGVOY",
  "326167P1",
  "320015P2",
  "64708P2",
  "200419P2",
  "105668P1",
  "104589P11",
  "2360M5",
  "62707P3",
  "241329P1",
  "2784P8",
  "3087MOLL",
  "166701P1",
  "124957P2",
  "5069WEST45",
] as const;

export type MauiTargetedNarrativeDescriptionProductCode =
  (typeof MAUI_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const MAUI_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  MauiTargetedNarrativeDescriptionProductCode,
  string
> = {
  "5501HASKY": "Travel Maui's famous Road to Hana in style, enjoying a luxurious small-group sightseeing road trip by Limo-Van and a stunning helicopter flight back, during this 6-hour adventure. Sit back and relax inside your plush Limo-Van on the way to Hana, stopping at the Hawaiian hamlet of Ke\u2019anae, and at a gorgeous waterfall, where you\u2019ll have time to swim (conditions permitting ). Stops include Hana Highway - Road to Hana, Upper Waikani Falls, Hana. You\u2019ll also enjoy a beachside lunch before eventually boarding a helicopter for an incredible 36-minute flight above Haleakala Crater and the island\u2019s rugged coast. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "5069WEST60": "This Maui helicopter tour is packed with jaw-dropping sights, from waterfalls tumbling through hidden valleys to the tallest sea cliffs of Earth. During this Maui helicopter tour of the West Maui Mountains and Molokai, visitors will soar above mist shrouded ridgelines that are covered in native ferns, and get bird\u2019s eye views of parts of the island that are only accessible by air. Stops include West Maui Mountains, Moloka\u2018i. Crane your neck up as a 1,100-foot (335-meter) waterfall spills all the way down towards the sea, or casually look down as the blue Pacific rolls right underneath your feet. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "5069COMP60": "Maui is an island that\u2019s best seen by air, and on this complete island Maui helicopter tour, visitors soar above valleys and waterfalls that are otherwise inaccessible. Fly deep inside the West Maui Mountains where there aren\u2019t even any trails, and gaze upon the colorful cinder cones of Haleakala Crater. Stops include Haleakala Crater, Hana Highway - Road to Hana, West Maui Mountains. Off the coast of Hana, watch as waterfalls tumble their way directly into the sea, and see hidden coves and white sand beaches you never even knew were there. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "7029OGGHAN": "Drink in the lush beauty of Maui\u2019s Hana Rainforest and northern shores from the air on a scenic helicopter flight, including a stop at the Wailua Valley. Glide over the jungle-clad north coast, passing beauty spots like the \u2018Jaws\u2019 surf break beach and Jurassic Rock. Stops include Hana Rainforest, Hana Highway - Road to Hana. Then, land in an untouched spot in the verdant Wailua Valley, stepping out to explore the tropical vegetation and admire views over waterfalls and canyons before your return flight. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "5069DOM": "Soar above scenic Maui and Molokai on this unforgettable \u2018doors off\u2019 helicopter flight. Feel the island breeze in your hair as you enjoy the only doors-off helicopter flight on Maui, gliding above scenic vistas of towering waterfalls, sparkling rainbows, and unspoiled valleys thick with rainforest. Stops include Molokai, West Maui Mountains. Transportation, equipment, and local commentary are handled so you can focus on Maui's volcanoes, waterfalls, reefs, and cultural landmarks. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "7029OGGVOY": "Soar above two scenic Hawaiian Islands on a helicopter tour of Maui and Molokai from Kahalui. Watch surfers riding Maui\u2019s breaking waves as you fly towards Molokai\u2019s sheer coastal cliffs, capture aerial images of Kahiwa Falls and the isolated North Shore, then turn towards the emerald green Halawa Valley. Stops include Molokai, Halawa Valley, Iao Valley State Park, Honokohau Falls. Watch for whales and dolphins as you cross Pailolo channel, swoop over Maui\u2019s lush rainforest canopy and explore Iao Valley State Park, then enjoy views of Honokohau Falls and Haleakala volcano on your return flight to Kahalui. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "326167P1": "See the best of Maui on this customizable, private Road to Hana adventure, where the day unfolds at your pace. Stop at stunning spots like Pua'a Ka'a, Wai'anapanapa State Park, Ke\u2018anae Point, Upper Waikani Falls, and Koki Beach, with time to explore volcanic beaches, waterfalls, and dramatic coastal views. Stops include Paia, Road to Hana, Ke'anae Peninsula, Wai'anapanapa State Park, Hana. Transportation, equipment, and local commentary are handled so you can focus on Maui's volcanoes, waterfalls, reefs, and cultural landmarks. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "320015P2": "Explore Maui on this private VIP Backstage Pass Experience that gets farther off the beaten path than typical organized tours. Organized tours are usually helpful for getting oriented, but they hardly ever truly get off the beaten path. Stops include Kahului, Road to Hana, Waterfall Swim Spot, Hana Coast, Black Sand Beach. This private VIP Backstage Pass Experience offers the chance to choose your own itinerary for day-long trips to Maui's most off-the-beaten-path spots, or to sit back and relax and let your guides do all the work and planning. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "64708P2": "Explore Maui's rugged terrain during this thrilling ATV tour. After an orientation to the vehicle, take off for the top of the valley, where you can view the waterfalls from a distance. Stops include West Maui Mountains, Scenic Viewpoint. Traveling via ATV allows you access to parts of the valley that traditional tour vehicles can't reach. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "200419P2": "Enjoy unparalleled coastal views as you soar through jungle heights during this small-group zip lining excursion in Maui. Get hands-on assistance from your guide as you ride down six panoramic, sky-high lines. Stops include Kapalua Ziplines, Suspension Bridge, Dual Zipline Course. Tours include a fast-paced ATV ride deep into the rainforest and a trek over Hawaii's longest suspension bridge. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "105668P1": "Discover the beauty of Maui\u2019s waterfalls during a half-day tour. Meet your guide at a departure point for a small-group excursion that includes several waterfalls and optional cliff jumping. Stops include Maui Waterfalls, Scenic Viewpoint. Go for a hike and admire views during the journey to reach the waterfalls. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "104589P11": "See sunrise from the top of Maui\u2019s highest volcano during this informative tour of Haleakala National Park. Climb aboard an air-conditioned vehicle for a scenic tour of the dormant volcano and crater of Haleakala and the upcountry area. Stops include Haleakal\u0101 National Park, Haleakala Summit, Makawao, Pa'ia. Learn about the culture, history, and geology of Maui during the trip. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "2360M5": "Many visitors summit Maui's Haleakala for the sunrise but you can beat the crowds by visiting for an equally scenic sunset instead. Enjoy the best sunset view on Maui from the island's tallest peak. Stops include Kula Lodge Marketplace, Haleakal\u0101 National Park Visitor Center, Haleakala Summit. Transportation, equipment, and local commentary are handled so you can focus on Maui's volcanoes, waterfalls, reefs, and cultural landmarks. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "62707P3": "Sail aboard a catamaran to Molokini crater, one of Maui\u2019s best snorkel sites. The volcanic atoll off the south coast is a natural marine preserve, home to 250 species of tropical fish. Stops include Ma'alaea Harbor, Molokini Crater, Turtle Town. Join the crew at the helm of \u201cParagon II\u201d as Maui\u2019s afternoon trade winds get the boat to this top destination. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "241329P1": "The offshore crater of Molokini has some of the best snorkeling spots in Maui\u2014if you can reach them. Thankfully, this half-day snorkeling tour heads straight for Molokini and Turtle Town nearby on a 53-foot (16 meters) Lani Kai II boat with a 20-foot (6 meters) waterslide. Stops include Ma'alaea Harbor, Molokini Crater, Turtle Town. Visit two snorkeling locations, get the chance to spot whales, and enjoy onboard breakfast and lunch. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "2784P8": "Participate in a traditional Hawaiian luau during your time in Maui and learn about the Polynesian ancestry of the islands. Watch dancers portray the stories of fishing, gathering, and voyaging in \u201cTe Au Moana: The Ocean Tide\u201d. Stops include Te Au Moana Luau Grounds, Imu Ceremony, Oceanfront Performance Stage. After your pre-show entertainment, a delicious dinner is served at your table in a three-course family-style meal, with a fire knife performance. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "3087MOLL": "Soak up Hawaiian history and culture at the 3-hour Old Lahaina Luau in Maui. Enjoy hula dancing, an oceanfront setting and fresh island fillets, as well as other traditional dishes. Stops include Old Lahaina Luau Grounds, Imu Ceremony, Oceanfront Performance Stage. You'll be greeted with a Hawaiian lei and tropical drink from the bar before settling in for a lively performance against the Maui sunset. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "166701P1": "Indulge in a delicious feast and Hawaiian culture during the Mokapu Luau at the Andaz Maui. Take your seat on the grassy lawn and watch performers as they take you through Hawaiian history and the Polynesian culture that has created the island. Stops include Mokapu Luau Grounds, Imu Ceremony, Oceanfront Performance Stage. Enjoy a delicious plated, ohana-style meal as well as unlimited handcrafted cocktails while you watch the performance. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "124957P2": "Join the Pride of Maui for a premium whale watching and snorkeling experience aboard Maui's largest and most stable Maxi Power Catamaran. With 360-degree panoramic views, snorkeling at a vibrant coral reef, and a full barbecue lunch, this half-day tour offers memories that last a lifetime. Stops include Ma'alaea Harbor, Whale Watching Waters, Coral Reef Snorkel Site. Enjoy spacious decks, first-class service, and amenities like a water slide, warm showers, and snorkeling gear provided for all guests. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
  "5069WEST45": "On this exclusive helicopter tour of Maui, soar past valleys and hidden waterfalls that are inaccessible by land, and hover above ridgelines that sit at the heart of the rugged West Maui mountains. Cross the channel to neighboring Molokai, where vertical sea cliffs spill 4,000 feet to the turbid shoreline below, and get up-close views of a part of the world that has barely been touch by man. Stops include West Maui Mountains, Molokai. Transportation, equipment, and local commentary are handled so you can focus on Maui's volcanoes, waterfalls, reefs, and cultural landmarks. Ideal for visitors basing on Maui who want a guided island experience without coordinating transport, gear, or park logistics on their own.",
};

export const getMauiTargetedNarrativeDescription = (productCode: string) =>
  MAUI_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as MauiTargetedNarrativeDescriptionProductCode
  ];
