export const ORLANDO_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "3170P78",
  "331790P2",
  "42054P2",
  "3170P51",
  "42054P4",
  "3170P40",
  "123164P1",
  "120040P3",
  "317042",
  "3170P41",
  "42054P5",
  "3170P32",
  "42627P1",
  "5580079P3",
  "109065P4",
  "105290P7",
  "58194P1",
  "39750P18",
  "37177P6",
  "5039P5",
  "53748P4",
  "357987P1"
] as const;

export type OrlandoTargetedNarrativeDescriptionProductCode =
  (typeof ORLANDO_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const ORLANDO_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  OrlandoTargetedNarrativeDescriptionProductCode,
  string
> = {
  "3170P78": "Enjoy photo stops by the launch pads and the vehicle assembly building, touch a moon rock and ride the shuttle launch experience simulator on this small-group tour at the Kennedy Space Center. Learn about the science and history of the space program from your tour guide on the ride from Orlando. Upon arrival, start with a rocket garden tour before heading off on a special KSC Explore Bus tour to see the special parts of the NASA working space flight facility, then explore on your own time for the rest of your time there. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "331790P2": "Experience Orlando after dark from a premier helicopter flight with city lights, theme-park skylines, and seasonal fireworks views when schedules allow. Digital photo package included. Stops include Downtown Orlando, Disney Springs, Gaylord Palms Resort & Convention Center. Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "42054P2": "See magical Orlando from a unique perspective in a helicopter. Get a bird’s eye view of the theme parks, the Orlando Eye, the Florida sunset, or even catch some fireworks on your sightseeing chopper tour. Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "3170P51": "Explore outer space and the South Florida swamp during this day trip from Orlando. At the Kennedy Space Center, meet an astronaut, then go on to explore the visitor complex and hear about the United States' space travel history. Then hop on an airboat for a 30-min ride up the St Johns River. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "42054P4": "Fly over Orlando and its famous theme parks by helicopter. A chance to see the US's most popular theme parks from a different perspective. Stops include MaxFlight Helicopter Services Inc., Universal Studios Florida, Magic Kingdom Park, Epcot, Disney Springs, Lake Eola Park. Private tour: your group enjoys the ride on your own with in-flight commentary. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "3170P40": "Spend a day with central Florida’s manatees on this small-group river cruise and wildlife park adventure. Begin with a boat ride on the Crystal River. Snorkel near these gentle giants, then enjoy the afternoon at Homosassa Springs Wildlife State Park. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "123164P1": "A good choice for nature lovers, this tour takes you into a unique part of Rock Springs Run known as \"Emerald Cut.” The first part of the tour is an upstream paddle through calm waters and overhead tree canopy, with stops to hop off your clear kayak and into the fresh spring water. Keep your eyes peeled for for fish, turtles, birds, small alligators, and more.Clear kayak tour Local guide See wild animals in their natural habitat Kayak and safety gear provided Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "120040P3": "Enjoy a fun dune buggy tour in St. Cloud—just outside Orlando and don’t be afraid to get dirty. Grab your helmet and goggles, hop on your assigned 2-person buggy, and hit the trails and enjoy pure dune buggy driving experience through the lush countryside of Florida. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "317042": "Step back in time with a visit to enchanting St Augustine — one of America’s oldest towns — on this full-day tour from Orlando. This 10-hour excursion arrives in St Augustine by mid-morning, giving you hours to spend on your favorite activities. Stroll along cobbled pathways, admire Spanish Colonial architecture, indulge in delicious seafood at a waterside restaurant, see historic landmarks, and add on an optional sightseeing cruise or trolley tour.10-hour trip to St Augustine from Orlando Explore and enjoy a relaxing lunch in colonial St Augustine, self-proclaimed oldest city in the US! Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "3170P41": "Explore Clearwater Beach on a day trip from Orlando. Popular choice with kids and families. Stops include Clearwater Beach, Clearwater Beach Marina, Captain Memo's Pirate Cruise, Clearwater Marine Aquarium. Round-trip transfers from central meeting points is included. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "42054P5": "Take a private helicopter tour from Kissimmee over Orlando's theme-park corridor and onward to the Space Coast with views toward Port Canaveral and Cape Canaveral. In-flight commentary and taxes included for this premium aerial day trip beyond the theme parks. Stops include MaxFlight Helicopter Services Inc., Space Coast, Port Canaveral. Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "3170P32": "Embark on the ultimate space adventure at NASA’s Kennedy Space Center, where you can explore a range of exciting tour options. Walk beneath the largest rocket ever flown, meet a veteran NASA astronaut, and get up close with Space Shuttle Atlantis. Experience the thrilling Shuttle Launch Experience and discover interactive exhibits that bring space exploration to life. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "42627P1": "The Florida Everglades landscape is best explored with a licensed captain on an airboat. This guided tour covers alligator habitat and other wildlife viewing areas with live commentary from the captain throughout the ride. Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "5580079P3": "Step into a 1920s-themed evening at a murder mystery dinner show in Orlando. This interactive experience combines dining with live entertainment, where guests take part in solving a staged mystery. With a structured format and immersive setting, it offers a social, participatory alternative to traditional shows, allowing you to engage directly with the story while enjoying food and drinks.Enjoy an alternative Orlando experience beyond theme parks Interactive murder mystery lets you take part—not just watch One simple booking replaces separate dinner and evening plans Social format keeps groups Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "109065P4": "On this kayaking tour, you can look out for a variety of local wildlife, including manatees, monkeys, and birds. The all-clear kayak option provides an immersive experience, allowing you to see the underwater world clearly as you paddle. Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "105290P7": "Take a break from the hustle and bustle of Orlando and spend time in nature with this kayaking tour through Silver Springs State Park. Ideal for nature lovers, this wildlife-focused activity offers the opportunity to see manatees (depending on the season), turtles, and wild birds in their native habitats. Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "58194P1": "See Lake Louisa State Park from a unique perspective away from the crowds during a small-group horseback ride along its scenic trails. As you walk along the 6-mile (10-kilometer) route and access places that cars can’t reach, hear interesting insights about the state park’s wildlife, history, and local culture from your guide. Note: participants must be at least eight years old, and have a BMI score of 31 or lower.No prior experience needed—the horses are used to beginners Head to lesser-known vantage points to snap photos without the crowds Learn things about Lake Louisa most travelers miss E Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "39750P18": "Discover a side of Florida away from the theme parks–and enjoy a more active experience than on many other tours–on this stand-up paddleboard (SUP) and kayak adventure for beginners and experts alike, complete with wildlife spotting. Start with a lesson and hear facts about the local ecosystem before heading into the clear waters of a natural spring to spot monkeys, manatees, otters, turtles, and more.Go beyond sightseeing and kayak or paddleboard in a Florida natural spring Discover a unique ecosystem of monkeys, manatees, and other species Learn new skills–or sharpen existing ones–during an Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "37177P6": "Escape to Polynesia in air conditioned comfort. Polynesian fire Is an amazing luau dinner show experience that you and your family will not soon forget. Enjoy our live band serenading you will you dine on our buffet dinner. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "5039P5": "Discover the natural beauty of Florida—and explore beyond just the theme parks—on this airboat tour in Kissimmee, close to Orlando, including the ride itself plus a visit to a butterfly garden and a mining activity. Explore the lush landscape from the water, look out for native wildlife and get up close to reptiles, and hear stories and local insights along the way.Combine multiple experiences in one on this airboat tour in Kissimmee Explore the Florida landscape in a more active way than many other tours Work around your own schedule with a number of start times available Afterward, consider Transportation, equipment, and local commentary are handled so you can focus on Central Florida's wildlife, coastlines, and space-coast sights. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "53748P4": "Take the excitement of your Orlando vacation up a level with a tree top adventure. This ropes course is a series of aerial adventures with cargo nets, swinging logs, ziplines, trapeze swings and other obstacles to challenge yourself. Every level of climbing expertise will find something to test their skills, on a thrilling course set from 10 to 50 feet (3 to 15 meters) above the ground.Spend 2-3 hours challenging yourself on the ropes course This adventure is a thrill for the whole family (ages 7 years and older) Conveniently located near the Walt Disney World Resort. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
  "357987P1": "Experience the Indian River Lagoon's dazzling bioluminescence, just steps from Orlando, on this small-group tour. Paddleboard or kayak under the stars surrounded by glowing dinoflagellates, creating a mesmerizing natural light show with each stroke. Look out for Comb Jellies, native to the lagoon, which light up upon contact. Ideal for travelers basing in Orlando who want a guided Florida experience beyond the theme parks without coordinating boats, gear, or launch times on their own.",
};

export const getOrlandoTargetedNarrativeDescription = (productCode: string) =>
  ORLANDO_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as OrlandoTargetedNarrativeDescriptionProductCode
  ];
