export const PUERTO_VALLARTA_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "2736P31",
  "22116P7",
  "7053ZIP",
  "24191P1",
  "118966P4",
  "46209P3",
  "218207P4",
  "428665P1",
  "368259P2",
  "46209P5",
] as const;

export type PuertoVallartaTargetedNarrativeDescriptionProductCode =
  (typeof PUERTO_VALLARTA_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const PUERTO_VALLARTA_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  PuertoVallartaTargetedNarrativeDescriptionProductCode,
  string
> = {
  "2736P31": "In Puerto Vallarta, this guided UTV day leaves the resort strip for Sierra Madre mountain tracks in a Polaris RZR. After a safety briefing and driving lesson, the group follows rainforest trails and stream crossings to a natural swimming pool for a hike, swim, and included snacks. Hotel pickup and drop-off keep the outing on the jungle route rather than rental counters or self-navigation. Helmets, goggles, and a professional guide are included so visitors can focus on the terrain instead of vehicle logistics. The format suits visitors who want a guided off-road day without booking a UTV independently. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on Sierra Madre trails and the swim-hole stop that define this rainforest UTV tour.",
  "22116P7": "In Puerto Vallarta, this half-day ATV outing follows Sierra Madre mountain tracks away from crowded resorts. Drivers choose a single or two-person ATV, then pass Old Town streets and jungle rivers under a guide who handles briefing, safety gear, and souvenir photos. Morning and afternoon departures make it easier to pair the ride with a beach or bay day. A valid license is required for drivers, and the small-group format keeps the route on dirt tracks rather than a large convoy. The outing is aimed at visitors who want a guided off-road window without renting ATVs independently. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on Old Town pass-throughs and Sierra Madre trails that shape this Jalisco mountain ride.",
  "7053ZIP": "In Puerto Vallarta, this original canopy circuit pairs an optional speedboat crossing with ziplines above the Los Horcones River. The Los Veranos Canopy Tour course covers about two miles on cables as high as 328 feet, then continues to an included tequila tasting plus swim, kayak, and waterslide time when the river allows. Land or sea transport is handled so visitors can stay with the platforms rather than arranging a separate jungle transfer. Lunch at the riverside restaurant is available to purchase, while the tasting and course time stay in the published package. The format suits visitors who want a guided adventure day without assembling zipline, boat, and tasting tickets separately. Departures are confirmed at booking in Puerto Vallarta, and the itinerary stays on the river approach and Los Veranos canopy that define this outing.",
  "24191P1": "In Puerto Vallarta, this all-inclusive mega-yacht day sails Banderas Bay toward Playa Chica Locca, Quimixto, and Yelapa Beach. Breakfast, a fajita lunch, snacks, and an open bar are served on board, with snorkeling gear, kayaks, and paddleboards ready after the first anchor. A short trail hike to the Yelapa waterfall is available when water is flowing, with free time in the village or a massage back on the yacht. Two meeting places are listed at booking so the group can board at the more convenient dock, including Puerto Mágico. The format suits visitors who want a guided scenic day on the water without chartering a boat independently. Departures are confirmed at booking in Puerto Vallarta, and the itinerary stays on the published bay, beach, and village stops rather than adding extra mainland sightseeing.",
  "118966P4": "In Puerto Vallarta, this snorkeling day heads to the Marietas Islands with a published chance of entering Hidden Beach through the water tunnel when park conditions allow. Snorkel gear, life vests, drinking water, snacks, and national-park permits are included so the group can stay with the reefs rather than paying separate conservation windows. Dolphins, turtles, and tropical fish are the usual marine highlights on the published route. Private departures can be arranged on request, but the listed product is a guided boat outing rather than a self-guided rental. The format suits visitors who want a Marietas day without coordinating park fees and boat timing independently. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on the islands and Hidden Beach rather than adding extra bay villages.",
  "46209P3": "In Puerto Vallarta, this small-group half-day looks for humpback whales on Banderas Bay with a marine biologist guide. The boat includes a restroom, and lunch plus soft drinks are served on board so the morning stays on the water rather than a separate restaurant stop. Hotel pickup is listed for many properties, with a small cash port fee collected at departure. The group format is aimed at visitors who want expert commentary without booking a private charter. Seasonal whale presence still depends on winter migration, and the published route keeps a respectful distance from the animals. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on Marina Vallarta and Banderas Bay that define this wildlife outing.",
  "218207P4": "In Puerto Vallarta, this three-hour hidden beach tour leaves Punta de Mita for the Marietas water-tunnel swim when park access allows. The small boat is capped at eight travelers, with snorkeling gear, bottled water, lunch, and private transportation included. Guides handle the tunnel entry and in-water photos so the group can stay with Hidden Beach rather than assembling a self-guided boat. The meeting point is the Punta de Mita tourism cooperative in front of the small marina, and the return finishes at the same dock. The format suits visitors who want a compact island swim without a full-day Marietas cruise. Departures are confirmed at booking in Puerto Vallarta, and the itinerary stays on Punta de Mita and Hidden Beach rather than adding extra bay villages or resort stops.",
  "428665P1": "In Puerto Vallarta, this five-hour outing pairs a guided horseback ride along the Mascota River with an artisanal tequila tasting and Mexican BBQ lunch at La Dulce Vista. An open-concept bus leaves Marina Vallarta from the Nima Bay meeting point, then continues to the ranch for horse matching before the river trail. Margaritas and bottled water are included with lunch, and a short swim with the horses is offered when river conditions allow. The group is capped at 17 travelers, with a height rule for riders over 220 pounds and an 18-plus minimum for the tasting. The format suits visitors who want a guided countryside day without arranging horses, tasting-room timing, or ranch transport independently. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on the Mascota River and La Dulce Vista stops that define this ride.",
  "368259P2": "In Puerto Vallarta, this half-day hike follows a local guide from Zona Romántica to the Palo María River and Cascadas Palo Maria. Shared transport covers the short transfer into the Sierra Madre, then the group hikes, climbs, and swims in river pools with bottled water and snacks included. The outing is limited to 10 travelers and asks for moderate fitness, with a 10:00 a.m. start at Parque Lázaro Cárdenas. The route stays on the published waterfall trail rather than a multi-beach or jeep add-on. The format suits visitors who want a guided hiking window without finding the trailhead or river access independently. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on the Palo María River and waterfall stops that shape this mountain morning.",
  "46209P5": "In Puerto Vallarta, this private whale-watching charter gives a group the boat and a marine biologist for a morning on Banderas Bay. Lunch and soft drinks are served on board, and hotel pickup is listed so the outing stays on the water rather than marina logistics. The published season runs December to March, when humpback whales return to the bay, and the guide keeps a distance that will not disturb the animals. A cash port tax is collected, and the private format is capped at eight passengers. The outing is aimed at visitors who want a private wildlife morning without sharing the boat with another group. Meeting points are confirmed at booking in Puerto Vallarta, and the itinerary stays on Marina Vallarta and Banderas Bay that define this charter.",
};

export const getPuertoVallartaTargetedNarrativeDescription = (
  productCode: string
) =>
  PUERTO_VALLARTA_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as PuertoVallartaTargetedNarrativeDescriptionProductCode
  ];
