export const RIO_DE_JANEIRO_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "20297P1",
  "11557P1",
  "38668P1",
  "21513P8",
  "21715P2",
  "8753P120",
  "186670P1",
  "179234P2",
  "305170P2",
] as const;

export type RioDeJaneiroTargetedNarrativeDescriptionProductCode =
  (typeof RIO_DE_JANEIRO_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const RIO_DE_JANEIRO_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  RioDeJaneiroTargetedNarrativeDescriptionProductCode,
  string
> = {
  "20297P1": "In Rio de Janeiro, this private 7-to-8-hour circuit keeps one group in an air-conditioned vehicle for Christ the Redeemer atop Corcovado, Sugar Loaf Mountain, the Selarón Steps, the Metropolitan Cathedral, and the city's famous beaches. A certified guide and driver handle hotel, airport, or seaport pickup, and complimentary bottled water is listed on the product page. Christ the Redeemer and Sugar Loaf tickets are not treated as a guaranteed inclusion; the operator helps arrange them. The itinerary can change during the day to match the group's pace. Barra da Tijuca and Recreio pickups are asked to start at 6:30 a.m. to avoid heavy traffic. The format suits visitors who want a guided city window without assembling taxi, ticket, and landmark timing independently. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on Corcovado, Sugar Loaf, the Selarón Steps, and the Metropolitan Cathedral that define this private outing rather than a Petrópolis mountain add-on.",
  "11557P1": "In Rio de Janeiro, this private 8-hour city tour keeps one group with a dedicated guide for historic downtown, the Sambadrome, and the Metropolitan Cathedral before the Corcovado and Sugar Loaf ascents. The published route includes a Christ the Redeemer stop and lists the Colombo tea house as an own-expense lunch or snack. Hotel or airport pickup and an air-conditioned vehicle are included, with tickets listed on the product page. The format suits visitors who want a guided landmark day without assembling cable-car, van, and downtown timing independently. Commentary stays on the historic center and the two granite peaks rather than a rainforest jeep add-on. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on historic downtown, the Sambadrome, the Metropolitan Cathedral, Corcovado, and Sugar Loaf that shape this private circuit rather than a hang-gliding or helicopter window.",
  "38668P1": "In Rio de Janeiro, this private 8-to-9-hour outing starts at Corcovado and Christ the Redeemer, continues to Escadaria Selaron and Sugarloaf Mountain, then offers an afternoon choice of historic center, Tijuca Forest, or Santa Teresa. A driver-guide or a separate guide and driver stay with one group. Pickup is listed from hotels including Barra da Tijuca, plus airports and the cruise terminal. Entry tickets and lunch are not treated as guaranteed inclusions on the published page. History-focused afternoons use Cinelandia, the Metropolitan Cathedral, and the Etnias mural; nature-focused afternoons use Cascatinha Taunay and Pepino Beach. The format suits visitors who want a customizable guided day without booking three separate circuits. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on Corcovado, Escadaria Selaron, and Sugarloaf Mountain that define this private circuit rather than a Petrópolis imperial add-on.",
  "21513P8": "In Rio de Janeiro, this private 8-hour outing pairs a carioca guide and driver with one group so the day can stay on Christ the Redeemer, Sugar Loaf Mountain, Copacabana and Ipanema beaches, São Bento Monastery, Maracanã Stadium, or the Sambadrome. Hotel pickup and drop-off are included. The guide confirms themes such as food, history, or sport before departure and keeps the published stops limited to sites the group actually wants. Entrance tickets, food, and drinks are listed separately on the product page. The format suits visitors who want undivided attention without joining a coach loop or assembling taxi and ticket timing independently. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on the granite peaks, South Zone beaches, and carnival landmarks that define this private day rather than a hang-gliding or Petrópolis add-on.",
  "21715P2": "In Rio de Janeiro, this full-day van circuit travels through Tijuca Forest, stops at Centro De Visitantes Paineiras, and continues to Corcovado and Christ the Redeemer. The published route then uses the Morro da Urca cable car toward Sugarloaf Mountain and adds Maracana, Sambodromo da Marques de Sapucai, the Metropolitan Cathedral of Saint Sebastian, and Escadaria Selaron. Copacabana Beach, Ipanema Beach, and Avenida Atlantica appear as pass-bys. Hotel pickup is listed from South Zone and Barra da Tijuca hotels, with a published 8:30 a.m. start. Christ the Redeemer van admission is included; Sugarloaf tickets and barbecue lunch appear only on the upgraded full option. The format suits visitors who want a guided landmark day without coordinating forest, cable-car, and downtown timing independently. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on Paineiras, Corcovado, Sugarloaf Mountain, and the Sambodrome that shape this outing rather than a private custom circuit.",
  "8753P120": "In Rio de Janeiro, this small-group 9-hour day combines the Sambadromo, Christ the Redeemer, the Tijuca Rainforest, Sugarloaf Mountain, and Maracana Stadium. Buffet lunch is included, while drinks and desserts are listed separately. Admission tickets to Christ the Redeemer, Sugarloaf, the Sambodromo, and Maracana Stadium are published on the product page, with an air-conditioned vehicle and bilingual guide. Pickup runs from hotels in Leblon, Ipanema, Copacabana, Flamengo, and Centro between 8:00 a.m. and 9:30 a.m.; groups that skip hotel confirmation meet at Hotel Rio Othon Palace on Avenida Atlântica in Copacabana. The format suits visitors who want a single guided highlights day without buying four attraction tickets independently. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on the Sambadromo, Corcovado, Tijuca Rainforest, and Sugarloaf Mountain that define this outing rather than a private tailor-made loop.",
  "186670P1": "In Rio de Janeiro, this hang-gliding or paragliding outing starts with a short training session, then launches from the Pedra Bonita ramp inside Tijuca National Park and lands on São Conrado beach. No prior flight experience is required. A Level 4 instructor, helmet, emergency parachute, flight belt, and one GoPro photo-and-video set are included. Mandatory insurance and extra cameras are listed separately. Flight time depends on weather, and the published duration is about one hour and thirty minutes including briefing and recovery. The meeting point is BETO ROTOR on Avenida Prefecto Mendes de Morais in São Conrado; an optional South Zone hotel shuttle is listed at extra cost. The format suits visitors who want a guided tandem flight without arranging ramp access independently. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on Pedra Bonita, Tijuca National Park, and São Conrado beach that define this aerial window rather than a city-van or helicopter add-on.",
  "179234P2": "In Rio de Janeiro, this 25-minute helicopter flight departs the Jacarepaguá helipad on Avenida Ayrton Senna in Barra da Tijuca after a safety briefing. The published aerial route looks over Christ the Redeemer, Copacabana Beach, Ipanema Beach, and Sugar Loaf Mountain. The outing stays on the flight window rather than adding a ground city circuit or cable-car ticket. Pilot commentary covers the granite peaks and South Zone shoreline from above. The format suits visitors who want a short guided aerial window without booking a full-day van loop. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on the Jacarepaguá helipad and the Christ the Redeemer, Copacabana, Ipanema, and Sugar Loaf views that define this flight rather than a Pedra Bonita hang-gliding launch.",
  "305170P2": "In Rio de Janeiro, this full-day excursion leaves the coast for Petrópolis, the former imperial summer capital in the Serra dos Órgãos. An accredited guide covers the Imperial Museum with the included ticket, then continues to Palácio Quitandinha and the Santos Dumont House. A buffet lunch is included; drinks, desserts, and optional Bohemia Brewery entry are listed separately on the product page. Round-trip transport uses an air-conditioned vehicle from a Rio de Janeiro hotel pickup or listed meeting point, with a published 8:00 a.m. start. The mountain day is aimed at visitors who want a guided imperial-history window without self-driving the serra road. Meeting points are confirmed at booking in Rio de Janeiro, and the itinerary stays on the Imperial Museum, Palácio Quitandinha, and the Santos Dumont House that shape this Petrópolis outing rather than a Corcovado or Sugar Loaf city circuit.",
};

export const getRioDeJaneiroTargetedNarrativeDescription = (
  productCode: string
) =>
  RIO_DE_JANEIRO_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as RioDeJaneiroTargetedNarrativeDescriptionProductCode
  ];
