export const SINGAPORE_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES = [
  "203208P12",
  "30791P719",
  "40856P7",
  "223757P4",
  "102132P3",
  "24380P991",
  "124015P1",
  "45610P13",
  "5570MGK",
  "277546P4",
  "104357P24",
  "57811P2",
] as const;

export type SingaporeTargetedNarrativeDescriptionProductCode =
  (typeof SINGAPORE_TARGETED_NARRATIVE_DESCRIPTION_PRODUCT_CODES)[number];

export const SINGAPORE_TARGETED_NARRATIVE_DESCRIPTIONS: Record<
  SingaporeTargetedNarrativeDescriptionProductCode,
  string
> = {
  "203208P12": "In Singapore, this private six-hour car or minibus charter leaves a hotel lobby for a published highlights list rather than a shared coach loop. The driver can keep Merlion Park, the Singapore River, Raffles City, China Square, Buddha Tooth Relic Temple and Museum, Little India, Mount Faber Park, Henderson Waves, Marina Bay, Gardens by the Bay, and Sentosa Island on the window, or swap stops when the group wants more time at a ridge or quarter. An air-conditioned vehicle and bottled water are listed; entrance fees stay separate. Jurong, Woodlands, and Malaysian-border pickups carry a published surcharge. The format suits visitors who want a guided island circuit without assembling MRT transfers independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Merlion Park, Little India, Mount Faber, and Gardens by the Bay that define this private city day rather than a hop-on ticket.",
  "30791P719": "In Singapore, this private eight-hour walking day is shaped by a local host instead of a fixed coach script. Published options include Marina Bay Sands Skypark, Gardens by the Bay, Chinatown, and Tiong Bahru, with the host suggesting MRT or taxi links when the group wants to cover more ground. The default meeting is Starbucks at Chinatown Point on New Bridge Road; a central hotel meetup can be confirmed in advance. Food, attraction tickets, and transport fares are listed separately. The format suits visitors who want a full Singapore day without booking four district tours independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Marina Bay Sands Skypark, Gardens by the Bay, Chinatown, and Tiong Bahru that shape this outing rather than a Pulau Ubin add-on.",
  "40856P7": "In Singapore, this private evening circuit leaves a city hotel lobby at 6 pm for Little India, the Gardens by the Bay light show, Clarke Quay, a shared Singapore River cruise, and Marina Bay Sands SkyPark. An English-speaking guide and air-conditioned private vehicle are listed, with the SkyPark entrance and river-cruise ticket included on the published visit list. Food, dinner stops, and gratuities stay separate. The window is about three hours 30 minutes from pickup to hotel drop-off. The format suits visitors on a short layover who want guided night landmarks without buying cruise and SkyPark tickets independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Little India, Gardens by the Bay, the Singapore River, and SkyPark that define this night outing rather than a daytime hawker walk.",
  "223757P4": "In Singapore, this small-group food and culture walk covers Chinatown, Little India, and Kampong Glam with a fourth-generation Singapore-Chinese-Peranakan host. The published 5.5-hour window includes street food from UNESCO-inscribed hawker centres plus a Sultan Mosque stop, with coffee, lunch, dinner snacks, and drinks listed among inclusions. Groups are capped at eight. Central hotel or MRT pickup is offered for a 9:00 am start in Chinatown. The route stays on the three historic quarters rather than a Marina Bay night circuit. The format suits visitors who want a guided three-culture tasting day without assembling hawker and mosque timing independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Chinatown, Little India, Kampong Glam, and Sultan Mosque that shape this outing rather than a private car day.",
  "102132P3": "In Singapore, this private three-hour tasting walk starts on Arab Street in Kampong Glam and continues through Little India and Chinatown with nine included food and drink stops. A licensed guide and MRT tickets are listed; extra dishes and gratuities stay separate. The published end is near Buddha Tooth Relic Temple on South Bridge Road. An upgrade adds a private vehicle with hotel transfers. The route stays on Malay, Indian, and Chinese neighbourhood eateries rather than a Michelin-only Chinatown loop. The format suits visitors who want a guided three-quarter tasting without coordinating stall queues independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Kampong Glam, Arab Street, Little India, and Chinatown that define this private food window rather than a night river cruise.",
  "24380P991": "In Singapore, this private 2.5-hour hawker tasting stays in the Chinatown area with a local host and five included dishes such as chicken rice, spring rolls, dim sum, and kaya toast. Morning, noon, or night departures are published so the group can work around flights. The meeting is Chinatown MRT Exit A; the published end is Lau Pa Sat on Raffles Quay. Local transport is included; extra drinks stay separate. The route is a compact Chinatown hawker window rather than a three-quarter cultural day. The format suits visitors who want a private tasting without joining a ten-person morning group. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Maxwell Food Centre and Lau Pa Sat that shape this outing rather than a Kampong Glam add-on.",
  "124015P1": "In Singapore, this private licensed walk covers Chinatown, the Civic District, Thian Hock Keng Temple, Marina Bay, and Merlion Park on three-, four-, or six-hour options. The three-hour meeting is Chinatown MRT or Telok Ayer MRT; longer options add hotel pickup in central areas and ports. A local drink is included. Commentary stays on colonial streets, temple architecture, and waterfront landmarks rather than a hawker tasting script. The six-hour window can finish in Kampong Glam or Little India. The format suits visitors who want a guided heritage circuit without assembling Civic District and Chinatown stops independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Chinatown, the Civic District, Thian Hock Keng Temple, and Merlion Park that define this walk rather than a Pulau Ubin kayak day.",
  "45610P13": "In Singapore, this small-group Chinatown hawker walk leaves Chinatown MRT Exit E at 9:30 am for nine to ten tastings at Michelin Guide and Bib Gourmand stalls. Published stops include Maxwell Food Centre, South Bridge Road, Sago Street, and Chinatown Street Market, with Jamae Mosque, Sri Mariamman Temple, and Buddha Tooth Relic Temple listed as pass-bys. The group is capped at ten. Food and drinks on the tasting list are included; transport and extra purchases stay separate. The walk ends at Chinatown Complex on Smith Street. The format suits visitors who want a guided hawker introduction without queuing independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Chinatown, Maxwell Food Centre, Sago Street, and Chinatown Street Market that define this tasting rather than a Little India add-on.",
  "5570MGK": "In Singapore, this four-hour guided kayak session leaves a Pulau Ubin shophouse near the jetty for an open-sea crossing and mangrove-forest channels. Tandem kayaks, personal flotation devices, lockers, drinking-water refills, and a rinse-off are listed. No prior kayaking experience is required. The Changi Point ferry is at guest expense. Commentary stays on mangrove birds such as kingfishers, eagles, and herons rather than a downtown bike loop. Sessions run morning or afternoon from shophouse No. 34. The format suits visitors who want a guided island paddle without renting kayaks independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Pulau Ubin and the mangrove forest that define this outing rather than a Marina Bay night ride.",
  "277546P4": "In Singapore, this three-hour licensed heritage walk covers Kampong Glam, Little India including Tekka Centre, and Chinatown including Buddha Tooth Relic Temple and Museum. The meeting is the Let's Go Tour shop on Crawford Lane; the published end is Chinatown Complex. Commentary stays on Chinese, Indian, and Malay street history and photo stops rather than included tastings. Gratuities are listed separately. The route is a compact three-quarter introduction rather than a 5.5-hour food day. The format suits visitors who want guided heritage streets without booking three neighbourhood walks independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Kampong Glam, Little India, Tekka Centre, and Chinatown that shape this outing rather than a Gardens by the Bay night show.",
  "104357P24": "In Singapore, this private licensed walking outing is customizable from two to eight hours, with a hotel or cruise-terminal meetup when the stay is in the city. The guide shapes the day around published neighbourhood preferences such as the Civic District and Chinatown, plus ticket-booking help for visits the group wants to add. Food and attraction tickets stay separate. Hotels outside the centre use a convenient city meeting point. The format suits visitors who want a tailored walk without a fixed coach script. Meeting points are confirmed at booking in Singapore, and the itinerary stays on the Civic District and Chinatown that define this custom window rather than a Mount Faber car day.",
  "57811P2": "In Singapore, this two-hour guided night bike ride leaves the Crawford Lane shop for Kallang Riverside Park, a Formula One pit-building stretch, Merlion Park, and pass-bys of the Singapore Flyer, Gardens by the Bay Super Trees, Marina Bay Sands, Esplanade Theatres on the Bay, and the Fullerton Hotel. A bicycle, helmet, poncho, and water are included with a licensed local guide. The ride returns to the bike shop. Hotel pickup is not listed. The format suits visitors who want a guided Marina Bay night loop without renting independently. Meeting points are confirmed at booking in Singapore, and the itinerary stays on Kallang Riverside, Merlion Park, and the Marina Bay landmarks that define this ride rather than a Chinatown hawker walk.",
};

export const getSingaporeTargetedNarrativeDescription = (
  productCode: string
) =>
  SINGAPORE_TARGETED_NARRATIVE_DESCRIPTIONS[
    productCode as SingaporeTargetedNarrativeDescriptionProductCode
  ];
