// This file is auto-generated by scripts/generate-sedona-pages.ts. Do not edit manually.
import CityTourBookingPage from "../CityTourBookingPage";
import { getCityTourBySlug } from "../cityTourData";

const tour = getCityTourBySlug("rim-to-rim-backpacking-571816");

export default function CityTourBookingRoute() {
  return <CityTourBookingPage tour={tour} />;
}
