// This file is auto-generated by scripts/generate-sedona-pages.ts. Do not edit manually.
import CityTourBookingPage from "../CityTourBookingPage";
import { getCityTourBySlug } from "../cityTourData";

const tour = getCityTourBySlug("sedona-red-rocks-highlights-tours-307177");

export default function CityTourBookingRoute() {
  return <CityTourBookingPage tour={tour} />;
}
