import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

type HarvestRecord = { source: string; id: string; title: string; route: string | null };
type HarvestItem = { records: HarvestRecord[]; description: string; headline: string; supplemental: Record<string,string>; images: string[]; rewriteReady: boolean; imageReady: boolean };
type Harvest = { summary: Record<string,unknown>; items: HarvestItem[] };

const root = process.cwd();
const harvest = JSON.parse(await readFile(path.join(root,"reports/fareharbor-rebuild-harvest.json"),"utf8")) as Harvest;

const clean = (s:string) => s.replace(/\s+/g," ").trim();
const noPrices = (s:string) => clean(s)
  .replace(/(?:starting\s+at\s+|from\s+)?\$\s?\d+(?:\.\d{1,2})?(?:\s*(?:per|\/)[^.,;]*)?/gi," ")
  .replace(/\b(?:rates?|pricing|prices?)\s*[:-]?\s*(?:\$?\d[^.]*)(?:\.|$)/gi," ")
  .replace(/\s+([,.;:!?])/g,"$1").replace(/\s{2,}/g," ").trim();
const cityFromRoute = (route:string|null) => {
  if (!route) return "the destination";
  const p=route.split("/").filter(Boolean); const i=p.indexOf("tours");
  const slug=i>0?p[i-1]:"the-destination";
  return slug.split("-").map(w=>w? w[0].toUpperCase()+w.slice(1):w).join(" ");
};
const rewrite = (item:HarvestItem, rec:HarvestRecord) => {
  const city=cityFromRoute(rec.route); let source=noPrices(item.description);
  source=source
    .replace(/\bwe\b/gi,"the operator").replace(/\bour\b/gi,"the operator's")
    .replace(/\byou(?:'ll| will)?\b/gi,"guests").replace(/\byour\b/gi,"guests'")
    .replace(/!+/g,".");
  const sentences=source.split(/(?<=[.!?])\s+/).map(clean).filter(s=>s.length>=25 && !/\b(?:book now|reserve now|call us)\b/i.test(s)).slice(0,5);
  const body=sentences.join(" ");
  const intro=`Explore ${rec.title} in ${city}. This local experience is presented with operator-supplied details reviewed and rewritten for All Outdoor Adventures.`;
  return clean(`${intro} ${body}`);
};

const overlay: Record<string, unknown> = {};
let rewrittenRoutes=0, imageRoutes=0;
for (const item of harvest.items) {
  if (!item.rewriteReady) continue;
  for (const rec of item.records) {
    if (!rec.route) continue;
    const description=rewrite(item,rec);
    if (description.length < 120) continue;
    const images=Array.from(new Set(item.images.filter(Boolean))).slice(0,8);
    const highlights=Object.values(item.supplemental??{}).map(noPrices).filter(v=>v.length>=20).slice(0,5);
    overlay[rec.route]={ description, images, highlights, hasTwoImages: images.length>=2 };
    rewrittenRoutes += 1; if (images.length>=2) imageRoutes += 1;
  }
}

const generated=`// AUTO-GENERATED by scripts/apply-fareharbor-rebuild.ts. Do not hand edit.\nexport type FareHarborContentOverlay = { description:string; images:string[]; highlights:string[]; hasTwoImages:boolean };\nexport const fareHarborContentOverlayByRoute = ${JSON.stringify(overlay)} as Record<string,FareHarborContentOverlay>;\n`;
await writeFile(path.join(root,"src/data/fareharborContentOverlay.generated.ts"),generated,"utf8");

const appendOnce=async(file:string,marker:string,block:string)=>{
  const p=path.join(root,file); let s=await readFile(p,"utf8"); if(s.includes(marker)) return;
  s += `\n\n${block}\n`; await writeFile(p,s,"utf8");
};

await appendOnce("src/data/tours.ts","[FH-CONTENT-REBUILD-OVERLAY]",`// [FH-CONTENT-REBUILD-OVERLAY]\nimport("./fareharborContentOverlay.generated").then(({ fareHarborContentOverlayByRoute }) => {\n  for (const tour of tours) {\n    if (tour.bookingProvider !== "fareharbor") continue;\n    const route = \`/destinations/\${tour.destination.stateSlug}/\${tour.destination.citySlug}/tours/\${tour.slug}\`;\n    const o = fareHarborContentOverlayByRoute[route]; if (!o) continue;\n    tour.longDescription = o.description; tour.shortDescription = o.description.slice(0,220);\n    tour.content = { ...(tour.content ?? {}), overview:o.description, highlights:o.highlights };\n    if (o.images.length) { tour.heroImage=o.images[0]; tour.primaryImageUrl=o.images[0]; tour.galleryImages=o.images.slice(1); }\n    if (!tour.pricing?.isReliable) { tour.startingPrice=undefined; tour.badges={...tour.badges,priceFrom:undefined}; }\n  }\n});`);

await appendOnce("src/engine2/data/loadEngine2.ts","[FH-CONTENT-REBUILD-OVERLAY]",`// [FH-CONTENT-REBUILD-OVERLAY]\nimport("../../data/fareharborContentOverlay.generated").then(({ fareHarborContentOverlayByRoute }) => {\n  for (const tour of engine2Tours) {\n    if (tour.bookingProvider !== "fareharbor") continue; const o=fareHarborContentOverlayByRoute[tour.seo.canonicalPath]; if(!o) continue;\n    tour.content={...tour.content,experienceText:o.description,overview:o.description,highlights:o.highlights.length?o.highlights:tour.content.highlights};\n    tour.seo={...tour.seo,description:o.description.slice(0,300)};\n    if(o.images.length) tour.images={hero:o.images[0],gallery:o.images.slice(1)};\n    if(tour.pricing) tour.pricing={...tour.pricing,price:undefined};\n  }\n});`);

// Make unresolved FareHarbor Engine2 pages truthful: no invented $129 and external Learn More CTA.
{
 const p=path.join(root,"src/engine2/pages/Engine2TourPage.tsx"); let s=await readFile(p,"utf8");
 s=s.replace("const showFallbackPrice = !overridePriceLabel && !enginePriceLabel;","const showFallbackPrice = isViatorTour && !overridePriceLabel && !enginePriceLabel;");
 s=s.replace(/\{showFallbackPrice \? \([\s\S]*?From \$129 per person[\s\S]*?\) : null\}/m,"{showFallbackPrice ? (\n            <p className=\"mt-4 text-sm font-semibold text-white/90\">Price shown by booking provider</p>\n          ) : null}");
 s=s.replace(/\) : bookingPath \? \(\s*<Link href=\{bookingPath\}>[\s\S]*?<\/Link>\s*\) : null\}/m,`) : bookingPath ? (\n              <a href={tour.bookingUrl ?? tour.booking.bookingUrl} target=\"_blank\" rel={EXTERNAL_CTA_REL} className=\"inline-flex items-center justify-center rounded-md bg-[#2f8a3d] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[#287a35]\">Learn More</a>\n            ) : null}`);
 await writeFile(p,s,"utf8");
}

console.info(`[fh-rebuild-apply] overlayRoutes=${Object.keys(overlay).length} rewrittenRecords=${rewrittenRoutes} twoPlusImageRecords=${imageRoutes}`);
