import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { toursGenerated } from "../src/data/tours.generated";
import { getFareharborItemFromUrl } from "../src/lib/fareharbor";

type FareharborTourContent = {
  sourceOperatorSlug: string;
  sourceItemId: string;
  heroImageUrl?: string;
  sourceDescription?: string;
};

const OUTPUT_PATH = path.resolve("src/data/fareharborContent.generated.ts");
const API_BASE = "https://fareharbor.com/api/v1";
const MAX_SNIPPET_LENGTH = 220;

const toCacheKey = (operatorSlug: string, itemId: string) => `${operatorSlug}:${itemId}`;

const normalizeWhitespace = (value: string) => value.replace(/\s+/g, " ").trim();

const stripHtml = (value?: string) => {
  if (!value) return undefined;
  const withoutTags = value
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'");
  const normalized = normalizeWhitespace(withoutTags);
  return normalized || undefined;
};

const clampSnippet = (value?: string) => {
  if (!value) return undefined;
  const normalized = normalizeWhitespace(value);
  if (normalized.length <= MAX_SNIPPET_LENGTH) return normalized;
  const chunk = normalized.slice(0, MAX_SNIPPET_LENGTH - 1);
  const cut = chunk.lastIndexOf(" ");
  return `${(cut > 100 ? chunk.slice(0, cut) : chunk).trim()}…`;
};

const collectImageCandidates = (payload: unknown): string[] => {
  const results = new Set<string>();
  const queue: unknown[] = [payload];

  while (queue.length) {
    const current = queue.shift();
    if (!current) continue;

    if (typeof current === "string") {
      const trimmed = current.trim();
      if (
        /^https?:\/\//i.test(trimmed) &&
        /(filestackcontent\.com|fareharbor\.com|images\.|cloudfront)/i.test(trimmed) &&
        /\.(jpg|jpeg|png|webp)(\?|$)/i.test(trimmed)
      ) {
        results.add(trimmed);
      }
      continue;
    }

    if (Array.isArray(current)) {
      queue.push(...current);
      continue;
    }

    if (typeof current === "object") {
      const record = current as Record<string, unknown>;
      Object.entries(record).forEach(([key, value]) => {
        if (typeof value === "string") {
          const lower = key.toLowerCase();
          if (/(image|photo|media|cover|hero)/.test(lower)) {
            queue.push(value);
          }
        } else if (value && typeof value === "object") {
          queue.push(value);
        } else if (Array.isArray(value)) {
          queue.push(...value);
        }
      });
    }
  }

  return [...results];
};

const pickDescription = (payload: Record<string, unknown>) => {
  const candidates = [
    payload.description,
    payload.short_description,
    payload.summary,
    payload.seo_description,
    payload.marketing_description,
  ];

  for (const candidate of candidates) {
    if (typeof candidate === "string" && candidate.trim()) {
      const text = clampSnippet(stripHtml(candidate));
      if (text) return text;
    }
  }

  return undefined;
};

const fetchItemPayload = async (operatorSlug: string, itemId: string) => {
  const endpoint = `${API_BASE}/companies/${operatorSlug}/items/${itemId}/`;
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 8000);
  try {
    const response = await fetch(endpoint, {
      signal: controller.signal,
      headers: { Accept: "application/json" },
    });
    if (!response.ok) {
      throw new Error(`FareHarbor item request failed (${response.status})`);
    }
    return (await response.json()) as Record<string, unknown>;
  } finally {
    clearTimeout(timeout);
  }
};

const loadExistingCache = async () => {
  try {
    const source = await readFile(OUTPUT_PATH, "utf8");
    const jsonMatch = source.match(/=\s*(\{[\s\S]*\});\s*$/);
    if (!jsonMatch?.[1]) return {} as Record<string, FareharborTourContent>;
    return JSON.parse(jsonMatch[1]) as Record<string, FareharborTourContent>;
  } catch {
    return {} as Record<string, FareharborTourContent>;
  }
};

const writeCache = async (contentByKey: Record<string, FareharborTourContent>) => {
  const output = `export type FareharborTourContent = {\n  sourceOperatorSlug: string;\n  sourceItemId: string;\n  heroImageUrl?: string;\n  sourceDescription?: string;\n};\n\n// This file is auto-generated by scripts/enrich-fareharbor-tour-content.ts. Do not edit manually.\nexport const fareharborTourContentByKey: Record<string, FareharborTourContent> = ${JSON.stringify(contentByKey, null, 2)};\n`;
  await writeFile(OUTPUT_PATH, output, "utf8");
};

const run = async () => {
  const existing = await loadExistingCache();
  const fareharborTours = toursGenerated.filter(tour => tour.bookingProvider === "fareharbor");
  let remoteFetchDisabled = false;

  for (const tour of fareharborTours) {
    const reference = getFareharborItemFromUrl(tour.bookingUrl);
    if (!reference) continue;

    const key = toCacheKey(reference.companyShortname, reference.itemId);
    const fallback: FareharborTourContent = {
      sourceOperatorSlug: reference.companyShortname,
      sourceItemId: reference.itemId,
      heroImageUrl: tour.heroImage,
      sourceDescription: clampSnippet(stripHtml(tour.shortDescription ?? tour.longDescription)),
    };

    if (remoteFetchDisabled) {
      existing[key] = existing[key] ?? fallback;
      continue;
    }

    try {
      const payload = await fetchItemPayload(reference.companyShortname, reference.itemId);
      const imageCandidates = collectImageCandidates(payload);
      const preferredImage = imageCandidates[0] ?? fallback.heroImageUrl;
      existing[key] = {
        sourceOperatorSlug: reference.companyShortname,
        sourceItemId: reference.itemId,
        heroImageUrl: preferredImage,
        sourceDescription: pickDescription(payload) ?? fallback.sourceDescription,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (/ENETUNREACH|EAI_AGAIN|fetch failed|aborted/i.test(message)) {
        remoteFetchDisabled = true;
      }
      existing[key] = existing[key] ?? fallback;
    }
  }

  await writeCache(existing);
  console.log(`FareHarbor content enrichment updated for ${Object.keys(existing).length} items.`);
};

run().catch(error => {
  console.error(error);
  process.exit(1);
});
