import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

type CsvRow = Record<string, string>;

const DATA_DIR = path.resolve("data");
const OUTPUT_DIR = path.resolve("src/data/generated");

const sanitizeText = (value?: string) =>
  value?.replace(/\r/g, " ").replace(/\n/g, " ").trim() ?? "";

const parseCsvRows = (text: string) => {
  const rows: string[][] = [];
  let current = "";
  let row: string[] = [];
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === '"') {
      if (inQuotes && next === '"') {
        current += '"';
        index += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === "," && !inQuotes) {
      row.push(current);
      current = "";
      continue;
    }

    if (char === "\n" && !inQuotes) {
      row.push(current);
      rows.push(row);
      row = [];
      current = "";
      continue;
    }

    if (char !== "\r") {
      current += char;
    }
  }

  if (current.length || row.length) {
    row.push(current);
    rows.push(row);
  }

  return rows;
};

const parseCsv = (text: string): CsvRow[] => {
  const rows = parseCsvRows(text).filter((row) =>
    row.some((cell) => cell.trim().length > 0),
  );
  const [headers, ...dataRows] = rows;

  if (!headers) {
    return [];
  }

  return dataRows.map((row) => {
    const record: CsvRow = {};
    headers.forEach((header, index) => {
      record[header] = sanitizeText(row[index]);
    });
    return record;
  });
};

const writeGeneratedFile = (filename: string, rows: CsvRow[]) => {
  const contents = `export type CsvRow = Record<string, string>;

// This file is auto-generated by scripts/generate-tour-csv-data.ts. Do not edit manually.
export const ${filename}: CsvRow[] = ${JSON.stringify(rows, null, 2)};
`;
  writeFileSync(path.join(OUTPUT_DIR, `${filename}.generated.ts`), contents, "utf8");
};

const run = () => {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const australiaCsv = readFileSync(path.join(DATA_DIR, "australia.csv"), "utf8");
  writeGeneratedFile("australiaTourRows", parseCsv(australiaCsv));

  const europeCanoeingCsv = readFileSync(
    path.join(DATA_DIR, "europe/europe-canoeing.csv"),
    "utf8",
  );
  const europeCyclingCsv = readFileSync(
    path.join(DATA_DIR, "europe/europe-cycling.csv"),
    "utf8",
  );
  const europeHikingCsv = readFileSync(
    path.join(DATA_DIR, "europe/europe-hiking.csv"),
    "utf8",
  );

  const europeRows = [
    { name: "europeCanoeingRows", rows: parseCsv(europeCanoeingCsv) },
    { name: "europeCyclingRows", rows: parseCsv(europeCyclingCsv) },
    { name: "europeHikingRows", rows: parseCsv(europeHikingCsv) },
  ];

  europeRows.forEach(({ name, rows }) => {
    writeGeneratedFile(name, rows);
  });
};

run();
