import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const OUTPUT_PATH = path.resolve("src/data/generated/europe.generated.ts");

const CSV_SOURCES = [
  {
    constName: "europeCanoeingCsv",
    path: path.resolve("data/europe/europe-canoeing.csv"),
  },
  {
    constName: "europeCyclingCsv",
    path: path.resolve("data/europe/europe-cycling.csv"),
  },
  {
    constName: "europeHikingCsv",
    path: path.resolve("data/europe/europe-hiking.csv"),
  },
];

const escapeTemplateLiteral = (value: string) =>
  value.replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const generate = async () => {
  const outputs = await Promise.all(
    CSV_SOURCES.map(async (source) => {
      const contents = await readFile(source.path, "utf8");
      const escaped = escapeTemplateLiteral(contents);
      return `export const ${source.constName} = \`${escaped}\`;`;
    }),
  );

  const output = `// This file is auto-generated by scripts/generate-europe-generated-ts.ts. Do not edit manually.

${outputs.join("\n\n")}
`;

  await writeFile(OUTPUT_PATH, output, "utf8");
};

generate().catch((error) => {
  console.error("[generate-europe-generated-ts] Failed to generate:", error);
  process.exitCode = 1;
});
