import fs from "node:fs";
import path from "node:path";

type Enrichment = {
  ratingValue?: number;
  ratingCount?: number;
  price?: number;
  currency?: string;
};

function parseCsv(csv: string) {
  const lines = csv.trim().split(/\r?\n/);
  const header = lines.shift();
  if (!header) return {};

  const cols = header.split(",").map(s => s.trim());
  const idx = (name: string) => cols.indexOf(name);

  const iTourId = idx("tourId");
  const iRatingValue = idx("ratingValue");
  const iRatingCount = idx("ratingCount");
  const iPrice = idx("price");
  const iCurrency = idx("currency");

  const out: Record<string, Enrichment> = {};

  for (const line of lines) {
    if (!line.trim()) continue;
    const row = line.split(",").map(s => s.trim());

    const tourId = row[iTourId];
    if (!tourId) continue;

    const ratingValue = row[iRatingValue]
      ? Number(row[iRatingValue])
      : undefined;
    const ratingCount = row[iRatingCount]
      ? Number(row[iRatingCount])
      : undefined;
    const price = row[iPrice] ? Number(row[iPrice]) : undefined;
    const currency = row[iCurrency] || undefined;

    out[tourId] = { ratingValue, ratingCount, price, currency };
  }

  return out;
}

const repoRoot = process.cwd();
const csvPath = path.join(repoRoot, "data", "tourEnrichment.csv");
const outPath = path.join(
  repoRoot,
  "src",
  "data",
  "generated",
  "tourEnrichment.generated.ts"
);

const csv = fs.readFileSync(csvPath, "utf8");
const data = parseCsv(csv);

fs.mkdirSync(path.dirname(outPath), { recursive: true });

const file = `// AUTO-GENERATED by scripts/generate-tour-enrichment.ts. Do not edit by hand.\nexport type TourEnrichment = {\n  ratingValue?: number;\n  ratingCount?: number;\n  price?: number;\n  currency?: string;\n};\n\nexport const tourEnrichmentById: Record<string, TourEnrichment> = ${JSON.stringify(data, null, 2)} as const;\n`;

fs.writeFileSync(outPath, file, "utf8");
console.log(`Wrote ${outPath} (${Object.keys(data).length} rows)`);
