export type RetiredGuideRecord = {
  stateSlug: string;
  citySlug: string;
  activeTourCount: 0 | 1 | 2 | 3;
  redirectTo: string;
};
export type ProtectedLowInventoryGuideRecord = {
  stateSlug: string;
  citySlug: string;
  activeTourCount: 0 | 1 | 2 | 3;
  reason: string;
};
export const LOW_INVENTORY_GUIDES_REVIEWED = 200 as const;
export const PROTECTED_LOW_INVENTORY_GUIDES: ProtectedLowInventoryGuideRecord[] =
  [
    {
      stateSlug: "arizona",
      citySlug: "phoenix",
      activeTourCount: 0,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "arizona",
      citySlug: "scottsdale",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "california",
      citySlug: "napa",
      activeTourCount: 1,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "california",
      citySlug: "newport-beach",
      activeTourCount: 0,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "california",
      citySlug: "sacramento",
      activeTourCount: 2,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "colorado",
      citySlug: "boulder",
      activeTourCount: 3,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "florida",
      citySlug: "tampa",
      activeTourCount: 2,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "georgia",
      citySlug: "atlanta",
      activeTourCount: 1,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "hawaii",
      citySlug: "hilo",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "illinois",
      citySlug: "chicago",
      activeTourCount: 2,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "indiana",
      citySlug: "indianapolis",
      activeTourCount: 0,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "maine",
      citySlug: "bar-harbor",
      activeTourCount: 0,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "new-mexico",
      citySlug: "albuquerque",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "pennsylvania",
      citySlug: "philadelphia",
      activeTourCount: 3,
      reason: "top-50-us-city-guide",
    },
    {
      stateSlug: "south-carolina",
      citySlug: "charleston",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "texas",
      citySlug: "san-antonio",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "wyoming",
      citySlug: "cody",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "wyoming",
      citySlug: "jackson",
      activeTourCount: 2,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "wyoming",
      citySlug: "jackson-hole",
      activeTourCount: 0,
      reason: "flagship-tourism-destination",
    },
    {
      stateSlug: "wyoming",
      citySlug: "yellowstone-national-park",
      activeTourCount: 1,
      reason: "national-park-guide",
    },
  ];

export const RETIRED_LOW_INVENTORY_GUIDES: RetiredGuideRecord[] = [
  {
    stateSlug: "alaska",
    citySlug: "fairbanks",
    activeTourCount: 1,
    redirectTo: "/guides/us/alaska",
  },
  {
    stateSlug: "arizona",
    citySlug: "cottonwood",
    activeTourCount: 2,
    redirectTo: "/guides/us/arizona",
  },
  {
    stateSlug: "arizona",
    citySlug: "page",
    activeTourCount: 1,
    redirectTo: "/guides/us/arizona",
  },
  {
    stateSlug: "arizona",
    citySlug: "prescott",
    activeTourCount: 1,
    redirectTo: "/guides/us/arizona",
  },
  {
    stateSlug: "california",
    citySlug: "avalon",
    activeTourCount: 2,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "bonita",
    activeTourCount: 2,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "burlingame",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "carpinteria",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "indio",
    activeTourCount: 0,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "lake-elsinore",
    activeTourCount: 0,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "marina-del-rey",
    activeTourCount: 2,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "oceanside",
    activeTourCount: 3,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "pismo-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "poway",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "rio-linda",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "santee",
    activeTourCount: 2,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "solvang",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "sonoma",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "temecula",
    activeTourCount: 2,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "california",
    citySlug: "ventura",
    activeTourCount: 1,
    redirectTo: "/guides/us/california",
  },
  {
    stateSlug: "connecticut",
    citySlug: "colchester",
    activeTourCount: 2,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "connecticut",
    citySlug: "east-lyme",
    activeTourCount: 1,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "connecticut",
    citySlug: "montville",
    activeTourCount: 1,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "connecticut",
    citySlug: "new-london",
    activeTourCount: 2,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "connecticut",
    citySlug: "salisbury",
    activeTourCount: 1,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "connecticut",
    citySlug: "thomaston",
    activeTourCount: 1,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "connecticut",
    citySlug: "wolcott",
    activeTourCount: 1,
    redirectTo: "/guides/us/connecticut",
  },
  {
    stateSlug: "delaware",
    citySlug: "dewey-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "florida",
    citySlug: "apopka",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "bonita-springs",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "bradenton-beach",
    activeTourCount: 0,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "canal-point",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "cape-canaveral",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "clermont",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "cocoa-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "deland",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "delray-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "estero",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "eustis",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "fellsmere",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "fort-myers-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "fort-walton-beach",
    activeTourCount: 3,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "fort-white",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "gainesville",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "greenacres",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "gulfport",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "hallandale-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "hastings",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "homestead",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "homosassa",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "key-biscayne",
    activeTourCount: 0,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "kissimmee",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "lake-wales",
    activeTourCount: 3,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "lakeland",
    activeTourCount: 3,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "lecanto",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "lighthouse-point",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "matlacha",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "new-smyrna-beach",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "nokomis",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "north-fort-myers",
    activeTourCount: 3,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "north-miami",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "orange-city",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "osprey",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "oviedo",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "palm-harbor",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "pembroke-pines",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "pensacola-beach",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "riviera-beach",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "sanford",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "st-cloud",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "summerland-key",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "tarpon-springs",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "titusville",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "town-n-country",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "vero-beach",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "warrington",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "weston",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "winter-haven",
    activeTourCount: 2,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "florida",
    citySlug: "winter-park",
    activeTourCount: 1,
    redirectTo: "/guides/us/florida",
  },
  {
    stateSlug: "georgia",
    citySlug: "blairsville",
    activeTourCount: 2,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "braselton",
    activeTourCount: 1,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "covington",
    activeTourCount: 3,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "helen",
    activeTourCount: 2,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "juliette",
    activeTourCount: 1,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "leesburg",
    activeTourCount: 3,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "macon",
    activeTourCount: 2,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "peachtree-city",
    activeTourCount: 1,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "roswell",
    activeTourCount: 2,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "georgia",
    citySlug: "summerville",
    activeTourCount: 1,
    redirectTo: "/guides/us/georgia",
  },
  {
    stateSlug: "hawaii",
    citySlug: "haleiwa",
    activeTourCount: 3,
    redirectTo: "/guides/us/hawaii",
  },
  {
    stateSlug: "hawaii",
    citySlug: "hanalei",
    activeTourCount: 1,
    redirectTo: "/guides/us/hawaii",
  },
  {
    stateSlug: "hawaii",
    citySlug: "honomu",
    activeTourCount: 2,
    redirectTo: "/guides/us/hawaii",
  },
  {
    stateSlug: "idaho",
    citySlug: "coeur-dalene",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "kentucky",
    citySlug: "new-haven",
    activeTourCount: 2,
    redirectTo: "/guides/us/kentucky",
  },
  {
    stateSlug: "louisiana",
    citySlug: "abita-springs",
    activeTourCount: 1,
    redirectTo: "/guides/us/louisiana",
  },
  {
    stateSlug: "louisiana",
    citySlug: "baton-rouge",
    activeTourCount: 1,
    redirectTo: "/guides/us/louisiana",
  },
  {
    stateSlug: "louisiana",
    citySlug: "laplace",
    activeTourCount: 2,
    redirectTo: "/guides/us/louisiana",
  },
  {
    stateSlug: "louisiana",
    citySlug: "ponchatoula",
    activeTourCount: 1,
    redirectTo: "/guides/us/louisiana",
  },
  {
    stateSlug: "louisiana",
    citySlug: "vacherie",
    activeTourCount: 1,
    redirectTo: "/guides/us/louisiana",
  },
  {
    stateSlug: "louisiana",
    citySlug: "venice",
    activeTourCount: 3,
    redirectTo: "/guides/us/louisiana",
  },
  {
    stateSlug: "maine",
    citySlug: "bethel",
    activeTourCount: 2,
    redirectTo: "/guides/us/maine",
  },
  {
    stateSlug: "maine",
    citySlug: "harpswell",
    activeTourCount: 0,
    redirectTo: "/guides/us/maine",
  },
  {
    stateSlug: "maine",
    citySlug: "kennebunk",
    activeTourCount: 2,
    redirectTo: "/guides/us/maine",
  },
  {
    stateSlug: "maryland",
    citySlug: "cambridge",
    activeTourCount: 2,
    redirectTo: "/guides/us/maryland",
  },
  {
    stateSlug: "maryland",
    citySlug: "denton",
    activeTourCount: 1,
    redirectTo: "/guides/us/maryland",
  },
  {
    stateSlug: "maryland",
    citySlug: "edgewater",
    activeTourCount: 3,
    redirectTo: "/guides/us/maryland",
  },
  {
    stateSlug: "maryland",
    citySlug: "lusby",
    activeTourCount: 0,
    redirectTo: "/guides/us/maryland",
  },
  {
    stateSlug: "maryland",
    citySlug: "monkton",
    activeTourCount: 1,
    redirectTo: "/guides/us/maryland",
  },
  {
    stateSlug: "maryland",
    citySlug: "vienna",
    activeTourCount: 1,
    redirectTo: "/guides/us/maryland",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "beverly",
    activeTourCount: 0,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "brookline",
    activeTourCount: 1,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "chelsea",
    activeTourCount: 1,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "holbrook",
    activeTourCount: 0,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "lexington",
    activeTourCount: 1,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "mashpee",
    activeTourCount: 0,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "nantucket",
    activeTourCount: 2,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "north-andover",
    activeTourCount: 3,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "quincy",
    activeTourCount: 3,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "revere",
    activeTourCount: 1,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "sandwich",
    activeTourCount: 0,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "somerville",
    activeTourCount: 0,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "sudbury",
    activeTourCount: 3,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "massachusetts",
    citySlug: "winthrop",
    activeTourCount: 0,
    redirectTo: "/guides/us/massachusetts",
  },
  {
    stateSlug: "michigan",
    citySlug: "grosse-ile-township",
    activeTourCount: 1,
    redirectTo: "/guides/us/michigan",
  },
  {
    stateSlug: "michigan",
    citySlug: "lake-leelanau",
    activeTourCount: 0,
    redirectTo: "/guides/us/michigan",
  },
  {
    stateSlug: "michigan",
    citySlug: "mount-pleasant",
    activeTourCount: 2,
    redirectTo: "/guides/us/michigan",
  },
  {
    stateSlug: "michigan",
    citySlug: "traverse-city",
    activeTourCount: 1,
    redirectTo: "/guides/us/michigan",
  },
  {
    stateSlug: "minnesota",
    citySlug: "minneapolis",
    activeTourCount: 0,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "minnesota",
    citySlug: "stillwater",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "mississippi",
    citySlug: "natchez",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "missouri",
    citySlug: "branson",
    activeTourCount: 0,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "missouri",
    citySlug: "kansas-city",
    activeTourCount: 0,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "missouri",
    citySlug: "st-louis",
    activeTourCount: 0,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "atlantic-highlands",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "brick-township",
    activeTourCount: 2,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "edgewater",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "fieldsboro",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "hillsdale",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "keyport",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "lavallette",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "middletown-township",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "millville",
    activeTourCount: 0,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "ocean-city",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "shamong",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "wallington",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-jersey",
    citySlug: "wildwood-crest",
    activeTourCount: 1,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "new-mexico",
    citySlug: "las-cruces",
    activeTourCount: 0,
    redirectTo: "/guides/us/new-mexico",
  },
  {
    stateSlug: "new-york",
    citySlug: "hammondsport",
    activeTourCount: 2,
    redirectTo: "/guides/us/new-york",
  },
  {
    stateSlug: "new-york",
    citySlug: "napanoch",
    activeTourCount: 1,
    redirectTo: "/guides/us/new-york",
  },
  {
    stateSlug: "new-york",
    citySlug: "rushville",
    activeTourCount: 3,
    redirectTo: "/guides/us/new-york",
  },
  {
    stateSlug: "north-carolina",
    citySlug: "charlotte",
    activeTourCount: 0,
    redirectTo: "/guides/us/north-carolina",
  },
  {
    stateSlug: "north-carolina",
    citySlug: "highlands",
    activeTourCount: 1,
    redirectTo: "/guides/us/north-carolina",
  },
  {
    stateSlug: "north-carolina",
    citySlug: "kill-devil-hills",
    activeTourCount: 2,
    redirectTo: "/guides/us/north-carolina",
  },
  {
    stateSlug: "north-carolina",
    citySlug: "nags-head",
    activeTourCount: 1,
    redirectTo: "/guides/us/north-carolina",
  },
  {
    stateSlug: "north-carolina",
    citySlug: "raleigh",
    activeTourCount: 1,
    redirectTo: "/guides/us/north-carolina",
  },
  {
    stateSlug: "ohio",
    citySlug: "cincinnati",
    activeTourCount: 0,
    redirectTo: "/guides/us/ohio",
  },
  {
    stateSlug: "ohio",
    citySlug: "cleveland",
    activeTourCount: 0,
    redirectTo: "/guides/us/ohio",
  },
  {
    stateSlug: "ohio",
    citySlug: "columbus",
    activeTourCount: 0,
    redirectTo: "/guides/us/ohio",
  },
  {
    stateSlug: "ohio",
    citySlug: "lancaster",
    activeTourCount: 2,
    redirectTo: "/guides/us/ohio",
  },
  {
    stateSlug: "ohio",
    citySlug: "rockbridge",
    activeTourCount: 1,
    redirectTo: "/guides/us/ohio",
  },
  {
    stateSlug: "oklahoma",
    citySlug: "oklahoma-city",
    activeTourCount: 2,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "oregon",
    citySlug: "cascade-locks",
    activeTourCount: 1,
    redirectTo: "/guides/us/oregon",
  },
  {
    stateSlug: "pennsylvania",
    citySlug: "bethlehem",
    activeTourCount: 0,
    redirectTo: "/guides/us/pennsylvania",
  },
  {
    stateSlug: "pennsylvania",
    citySlug: "gettysburg",
    activeTourCount: 1,
    redirectTo: "/guides/us/pennsylvania",
  },
  {
    stateSlug: "rhode-island",
    citySlug: "warwick",
    activeTourCount: 3,
    redirectTo: "/guides/us/rhode-island",
  },
  {
    stateSlug: "south-carolina",
    citySlug: "columbia",
    activeTourCount: 0,
    redirectTo: "/guides/us/south-carolina",
  },
  {
    stateSlug: "south-carolina",
    citySlug: "mount-pleasant",
    activeTourCount: 2,
    redirectTo: "/guides/us/south-carolina",
  },
  {
    stateSlug: "south-dakota",
    citySlug: "rapid-city",
    activeTourCount: 2,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "tennessee",
    citySlug: "franklin",
    activeTourCount: 1,
    redirectTo: "/guides/us/tennessee",
  },
  {
    stateSlug: "tennessee",
    citySlug: "granville",
    activeTourCount: 1,
    redirectTo: "/guides/us/tennessee",
  },
  {
    stateSlug: "tennessee",
    citySlug: "greenbrier",
    activeTourCount: 0,
    redirectTo: "/guides/us/tennessee",
  },
  {
    stateSlug: "tennessee",
    citySlug: "johnson-city",
    activeTourCount: 1,
    redirectTo: "/guides/us/tennessee",
  },
  {
    stateSlug: "tennessee",
    citySlug: "williamsport",
    activeTourCount: 1,
    redirectTo: "/guides/us/tennessee",
  },
  {
    stateSlug: "texas",
    citySlug: "dallas",
    activeTourCount: 0,
    redirectTo: "/guides/us/texas",
  },
  {
    stateSlug: "texas",
    citySlug: "fort-worth",
    activeTourCount: 1,
    redirectTo: "/guides/us/texas",
  },
  {
    stateSlug: "utah",
    citySlug: "salt-lake-city",
    activeTourCount: 0,
    redirectTo: "/guides/us/utah",
  },
  {
    stateSlug: "vermont",
    citySlug: "manchester",
    activeTourCount: 3,
    redirectTo: "/guides/us/vermont",
  },
  {
    stateSlug: "washington",
    citySlug: "chelan",
    activeTourCount: 0,
    redirectTo: "/guides/us/washington",
  },
  {
    stateSlug: "west-virginia",
    citySlug: "harpers-ferry",
    activeTourCount: 2,
    redirectTo: "/guides/us",
  },
  {
    stateSlug: "wisconsin",
    citySlug: "washburn",
    activeTourCount: 2,
    redirectTo: "/guides/us/wisconsin",
  },
];

const retiredGuideRedirects = new Map(
  RETIRED_LOW_INVENTORY_GUIDES.map(guide => [
    `${guide.stateSlug}/${guide.citySlug}`,
    guide.redirectTo,
  ])
);

const protectedLowInventoryGuideKeys = new Set(
  PROTECTED_LOW_INVENTORY_GUIDES.map(
    guide => `${guide.stateSlug}/${guide.citySlug}`
  )
);

export const getRetiredGuideRedirect = (
  stateSlug: string,
  citySlug: string
): string | null =>
  retiredGuideRedirects.get(`${stateSlug}/${citySlug}`) ?? null;

export const isRetiredLowInventoryGuide = (
  stateSlug: string,
  citySlug: string
): boolean => Boolean(getRetiredGuideRedirect(stateSlug, citySlug));

export const isProtectedLowInventoryGuide = (
  stateSlug: string,
  citySlug: string
): boolean => protectedLowInventoryGuideKeys.has(`${stateSlug}/${citySlug}`);
