const BLACKLIST = [
  /one of the most valuable things to do/i,
  /balanced itinerary/i,
  /travelers comparing attractions/i,
  /easy recommendation/i,
  /plan for 60 to 150 minutes/i,
  /you should/i,
  /pair this with nearby dining/i,
  /established network of cultural and public places/i,
  /identifiable physical features/i,
  /city-level events across the year/i,
  /civic references/i,
  /clear sense of place/i,
  /published reference/i,
  /documented/i,
  /This summary reflects/i,
  /reference sources/i,
  /urban system/i,
  /recognized municipality/i,
  /administrative/i,
  /civic administration/i,
  /public records generally/i,
  /build each day/i,
  /anchor area/i,
  /reduce transit time/i,
  /first-time visitors/i,
  /pair iconic/i,
];

export const validateNoBoilerplate = (description: string): boolean =>
  !BLACKLIST.some(pattern => pattern.test(description));
