// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborKeyWestLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "176775",
    "company": "floridakeysventures",
    "title": "Key West History And Culture Southernmost Walking Tour",
    "publicPath": "/destinations/florida/key-west/tours/key-west-history-and-culture-southernmost-walking-tour-176775",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The walk includes the Southernmost Point. Guests stay on foot the whole time, pausing while the guide talks at each site. They stand at the sites while the explanation is given. Guests keep walking while that account is given, moving at the guide's pace. The explanation happens outdoors, in front of the buildings, and the group moves on only after it is given.",
      "Each pause is there so guests can look at the place the story belongs to."
    ],
    "schemaDescription": "Walking tour in Key West with time at the Southernmost Point while a guide explains each outdoor stop.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/0XJii9coR2a45nUfjWJD"
    ],
    "productImage": "https://cdn.filestackcontent.com/4HsbXVxTRSXODU1F49pa",
    "wordCount": 78,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "107 Fitzpatrick St Key West, FL 33040",
    "visiblePriceLabel": "From $49.99",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+",
        "amountLabel": "$49.99"
      },
      {
        "label": "Child",
        "note": "Ages 7-11",
        "amountLabel": "$39.99"
      },
      {
        "label": "Toddler",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "49.99",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridakeysventures/items/176775/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "203230",
    "company": "floridakeysventures",
    "title": "Key West Historic Bahama Village & Hemingway Heritage",
    "publicPath": "/destinations/florida/key-west/tours/key-west-historic-bahama-village-and-hemingway-heritage-203230",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The walk covers Key West's historic districts and Old Town. Guests stay on foot the whole time, pausing while the guide talks at each site. They stand at the sites while the explanation is given. Guests keep walking while that account is given, moving at the guide's pace.",
      "The explanation happens outdoors, in front of the buildings, and the group moves on only after it is given. Each pause is there so guests can look at the place the story belongs to."
    ],
    "schemaDescription": "Walking tour of Key West historic districts and Old Town. The group stays on foot while a guide talks at each site.",
    "highlights": [
      "1.5 walking tour",
      "Groups are capped at 12"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/Zjd7meM5Tz2cNHinQ1t9"
    ],
    "productImage": "https://cdn.filestackcontent.com/7EnDEvYSfK01EcfWuxd1",
    "wordCount": 82,
    "durationLabel": "1.5",
    "durationIso": null,
    "meetingLocation": "516 Duval Street Key West, FL 33040",
    "visiblePriceLabel": "From $56.99",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+",
        "amountLabel": "$56.99"
      },
      {
        "label": "Child",
        "note": "Ages 7-11",
        "amountLabel": "$39.99"
      },
      {
        "label": "Toddler",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "56.99",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridakeysventures/items/203230/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "104492",
    "company": "keywestfishing-charters",
    "title": "Cowgirl 45' Premium Offshore Fishing Charter",
    "publicPath": "/destinations/florida/key-west/tours/cowgirl-45-premium-offshore-fishing-charter-104492",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Fish the waters off Key West aboard Cowgirl, a 45-foot Hatteras available for private offshore charters of four to twelve hours. With a maximum of six guests, the trip can range from a half-day introduction to a long run into deeper water.",
      "Depending on season and conditions, the crew may work reefs, wrecks or offshore grounds for species such as mahi-mahi, wahoo, tuna, sailfish, snapper and sharks. Fishing success and particular species are never guaranteed. An air-conditioned cabin provides a break from the weather between bites.",
      "A captain and mate accompany each trip. Bait, rods, reels, lures, tackle, Florida fishing licenses, ice and coolers are listed as included, and legal catch can be cleaned and bagged at the dock. Guests bring their own food and drinks."
],
    "schemaDescription": "Private offshore fishing charter on a 45-foot Hatteras out of Key West for up to six guests, offered for 4, 6, 8, 10, or 12 hours. A captain, a mate, and tackle are included.",
    "highlights": [
      "4- to 12-hour harbor outing in Key West",
      "Captain and mate on every trip"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/KLbmMCxcR7iJvPIwv4d9"
    ],
    "productImage": "https://cdn.filestackcontent.com/UxWDijTVS9CElGrgZCj8",
    "wordCount": 126,
    "durationLabel": "4-12 Hours",
    "durationIso": null,
    "meetingLocation": "1801 N Roosevelt Blvd, Key West, Florida 33040",
    "visiblePriceLabel": "From $1,050",
    "priceRows": [
      {
        "label": "Half Day Private Charter",
        "note": "4 Hours | Price Includes up to 6 People | All Ages",
        "amountLabel": "$1,050"
      },
      {
        "label": "3/4 Day Private Charter",
        "note": "6 Hours | Price Includes up to 6 People | All Ages",
        "amountLabel": "$1,350"
      },
      {
        "label": "Full Day Private Charter",
        "note": "8 Hours | Price Includes up to 6 People | All Ages",
        "amountLabel": "$1,550"
      },
      {
        "label": "10 Hour Charter",
        "note": "10 Hours | Price Includes up to 6 People | All Ages",
        "amountLabel": "$1,750"
      },
      {
        "label": "12 Hour Charter",
        "note": "12 Hours | Price Includes up to 6 People | All Ages",
        "amountLabel": "$1,950"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1050.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 1022,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.8 from 1022 reviews on GET https://fareharbor.com/api/v1/companies/keywestfishing-charters/items/104492/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "638390",
    "company": "laromayachtsflorida",
    "title": "The Atlantia",
    "publicPath": "/destinations/florida/key-west/tours/the-atlantia-638390",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The Atlantia is a power catamaran of 64 feet, with a beam of 33 feet, chartered from Key West for four to eight hours. Six staterooms, six bathrooms, and crew quarters are on board. Up to 12 guests can stay overnight, and a day charter also takes up to 12.",
      "The galley has an island and an industrial dishwasher. A hood sits over the full-size range. The oven is full size as well, and the sink is a double bay. The salon has a television that retracts, plus a lounge and dining area with two tables that convert. Decks are teak. Lounges sit at the bow and at the stern. Outside there are two refrigerators, sinks, and a machine for ice. Navigation gear is at the helm."
    ],
    "schemaDescription": "Private charter of the 64-foot Atlantia power catamaran in Key West, booked for four to eight hours, with six staterooms and room for up to 12 guests.",
    "highlights": [
      "4- to 8-hour guided outing in Key West",
      "Groups stay at a maximum of 12 guests"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/UV7VbaC8RwKQanIogE8b",
    "wordCount": 128,
    "durationLabel": "4 - 8 Hours",
    "durationIso": null,
    "meetingLocation": "7001 Shrimp Road Key West, FL 33040",
    "visiblePriceLabel": "From $6,000",
    "priceRows": [
      {
        "label": "Eight Hour Charter",
        "note": "Up to 12 Guests",
        "amountLabel": "$6,000"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "6000.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/laromayachtsflorida/items/638390/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "638423",
    "company": "laromayachtsflorida",
    "title": "The \"Somewhere\"",
    "publicPath": "/destinations/florida/key-west/tours/the-somewhere-638423",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The Somewhere is a Lagoon 450 F flybridge catamaran chartered in Key West for four to eight hours, with a maximum of 12 guests. It works for a couple and also for a larger group. The cockpit is large. The flybridge keeps the lines and controls within reach. A forward cockpit is there for the breeze.",
      "Below, there are four cabins, each with an ensuite head and a separate shower, and headroom of 6 feet 6 inches or more. The saloon has a C-shaped galley and windows with a full circle of views. Sliding doors meet flush floors and decks."
    ],
    "schemaDescription": "Charter of the Lagoon 450 F flybridge catamaran Somewhere in Key West for four to eight hours, for up to 12 guests, with four cabins and a flybridge.",
    "highlights": [
      "4- to 8-hour guided outing in Key West",
      "Lagoon",
      "Groups stay at a maximum of 12 guests"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/decacu4jS1KjdaOl3XbS",
    "wordCount": 101,
    "durationLabel": "4 - 8 Hours",
    "durationIso": null,
    "meetingLocation": "7001 Shrimp Road Key West, FL 33040",
    "visiblePriceLabel": "From $4,500",
    "priceRows": [
      {
        "label": "Eight Hour Charter",
        "note": "Up to 12 Guests",
        "amountLabel": "$4,500"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "4500.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/laromayachtsflorida/items/638423/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "639170",
    "company": "laromayachtsflorida",
    "title": "Sunset Atlantia",
    "publicPath": "/destinations/florida/key-west/tours/sunset-atlantia-639170",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "See the Key West sunset from Atlantia, a 64-foot power catamaran with a broad 33-foot beam. The two-hour evening charter accommodates up to 12 guests and provides substantially more interior and deck space than a small sightseeing boat.",
      "The vessel has teak deck areas at the bow and stern, outdoor refrigeration and sinks, and an interior salon with convertible tables. Six staterooms and bathrooms are aboard, along with a full galley. These amenities make the boat itself an important part of the experience while the evening light changes over the Keys.",
      "The charter departs from Shrimp Road in Key West. Confirm boarding time, food and beverage arrangements and which spaces are available to guests during the sunset outing. The sailing course depends on weather and water conditions."
],
    "schemaDescription": "Two-hour evening charter in Key West on the 64-foot Atlantia power catamaran, for up to 12 guests, with six staterooms and a full galley.",
    "highlights": [
      "two-hour guided outing in Key West",
      "Groups stay at a maximum of 12 guests"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/ffg3ALRnRL265ybaJwEu",
    "wordCount": 127,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "7001 Shrimp Road Key West, FL 33040",
    "visiblePriceLabel": "From $2,000",
    "priceRows": [
      {
        "label": "Sunset Cruise",
        "note": "Up to 12 Guests",
        "amountLabel": "$2,000"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "2000.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/laromayachtsflorida/items/639170/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "639172",
    "company": "laromayachtsflorida",
    "title": "Sunset \"Somewhere\"",
    "publicPath": "/destinations/florida/key-west/tours/sunset-somewhere-639172",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Spend two evening hours aboard a Lagoon 450 F flybridge catamaran for a private-style Key West sunset experience. The vessel accommodates up to 12 guests and combines broad outdoor spaces with an interior designed for panoramic views.",
      "A large cockpit and elevated flybridge create several places to enjoy the breeze, while a forward cockpit offers another open-air perspective. Inside, the saloon is surrounded by windows and connects to a C-shaped galley. Four cabins each have their own head and separate shower, although the sunset cruise is centered on shared deck and salon spaces.",
      "Departure is from Shrimp Road in Key West. Confirm the exact boarding time, food and beverage arrangements and which onboard areas are available during the charter. Weather determines the evening course and sunset visibility."
],
    "schemaDescription": "Two-hour evening charter in Key West on the Lagoon 450 F flybridge catamaran Somewhere, for up to 12 guests, with four cabins and a flybridge.",
    "highlights": [
      "two-hour guided outing in Key West",
      "Lagoon",
      "Groups stay at a maximum of 12 guests"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/i4ADNzRdS3iashVlHD1h",
    "wordCount": 127,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "7001 Shrimp Road Key West, FL 33040",
    "visiblePriceLabel": "From $1,500",
    "priceRows": [
      {
        "label": "Sunset Cruise",
        "note": "Up to 12 Guests",
        "amountLabel": "$1,500"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1500.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/laromayachtsflorida/items/639172/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "626355",
    "company": "namastealldaykeywest",
    "title": "Tailored Sandbar Experience",
    "publicPath": "/destinations/florida/key-west/tours/tailored-sandbar-experience-626355",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Escape Key West's busier waterfront on a four-hour private charter designed around time at a sandbar. With a maximum of six guests, the experience emphasizes a relaxed stretch in the shallow waters of the Florida Keys rather than a crowded shared excursion.",
      "The captain selects an appropriate sandbar according to tide, wind and boat traffic, with the goal of finding space away from concentrations of other boats when conditions permit. From the water, the low-lying Keys landscape and open horizon provide the backdrop. No particular sandbar should be assumed in advance.",
      "The listed meeting point is on Shrimp Road in Key West. Confirm what is provided aboard, swimming expectations and the day's likely destination before departure. Sun protection is especially important during several hours on exposed water."
],
    "schemaDescription": "Private sandbar charter in Key West, held away from a crowd of other boats.",
    "highlights": [
      "four-hour harbor outing in Key West",
      "Groups stay at a maximum of 6 guests"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/VjRAjbQwSqi0xdZMZdY1"
    ],
    "productImage": "https://cdn.filestackcontent.com/eWvlhjg8TiS4pCYrHPMa",
    "wordCount": 127,
    "durationLabel": "4 hours",
    "durationIso": "PT4H",
    "meetingLocation": "7001 Shrimp Rd, Key West, FL, USA",
    "visiblePriceLabel": "From $750",
    "priceRows": [
      {
        "label": "Half Day Charter",
        "note": "",
        "amountLabel": "$750"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "750.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/namastealldaykeywest/items/626355/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "417200",
    "company": "saltysandbars",
    "title": "Half Day Charter 4hrs Boston Whaler",
    "publicPath": "/destinations/florida/key-west/tours/half-day-charter-4hrs-boston-whaler-417200",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Spend four private hours on a Boston Whaler 230 Vantage with a captain, giving your group time to explore Key West's surrounding waters without sharing the boat. The bow-rider seats up to six comfortably and includes both open lounging space and shade.",
      "The charter is intentionally flexible rather than tied to a fixed sightseeing timetable. Depending on conditions and your priorities, the captain can discuss accessible destinations and time on the water. The boat includes a bow lounge, sun pad, Bluetooth audio, freshwater shower and a preparation sink.",
      "Fuel, a cooler with ice, bottled water, soda and chips are listed as included. Departure is from the Palm Avenue Causeway area. Discuss desired activities and any swimming plans before departure so the four-hour window can be used effectively."
],
    "schemaDescription": "Four-hour private charter on a Boston Whaler 230 Vantage bow-rider in Key West, with a captain and seating for six.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/tAXXbINpRYmNV8fSCzEI"
    ],
    "productImage": "https://cdn.filestackcontent.com/BNWLrJ0QdCQUX1Dl43zA",
    "wordCount": 127,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "811 Palm Ave Cswy 10 Key West, FL 33040",
    "visiblePriceLabel": "From $649",
    "priceRows": [
      {
        "label": "Half Day Charter",
        "note": "Up to 6 guests • 4 Hours",
        "amountLabel": "$649"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "649.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 187,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 187 reviews on GET https://fareharbor.com/api/v1/companies/saltysandbars/items/417200/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "417207",
    "company": "saltysandbars",
    "title": "3/4 Day 6hrs Boston Whaler",
    "publicPath": "/destinations/florida/key-west/tours/34-day-6hrs-boston-whaler-417207",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Extend the private Key West experience to six hours aboard a Boston Whaler 230 Vantage. The additional time gives a group of up to six more flexibility to cruise, linger at a favorite spot or combine activities without the pace of a shorter charter.",
      "The bow-rider has a lounge and sun pad forward, shaded seating, Bluetooth audio, a freshwater shower and a preparation sink. A captain handles the boat, while the itinerary remains flexible rather than following a shared-tour schedule. Weather and sea conditions determine which areas are practical on the day.",
      "Fuel, a cooler with ice, bottled water, soda and chips are listed as included. The charter departs from the Palm Avenue Causeway area in Key West. Confirm preferred activities, boarding details and what to bring before arrival."
],
    "schemaDescription": "Six-hour private charter on a newer Boston Whaler 230 Vantage bow-rider in Key West, with a captain and seating for six.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/SgVH47iFTRiTrmuNYhZ5"
    ],
    "productImage": "https://cdn.filestackcontent.com/YEuiJ9MCSLOuMzZtp2y3",
    "wordCount": 129,
    "durationLabel": "6 Hours",
    "durationIso": "PT6H",
    "meetingLocation": "811 Palm Ave Cswy 10 Key West, FL 33040",
    "visiblePriceLabel": "From $849",
    "priceRows": [
      {
        "label": "Full Day Charter",
        "note": "Up to 6 guests • 6 Hours",
        "amountLabel": "$849"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "849.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 187,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 187 reviews on GET https://fareharbor.com/api/v1/companies/saltysandbars/items/417207/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "515385",
    "company": "saltysandbars",
    "title": "5Hour Multiple Sandbar Hangout Boston Whaler",
    "publicPath": "/destinations/florida/key-west/tours/5hour-multiple-sandbar-hangout-boston-whaler-515385",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Spend about five private hours on a Boston Whaler exploring Key West's shallow-water recreation areas and settling in at a sandbar. The open powerboat format suits a relaxed day built around being on the water rather than following a narrated sightseeing circuit.",
      "A sandbar stop can mean swimming, wading and simply enjoying the clear shallows, with the exact location selected according to tide, wind and boat traffic. Because the charter is private, the pace is centered on your group within the available time. A Bluetooth sound system is installed aboard the boat.",
      "Departure is from the Palm Avenue Causeway area in Key West. Confirm what drinks, snacks, shade and water equipment are included, and ask the operator about the planned sandbar and current conditions before setting out."
],
    "schemaDescription": "Private sandbar charter of about five hours on a Boston Whaler in Key West, with a captain aboard.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/jLcExHEVRlKUVfGnvsfT"
    ],
    "productImage": "https://cdn.filestackcontent.com/UfxH7cWARrKPdXE5OUQA",
    "wordCount": 127,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "811 Palm Ave Cswy 10 Key West, FL 33040",
    "visiblePriceLabel": "From $749",
    "priceRows": [
      {
        "label": "Five Hour Sandbar",
        "note": "Up to 6 People",
        "amountLabel": "$749"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "749.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 187,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 187 reviews on GET https://fareharbor.com/api/v1/companies/saltysandbars/items/515385/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "26077",
    "company": "schoonerjolly",
    "title": "Florida Keys Sunset Sail",
    "publicPath": "/destinations/florida/key-west/tours/florida-keys-sunset-sail-26077",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Watch the sun drop toward the Gulf on a two-hour sail from Key West. The route gives passengers a water-level view of the island's historic waterfront as daylight changes into the softer colors of evening.",
      "The operator lists the Historic Seaport, Key West Bight, Mallory Square and Fort Zachary Taylor among the sights, along with the Navy Mole, Truman Annex and Harry S. Truman's Little White House area. Christmas Tree Island is also associated with the route. Actual views depend on the sailing course and conditions.",
      "This is a sightseeing sail rather than a sequence of shore stops. Confirm the departure point and boarding time before travel, since sunset schedules shift through the year. Bring a light layer for the breeze even after a warm Key West afternoon."
],
    "schemaDescription": "Two-hour sunset sail in Key West, passing the Historic Seaport, Key West Bight, Mallory Square, and Fort Zachary Taylor.",
    "highlights": [
      "two-hour harbor outing in Key West",
      "Christmas Tree Island and Mallory Square"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/jkb8Ow99SMKrclylzRcB"
    ],
    "productImage": "https://cdn.filestackcontent.com/rYOWrfRTpiNlWy9n0MOz",
    "wordCount": 128,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Key West, FL",
    "visiblePriceLabel": "From $95",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13 & up",
        "amountLabel": "$95"
      },
      {
        "label": "Child",
        "note": "Ages 4-12",
        "amountLabel": "$45"
      },
      {
        "label": "Toddler",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "95.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 487,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 487 reviews on GET https://fareharbor.com/api/v1/companies/schoonerjolly/items/26077/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "628106",
    "company": "sixfinsjetskirental",
    "title": "SIX FINS KEY WEST: 2-HOUR FLAGSHIP GUIDED JET SKI TOUR",
    "publicPath": "/destinations/florida/key-west/tours/six-fins-key-west-2-hour-flagship-guided-jet-ski-tour-628106",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Circle Key West by personal watercraft on a two-hour guided route covering roughly 28 miles. Six Fins departs from the Perry Hotel and Marina using Yamaha VX WaveRunners, with a Coast Guard-licensed lead guide keeping the small group together and adding context at stops.",
      "The route is designed to show the island from the water while giving riders an active experience between landmarks. Marine life may be seen along the way, but sightings are not guaranteed. Conditions can alter the exact course or stops.",
      "Drivers must be at least 16; passengers may be as young as six. Each machine carries one driver and up to two passengers with a 530-pound combined limit. Drivers born on or after January 1, 1988 need the required Florida boating-safety credential. Confirm current licensing requirements before arrival."
],
    "schemaDescription": "Two-hour guided jet ski circumnavigation of Key West from the Perry Hotel and Marina, on Yamaha VX Waverunners with a Coast Guard-licensed lead guide.",
    "highlights": [
      "Brand-new Yamaha VX Waverunners"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/j1pbM7bJT36f6xNJFVPP"
    ],
    "productImage": "https://cdn.filestackcontent.com/jEA9hOfQj2oZMMAyvqf4",
    "wordCount": 132,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "7025 Shrimp Rd. at Coconut Row, Dock J, Slip 1 Key West, FL 33040",
    "visiblePriceLabel": "From $209",
    "priceRows": [
      {
        "label": "Driver",
        "note": "",
        "amountLabel": "$209"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "209.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinsjetskirental/items/628106/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "22878",
    "company": "southpointdiverskw",
    "title": "Morning 2-Tank Dive: Vandenberg Wreck",
    "publicPath": "/destinations/florida/key-west/tours/morning-2-tank-dive-vandenberg-wreck-22878",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Southpoint Divers runs a morning dive of two tanks on the USNS General Hoyt S. Vandenberg. The ship was sunk in 2009. It is Key West's largest artificial reef and the second-largest artificial reef anywhere. It lies about six miles south-southeast of Key West, inside the national marine sanctuary of the Florida Keys, on the bottom at 140 feet. Divers are limited to 100 feet, which is the deck.",
      "Corals cover the steel, and fish use the deck and the corridors. Two tanks are the dive plan. Also included are weights, gloves, water, ice in a cooler, and a boat with a cover."
    ],
    "schemaDescription": "Morning two-tank dive on the USNS General Hoyt S. Vandenberg, sunk in 2009 about six miles from Key West. Divers are limited to the deck at 100 feet.",
    "highlights": [
      "4.5 guided outing",
      "Florida Keys National Marine Sanctuary",
      "tanks & weights"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/D0iqBBR02Z9H4OO25wwq"
    ],
    "productImage": "https://cdn.filestackcontent.com/mEbdkwwRdiJILAx7Cnow",
    "wordCount": 105,
    "durationLabel": "4.5",
    "durationIso": null,
    "meetingLocation": "606 Front Street Key West Florida 33040",
    "visiblePriceLabel": "From $65",
    "priceRows": [
      {
        "label": "Certified Diver with Gear Package",
        "note": "Tanks, weights, BCD & regulator (wetsuit if need)",
        "amountLabel": "$174"
      },
      {
        "label": "Certified Diver tanks/weights only",
        "note": "Option to add gear piece by piece",
        "amountLabel": "$134"
      },
      {
        "label": "Rider",
        "note": "",
        "amountLabel": "$65"
      },
      {
        "label": "Deep / Wreck Certification",
        "note": "",
        "amountLabel": "$859"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "65.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/southpointdiverskw/items/22878/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "624612",
    "company": "undergrounddonutour",
    "title": "Key West Southernmost Sweet Treats Tour",
    "publicPath": "/destinations/florida/key-west/tours/key-west-southernmost-sweet-treats-tour-624612",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Walk through Key West's colorful Old Town on a two-hour food tour built around sweets and local treats. The outing begins at Glazed Donuts before continuing through tropical streets and historic neighborhoods with a guide adding island stories along the way.",
      "Tastings rotate, but the operator mentions possibilities including fresh donuts, Key lime pie, cookies, ice cream and conch fritters—the latter sometimes playfully described as Key West's savory 'donuts.' The exact lineup can change, so individual foods should not be treated as guaranteed on every departure.",
      "Groups are capped at 20. The route does not finish where it starts, and the operator lists the experience as accessible to strollers and wheelchairs. Tips and parking are extra. Confirm dietary restrictions and the current tasting lineup before arrival on Duval Street."
],
    "schemaDescription": "Two-hour Key West walk for up to 20 guests, starting at Glazed Donuts and continuing through Old Town for rotating sweets and island history.",
    "highlights": [
      "two-hour walking tour in Key West",
      "Groups stay at a maximum of 20 guests"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/ucavwJ29Qq62vEB34mOM"
    ],
    "productImage": "https://cdn.filestackcontent.com/HPV1P8fNS2qRfCdHLUZP",
    "wordCount": 129,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": "430 Duval Street Key West, FL 33040",
    "visiblePriceLabel": "From $65",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 11+",
        "amountLabel": "$65"
      },
      {
        "label": "Kid",
        "note": "Ages 10 & Under",
        "amountLabel": "$55"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "65.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1463,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 5 from 1463 reviews on GET https://fareharbor.com/api/v1/companies/undergrounddonutour/items/624612/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  }
];
