// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborStPetersburgLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "520862",
    "company": "fatherdaughtercharters",
    "title": "Sunset Sail",
    "publicPath": "/destinations/florida/st-petersburg/tours/sunset-sail-520862",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests go out for a sunset sail. The water is usually calmer once the afternoon wind drops. From the water, guests see SkyBeach Resort Marina."
    ],
    "schemaDescription": "Sunset sail from SkyBeach Resort Marina, usually on calmer water after the afternoon wind drops.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/dr5U0nMoQgSgV5ob9qXI"
    ],
    "productImage": "https://cdn.filestackcontent.com/0d4wY48USeaKHeRSYXmO",
    "wordCount": 25,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6800 Sunshine Drive South St. Petersburg, FL 33705",
    "visiblePriceLabel": "From $899",
    "priceRows": [
      {
        "label": "Sunset Sail",
        "note": "2 hours • Ages 3+",
        "amountLabel": "$899"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "899.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/fatherdaughtercharters/items/520862/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "521546",
    "company": "fatherdaughtercharters",
    "title": "Full-Day Sail",
    "publicPath": "/destinations/florida/st-petersburg/tours/full-day-sail-521546",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This full-day private sail lets the group choose one destination: Egmont Key, Anna Maria, or Shell Key. Egmont Key is a historic island with gopher tortoises, the remains of Fort Dade, and secluded beaches. Anna Maria is a coastal town. Shell Key is set aside for shelling and undeveloped shoreline. The charter length is eight hours."
    ],
    "schemaDescription": "Full-day private sail with a choice of Egmont Key, Anna Maria, or Shell Key. Egmont Key includes the remains of Fort Dade.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/7JZkwDwQ4WAYNCezIEcF"
    ],
    "productImage": "https://cdn.filestackcontent.com/ABOPSt8QGquxdkSwgxF2",
    "wordCount": 57,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6800 Sunshine Drive South St. Petersburg, FL 33705",
    "visiblePriceLabel": "From $1,495",
    "priceRows": [
      {
        "label": "Full-Day Private Charter",
        "note": "8 hours • Ages 3+",
        "amountLabel": "$1,495"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1495.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/fatherdaughtercharters/items/521546/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "521595",
    "company": "fatherdaughtercharters",
    "title": "Dolphin Spotting Sail",
    "publicPath": "/destinations/florida/st-petersburg/tours/dolphin-spotting-sail-521595",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The skyline is the main view as the boat moves through the harbor. Guests sail on a catamaran for this cruise."
    ],
    "schemaDescription": "Two-hour dolphin-spotting sail on a catamaran, with the city skyline as the main view from the harbor.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/PeqtaSvTCygDg03N4ZCg"
    ],
    "productImage": "https://cdn.filestackcontent.com/eDDIPtISXaeUdvdqRhl7",
    "wordCount": 21,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6800 Sunshine Drive South St. Petersburg, FL 33705",
    "visiblePriceLabel": "From $900",
    "priceRows": [
      {
        "label": "Quarter-Day Private Charter",
        "note": "2 hours • Ages 3+",
        "amountLabel": "$900"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "900.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/fatherdaughtercharters/items/521595/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
