// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborDelMarLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "481283",
    "company": "animalcenter",
    "title": "HowlOWeen Harvest Family Festival",
    "publicPath": "/destinations/california/del-mar/tours/howloween-harvest-family-festival-481283",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Families meet animal ambassadors and move between activity stations. Trick-or-treat stops are set around the activity areas. Face painting is offered along with the animal visits. A small pumpkin patch is on site, and each child may take one pumpkin. A few rooms are arranged as a mild haunt for young children.",
      "Music plays while the stations stay open. Staff stay with the group while the animals are part of the program."
    ],
    "schemaDescription": "Four-hour family festival with animal ambassadors, activity stations, and trick-or-treat stops.",
    "highlights": [
      "4 hours guided outing",
      "Howl-O-Ween Harvest Family Festival",
      "Festive, themed music throughout the event"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/9H7WEa7xR9WevF7kDcEg"
    ],
    "productImage": "https://cdn.filestackcontent.com/14TeaaaLR7St7gA8WAoW",
    "wordCount": 74,
    "durationLabel": "4 hours",
    "durationIso": "PT4H",
    "meetingLocation": "6447 Helen Woodward Way Rancho Santa Fe, CA 92067",
    "visiblePriceLabel": "From $9.43",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18+",
        "amountLabel": "$9.43"
      },
      {
        "label": "Child",
        "note": "Ages 2 - 17. Children must be 5 years old to pet a reptiles.",
        "amountLabel": "$18.81"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "9.43",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/animalcenter/items/481283/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "502768",
    "company": "animalcenter",
    "title": "Zookeeper Camp",
    "publicPath": "/destinations/california/del-mar/tours/zookeeper-camp-502768",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The camp day is built around animal-care tasks with the staff. Preparing animal diets is one of those tasks. The group also sets up enrichment for the animals. Grooming and exercise are part of the same camp day. Mammals, reptiles, and birds are among the animals campers work with.",
      "Cleaning animal habitats is one of the camp tasks. Training sessions with the animals are part of the day. The camp keeps the group small so each camper can work close to the animals. Staff stay with the group while the animals are part of the program."
    ],
    "schemaDescription": "Six-hour zookeeper camp built around animal-care tasks.",
    "highlights": [
      "6 hours guided outing",
      "Groups stay at a maximum of 10 guests"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/BJ66n6AiTMulvKW6zWim"
    ],
    "productImage": "https://cdn.filestackcontent.com/ibmlLd4tT2201W0hqxks",
    "wordCount": 97,
    "durationLabel": "6 hours",
    "durationIso": "PT6H",
    "meetingLocation": "6447 Helen Woodward Way Rancho Santa Fe, CA 92067",
    "visiblePriceLabel": "From $223.66",
    "priceRows": [
      {
        "label": "Participant",
        "note": "Ages 9 - 16",
        "amountLabel": "$223.66"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "223.66",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/animalcenter/items/502768/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "502778",
    "company": "animalcenter",
    "title": "Veterinarian Camp - Half Day",
    "publicPath": "/destinations/california/del-mar/tours/veterinarian-camp---half-day-502778",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Campers meet a veterinarian and practice simple clinical skills. A microscope is set out so campers can look at cells. Canine CPR is practiced on a training dummy. The day includes a walk through a companion-animal hospital. Staff stay with the group while the animals are part of the program.",
      "Guests spend part of the visit in a hands-on session with the horses. Staff explain how the horses are cared for and how they behave. That same account stays with Equine Hospital."
    ],
    "schemaDescription": "Half-day veterinarian camp of about 3.5 hours, with clinical practice and a microscope.",
    "highlights": [
      "3.5 hours guided outing",
      "40 min: second activity and 30 min: third activity",
      "Groups stay at a maximum of 15 guests"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/3w21HAWTHWbmWrewGaAJ"
    ],
    "productImage": "https://cdn.filestackcontent.com/goB3rdXSFW4gMJNAvkTc",
    "wordCount": 84,
    "durationLabel": "3.5 hours",
    "durationIso": "PT3H30M",
    "meetingLocation": "6447 Helen Woodward Way Rancho Santa Fe, CA 92067",
    "visiblePriceLabel": "From $96.46",
    "priceRows": [
      {
        "label": "Participant",
        "note": "Ages 9 - 16",
        "amountLabel": "$96.46"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "96.46",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/animalcenter/items/502778/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "502784",
    "company": "animalcenter",
    "title": "Veterinarian Camp - Full Day",
    "publicPath": "/destinations/california/del-mar/tours/veterinarian-camp---full-day-502784",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Campers meet a veterinarian and practice simple clinical skills. A microscope is set out so campers can look at cells. Canine CPR is practiced on a training dummy. The day includes a walk through a companion-animal hospital. Staff stay with the group while the animals are part of the program."
    ],
    "schemaDescription": "Six-hour veterinarian camp with clinical practice, a microscope, and canine CPR practice.",
    "highlights": [
      "6 hours guided outing",
      "Groups stay at a maximum of 30 guests"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/aOgx21zkRt0iVtD4X60q"
    ],
    "productImage": "https://cdn.filestackcontent.com/CFihp53ZRhWtTGzA5RyZ",
    "wordCount": 51,
    "durationLabel": "6 hours",
    "durationIso": "PT6H",
    "meetingLocation": "6447 Helen Woodward Way Rancho Santa Fe, CA 92067",
    "visiblePriceLabel": "From $175.96",
    "priceRows": [
      {
        "label": "Participant",
        "note": "Ages 9 - 16",
        "amountLabel": "$175.96"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "175.96",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/animalcenter/items/502784/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "575652",
    "company": "animalcenter",
    "title": "Spring Adventure",
    "publicPath": "/destinations/california/del-mar/tours/spring-adventure-575652",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Spring Adventure is a seasonal program at the Helen Woodward Animal Center. Children meet live ambassadors from four groups: a mammal, a bird, an amphibian, and an invertebrate. One activity is a STEM session on butterfly conservation. The rest covers life cycles, young animals, and the shift from winter to spring for plants and animals.",
      "Schools are told the material lines up with the Next Generation science standards used in grades kindergarten through six. The program can run on the center's campus or travel to a classroom. Booking is by phone or email to the Education Office, with no payment up front and an invoice afterward. For Daisy Girl Scouts, the visit can be shaped toward parts of the Between Earth and Sky journey."
    ],
    "schemaDescription": "Spring program at the Helen Woodward Animal Center where children meet a mammal, a bird, an amphibian, and an invertebrate.",
    "highlights": [
      "Onsite: mini horse, chicken, frog"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/P1TOzw1XQoGD6l63r9ph"
    ],
    "productImage": "https://cdn.filestackcontent.com/sEO38S0T9esk4TOgzFek",
    "wordCount": 124,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6447 Helen Woodward Way Rancho Santa Fe, CA 92067",
    "visiblePriceLabel": "From $5.30",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18+",
        "amountLabel": "$5.30"
      },
      {
        "label": "Child- 60 minute seasonal",
        "note": "",
        "amountLabel": "$15.63"
      },
      {
        "label": "Extra Time Field Trip",
        "note": "Adds 30 minutes, add per child",
        "amountLabel": "$3.18"
      },
      {
        "label": "60 Minute Seasonal Outreach (Per class)",
        "note": "Outreaches only available to schools",
        "amountLabel": "$312.70"
      },
      {
        "label": "Extra Time Outreach",
        "note": "Adds 30 minutes, add per class - only available for schools",
        "amountLabel": "$63.60"
      },
      {
        "label": "HWAC Patch",
        "note": "",
        "amountLabel": "$6.36"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "5.30",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/animalcenter/items/575652/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
