// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborLagunaBeachLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "4351",
    "company": "lavidalaguna",
    "title": "Electric Bike Ride - Back Roads Laguna Tour",
    "publicPath": "/destinations/california/laguna-beach/tours/electric-bike-ride---back-roads-laguna-tour-4351",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The ride passes Laguna Beach and Heisler Park. Cyclists also come to Central Laguna and Bluebird Canyon. Mystic Hills and Main Beach are on the same loop. Later the route reaches Pyne Castle and North Laguna. Attention also goes to Crescent Bay Beach Park and Dana Point, with the guide attaching a story to each stop.",
      "Guests cover the sights by bike, stopping where the guide has something to say. Among the places guests actually encounter are Laguna Beach, Heisler Park, and Central Laguna. Later the route reaches Bluebird Canyon and Mystic Hills. Guests are on bikes rather than on foot, with pauses only where there is something to see or hear."
    ],
    "schemaDescription": "A two-hour bicycle outing with La Vida Laguna in Laguna Beach. The outing passes Heisler Park and Crescent Bay Beach Park.",
    "highlights": [
      "two-hour bicycle outing in Laguna Beach",
      "Heisler Park and Crescent Bay Beach Park",
      "Helmet"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/HNUlEehBTz6UDJCa2sZZ"
    ],
    "wordCount": 112,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": "1121 Glenneyre St. Laguna Beach, CA 92651",
    "visiblePriceLabel": "From $174.90",
    "priceRows": [
      {
        "label": "Rider",
        "note": "4'-10\" tall and ages 15+ to ride",
        "amountLabel": "$174.90"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "174.90",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/lavidalaguna/items/4351/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
