// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborHealdsburgLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "29264",
    "company": "getawayadventures",
    "title": "Healdsburg Sip 'N Cycle",
    "publicPath": "/destinations/california/healdsburg/tours/healdsburg-sip-n-cycle-29264",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Getaway Adventures runs this Healdsburg ride in Dry Creek Valley on paved back roads. Hours are 10:00 a.m. to 3:30 p.m. Adults 16 and older are $209. Ages 15 and under are $160. Distance is 10 to 12 miles, with two family wineries, a picnic, and a vineyard stop called Grapes 101.",
      "The meeting point is Getaway Adventures, also called Wine Country Bikes, at 359 Hudson Street in Healdsburg. An electric bike, a helmet, other gear, van support, bottled water, and bars are included. Wineries the page says may be visited include Quivira and Martorana. Mauritson, Bella, and Comstock are on the same list. So are Truett Hurst and Mill Creek, and so are Kokomo and Dry Creek. One departure does not stop at every name."
    ],
    "schemaDescription": "A guided outing with Getaway Adventures in Healdsburg.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/6QtlqGStTi683k9VDt9O"
    ],
    "productImage": "https://cdn.filestackcontent.com/CtHNMZJWQ7CYQmPbaoM5",
    "wordCount": 130,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "Dry Creek Wine Region: Healdsburg, CA",
    "visiblePriceLabel": "From $221.54",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 16 and up",
        "amountLabel": "$221.54"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "221.54",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/getawayadventures/items/29264/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
