// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborSantaMonicaLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "394572",
    "company": "unlimitedbiking",
    "title": "Santa Monica & Venice Beach eBike Tour",
    "publicPath": "/destinations/california/santa-monica/tours/santa-monica-and-venice-beach-ebike-tour-394572",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "A few optional stops leave time to step out for photographs and a closer look. Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. The booking runs about 3 hours. The ride starts near the Santa Monica Pier.",
      "Riders continue on to the Venice Canals. The same route also passes through Marina del Rey. Muscle Beach is one of the places the group stops. The Art Walls are a stop where riders take photographs. Much of the riding follows the shore, with the ocean alongside.",
      "Some guests ride pedal-assist bikes, and others ride ordinary bikes. The guide stops so riders can take photographs along the way. People stay with the bikes for the riding portion of the booking."
    ],
    "schemaDescription": "A bicycle outing with Unlimited Biking in Santa Monica. The outing passes Santa Monica Pier.",
    "highlights": [
      "Santa Monica Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/KrOFAf0zSgWSZWZkGoaM"
    ],
    "productImage": "https://cdn.filestackcontent.com/yB81A1USTWy88t1OtaEb",
    "wordCount": 131,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "1431 Ocean Ave Santa Monica, CA 90401",
    "visiblePriceLabel": "From $85",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$85"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "85.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.5,
      "reviewCount": 2375,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.5 from 2375 reviews on GET https://fareharbor.com/api/v1/companies/unlimitedbiking/items/394572/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "394573",
    "company": "unlimitedbiking",
    "title": "Santa Monica & Venice Beach Bike Tour",
    "publicPath": "/destinations/california/santa-monica/tours/santa-monica-and-venice-beach-bike-tour-394573",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. The booking runs about 3 hours. The ride starts near the Santa Monica Pier. Riders continue on to the Venice Canals. The same route also passes through Marina del Rey.",
      "Muscle Beach is one of the places the group stops. The Art Walls are a stop where riders take photographs. Much of the riding follows the shore, with the ocean alongside. The guide stops so riders can take photographs along the way. People stay with the bikes for the riding portion of the booking."
    ],
    "schemaDescription": "A bicycle outing with Unlimited Biking in Santa Monica. The outing passes Santa Monica Pier.",
    "highlights": [
      "Santa Monica Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/qnI3CEYBRiGSGGMnAZXZ"
    ],
    "productImage": "https://cdn.filestackcontent.com/HfGFL3BVQtOKjYPLZJfg",
    "wordCount": 105,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "1431 Ocean Ave Santa Monica, CA 90401",
    "visiblePriceLabel": "From $65",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$65"
      },
      {
        "label": "Child",
        "note": "Ages 12 and under",
        "amountLabel": "$55"
      },
      {
        "label": "Adult - eBike Option",
        "note": "16+ in NY/DC/FL or 13+ in CA",
        "amountLabel": "$85"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "65.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.5,
      "reviewCount": 2375,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.5 from 2375 reviews on GET https://fareharbor.com/api/v1/companies/unlimitedbiking/items/394573/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "395126",
    "company": "unlimitedbiking",
    "title": "Santa Monica Private Bike Tour",
    "publicPath": "/destinations/california/santa-monica/tours/santa-monica-private-bike-tour-395126",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The booking runs about 4 hours. The ride starts near the Santa Monica Pier. Riders continue on to the Venice Canals. The same route also passes through Marina del Rey. Muscle Beach is one of the places the group stops.",
      "The Art Walls are a stop where riders take photographs. Much of the riding follows the shore, with the ocean alongside. People stay with the bikes for the riding portion of the booking. The ride passes Hour Options and Los Angeles. Cyclists also come to Santa Monica Pier and Venice Canals.",
      "Art Walls and Muscle Beach are on the same loop."
    ],
    "schemaDescription": "A 2- to 4-hour bicycle outing with Unlimited Biking in Santa Monica. The outing passes Santa Monica Pier.",
    "highlights": [
      "2- to 4-hour bicycle outing in Santa Monica",
      "Santa Monica Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/WuL2b88BTsew7XiMGXsf"
    ],
    "productImage": "https://cdn.filestackcontent.com/e0A0PLgiRpabLDScjFDu",
    "wordCount": 110,
    "durationLabel": "2-4 Hour",
    "durationIso": null,
    "meetingLocation": "1431 Ocean Ave Santa Monica, CA 90401",
    "visiblePriceLabel": "From $300",
    "priceRows": [
      {
        "label": "Two Hours Private Bike Tour",
        "note": "",
        "amountLabel": "$300"
      },
      {
        "label": "Three Hours Private Bike Tour",
        "note": "",
        "amountLabel": "$400"
      },
      {
        "label": "Four Hours Private Bike Tour",
        "note": "",
        "amountLabel": "$500"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "300.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.4,
      "reviewCount": 148,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.4 from 148 reviews on GET https://fareharbor.com/api/v1/companies/unlimitedbiking/items/395126/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  }
];
