// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborMiamiLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "132331",
    "company": "miamibeachwelcomecenter",
    "title": "Everglades Airboat and Florida Alligator Show Tour",
    "publicPath": "/destinations/florida/miami/tours/everglades-airboat-and-florida-alligator-show-tour-132331",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The booking is an airboat trip in the Florida Everglades. An alligator show is part of the same visit. The boat crosses the River of Grass. Mangroves line the marsh the boat runs through. The airboat is made to move fast across the marsh. A show by Florida Native people is included with the boat ride.",
      "Thick vegetation covers the ground the boat passes. Guests come alone or with family. The show also takes up food and hunting methods, as the hosts present them. The booking runs about 1 hour. The airboat is the reason for the day, and the marsh is the setting."
    ],
    "schemaDescription": "An one-hour airboat outing with South Beach Welcome Center.",
    "highlights": [
      "1 Hours airboat outing"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/WKQAWo7UTryARUKtiHrn",
    "wordCount": 104,
    "durationLabel": "1 Hours",
    "durationIso": "PT1H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $14.99",
    "priceRows": [
      {
        "label": "Person",
        "note": "$45.00 • (Price online is a Partial Payment Reservation)",
        "amountLabel": "$14.99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "14.99",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/miamibeachwelcomecenter/items/132331/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "660368",
    "company": "sfairboatadventures",
    "title": "Nightime Python Road Hunt",
    "publicPath": "/destinations/florida/miami/tours/nightime-python-road-hunt-660368",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Nightime Python Road Hunt is a four-hour guided outing with South Florida Airboat Adventures in Miami. The sail runs in the evening under the stars.",
      "Groups are capped at 4."
    ],
    "schemaDescription": "Nightime Python Road Hunt is a four-hour guided outing with South Florida Airboat Adventures in Miami.",
    "highlights": [
      "four-hour guided outing in Miami",
      "Groups are capped at 4"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/eD1QWTMYTIeokra7lAOQ",
    "wordCount": 31,
    "durationLabel": "4 Hours",
    "durationIso": "PT4H",
    "meetingLocation": "5334 FL-90, Miami, FL 33185",
    "visiblePriceLabel": "From $800",
    "priceRows": [
      {
        "label": "Group",
        "note": "Night hunt group up to four people total",
        "amountLabel": "$800"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "800.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sfairboatadventures/items/660368/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "469657",
    "company": "sfjetskirentals",
    "title": "SeaRay Sundecker 27’",
    "publicPath": "/destinations/florida/miami/tours/searay-sundecker-27-469657",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Trip: Tour Brickell/Biscayne Bay, marine stadium, Hobie Beach; quick swim at Monument Island or Picnic Island; sunset option via Miami River/Brickell and Fisher Island. Trip: More swim time; tour Millionaire Homes and Sunset Islands; marine stadium/Hobie Beach; recommended Vizcaya sandbar or other sandbars.",
      "Trip: Combines the above with more flexibility to linger at favored spots; options include Bear Cut, Nixon sandbar, No Name Harbor, Vizcaya Museum, and Key Biscayne. Trip: Access to VIP/exclusive locations weather permitting, such as Stittsville and Fowey Rocks; Haulover sandbar recommended. Space for up to 11 guests with room to move around.",
      "Options to visit sandbars, Millionaire's Row, Vizcaya, and scenic sunset routes."
    ],
    "schemaDescription": "A guided outing with Jetski Rentals of South Florida in Miami. The outing passes Monument Island, Picnic Island, and Fisher Island.",
    "highlights": [
      "Monument Island and Picnic Island",
      "Captain"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/zxnbwwpETSucNAKlpo90"
    ],
    "productImage": "https://cdn.filestackcontent.com/97GgWakRRqOVVestUsXN",
    "wordCount": 111,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "201 NW S River Dr Miami, FL 33128 USA",
    "visiblePriceLabel": "From $300",
    "priceRows": [
      {
        "label": "2 Hour Rental",
        "note": "",
        "amountLabel": "$300"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "300.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sfjetskirentals/items/469657/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "371933",
    "company": "skytoursmiami",
    "title": "Miami Downtown Private Airplane Tour",
    "publicPath": "/destinations/florida/miami/tours/miami-downtown-private-airplane-tour-371933",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a guided outing with Sky Tours Miami. Private flight, Pilot, and Headset are included. The outing reaches Vizcaya Museum.",
      "Groups are capped at 3. Guests must be at least 5 years old."
    ],
    "schemaDescription": "This is a guided outing with Sky Tours Miami.",
    "highlights": [
      "30 Mins guided outing",
      "Vizcaya Museum",
      "Private flight"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/nyIu36e6QPmi5bNhlTSt"
    ],
    "productImage": "https://cdn.filestackcontent.com/0DSwzrjqRkyXiQSydi6v",
    "wordCount": 34,
    "durationLabel": "30 Mins",
    "durationIso": null,
    "meetingLocation": "14005 SW 127th St. Unit 120 A Miami, FL 33186",
    "visiblePriceLabel": "From $69",
    "priceRows": [
      {
        "label": "Person",
        "note": "Ages 5+",
        "amountLabel": "$69"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "69.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 278,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 278 reviews on GET https://fareharbor.com/api/v1/companies/skytoursmiami/items/371933/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  }
];
