// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborLosAngelesLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "168579",
    "company": "alldayla",
    "title": "LA Essential Star Homes Tour",
    "publicPath": "/destinations/california/los-angeles/tours/la-essential-star-homes-tour-168579",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride in an open-air vehicle rather than walking between sights. The outing does not include stops, so the sights are seen from the vehicle. The length runs up to about 2 hours and changes with traffic. The vehicle passes through city neighborhoods on the same drive.",
      "Moviemaking landmarks are among the sights seen from the vehicle. Residential neighborhoods are part of the same ride. Architectural buildings are visible from the open-air vehicle. Historic sites are also on the drive and are seen without a stop. Guests are asked to bring a camera for the ride.",
      "People stay aboard the vehicle for the length of the outing. There is no walking portion, because the operator does not schedule stops. The same open-air ride is how every sight on the outing is viewed. The ride stays in Los Angeles."
    ],
    "schemaDescription": "A two-hour guided outing with Golden Ticket LA.",
    "highlights": [
      "2 hours guided outing"
    ],
    "galleryImages": [],
    "wordCount": 141,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $51.94",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+",
        "amountLabel": "$51.94"
      },
      {
        "label": "Child",
        "note": "Ages 11 and under",
        "amountLabel": "$41.34"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "51.94",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 1335,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 1335 reviews on GET https://fareharbor.com/api/v1/companies/alldayla/items/168579/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "518084",
    "company": "alldayla",
    "title": "Private Los Angeles Tour (Beverly Hills)",
    "publicPath": "/destinations/california/los-angeles/tours/private-los-angeles-tour-beverly-hills-518084",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "A private group sets the sights, the departure time, and the length of the outing. The pace stays with the guests instead of following a fixed public timetable. Stops include well-known sights and places left out of ordinary travel guides. The private booking is limited to 7 guests.",
      "Free pickup is available in Beverly Hills. Guests are asked to bring a camera for the outing. The outing runs for about 3 hours. There is no set walking route, and the group sets the stops. Small groups book the same private outing, and the plan is built around that party.",
      "The operator leads the outing, and the plan changes with the group's size and interests. Guests visit both the better-known sights and the places the travel guides skip."
    ],
    "schemaDescription": "A three-hour guided outing with Golden Ticket LA in Los Angeles.",
    "highlights": [
      "three-hour guided outing in Los Angeles"
    ],
    "galleryImages": [],
    "wordCount": 129,
    "durationLabel": "3 hours",
    "durationIso": "PT3H",
    "meetingLocation": "6808 Hollywood Blvd, Los Angeles, CA, 90028",
    "visiblePriceLabel": "From $470.83",
    "priceRows": [
      {
        "label": "Private Group",
        "note": "(Up to 7 People)",
        "amountLabel": "$470.83"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "470.83",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 1335,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 1335 reviews on GET https://fareharbor.com/api/v1/companies/alldayla/items/518084/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "680527",
    "company": "graveline",
    "title": "Manson Family Murders Funeral Limo Tour of LA",
    "publicPath": "/destinations/california/los-angeles/tours/manson-family-murders-funeral-limo-tour-of-la-680527",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests step inside cinematic, tension-filled recounting of Manson Family murders aboard vintage funeral limo. Tate et al. last supper (El Coyote restaurant) - Stop by the legendary Mexican cantina where Sharon Tate and her friends shared their final meal. Manson, Wilson and Melcher clubbing (The Whiskey a Go-Go) - Visit the nightclub tied to Manson and Dennis Wilson.",
      "Cielo Drive - Visit the former site of the Tate-Polanski residence. Clothing found (Benedict Canyon) - See the ravine where discarded clothes from the Tate murders were located. Gun found (Longview Valley Dr) - See the yard where the gun used in the Tate killings was found.",
      "Sadie Atkins Strip Club (Candy Cat) - Visit the former site where Susan Atkins once performed. Manson's Favorite Hot Dog stand - Take a break and view an authentic Manson artifact up close. Family HQ/ Spahn Ranch - Explore the state park that once housed the Spahn Movie Ranch."
    ],
    "schemaDescription": "A 3.5-hour guided outing with Grave Line Tours in Los Angeles. The outing passes Whiskey.",
    "highlights": [
      "3.5-hour guided outing in Los Angeles",
      "Whiskey",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/ExVHF9QgR62r80ruHGN3"
    ],
    "wordCount": 149,
    "durationLabel": "3.5 hours",
    "durationIso": "PT3H30M",
    "meetingLocation": "6801 Hollywood Boulevard Los Angeles, CA 90028",
    "visiblePriceLabel": "From $98.18",
    "priceRows": [
      {
        "label": "Adult",
        "note": "",
        "amountLabel": "$98.18"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "98.18",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/graveline/items/680527/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "680528",
    "company": "graveline",
    "title": "Death Becomes Her Funeral Limo Tour of Los Angeles",
    "publicPath": "/destinations/california/los-angeles/tours/death-becomes-her-funeral-limo-tour-of-los-angeles-680528",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride in a custom funeral limo with atmospheric lighting and curated audio. Expert storytelling that brings victims, killers, and scandals vividly to life. Two-hour sightseeing tour of Los Angeles' notorious true crime and paranormal locations. Guided storytelling and curated audio within the limo.",
      "Atmospheric lighting and visual background materials in the vehicle. The day moves through Sunset Grove double homicide and beheading, Former Ed Buck apartment, and Barney's Beanery. Next come Beverly Hills jewelry heist site, Spadena House (Witch's House), and Michael Jackson's Carolwood Drive home. Later the group reaches Menendez Mansion on North Elm Drive, Greystone Mansion murder-suicide site, and Viper Room (River Phoenix overdose site).",
      "The group also comes to Brittany Murphy's final Hollywood Hills home and Sunset Tower hauntings."
    ],
    "schemaDescription": "A two-hour guided outing with Grave Line Tours in Los Angeles. The outing passes Sunset Grove double homicide and beheading, Former Ed Buck apartment, and Barney's Beanery.",
    "highlights": [
      "two-hour guided outing in Los Angeles",
      "Sunset Grove double homicide and beheading and Former Ed Buck apartment",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/1h3CHyuXQPCCwreMOxej"
    ],
    "wordCount": 125,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": "6801 Hollywood Boulevard Los Angeles, CA 90028",
    "visiblePriceLabel": "From $75.08",
    "priceRows": [
      {
        "label": "Adult",
        "note": "",
        "amountLabel": "$75.08"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "75.08",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/graveline/items/680528/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "680529",
    "company": "graveline",
    "title": "Hollywood Horror Story: The Black Dahlia Funeral Limo Tour",
    "publicPath": "/destinations/california/los-angeles/tours/hollywood-horror-story-the-black-dahlia-funeral-limo-tour-680529",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Chancellor Apartments - Outside view of Room 501 and discussion of Short's life there. Pig'n'Whistle - Sidewalk stop to place Short in Hollywood's café scene. Boardners - Outside visit and stories of its noir-era patrons. Hollywood Cherokee building - Stop outside the gynecologist's former office and related background.",
      "The Frolic Room - Sidewalk stop examining its connection to Dahlia-era nightlife. Florentine Gardens - Stop discussing suspect connections and alleged encounters. Guardian Arms - Outside stop covering a short stay tied to suspect Margolis. Sowden (Hodel) House - Street-level viewing and discussion of allegations against Hodel.",
      "Biltmore Hotel - Stop covering the last known sightings and conflicting accounts. Hotel Cecil - Outside stop linking the hotel to broader true crime legends. Herald Examiner Building - Discussion of media sensationalism and leaked details. Catalina St bungalow - Stop covering theories tying the bungalow to the murder.",
      "Walter Bayley residence - Stop about another suspect's former home. Body discovery location - Site visit to the lot where Short's body was found."
    ],
    "schemaDescription": "A three-hour guided outing with Grave Line Tours in Los Angeles.",
    "highlights": [
      "three-hour guided outing in Los Angeles",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/63VVGBa4RRpzlTO7xFgE"
    ],
    "wordCount": 158,
    "durationLabel": "3 hours",
    "durationIso": "PT3H",
    "meetingLocation": "6801 Hollywood Boulevard Los Angeles, CA 90028",
    "visiblePriceLabel": "From $98.18",
    "priceRows": [
      {
        "label": "Adult",
        "note": "",
        "amountLabel": "$98.18"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "98.18",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/graveline/items/680529/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "333382",
    "company": "hollywoodbustoursla",
    "title": "A Taste of LA: Half Day Tour of the BEST of Los Angeles",
    "publicPath": "/destinations/california/los-angeles/tours/a-taste-of-la-half-day-tour-of-the-best-of-los-angeles-333382",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests meet best of Los Angeles in streamlined half-day VIP-style sightseeing tour. Guests travel in new climate-controlled 2025 luxury mini-coach alongside entertaining driver guide who shares local accounts and fun facts. Tour begins and ends at Hollywood Visitor Center for easy access toward Hollywood highlights.",
      "The ticket also covers complimentary also self-guided Hollywood Walk of Fame walking outing, and the team will assist guests with setup during check-in so guests explore at the own pace. Guests travel in brand-new 2025 luxury, climate-controlled coaches. Entertaining local driver guide sharing stories and fun facts.",
      "Four curated stops allowing time to explore, eat, and take photos. Transportation aboard a 2025 climate-controlled luxury mini-coach. Entertaining driver guide providing local commentary and insights. Free multilingual audio guide app with pre-recorded commentary in 11 languages. Guests stop time at Beverly Hills and Rodeo Drive."
    ],
    "schemaDescription": "A 5-hour guided outing with Hollywood Bus Tours, LLC in Los Angeles. The outing passes Farmers Market, Santa Monica Pier, and Grove.",
    "highlights": [
      "5-hour guided outing in Los Angeles",
      "Farmers Market and Santa Monica Pier",
      "Stop time at Santa Monica Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/jcqlwBmITLuruspiO5W9"
    ],
    "wordCount": 149,
    "durationLabel": "5 hours",
    "durationIso": "PT5H",
    "meetingLocation": "7046 Hollywood Blvd Los Angeles, CA 90028",
    "visiblePriceLabel": "From $83.74",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+",
        "amountLabel": "$83.74"
      },
      {
        "label": "Child",
        "note": "Ages 3-11",
        "amountLabel": "$73.14"
      },
      {
        "label": "Infant",
        "note": "Ages 0-2",
        "amountLabel": "$5.30"
      },
      {
        "label": "32-Seat Private Tour",
        "note": "",
        "amountLabel": "$2,542.94"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "83.74",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 9992,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 9992 reviews on GET https://fareharbor.com/api/v1/companies/hollywoodbustoursla/items/333382/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  }
];
