// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborStPetersburgLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "520862",
    "company": "fatherdaughtercharters",
    "title": "Sunset Sail",
    "publicPath": "/destinations/florida/st-petersburg/tours/sunset-sail-520862",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Leave St. Petersburg's shoreline behind for a private sunset sail departing from SkyBeach Resort Marina. The two-hour outing trades the busy waterfront for open views across the bay, where the changing light becomes the centerpiece of the evening.",
      "From the boat, the marina and surrounding waterfront take on a different perspective. The operator notes that the water can become calmer as afternoon winds ease, although sailing conditions naturally vary from day to day. There is time to enjoy the movement of the boat and the colors over the water rather than rushing between sightseeing stops.",
      "This experience is listed for guests aged three and older, with departure from Sunshine Drive South in St. Petersburg. Confirm the precise boarding instructions and weather arrangements when booking, particularly if your plans depend on a specific sunset time."
],
    "schemaDescription": "Sunset sail from SkyBeach Resort Marina, usually on calmer water after the afternoon wind drops.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/dr5U0nMoQgSgV5ob9qXI"
    ],
    "productImage": "https://cdn.filestackcontent.com/0d4wY48USeaKHeRSYXmO",
    "wordCount": 134,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6800 Sunshine Drive South St. Petersburg, FL 33705",
    "visiblePriceLabel": "From $899",
    "priceRows": [
      {
        "label": "Sunset Sail",
        "note": "2 hours • Ages 3+",
        "amountLabel": "$899"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "899.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/fatherdaughtercharters/items/520862/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "521546",
    "company": "fatherdaughtercharters",
    "title": "Full-Day Sail",
    "publicPath": "/destinations/florida/st-petersburg/tours/full-day-sail-521546",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Spend a full day under sail from St. Petersburg on an eight-hour private charter that can be shaped around one of three coastal destinations: Egmont Key, Anna Maria Island or Shell Key. Each offers a different introduction to the waters and islands at the mouth of Tampa Bay.",
      "Egmont Key is known for its quiet beaches, gopher tortoises and the remains of historic Fort Dade. Anna Maria Island offers the atmosphere of a Gulf Coast beach community, while Shell Key is valued for its largely undeveloped shoreline and shelling opportunities. The choice of destination is part of planning the day, not a promise to visit all three.",
      "Depart from the SkyBeach Resort Marina area on Sunshine Drive South. The operator lists this as a private charter for ages three and older. Confirm your preferred destination, sailing conditions and any shore-access arrangements before departure."
],
    "schemaDescription": "Full-day private sail with a choice of Egmont Key, Anna Maria, or Shell Key. Egmont Key includes the remains of Fort Dade.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/7JZkwDwQ4WAYNCezIEcF"
    ],
    "productImage": "https://cdn.filestackcontent.com/ABOPSt8QGquxdkSwgxF2",
    "wordCount": 143,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6800 Sunshine Drive South St. Petersburg, FL 33705",
    "visiblePriceLabel": "From $1,495",
    "priceRows": [
      {
        "label": "Full-Day Private Charter",
        "note": "8 hours • Ages 3+",
        "amountLabel": "$1,495"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1495.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/fatherdaughtercharters/items/521546/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "521595",
    "company": "fatherdaughtercharters",
    "title": "Dolphin Spotting Sail",
    "publicPath": "/destinations/florida/st-petersburg/tours/dolphin-spotting-sail-521595",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "See St. Petersburg from the water on a private two-hour catamaran sail with an eye out for dolphins. The city's skyline provides a backdrop as the boat leaves the marina and moves into the surrounding harbor waters.",
      "Dolphins inhabit the Tampa Bay region, but they are wild animals and appearances cannot be guaranteed. The appeal of this excursion is as much the relaxed sailing experience and waterfront scenery as the possibility of spotting marine life. A catamaran offers a different perspective from a land-based walk along the shore.",
      "The cruise departs from the SkyBeach Resort Marina area on Sunshine Drive South. The operator lists the charter for guests aged three and older. Check the current boarding instructions and weather policy before travel, and bring sun protection appropriate for an outing on the water."
],
    "schemaDescription": "Two-hour dolphin-spotting sail on a catamaran, with the city skyline as the main view from the harbor.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/PeqtaSvTCygDg03N4ZCg"
    ],
    "productImage": "https://cdn.filestackcontent.com/eDDIPtISXaeUdvdqRhl7",
    "wordCount": 133,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6800 Sunshine Drive South St. Petersburg, FL 33705",
    "visiblePriceLabel": "From $900",
    "priceRows": [
      {
        "label": "Quarter-Day Private Charter",
        "note": "2 hours • Ages 3+",
        "amountLabel": "$900"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "900.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/fatherdaughtercharters/items/521595/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
