// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborMiamiBeachLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "266593",
    "company": "305toursandrentals",
    "title": "Miami Boat Tour with FREE South Beach Bicycle Rental",
    "publicPath": "/destinations/florida/miami-beach/tours/miami-boat-tour-with-free-south-beach-bicycle-rental-266593",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "305 Tours pairs a narrated boat cruise of 90 minutes with a South Beach bike rental of three hours, usable the same day or later. Pickup is a South Beach hotel or the shop. On the water the boat crosses Biscayne Bay and passes the downtown skyline, then the port, Fisher Island, and the row of houses the page calls Millionaire's Row. Drinks and small snacks are sold on board.",
      "The rental includes a bicycle, a helmet, a lock, and a bottle of water. The land route in the description goes by the Versace Mansion and Star Island, then Lincoln Road, Ocean Drive, the Art Deco District, and South Pointe Park. Those bike stops are separate from the 90 minutes afloat."
    ],
    "schemaDescription": "A three-hour bicycle outing with 305 Tours & Rentals. The outing passes Fisher Island, Star Island, and South Pointe Park.",
    "highlights": [
      "3 Hour bicycle outing",
      "Fisher Island and Star Island"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/kekAePQFQNam02qguFGM",
    "wordCount": 121,
    "durationLabel": "3 Hour",
    "durationIso": "PT3H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $59",
    "priceRows": [
      {
        "label": "11 and over",
        "note": "Ages 11+",
        "amountLabel": "$69"
      },
      {
        "label": "Child",
        "note": "Ages 2-10",
        "amountLabel": "$59"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "59.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 33,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.7 from 33 reviews on GET https://fareharbor.com/api/v1/companies/305toursandrentals/items/266593/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "266597",
    "company": "305toursandrentals",
    "title": "Miami City and Boat Tour Combo with FREE South Beach Bicycle Rental",
    "publicPath": "/destinations/florida/miami-beach/tours/miami-city-and-boat-tour-combo-with-free-south-beach-bicycle-rental-266597",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This 305 Tours booking is listed at five hours: a city tour of about four hours, a boat cruise, and a three-hour South Beach bike rental on the same day or another day. Pickup is a South Beach hotel or the shop. The air-conditioned bus covers the Art Deco District and Ocean Drive, then downtown, Brickell, Coconut Grove, and Coral Gables. Little Havana and Calle Ocho are on that same bus loop.",
      "The boat is a narrated cruise of 90 minutes on Biscayne Bay, passing the downtown skyline, the port, Fisher Island, and Millionaire's Row. Drinks and light snacks are sold aboard. The bike rental includes a bicycle, a helmet, a lock, and bottled water. The bike notes name the Versace Mansion, Star Island, Lincoln Road, Ocean Drive, the Art Deco streets, and South Pointe Park."
    ],
    "schemaDescription": "A 5-hour bicycle outing with 305 Tours & Rentals. The outing passes Fisher Island, Star Island, and South Pointe Park.",
    "highlights": [
      "5 Hours bicycle outing",
      "Fisher Island and Star Island"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/wpgG3jOSWxAOOvHj5RQ4",
    "wordCount": 138,
    "durationLabel": "5 Hours",
    "durationIso": "PT5H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $79",
    "priceRows": [
      {
        "label": "11 and over",
        "note": "Ages 11+",
        "amountLabel": "$89"
      },
      {
        "label": "Child",
        "note": "Ages 2-10",
        "amountLabel": "$79"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "79.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 33,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.7 from 33 reviews on GET https://fareharbor.com/api/v1/companies/305toursandrentals/items/266597/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "575606",
    "company": "bobbysbikehike",
    "title": "Miami Beach Bikes, Bites & Views Food Tour (Adults Only)",
    "publicPath": "/destinations/florida/miami-beach/tours/miami-beach-bikes-bites-and-views-food-tour-adults-only-575606",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Art Deco buildings in the financial district are what guests are taken to see. The tasting also stops near Art Deco."
    ],
    "schemaDescription": "Art Deco buildings in the financial district are what guests are taken to see.",
    "highlights": [
      "4.5-hour bicycle outing in Miami Beach",
      "Bikes"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/yWn9XmeHRYaOIKHpJizi"
    ],
    "productImage": "https://cdn.filestackcontent.com/mdcBKF4lTbahj8bdgPPX",
    "wordCount": 21,
    "durationLabel": "4.5 hours",
    "durationIso": "PT4H30M",
    "meetingLocation": "959 West Ave Suite 1 Miami Beach, FL 33139",
    "visiblePriceLabel": "From $84.99",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18+",
        "amountLabel": "$84.99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "84.99",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 398,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.9 from 398 reviews on GET https://fareharbor.com/api/v1/companies/bobbysbikehike/items/575606/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "107989",
    "company": "southfloridatrikketours",
    "title": "Everglades Airboat Adventure + FREE 2 HOURS with Rentals.",
    "publicPath": "/destinations/florida/miami-beach/tours/everglades-airboat-adventure-free-2-hours-with-rentals-107989",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Miami Beach Bike Rental lists this as a 4.5-hour trip from the Art Deco district in South Beach to Everglades National Park and back. A coach takes the group out and returns it to the same drop-off. On the airboat the operator names alligators, turtles, birds, snakes, and other reptiles in a subtropical area it measures at 1.5 million acres.",
      "The route then goes to an alligator farm. There the guide compares caimans, crocodiles, and other species, and explains historic methods used to capture alligators. The booking also includes two free hours on a rental. The airboat time and the farm stop are both inside the 4.5 hours."
    ],
    "schemaDescription": "A 4.5-hour airboat outing with South Florida Trikke Tours in Miami Beach. The outing passes Everglades National Park.",
    "highlights": [
      "4.5-hour harbor outing in Miami Beach",
      "Everglades National Park"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/t10LSbZvTt6s2EsIDFhn"
    ],
    "productImage": "https://cdn.filestackcontent.com/DokRtLLrSNiXv03swq6F",
    "wordCount": 113,
    "durationLabel": "4.5 hours",
    "durationIso": "PT4H30M",
    "meetingLocation": "233 14th Street Miami Beach, FL 33139",
    "visiblePriceLabel": "From $69",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$69"
      },
      {
        "label": "Child",
        "note": "Ages 3-12",
        "amountLabel": "$59"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "69.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 2155,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 2155 reviews on GET https://fareharbor.com/api/v1/companies/southfloridatrikketours/items/107989/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "117385",
    "company": "southfloridatrikketours",
    "title": "Miami City and Boat Tour Combo Little Havana Included plus FREE 2 HOURS with Rentals.",
    "publicPath": "/destinations/florida/miami-beach/tours/miami-city-and-boat-tour-combo-little-havana-included-plus-free-2-hours-with-rentals-117385",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Pickup for this combo is the South Beach shop. An air-conditioned bus then covers the Art Deco District and Ocean Drive. Downtown Miami and Brickell Avenue follow. Little Havana and Calle Ocho close the land loop. A narrated cruise of 90 minutes runs on Biscayne Bay, past the downtown skyline, the port, Fisher Island, and Millionaire's Row. Drinks and light snacks are for sale on the boat.",
      "A bike is included. The described ride passes the Versace Mansion and Star Island, then Lincoln Road, Ocean Drive, the Art Deco District, and South Pointe Park. The title adds two free hours on a rental. The operator says the city-and-boat day can last from three hours to eight, depending on how the stops are used."
    ],
    "schemaDescription": "A harbor outing with South Florida Trikke Tours on Miami Beach Harbor. The sail passes Fisher Island, Star Island, and South Pointe Park.",
    "highlights": [
      "Fisher Island and Star Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/71gYJqsRQ9iUpTexLCIz"
    ],
    "productImage": "https://cdn.filestackcontent.com/DYYUaSQ1usrWWUcOQMwA",
    "wordCount": 126,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "233 14th Street Miami Beach, FL 33139",
    "visiblePriceLabel": "From $89",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$89"
      },
      {
        "label": "Child",
        "note": "Ages 3-12",
        "amountLabel": "$79"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "89.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 2155,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 2155 reviews on GET https://fareharbor.com/api/v1/companies/southfloridatrikketours/items/117385/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "297478",
    "company": "southfloridatrikketours",
    "title": "Everglades Airboat and Millionaire's Row Cruiser Tour Combo + FREE 2 HOURS with Rentals.",
    "publicPath": "/destinations/florida/miami-beach/tours/everglades-airboat-and-millionaires-row-cruiser-tour-combo-free-2-hours-with-rentals-297478",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The booking is an airboat trip in the Florida Everglades. After the ride there is a short wildlife talk that includes rescued alligators. Count on about 2 hours, including the ride to the park and back. The airboat is the reason for the day. The coach is only the way there and back.",
      "Time on the water is about 2 hours. The route also reaches Bayside Marketplace and Biscayne Bay. Downtown Miami and Star Island are part of the same outing."
    ],
    "schemaDescription": "A airboat outing with South Florida Trikke Tours in Miami Beach. The outing passes Star Island.",
    "highlights": [
      "Star Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/hp2VsKm3SWIQOMXDSbDk"
    ],
    "productImage": "https://cdn.filestackcontent.com/h2YQcb7tTs6Md5MWUmkZ",
    "wordCount": 81,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "233 14th Street Miami Beach, FL 33139",
    "visiblePriceLabel": "From $119",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$119"
      },
      {
        "label": "Child",
        "note": "Ages 3-12",
        "amountLabel": "$109"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "119.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 2155,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 2155 reviews on GET https://fareharbor.com/api/v1/companies/southfloridatrikketours/items/297478/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "176702",
    "company": "us2u",
    "title": "Key West Tour with Dolphin Spotting Boat from Miami",
    "publicPath": "/destinations/florida/miami-beach/tours/key-west-tour-with-dolphin-spotting-boat-from-miami-176702",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "US2U sells this as a coach day from Miami down to Key West, listed at 14 hours. The bus leaves selected Miami points around 6:30 a.m. and uses the Overseas Highway. Arrival in Key West is around 11:30 a.m., traffic allowing. There, a boat goes out to look for dolphins, and drinks are served on that boat. Unguided free time in town follows.",
      "The coach leaves Key West around 5:30 p.m. and is aimed at Miami around 9:00 p.m., again depending on traffic. The boat is the wildlife leg. The rest of the island time is on foot without a guide."
    ],
    "schemaDescription": "A 14-hour harbor outing with US2U on Miami Beach Harbor.",
    "highlights": [
      "14-hour harbor outing in Miami Beach",
      "Refreshments on the boat"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/ghxzLhlSmGjaZLqIZ3JV"
    ],
    "productImage": "https://cdn.filestackcontent.com/Urj6Sb5jR2qmdDnXq5cQ",
    "wordCount": 109,
    "durationLabel": "14 hours",
    "durationIso": "PT14H",
    "meetingLocation": "700 Collins Avenue Miami Beach, FL 33139",
    "visiblePriceLabel": "From $199",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18-100",
        "amountLabel": "$199"
      },
      {
        "label": "Child",
        "note": "Ages 2-17",
        "amountLabel": "$199"
      },
      {
        "label": "Infant",
        "note": "Ages 0-1",
        "amountLabel": "$199"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "199.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 3.7,
      "reviewCount": 383,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 3.7 from 383 reviews on GET https://fareharbor.com/api/v1/companies/us2u/items/176702/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "81627",
    "company": "us2u",
    "title": "Everglades Airboat and Wildlife Sanctuary with round-trip transportation",
    "publicPath": "/destinations/florida/miami-beach/tours/everglades-airboat-and-wildlife-sanctuary-with-round-trip-transportation-81627",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The booking is an airboat trip in the Florida Everglades. A coach takes the group from Miami out to the wetlands and back again. The airboat portion is guided, and the boat is mostly covered. A park ranger leads the boat and talks about the wetlands.",
      "After the ride there is a short wildlife talk that includes rescued alligators. Guests then have time to walk the park exhibits. A snack bar and a souvenir shop are on the same grounds. Which animals appear depends on the season, and nothing is promised.",
      "The airboat is the reason for the day. The coach is only the way there and back."
    ],
    "schemaDescription": "A 5-hour airboat outing with US2U in Miami Beach.",
    "highlights": [
      "5-hour harbor outing in Miami Beach",
      "Groups are capped at 45"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/o8pXwQ4QmGGqBPp5auMg"
    ],
    "productImage": "https://cdn.filestackcontent.com/wt9N5qVvQEWdWNkdZsQw",
    "wordCount": 108,
    "durationLabel": "5 hours",
    "durationIso": "PT5H",
    "meetingLocation": "700 Collins Avenue Miami Beach, FL 33139",
    "visiblePriceLabel": "From $79",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18-100",
        "amountLabel": "$79"
      },
      {
        "label": "Child",
        "note": "Ages 2-17",
        "amountLabel": "$79"
      },
      {
        "label": "Infant",
        "note": "Ages 0-1",
        "amountLabel": "$79"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "79.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 3.7,
      "reviewCount": 383,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 3.7 from 383 reviews on GET https://fareharbor.com/api/v1/companies/us2u/items/81627/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "81669",
    "company": "us2u",
    "title": "Key West Tour with Snorkel Boat from Miami",
    "publicPath": "/destinations/florida/miami-beach/tours/key-west-tour-with-snorkel-boat-from-miami-81669",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "A few optional stops leave time to step out for photographs and a closer look. The route also reaches Mallory Square and Southernmost Point. Key West Ca and Miami Ca are part of the same outing. Later the group comes to Florida Keys."
    ],
    "schemaDescription": "A 15-hour harbor outing with US2U on Miami Beach Harbor. The sail passes Seven Mile Bridge and Mallory Square.",
    "highlights": [
      "15-hour harbor outing in Miami Beach",
      "Seven Mile Bridge and Mallory Square",
      "Basic snorkel gear"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/l8XgSOZURCQWNL6Pwyxx"
    ],
    "productImage": "https://cdn.filestackcontent.com/ny1IR7ZiTWaZX6LxM49I",
    "wordCount": 43,
    "durationLabel": "15 hours",
    "durationIso": "PT15H",
    "meetingLocation": "700 Collins Avenue Miami Beach, FL 33139",
    "visiblePriceLabel": "From $169",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18-100",
        "amountLabel": "$169"
      },
      {
        "label": "Child",
        "note": "Ages 2-17",
        "amountLabel": "$169"
      },
      {
        "label": "Infant",
        "note": "Ages 0-1",
        "amountLabel": "$169"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "169.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 3.7,
      "reviewCount": 383,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 3.7 from 383 reviews on GET https://fareharbor.com/api/v1/companies/us2u/items/81669/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  }
];
