// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborGoodlandLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "128312",
    "company": "floridaadventuresandrentals",
    "title": "Sunset Eco-Tour",
    "publicPath": "/destinations/florida/goodland/tours/sunset-eco-tour-128312",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "From the water, guests see Rookery Bay Reserve and Gulf Coast. Florida Adventures and Marco Island come into view as the boat moves."
    ],
    "schemaDescription": "Two-hour sunset eco-tour with views of Rookery Bay Reserve and the Gulf Coast.",
    "highlights": [
      "two-hour guided outing in Goodland",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/83CS5ZiaTsCDlGa4CSzb"
    ],
    "productImage": "https://cdn.filestackcontent.com/VxIJbDn1TDWYDwXF6Bp1",
    "wordCount": 23,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $425",
    "priceRows": [
      {
        "label": "Private Tour: Up to 6 People",
        "note": "",
        "amountLabel": "$425"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "7 to 12 People",
        "amountLabel": "$800"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "13 to 17 People",
        "amountLabel": "$1,100"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "425.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/128312/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "154092",
    "company": "floridaadventuresandrentals",
    "title": "4 Hour Shelling Tour",
    "publicPath": "/destinations/florida/goodland/tours/4-hour-shelling-tour-154092",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "4 Hour Shelling Tour is a four-hour guided outing with Florida Adventures and Rentals in Goodland. Shell Bags, Bottled Water, and Cooler with ice for guest use are included. The outing reaches Marco Island.",
      "Groups are capped at 17. A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "Four-hour shelling tour that reaches Marco Island. Shell bags, bottled water, and a cooler with ice are included.",
    "highlights": [
      "four-hour guided outing in Goodland",
      "Marco Island",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/x6ITTQ3a7iwPtm4WrQ9J"
    ],
    "productImage": "https://cdn.filestackcontent.com/9UOMjxEsRJOItMfD0TBs",
    "wordCount": 51,
    "durationLabel": "4 Hours",
    "durationIso": "PT4H",
    "meetingLocation": "Goodland Boat Park | 750 Palm Point Dr Goodland, FL 34140",
    "visiblePriceLabel": "From $140",
    "priceRows": [
      {
        "label": "Person",
        "note": "",
        "amountLabel": "$140"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "140.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/154092/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "44195",
    "company": "floridaadventuresandrentals",
    "title": "Marco Island Wildlife Sightseeing and Shelling Tour",
    "publicPath": "/destinations/florida/goodland/tours/marco-island-wildlife-sightseeing-and-shelling-tour-44195",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a two-hour guided outing with Florida Adventures and Rentals in Goodland. Shell Bags, Bottled Water, and Cooler with ice for guest use are included.",
      "A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "Two-hour wildlife sightseeing and shelling tour, with shell bags, bottled water, and a cooler with ice.",
    "highlights": [
      "two-hour guided outing in Goodland",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/UwKHeLZ1TFODH7tvBlIP"
    ],
    "productImage": "https://cdn.filestackcontent.com/a7VDgVWLT2Ss2ueq63rL",
    "wordCount": 38,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $89",
    "priceRows": [
      {
        "label": "Toddler",
        "note": "0-2 years old",
        "amountLabel": "$19"
      },
      {
        "label": "Kid",
        "note": "Ages 3-10",
        "amountLabel": "$65"
      },
      {
        "label": "Adult",
        "note": "Ages 11+",
        "amountLabel": "$89"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "89.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/44195/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "44212",
    "company": "floridaadventuresandrentals",
    "title": "Dolphin Tours",
    "publicPath": "/destinations/florida/goodland/tours/dolphin-tours-44212",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Dolphin Tours is a two-hour guided outing with Florida Adventures and Rentals in Goodland. Water Bottles and Cooler with ice for guest use are included.",
      "A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "Two-hour dolphin tour. Water bottles and a cooler with ice are included.",
    "highlights": [
      "two-hour guided outing in Goodland",
      "Water Bottles"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/nz8njh4bQmaXt2KF1S3b"
    ],
    "productImage": "https://cdn.filestackcontent.com/vF5Rh2GuTPqsqrDFoWIV",
    "wordCount": 37,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $89",
    "priceRows": [
      {
        "label": "Toddler",
        "note": "0-2 years old",
        "amountLabel": "$19"
      },
      {
        "label": "Kid",
        "note": "Ages 3-10",
        "amountLabel": "$65"
      },
      {
        "label": "Adult",
        "note": "Ages 11+",
        "amountLabel": "$89"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "89.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/44212/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "44214",
    "company": "floridaadventuresandrentals",
    "title": "3 Hour Eco Tour",
    "publicPath": "/destinations/florida/goodland/tours/3-hour-eco-tour-44214",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This three-hour eco cruise goes through the Ten Thousand Islands. Captains and guides talk about the ecology of the mangrove islands. The boat searches for dolphins and covers the local population. After the mangroves, the group stops on a private beach to look for tropical shells along the Gulf coast.",
      "The boats have comfortable seating. A ladder at the front is there for stepping onto the beach. Children and adults are both expected on the trip."
    ],
    "schemaDescription": "Three-hour eco cruise through the Ten Thousand Islands, with a dolphin search and a private-beach stop for shells.",
    "highlights": [
      "three-hour guided outing in Goodland",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/88i2Sk2vTT2oX42D4qit"
    ],
    "productImage": "https://cdn.filestackcontent.com/lZ1iMDFeQi4GodXv1xVg",
    "wordCount": 77,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Toddler",
        "note": "0-2 years old",
        "amountLabel": "$19"
      },
      {
        "label": "Kid",
        "note": "Ages 3-10",
        "amountLabel": "$79"
      },
      {
        "label": "Adult",
        "note": "Ages 11+",
        "amountLabel": "$99"
      },
      {
        "label": "Private Tour: Up to 6 People",
        "note": "",
        "amountLabel": "$525"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "",
        "amountLabel": "$999"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "",
        "amountLabel": "$1,299"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/44214/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "49231",
    "company": "floridaadventuresandrentals",
    "title": "Private Wildlife Sightseeing and Shelling Tour",
    "publicPath": "/destinations/florida/goodland/tours/private-wildlife-sightseeing-and-shelling-tour-49231",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a two-hour guided outing with Florida Adventures and Rentals in Goodland. Shell Bags, Bottled Water, and Cooler with ice for guest use are included.",
      "A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "Two-hour private wildlife sightseeing and shelling tour, with shell bags, bottled water, and a cooler with ice.",
    "highlights": [
      "two-hour guided outing in Goodland",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/fyw32p6aQpOOHHxqlbEo"
    ],
    "productImage": "https://cdn.filestackcontent.com/vc3AxPPTY2f3KKUaCoKd",
    "wordCount": 38,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $425",
    "priceRows": [
      {
        "label": "Private Tour: Up to 6 People",
        "note": "1 to 6 People",
        "amountLabel": "$425"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "7 to 12 People",
        "amountLabel": "$800"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "13 to 17 People",
        "amountLabel": "$1,100"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "425.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/49231/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "525862",
    "company": "floridaadventuresandrentals",
    "title": "2 Hour Private Tour",
    "publicPath": "/destinations/florida/goodland/tours/2-hour-private-tour-525862",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Indulge in the ultimate luxury with the private boat tours, where every aspect of the experience is tailored to the desires, designed for fun with friends or special celebrations. After that, cruise the waterways, spy on homes, and jam out to the favorite tunes while soaking up the sun.",
      "After that, with options to look at hidden islands, sip cool drinks, and dance toward the beat, the private tours promise exhilarating ride that's totally tailored to the crew's vibe. That is customizable for great day on the water for guests and the party. Popular activities include stopping on an isolated island, seeing the mansions from the water, finding dolphins, and cruising around Marco Island."
    ],
    "schemaDescription": "Two-hour private boat tour that can stop at an isolated island, pass waterfront houses, look for dolphins, and cruise around Marco Island.",
    "highlights": [
      "two-hour harbor outing in Goodland",
      "Marco Island",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/GRYbjyfgTHG5OUXmYJUQ"
    ],
    "productImage": "https://cdn.filestackcontent.com/COMQwkvRkaN3KKjzuhiK",
    "wordCount": 114,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $425",
    "priceRows": [
      {
        "label": "Private Tour: Up to 6 People",
        "note": "",
        "amountLabel": "$425"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "",
        "amountLabel": "$800"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "",
        "amountLabel": "$1,100"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "425.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/525862/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "525864",
    "company": "floridaadventuresandrentals",
    "title": "3 Hour Private Tour",
    "publicPath": "/destinations/florida/goodland/tours/3-hour-private-tour-525864",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Indulge in the ultimate luxury with the private boat tours, where every aspect of the experience is tailored to the desires, designed for fun with friends or special celebrations. After that, cruise the waterways, spy on homes, and jam out to the favorite tunes while soaking up the sun.",
      "After that, with options to look at hidden islands, sip cool drinks, and dance toward the beat, the private tours promise exhilarating ride that's totally tailored to the crew's vibe. That is customizable for great day on the water for guests and the party. Popular activities include stopping on an isolated island, seeing the mansions from the water, finding dolphins, and cruising around Marco Island."
    ],
    "schemaDescription": "Three-hour private boat tour that can stop at an isolated island, pass waterfront houses, look for dolphins, and cruise around Marco Island.",
    "highlights": [
      "three-hour harbor outing in Goodland",
      "Marco Island",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/yeWsQ9rQ7OiBgH447561"
    ],
    "productImage": "https://cdn.filestackcontent.com/ltOok1RiT8S4QaUMmV3Q",
    "wordCount": 114,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $525",
    "priceRows": [
      {
        "label": "Private Tour: Up to 6 People",
        "note": "",
        "amountLabel": "$525"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "",
        "amountLabel": "$999"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "",
        "amountLabel": "$1,299"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "525.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/525864/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "525865",
    "company": "floridaadventuresandrentals",
    "title": "4 Hour Private Tour",
    "publicPath": "/destinations/florida/goodland/tours/4-hour-private-tour-525865",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "From the water, guests see Keywaydin Island and Marco Island. The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "Four-hour private boat tour that can visit Keywaydin Island or Marco Island, with stops chosen before departure.",
    "highlights": [
      "four-hour harbor outing in Goodland",
      "Shell Bags"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/YJLDIdbbQx69gq67jNw5"
    ],
    "productImage": "https://cdn.filestackcontent.com/3zgLmjjPSWqzoQQ0j7GM",
    "wordCount": 63,
    "durationLabel": "4 Hours",
    "durationIso": "PT4H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $750",
    "priceRows": [
      {
        "label": "Private Tour: Up to 6 People",
        "note": "",
        "amountLabel": "$750"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "",
        "amountLabel": "$1,299"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "",
        "amountLabel": "$1,699"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "750.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/525865/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "76676",
    "company": "floridaadventuresandrentals",
    "title": "Private Dolphin Tours",
    "publicPath": "/destinations/florida/goodland/tours/private-dolphin-tours-76676",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Private Dolphin Tours is a two-hour guided outing with Florida Adventures and Rentals in Goodland. Water Bottles and Cooler with ice for guest use are included.",
      "A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "Two-hour private dolphin tour. Water bottles and a cooler with ice are included.",
    "highlights": [
      "two-hour guided outing in Goodland",
      "Water Bottles"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/4tU5lTaTuSq5LM23MWEw"
    ],
    "productImage": "https://cdn.filestackcontent.com/KDRotEB8RFSRppMNjQMa",
    "wordCount": 38,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Goodland Boat Park, 750 Palm Point Dr., Goodland, FL 34140",
    "visiblePriceLabel": "From $475",
    "priceRows": [
      {
        "label": "Private Tour: Up to 6 People",
        "note": "1 to 6 People",
        "amountLabel": "$475"
      },
      {
        "label": "Private Tour: Up to 12 People",
        "note": "1 to 12 People",
        "amountLabel": "$900"
      },
      {
        "label": "Private Tour: Up to 17 People",
        "note": "Up to 17 People",
        "amountLabel": "$1,199"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "475.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/76676/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "239475",
    "company": "floridaislandtours",
    "title": "Island Paradise: Dolphin, Shelling, Birding Eco Boat Tour",
    "publicPath": "/destinations/florida/goodland/tours/island-paradise-dolphin-shelling-birding-eco-boat-tour-239475",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a harbor outing with Florida Island Tours. The group starts at Ten Thousand Islands National Wildlife Refuge. The group passes Ten Thousand Islands National Wildlife Refuge and Rookery Bay National Estuarine Research Reserve."
    ],
    "schemaDescription": "Eco boat tour for dolphins, shelling, and birding, starting at the Ten Thousand Islands refuge and passing Rookery Bay.",
    "highlights": [
      "Ten Thousand Islands National Wildlife Refuge and Rookery Bay National Estuarine Research Reserve"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/Bv8zJ4AnTwWTs1JVVvrB"
    ],
    "productImage": "https://cdn.filestackcontent.com/BwbJMCURqanzYzL5swi7",
    "wordCount": 35,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "Goodland • Marco Island • 10,000 Islands",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Standard Ticket",
        "note": "All Ages.",
        "amountLabel": "$129"
      },
      {
        "label": "Child Ticket",
        "note": "Ages 0 to 6",
        "amountLabel": "$99"
      },
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$625"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$1,100"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/239475/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "239489",
    "company": "floridaislandtours",
    "title": "Sand Bar Shelling Tour",
    "publicPath": "/destinations/florida/goodland/tours/sand-bar-shelling-tour-239489",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Sand Bar Shelling Tour is a guided outing lasting 2 with Florida Island Tours in Goodland. Cooler with ice, Shelling bags, and Parking are included. The outing reaches Kice Island.",
      "Groups are capped at 6."
    ],
    "schemaDescription": "Two-hour sandbar shelling tour that reaches Kice Island. A cooler with ice, shelling bags, and parking are included.",
    "highlights": [
      "2 guided outing",
      "Kice Island",
      "Groups are capped at 6"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/OyRN4Wo5RRwv35fpUFsL"
    ],
    "productImage": "https://cdn.filestackcontent.com/tP7p0yyQJKDdYuLy0UUy",
    "wordCount": 35,
    "durationLabel": "2",
    "durationIso": null,
    "meetingLocation": "220 Goodland Dr. Goodland, FL 34140",
    "visiblePriceLabel": "From $500",
    "priceRows": [
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$500"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$875"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "500.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/239489/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "239507",
    "company": "floridaislandtours",
    "title": "Barrier Island Shelling Tour",
    "publicPath": "/destinations/florida/goodland/tours/barrier-island-shelling-tour-239507",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Barrier Island Shelling Tour is a guided outing with Florida Island Tours. The outing starts at Kice Island. The group then visits Shell Island and Marco Island."
    ],
    "schemaDescription": "Barrier island shelling tour starting at Kice Island and continuing to Shell Island and Marco Island.",
    "highlights": [
      "Kice Island and Shell Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/O0vj9fx2RaHe2hhGKews"
    ],
    "productImage": "https://cdn.filestackcontent.com/YEADPrOxQCmtk7ou7tCd",
    "wordCount": 27,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "Goodland • Marco Island • 10,000 Islands",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Standard Ticket",
        "note": "All Ages.",
        "amountLabel": "$129"
      },
      {
        "label": "Child Ticket",
        "note": "Ages 0 to 6",
        "amountLabel": "$99"
      },
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$625"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$1,100"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/239507/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "239612",
    "company": "floridaislandtours",
    "title": "Family Fun Day with Fishing (4hrs)",
    "publicPath": "/destinations/florida/goodland/tours/family-fun-day-with-fishing-4hrs-239612",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a guided outing with Florida Island Tours in Goodland. Cooler with Ice, Shelling Bags, and Parking are included.",
      "Groups are capped at 6."
    ],
    "schemaDescription": "Four-hour family fishing day for up to six people. A cooler with ice, shelling bags, and parking are included.",
    "highlights": [
      "4hrs guided outing",
      "Groups are capped at 6"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/dEK6FM3ZRbSeXhfotP36"
    ],
    "productImage": "https://cdn.filestackcontent.com/WDrKet5SA8fLShqqRncQ",
    "wordCount": 25,
    "durationLabel": "4hrs",
    "durationIso": null,
    "meetingLocation": "220 Goodland Dr. Goodland, FL 34140",
    "visiblePriceLabel": "From $850",
    "priceRows": [
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$850"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "850.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/239612/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "352216",
    "company": "floridaislandtours",
    "title": "2hr Private Boat Tour",
    "publicPath": "/destinations/florida/goodland/tours/2hr-private-boat-tour-352216",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "2hr Private Boat Tour is a harbor outing lasting 2hrs with Florida Island Tours on Goodland Harbor.",
      "Cooler with Ice, Shelling Bags, and Parking are included."
    ],
    "schemaDescription": "Two-hour private boat tour. A cooler with ice, shelling bags, and parking are included.",
    "highlights": [
      "2hrs harbor outing"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/zgfsrZ4QTzuqcgjgVu8E"
    ],
    "productImage": "https://cdn.filestackcontent.com/mGQcc7TyO9QTcTw0nWOw",
    "wordCount": 26,
    "durationLabel": "2hrs",
    "durationIso": null,
    "meetingLocation": "220 Goodland Dr. Goodland, FL 34140",
    "visiblePriceLabel": "From $500",
    "priceRows": [
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$500"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$875"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "500.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/352216/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "417714",
    "company": "floridaislandtours",
    "title": "Best of Marco Island Tour",
    "publicPath": "/destinations/florida/goodland/tours/best-of-marco-island-tour-417714",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Florida Island Tours runs this two-hour sightseeing cruise, which leaves Goodland, crosses the mangrove estuary of the Ten Thousand Islands National Wildlife Refuge, reaches Marco Island, and returns. The guide is a Florida-certified master naturalist who also belongs to the historical society on Marco Island. Talk on the boat covers the Calusa, Cape Romano, how the island was developed, waterfront culture, and wildlife. Dolphins, manatees, and birds are animals guests may see.",
      "The route also takes in Goodland's waterfront bars and restaurants, then houses along the Marco Estates. A cooler with ice is included, and so is parking. The group cap is six."
    ],
    "schemaDescription": "Two-hour cruise from Goodland through the Ten Thousand Islands refuge to Marco Island and back, led by a Florida-certified master naturalist.",
    "highlights": [
      "two-hour guided outing in Goodland",
      "Marco Island and Marco Island Historical Society",
      "Groups are capped at 6"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/BTdUqlRTKXqzttPAN7Xw"
    ],
    "productImage": "https://cdn.filestackcontent.com/lYw27uHtQ86Ixj97LJHh",
    "wordCount": 105,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": "220 Goodland Dr. Goodland, FL 34140",
    "visiblePriceLabel": "From $85",
    "priceRows": [
      {
        "label": "Standard Ticket",
        "note": "All Ages.",
        "amountLabel": "$99"
      },
      {
        "label": "Child Ticket",
        "note": "Ages 0 to 6",
        "amountLabel": "$85"
      },
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$500"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$875"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "85.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/417714/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "417843",
    "company": "floridaislandtours",
    "title": "Half-Day Super Shelling Tour",
    "publicPath": "/destinations/florida/goodland/tours/half-day-super-shelling-tour-417843",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a private sandbar charter on the water. From the water, guests see Marco Island and Kice Island. Dickman's Point and Caxambas Sandbars come into view as the boat moves. The cruise also passes Second Chance and Shell Island."
    ],
    "schemaDescription": "Four-hour shelling trip passing Marco Island, Kice Island, Dickman's Point, and Shell Island, with time at the Caxambas sandbars.",
    "highlights": [
      "four-hour guided outing in Goodland",
      "Kice Island and Shell Island",
      "Parking"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/cO930ey7QiGeJn87UPKk"
    ],
    "productImage": "https://cdn.filestackcontent.com/Fk3ukq2MQ0Wt6EfBNRSn",
    "wordCount": 40,
    "durationLabel": "4 hours",
    "durationIso": "PT4H",
    "meetingLocation": "220 Goodland Dr. Goodland, FL 34140",
    "visiblePriceLabel": "From $149",
    "priceRows": [
      {
        "label": "Standard Ticket",
        "note": "All Ages.",
        "amountLabel": "$199"
      },
      {
        "label": "Child Ticket",
        "note": "Ages 0 to 6",
        "amountLabel": "$149"
      },
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$1,000"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$1,700"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "149.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/417843/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "597140",
    "company": "floridaislandtours",
    "title": "8hr Private Boat Tour",
    "publicPath": "/destinations/florida/goodland/tours/8hr-private-boat-tour-597140",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "From the water, guests see Marco Island and Ten Thousand Islands. Islands Beach and Sunset Free come into view as the boat moves."
    ],
    "schemaDescription": "Private boat tour of about eight hours with views of Marco Island and the Ten Thousand Islands.",
    "highlights": [
      "Marco Island sightseeing and Beach hopping",
      "Free parking"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/UDgRqXXnQv6L1n5Cqstp"
    ],
    "productImage": "https://cdn.filestackcontent.com/8qp1QRgTkyL0cRK8WBLo",
    "wordCount": 23,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "220 Goodland Dr Goodland FL 34140",
    "visiblePriceLabel": "From $2,000",
    "priceRows": [
      {
        "label": "Private charter 6-pack",
        "note": "All ages welcome • Up to six people",
        "amountLabel": "$2,000"
      },
      {
        "label": "Private Charter 12 Pack",
        "note": "All ages welcome - 7 to 12 people",
        "amountLabel": "$3,400"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "2000.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/floridaislandtours/items/597140/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
