// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborJoshuaTreeLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "459544",
    "company": "joshuatreeexcursions",
    "title": "Sightseeing Tour",
    "publicPath": "/destinations/california/joshua-tree/tours/sightseeing-tour-459544",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The route also reaches Skull Rock and Arch Rock. Ohlsen Ranch and Cholla Cactus Garden are part of the same outing. Later the group comes to Cap Rock Nature Trail and Key's View. There is time to look at More Info. Attention also goes to Joshua Tree Classic and Cholla Garden, with the guide attaching a story to each stop.",
      "Among the places guests actually encounter are Joshua Tree Classic, Cholla Garden, and Skull Rock. Later the guide turns to Arch Rock and Ohlsen Ranch, explaining what happened there. Guests come to Joshua Tree Classic and Cholla Garden, and they hear why those places are on the trip."
    ],
    "schemaDescription": "A 4.5-hour guided outing with Joshua Tree Excursions. The outing passes Cholla Garden, Cholla Cactus Garden, and Cap Rock Nature Trail.",
    "highlights": [
      "4.5 hours guided outing",
      "Cholla Garden and Cholla Cactus Garden"
    ],
    "galleryImages": [],
    "wordCount": 108,
    "durationLabel": "4.5 hours",
    "durationIso": "PT4H30M",
    "meetingLocation": null,
    "visiblePriceLabel": "From $487.60",
    "priceRows": [
      {
        "label": "Tour",
        "note": "Price includes up to 4 people",
        "amountLabel": "$487.60"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "487.60",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/joshuatreeexcursions/items/459544/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "459589",
    "company": "joshuatreeexcursions",
    "title": "Private Morning Hike",
    "publicPath": "/destinations/california/joshua-tree/tours/private-morning-hike-459589",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The guide will then take guests on a drive through the most parts of the park, on-route to the hike/sightseeing for the day. Optional lunch on the trail before continuing the journey. All on the way, the expert guide will share history and geology of the Park, stop with myriad of stories and talks about plants, animals, and other characteristics of the Park.",
      "Guests may even get in some rock scrambling toward the top of some of the rock formations for views and meets rarely had by others. After that, at the conclusion of the hike, time permitting, the guide will get guests to some of other popular sights in park before returning guests safely to the office or back to the lodging facility where guests relax and talk about the memories that guests have made, that will last a lifetime."
    ],
    "schemaDescription": "A 6-hour guided outing with Joshua Tree Excursions. The outing passes Joshua Tree National Park.",
    "highlights": [
      "6 hours guided outing",
      "Joshua Tree National Park"
    ],
    "galleryImages": [],
    "wordCount": 143,
    "durationLabel": "6 hours",
    "durationIso": "PT6H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $1,802",
    "priceRows": [
      {
        "label": "Tour",
        "note": "Price includes up to 4 people",
        "amountLabel": "$1,802"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1802.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/joshuatreeexcursions/items/459589/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "459590",
    "company": "joshuatreeexcursions",
    "title": "Private Sunset Hike",
    "publicPath": "/destinations/california/joshua-tree/tours/private-sunset-hike-459590",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The guide will then take guests on a drive through the most parts of the park, on-route to the hike/Sightseeing for the day. Optional lunch on the trail before continuing the journey. All on the way, the expert guide will share history and geology of the Park, stop with myriad of stories and talks about plants, animals, and other characteristics of the Park.",
      "Guests may even get in some rock scrambling toward the top of some of the rock formations for views and meets rarely had by others. After that, at the conclusion of the hike, time permitting, the guide will get guests to some of other popular sights in park before returning guests safely to the office or back to the lodging facility where guests relax and talk about the memories that guests have made, that will last a lifetime."
    ],
    "schemaDescription": "A 6-hour guided outing with Joshua Tree Excursions.",
    "highlights": [
      "6 hours guided outing"
    ],
    "galleryImages": [],
    "wordCount": 143,
    "durationLabel": "6 hours",
    "durationIso": "PT6H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $1,802",
    "priceRows": [
      {
        "label": "Tour",
        "note": "Price includes up to 4 people",
        "amountLabel": "$1,802"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1802.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/joshuatreeexcursions/items/459590/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "459591",
    "company": "joshuatreeexcursions",
    "title": "Hike & Climb",
    "publicPath": "/destinations/california/joshua-tree/tours/hike-and-climb-459591",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Duration About After meeting at the office, the guide will then take guests on a drive through the most parts of the park. On the way, guests receive detailed narration on park, its history, and interesting geology to Joshua Tree. Once at the trailhead, the guide will lead guests on mostly off-trail adventure through Joshua Tree wilderness.",
      "The climbing experience includes professional instruction from the certified rock guide, and all necessary equipment. After that, whether guests are first-time climber or multi-pitch expert, the guides will make sure guests have an experience. All throughout the day, the personal guides will share history and geology of the Park, stop with myriad of stories and talks about plants, animals, and other characteristics of the Park.",
      "Guests may even get to add in some rock scrambling toward the top of some of the otherworldly rock formations, for views and meets rarely had by others."
    ],
    "schemaDescription": "A 8-hour guided outing with Joshua Tree Excursions. The outing passes Joshua Tree National Park.",
    "highlights": [
      "8 hours guided outing",
      "Joshua Tree National Park"
    ],
    "galleryImages": [],
    "wordCount": 153,
    "durationLabel": "8 hours",
    "durationIso": "PT8H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $2,014",
    "priceRows": [
      {
        "label": "Tour",
        "note": "Price includes up to 2 cliimbers",
        "amountLabel": "$2,014"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "2014.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/joshuatreeexcursions/items/459591/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "402194",
    "company": "mustangsanctuary",
    "title": "Sunset Trail Ride",
    "publicPath": "/destinations/california/joshua-tree/tours/sunset-trail-ride-402194",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Attention also goes to Joshua Tree, and the guide explains why it is on the route. Guests stay on foot the whole time, pausing while the guide talks at each site. Guests do not travel by bus or by boat. They stand at the sites while the explanation is given.",
      "Guests keep walking while that account is given, moving at the guide's pace. The explanation happens outdoors, in front of the buildings, and the group moves on only after it is given. Each pause is there so guests can look at the place the story belongs to.",
      "Guests come to Joshua Tree, and they hear why it is on the trip."
    ],
    "schemaDescription": "A one-hour walking tour with Cascade Trails Mustang Sanctuary in Joshua Tree.",
    "highlights": [
      "one-hour walking tour in Joshua Tree"
    ],
    "galleryImages": [],
    "wordCount": 111,
    "durationLabel": "1 hour",
    "durationIso": "PT1H",
    "meetingLocation": "6353 Cascade Rd Joshua Tree, CA 92252",
    "visiblePriceLabel": "From $169.60",
    "priceRows": [
      {
        "label": "Person",
        "note": "8 years and older",
        "amountLabel": "$169.60"
      },
      {
        "label": "Group Ride Discount - Minimum 5 Riders",
        "note": "",
        "amountLabel": "$636"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "169.60",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/402194/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "513079",
    "company": "mustangsanctuary",
    "title": "El Dorado",
    "publicPath": "/destinations/california/joshua-tree/tours/el-dorado-513079",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Overnight guests sleep in a bell tent instead of taking a guided walk. Sleeping is on a queen bed, and linens are provided. A firepit on the site is there for the evening. A propane grill is on hand for cooking outdoors. Outdoor seating includes a picnic table for meals on the site.",
      "An outdoor shower and a sink are part of this site. Shared portable toilets are a short walk from the site. This booking is an overnight stay, not a sightseeing route through town. Guests spend the night on the site, and the firepit is the evening gathering place."
    ],
    "schemaDescription": "A guided outing with Cascade Trails Mustang Sanctuary.",
    "highlights": [],
    "galleryImages": [],
    "wordCount": 101,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $222.60",
    "priceRows": [
      {
        "label": "Two Nights",
        "note": "",
        "amountLabel": "$222.60"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "222.60",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/513079/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "514091",
    "company": "mustangsanctuary",
    "title": "La Luna",
    "publicPath": "/destinations/california/joshua-tree/tours/la-luna-514091",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Overnight guests sleep in a geodesic dome instead of taking a guided walk. Sleeping is on a queen bed, and linens are provided. A couch and a folding mattress give more room to sleep. A firepit on the site is there for the evening. A propane grill is on hand for cooking outdoors.",
      "An outdoor shower and a sink are part of this site. A private portable toilet is assigned to this site. A heater is available when the night turns cold. The dome is not insulated, so summers run hot and winters run cold. Guests bring their own drinking water for the stay.",
      "This booking is an overnight stay, not a sightseeing route through town. Guests spend the night on the site, and the firepit is the evening gathering place."
    ],
    "schemaDescription": "A guided outing with Cascade Trails Mustang Sanctuary in Joshua Tree.",
    "highlights": [],
    "galleryImages": [],
    "wordCount": 131,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "6353 Cascade Rd Joshua Tree, CA 92252",
    "visiblePriceLabel": "From $148.40",
    "priceRows": [
      {
        "label": "One Night",
        "note": "3 pm Check In • 11 am Check Out",
        "amountLabel": "$148.40"
      },
      {
        "label": "Two Nights",
        "note": "",
        "amountLabel": "$349.80"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "148.40",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/514091/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "514094",
    "company": "mustangsanctuary",
    "title": "Durango",
    "publicPath": "/destinations/california/joshua-tree/tours/durango-514094",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Overnight guests sleep in a bell tent instead of taking a guided walk. Sleeping is on a queen bed, and linens are provided. A firepit on the site is there for the evening. Outdoor seating includes a picnic table for meals on the site. Solar lights are inside for the evening hours.",
      "Shared portable toilets are a short walk from the site. A heater is available when the night turns cold. This booking is an overnight stay, not a sightseeing route through town. Guests spend the night on the site, and the firepit is the evening gathering place.",
      "Outdoors is where the account is given, with the site itself in front of the group."
    ],
    "schemaDescription": "A guided outing with Cascade Trails Mustang Sanctuary.",
    "highlights": [],
    "galleryImages": [],
    "wordCount": 114,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $95.40",
    "priceRows": [
      {
        "label": "One Night",
        "note": "3 pm Check In • 11 am Check Out",
        "amountLabel": "$95.40"
      },
      {
        "label": "Two Nights",
        "note": "",
        "amountLabel": "$190.80"
      },
      {
        "label": "Three Nights",
        "note": "",
        "amountLabel": "$286.20"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "95.40",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/514094/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "515026",
    "company": "mustangsanctuary",
    "title": "Campsite #6",
    "publicPath": "/destinations/california/joshua-tree/tours/campsite-6-515026",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests camp on a dry site and bring a tent, a camper, or a trailer. A firepit on the site is there for the evening. Shared portable toilets are a short walk from the site. Trailers parked on the site are limited to about 30 feet.",
      "The site has no hookups, so guests bring what they need for the night. This booking is an overnight stay, not a sightseeing route through town. Guests spend the night on the site, and the firepit is the evening gathering place. Outdoors is where the account is given, with the site itself in front of the group."
    ],
    "schemaDescription": "A guided outing with Cascade Trails Mustang Sanctuary.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/087AoVruQH651SNUwhLe"
    ],
    "wordCount": 103,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $31.80",
    "priceRows": [
      {
        "label": "One Night",
        "note": "",
        "amountLabel": "$31.80"
      },
      {
        "label": "Two Nights",
        "note": "",
        "amountLabel": "$63.60"
      },
      {
        "label": "Three Nights",
        "note": "",
        "amountLabel": "$95.40"
      },
      {
        "label": "Four Nights",
        "note": "",
        "amountLabel": "$127.20"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "31.80",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/515026/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "520036",
    "company": "mustangsanctuary",
    "title": "Campsite #7",
    "publicPath": "/destinations/california/joshua-tree/tours/campsite-7-520036",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests camp on a dry site and bring a tent, a camper, or a trailer. A firepit on the site is there for the evening. Shared portable toilets are a short walk from the site. Trailers parked on the site are limited to about 30 feet.",
      "The site has no hookups, so guests bring what they need for the night. This booking is an overnight stay, not a sightseeing route through town. Guests spend the night on the site, and the firepit is the evening gathering place. Outdoors is where the account is given, with the site itself in front of the group."
    ],
    "schemaDescription": "A guided outing with Cascade Trails Mustang Sanctuary.",
    "highlights": [],
    "galleryImages": [],
    "wordCount": 103,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $31.80",
    "priceRows": [
      {
        "label": "One Night",
        "note": "",
        "amountLabel": "$31.80"
      },
      {
        "label": "Two Nights",
        "note": "",
        "amountLabel": "$63.60"
      },
      {
        "label": "Three Nights",
        "note": "",
        "amountLabel": "$95.40"
      },
      {
        "label": "Four Nights",
        "note": "",
        "amountLabel": "$127.20"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "31.80",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/520036/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "587300",
    "company": "mustangsanctuary",
    "title": "In the Company of Horses & Wine",
    "publicPath": "/destinations/california/joshua-tree/tours/in-the-company-of-horses-and-wine-587300",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The tasting also stops near Northern California and Phineas Fittipaldi. Guests keep eating as they reach Cascade Trails Personalized and Curated Wine Tasting. Wiley Wines Guided are part of the same food route. Food is the thread: each stop is there for what guests taste, with the street as the setting.",
      "Among the places guests actually encounter are Northern California, Phineas Fittipaldi, and Cascade Trails Personalized. Later the guide turns to Curated Wine Tasting and Wiley Wines Guided, explaining what happened there. The stops exist for the food. Streets and storefronts are the setting, and tasting is the point.",
      "Guests come to Northern California and Phineas Fittipaldi, and they hear why those places are on the trip."
    ],
    "schemaDescription": "A 1.5-hour food walk with Cascade Trails Mustang Sanctuary in Joshua Tree.",
    "highlights": [
      "1.5-hour food walk in Joshua Tree",
      "Interactive Equine Experience"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/pQXu1NGT4OVShVE4nevg"
    ],
    "wordCount": 117,
    "durationLabel": "1.5 hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "6353 Cascade Rd Joshua Tree, CA 92252",
    "visiblePriceLabel": "From $106",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 21+",
        "amountLabel": "$106"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "106.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/587300/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "598562",
    "company": "mustangsanctuary",
    "title": "Morning Trail Ride",
    "publicPath": "/destinations/california/joshua-tree/tours/morning-trail-ride-598562",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Attention also goes to Joshua Tree, and the guide explains why it is on the route. Guests stay on foot the whole time, pausing while the guide talks at each site. Guests do not travel by bus or by boat. They stand at the sites while the explanation is given.",
      "Guests keep walking while that account is given, moving at the guide's pace. The explanation happens outdoors, in front of the buildings, and the group moves on only after it is given. Each pause is there so guests can look at the place the story belongs to.",
      "Guests come to Joshua Tree, and they hear why it is on the trip."
    ],
    "schemaDescription": "A one-hour walking tour with Cascade Trails Mustang Sanctuary in Joshua Tree.",
    "highlights": [
      "one-hour walking tour in Joshua Tree"
    ],
    "galleryImages": [],
    "wordCount": 111,
    "durationLabel": "1 Hour",
    "durationIso": "PT1H",
    "meetingLocation": "6353 Cascade Rd Joshua Tree, CA 92252",
    "visiblePriceLabel": "From $169.60",
    "priceRows": [
      {
        "label": "Person",
        "note": "8 years and older",
        "amountLabel": "$169.60"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "169.60",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 373,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 373 reviews on GET https://fareharbor.com/api/v1/companies/mustangsanctuary/items/598562/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  }
];
