// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborRedondoBeachLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "478885",
    "company": "beachebiking",
    "title": "2 Hour Beach E-Bike Ride",
    "publicPath": "/destinations/california/redondo-beach/tours/2-hour-beach-e-bike-ride-478885",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 24 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Hermosa Beach and Manhattan Beach. Cyclists also come to Santa Monica and Redondo Beach Pier. E-Bike Rental Includes and Amp Hour Battery are on the same loop. Later the route reaches E-Bike Orientation. Guests cover the sights by bike, stopping where the guide has something to say."
    ],
    "schemaDescription": "A bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/txmlzM1cQbCXWf0NTCQQ"
    ],
    "productImage": "https://cdn.filestackcontent.com/Pb0Jgt9QVebMYsrvvnPz",
    "wordCount": 103,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $42.40",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$42.40"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$42.40"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "42.40",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/478885/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "478891",
    "company": "beachebiking",
    "title": "4 Hr Beach E-Bike Ride",
    "publicPath": "/destinations/california/redondo-beach/tours/4-hr-beach-e-bike-ride-478891",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 24 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Santa Monica and Redondo Beach Pier. Cyclists also come to E-Bike Rental Includes and Amp Hour Battery. E-Bike Orientation are on the same loop. Guests cover the sights by bike, stopping where the guide has something to say. Among the places guests actually encounter are Santa Monica, Redondo Beach Pier, and E-Bike Rental Includes."
    ],
    "schemaDescription": "A bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/g7s2MrgBTc6kAsqqTvuh"
    ],
    "productImage": "https://cdn.filestackcontent.com/HFTBR3qsSu6mzf5ei1zy",
    "wordCount": 111,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $79.50",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$79.50"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$79.50"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "79.50",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/478891/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "478894",
    "company": "beachebiking",
    "title": "6 Hr E-Bike Ride",
    "publicPath": "/destinations/california/redondo-beach/tours/6-hr-e-bike-ride-478894",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 24 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Santa Monica and Redondo Beach Pier. Cyclists also come to E-Bike Rental Includes and Amp Hour Battery. E-Bike Orientation are on the same loop. Guests cover the sights by bike, stopping where the guide has something to say. Among the places guests actually encounter are Santa Monica, Redondo Beach Pier, and E-Bike Rental Includes."
    ],
    "schemaDescription": "A bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/dQH6BU9zS6CxcOacDchA"
    ],
    "productImage": "https://cdn.filestackcontent.com/R1wAT0UsTLi7bM69t0Z8",
    "wordCount": 111,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $100.70",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$100.70"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$100.70"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "100.70",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/478894/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "478898",
    "company": "beachebiking",
    "title": "1 Day E-Bike Rental (including overnight)",
    "publicPath": "/destinations/california/redondo-beach/tours/1-day-e-bike-rental-including-overnight-478898",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 24 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Marvin Braude Bike Trail and Santa Monica. Cyclists also come to Redondo Beach Pier and E-Bike Rental Includes. Amp Hour Battery and E-Bike Orientation are on the same loop. Guests cover the sights by bike, stopping where the guide has something to say.",
      "Among the places guests actually encounter are Marvin Braude Bike Trail, Santa Monica, and Redondo Beach Pier."
    ],
    "schemaDescription": "A bicycle outing with Beach E Biking. The outing passes Day E-Bike Rental, Marvin Braude Bike Trail, and E-Bike Orientation.",
    "highlights": [
      "Day E-Bike Rental and Marvin Braude Bike Trail"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/8vPrcuOSEKakmrwBJxrQ"
    ],
    "productImage": "https://cdn.filestackcontent.com/Q52GuMkDSeC5gxy28b1A",
    "wordCount": 116,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": null,
    "visiblePriceLabel": "From $116.60",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$116.60"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$116.60"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "116.60",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/478898/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "478902",
    "company": "beachebiking",
    "title": "2 Day E-Bike Rental",
    "publicPath": "/destinations/california/redondo-beach/tours/2-day-e-bike-rental-478902",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 48 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Beach Life Festival and Fiesta Hermoa. Cyclists also come to Santa Monica and Redondo Beach Pier. E-Bike Rental Includes and Amp Hour Battery are on the same loop. Later the route reaches E-Bike Orientation. Guests cover the sights by bike, stopping where the guide has something to say."
    ],
    "schemaDescription": "A 48-hour bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "48 Hours bicycle outing",
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/lEcvhRXQyessYAkNjjlP"
    ],
    "productImage": "https://cdn.filestackcontent.com/gbBSlaCsQYOA1wI7Wgg9",
    "wordCount": 104,
    "durationLabel": "48 Hours",
    "durationIso": "PT48H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $212",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$212"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$212"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "212.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/478902/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "478908",
    "company": "beachebiking",
    "title": "3 Day E-Bike Rental",
    "publicPath": "/destinations/california/redondo-beach/tours/3-day-e-bike-rental-478908",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 72 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Beach Life Festival and Fiesta Hermoa. Cyclists also come to Santa Monica and Redondo Beach Pier. E-Bike Rental Includes and Amp Hour Battery are on the same loop. Later the route reaches E-Bike Orientation. Guests cover the sights by bike, stopping where the guide has something to say."
    ],
    "schemaDescription": "A 72-hour bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "72 Hours bicycle outing",
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/erN7yLkxQWGcuiuKw3T8"
    ],
    "productImage": "https://cdn.filestackcontent.com/jh5FuMKhQEW99iZwTIkf",
    "wordCount": 104,
    "durationLabel": "72 Hours",
    "durationIso": "PT72H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $265",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$265"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$265"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "265.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/478908/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "479100",
    "company": "beachebiking",
    "title": "4 Day E-Bike Rental",
    "publicPath": "/destinations/california/redondo-beach/tours/4-day-e-bike-rental-479100",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 96 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Beach Life Festival and Fiesta Hermoa. Cyclists also come to Santa Monica and Redondo Beach Pier. E-Bike Rental Includes and Amp Hour Battery are on the same loop. Later the route reaches E-Bike Orientation. Guests cover the sights by bike, stopping where the guide has something to say."
    ],
    "schemaDescription": "A 96-hour bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "96 Hours bicycle outing",
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/9jlIbmABSpC5knofFUrN"
    ],
    "productImage": "https://cdn.filestackcontent.com/fq6swO0JT5ePBXYSB9mZ",
    "wordCount": 104,
    "durationLabel": "96 Hours",
    "durationIso": "PT96H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $307.40",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$307.40"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$307.40"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "307.40",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/479100/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "479103",
    "company": "beachebiking",
    "title": "7 Day E-Bike Rental",
    "publicPath": "/destinations/california/redondo-beach/tours/7-day-e-bike-rental-479103",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes between the stops on this outing. The bikes are pedal-assist, so the motor helps on the hills. A helmet is included, and the shop fits the bike before departure. The booking runs about 168 hours. People stay with the bikes for the riding portion of the booking.",
      "The ride passes Beach Life Festival and Fiesta Hermosa. Cyclists also come to Santa Monica and Redondo Beach Pier. E-Bike Rental Includes and Amp Hour Battery are on the same loop. Later the route reaches E-Bike Orientation. Guests cover the sights by bike, stopping where the guide has something to say."
    ],
    "schemaDescription": "A 168-hour bicycle outing with Beach E Biking. The outing passes E-Bike Orientation, Redondo Beach Pier, and E-Bike Rental Includes.",
    "highlights": [
      "168 Hours bicycle outing",
      "E-Bike Orientation and Redondo Beach Pier"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/ew3F18DnQiiuN8JDPJqQ"
    ],
    "productImage": "https://cdn.filestackcontent.com/PTfS7XYLRNOdOoUUaoHx",
    "wordCount": 104,
    "durationLabel": "168 Hours",
    "durationIso": "PT168H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $434.60",
    "priceRows": [
      {
        "label": "Model E Bike • 24\" Wheels",
        "note": "For riders 4'10\" (148cm) to 5'4\" (163cm) - Cruiser with Step-through Frame",
        "amountLabel": "$434.60"
      },
      {
        "label": "Model E Bike • 26\" Wheels",
        "note": "For riders 5'4\" (163cm) and taller. Cruiser with Step-through Frame",
        "amountLabel": "$434.60"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "434.60",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/beachebiking/items/479103/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
