// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborHonoluluLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "141477",
    "company": "alohahawaiitours",
    "title": "Sights & Bites Circle Island Tour",
    "publicPath": "/destinations/hawaii/honolulu/tours/sights-and-bites-circle-island-tour-141477",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Discover Oʻahu beyond Waikīkī on an eight-hour narrated circle-island excursion that combines scenic viewpoints with stops connected to local food. Aloha Hawaii Tours lists hotel pickup in Waikīkī, making this a full-day introduction to different sides of the island.",
      "The itinerary includes Hālona Blowhole on the southeastern coast and the dramatic mountain panorama from Nuʻuanu Pali Lookout. Other scheduled locations include a macadamia nut farm, a shrimp-truck stop and Puaʻena Point on the North Shore. These places offer contrasting views of Oʻahu's volcanic coastline, agricultural traditions and surf-oriented communities.",
      "The operator lists the tour as stroller- and wheelchair-accessible; confirm individual stop accessibility and current pickup details before travel. Allow the full eight hours and check whether food purchases are included or paid separately."
],
    "schemaDescription": "An 8-hour guided outing with Aloha Hawaii Tours. The outing passes Halona Blowhole, Pali Lookout, and Macadamia Nut Farm.",
    "highlights": [
      "8-hour guided outing",
      "Halona Blowhole and Pali Lookout",
      "Narrated scenic drive"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/MjTOHvSE62q1lZf4Nvjg"
    ],
    "productImage": "https://cdn.filestackcontent.com/RDZLOzvKRVeXaOHkO86R",
    "wordCount": 123,
    "durationLabel": "8 Hours",
    "durationIso": "PT8H",
    "meetingLocation": "Pick-up from a Waikiki hotel is required",
    "visiblePriceLabel": "From $149",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$149"
      },
      {
        "label": "Child",
        "note": "Ages 4 - 12",
        "amountLabel": "$99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "149.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 3107,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.7 from 3107 reviews on GET https://fareharbor.com/api/v1/companies/alohahawaiitours/items/141477/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "163820",
    "company": "alohahawaiitours",
    "title": "Pearl Harbor City Tour / USS Arizona Memorial",
    "publicPath": "/destinations/hawaii/honolulu/tours/pearl-harbor-city-tour-uss-arizona-memorial-163820",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The commentary takes up Honolulu's World War II and Hawaii State Capitol. That same account stays with King Kamehameha Statue and Kawaiaha'o Church Historic Landmarks. The route keeps Iolani Palace in view. The locations are chosen because a film or television scene was shot there."
    ],
    "schemaDescription": "A 5-hour guided outing with Aloha Hawaii Tours. The outing passes USS Arizona Memorial, Hawaii State Capitol, and King Kamehameha Statue.",
    "highlights": [
      "5-hour guided outing",
      "USS Arizona Memorial and Hawaii State Capitol",
      "Transportation to and from Pearl Harbor"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/3FITLndfSoakiU32rgR7"
    ],
    "productImage": "https://cdn.filestackcontent.com/o4szOc7TDOTnYYWc5Ycw",
    "wordCount": 45,
    "durationLabel": "5 Hours",
    "durationIso": "PT5H",
    "meetingLocation": "Pick-up from Waikiki/Honolulu hotels only. Contact for other areas.",
    "visiblePriceLabel": "From $69",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 13+",
        "amountLabel": "$69"
      },
      {
        "label": "Child",
        "note": "Ages 4 to 12. Children 3 and under do not need a ticket",
        "amountLabel": "$45"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "69.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 3107,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.7 from 3107 reviews on GET https://fareharbor.com/api/v1/companies/alohahawaiitours/items/163820/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "201636",
    "company": "andyoucreations",
    "title": "Ocean and You",
    "publicPath": "/destinations/hawaii/honolulu/tours/ocean-and-you-201636",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Take to the water off Honolulu for a two-hour cruise with views back toward Waikīkī and Diamond Head. The shoreline looks different from the boat, with the volcanic outline of Lēʻahi rising beyond the hotels and beaches.",
      "The operator highlights Friday-night fireworks as a special feature of applicable sailings. The harbor offers a vantage point away from the busiest shoreline viewing areas. The source material also mentions marine life, but whales and dolphins are wild animals and should not be treated as guaranteed sightings on a sightseeing cruise.",
      "This is an onboard experience rather than a shore excursion. Confirm your departure day, boarding point and whether the fireworks are scheduled for your particular sailing. Ocean conditions, wildlife activity and the visibility of any display can vary."
],
    "schemaDescription": "The cruise is out on the harbor for the fireworks. Guests go out on the water to look for whales. Dolphins are also part of what the outing goes out to see. People stay aboard, and the animals are what the trip goes out to find.",
    "highlights": [
      "two-hour guided outing in Honolulu",
      "Fireworks show (Fridays only)"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/moF2kxwTYOuufX3nWG8S"
    ],
    "productImage": "https://cdn.filestackcontent.com/jqDLeHsfSNKuL9m0yJRh",
    "wordCount": 126,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "1125 Ala Moana Blvd D111 Honolulu, HI 96814",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 21+",
        "amountLabel": "$99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 1809,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 1809 reviews on GET https://fareharbor.com/api/v1/companies/andyoucreations/items/201636/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "334772",
    "company": "andyoucreations",
    "title": "Whales and You",
    "publicPath": "/destinations/hawaii/honolulu/tours/whales-and-you-334772",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Search for humpback whales off Oʻahu on a two-hour boat excursion from Honolulu. The outing is built around watching the ocean for marine mammals while enjoying a view back toward the island's south coast.",
      "Humpback whales migrate to Hawaiian waters seasonally, making the experience particularly relevant during the winter months. From offshore, the operator describes views toward Oʻahu's Gold Coast. The boat remains the viewing platform throughout the excursion; guests do not need to plan for a shore stop.",
      "Whales are wild animals, so encounters and their proximity to the vessel cannot be promised. Complimentary soft drinks are listed among the highlights. Confirm the seasonal sailing schedule, boarding instructions and current weather arrangements when reserving."
],
    "schemaDescription": "Guests go out on the water to look for whales. Animals the trip watches for include humpback whales. People stay aboard, and the animals are what the trip goes out to find. Travel stays on the boat for the whole trip. From the water, guests see Oahu's Gold Coast and Ho Mai.",
    "highlights": [
      "two-hour guided outing in Honolulu",
      "Complimentary Soft Drinks"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/VJrlVlkAQEOUwCYjozKk"
    ],
    "productImage": "https://cdn.filestackcontent.com/jGba9HUMRXSeKyD8ULPT",
    "wordCount": 115,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "1125 Ala Moana Blvd B1 Honolulu, HI 96814",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Adult",
        "note": "",
        "amountLabel": "$99"
      },
      {
        "label": "Child",
        "note": "3-11 years",
        "amountLabel": "$69"
      },
      {
        "label": "Infant",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 1809,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 1809 reviews on GET https://fareharbor.com/api/v1/companies/andyoucreations/items/334772/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "368817",
    "company": "andyoucreations",
    "title": "Turtles and You",
    "publicPath": "/destinations/hawaii/honolulu/tours/turtles-and-you-368817",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Snorkel off Waikīkī on a two-hour boat excursion focused on Oʻahu's reef environment and the possibility of seeing Hawaiian green sea turtles. The journey offers views of the coastline from the water before guests enter the ocean at a snorkeling site.",
      "The operator describes snorkeling above a patch reef, with scenic views back toward Waikīkī. Sea turtles are protected wildlife; sightings depend on conditions, and swimmers should keep a respectful distance without touching or pursuing animals. Even without an encounter, the reef setting offers a chance to appreciate the island's marine habitat.",
      "Complimentary soft drinks are listed in the operator's highlights. Confirm equipment, swimming requirements and current ocean conditions before departure. The precise snorkeling location can vary, and safe participation depends on the crew's instructions."
],
    "schemaDescription": "Guests snorkel from the boat over a patch reef. The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see.",
    "highlights": [
      "two-hour guided outing in Honolulu",
      "Scenic views of Waikiki coast",
      "Complimentary soft drinks"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/jIL1hFgT4qfMBgGu57UR"
    ],
    "productImage": "https://cdn.filestackcontent.com/6FcyxAhyRQqxAx6BjZwn",
    "wordCount": 125,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "1125 Ala Moana Blvd Honolulu, HI 96814",
    "visiblePriceLabel": "From $125",
    "priceRows": [
      {
        "label": "Adult",
        "note": "",
        "amountLabel": "$125"
      },
      {
        "label": "Child",
        "note": "2 -11 years",
        "amountLabel": "$99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "125.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 1809,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 1809 reviews on GET https://fareharbor.com/api/v1/companies/andyoucreations/items/368817/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "547932",
    "company": "bikehawaii",
    "title": "E-Bike Tour – Honolulu Rainforest Ride",
    "publicPath": "/destinations/hawaii/honolulu/tours/e-bike-tour-honolulu-rainforest-ride-547932",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a three-hour bicycle outing with Bike Hawaii. The rental is a pedal-assist electric bike.",
      "Groups are capped at 4. Guests must be at least 14 years old."
    ],
    "schemaDescription": "This is a three-hour bicycle outing with Bike Hawaii.",
    "highlights": [
      "three-hour bicycle outing",
      "Groups are capped at 4"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/MuBGzRwdQuOXjGw90hiQ"
    ],
    "productImage": "https://cdn.filestackcontent.com/5AaBMHHhStfHCNQGta4i",
    "wordCount": 31,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "We will pick you up in Waikiki in our air-conditioned shuttle",
    "visiblePriceLabel": "From $140",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 14+",
        "amountLabel": "$140"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "140.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 318,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.7 from 318 reviews on GET https://fareharbor.com/api/v1/companies/bikehawaii/items/547932/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "547939",
    "company": "bikehawaii",
    "title": "Hawaii Volcanic Rainforest Hike",
    "publicPath": "/destinations/hawaii/honolulu/tours/hawaii-volcanic-rainforest-hike-547939",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests walk a mountain trail for this outing. Guests stay on foot for the outing, and the mountain is the destination. The views are from the trail itself. The route also reaches Pearl Harbor and Pacific Ocean."
    ],
    "schemaDescription": "Guests walk a mountain trail for this outing.",
    "highlights": [
      "three-hour guided outing",
      "Groups are capped at 42"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/QhcfQfL9QuCyVuiAlq77"
    ],
    "productImage": "https://cdn.filestackcontent.com/LVnE4XMfTHKYIILh7VjM",
    "wordCount": 37,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "We will pick you up in Waikiki in our air-conditioned shuttle",
    "visiblePriceLabel": "From $90",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 14+",
        "amountLabel": "$90"
      },
      {
        "label": "Child",
        "note": "Ages 13 and under",
        "amountLabel": "$65"
      },
      {
        "label": "Make it Private",
        "note": "Up to 6 people - if more than 6, please add from above up to 14",
        "amountLabel": "$540"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "90.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 318,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.7 from 318 reviews on GET https://fareharbor.com/api/v1/companies/bikehawaii/items/547939/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "20498",
    "company": "biketourhawaii",
    "title": "Diamond Head Bike to Hike",
    "publicPath": "/destinations/hawaii/honolulu/tours/diamond-head-bike-to-hike-20498",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Explore Honolulu's Diamond Head neighborhood by bicycle on a guided outing lasting approximately three to four hours. The route links coastal streets and public landmarks around Waikīkī with views toward the famous volcanic crater known locally as Lēʻahi.",
      "The operator's listed sights include Kapiʻolani Park, the Duke Kahanamoku area, the World War I Natatorium Memorial and the exterior surroundings of Doris Duke's Shangri La. Black Point and the Diamond Head crater landscape also feature in the route. Some locations have appeared in film or television productions, adding another layer to the neighborhood's story.",
      "Bike rental and equipment are listed as part of the experience. The source description mixes cycling with hiking language, so confirm the current riding route and whether any actual crater hike or admission is included before booking."
],
    "schemaDescription": "A 3- to 4-hour bicycle outing with Bike Tour Hawaii. The outing passes WW1 Natatorium Memorial, Doris Duke's Shangri-La, and Hawaii FIVE-O.",
    "highlights": [
      "3- to 4-hour bicycle outing",
      "WW1 Natatorium Memorial and Doris Duke's Shangri-La",
      "Bike rental + equipment"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/y8ASo4gITNO2LB17j2ow"
    ],
    "productImage": "https://www.filepicker.io/api/file/NbBdP1xeS4W5IIMNA0u5",
    "wordCount": 130,
    "durationLabel": "3-4 Hours",
    "durationIso": null,
    "meetingLocation": "Meet at the Kuhio Beach Banyan Tree, Waikiki Beach",
    "visiblePriceLabel": "From $169",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18-60",
        "amountLabel": "$169"
      },
      {
        "label": "Child",
        "note": "Ages 12-17",
        "amountLabel": "$139"
      },
      {
        "label": "Senior",
        "note": "Ages 61 and up",
        "amountLabel": "$159"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "169.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/biketourhawaii/items/20498/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "20506",
    "company": "biketourhawaii",
    "title": "Hawaiian Foodie Bike Tour",
    "publicPath": "/destinations/hawaii/honolulu/tours/hawaiian-foodie-bike-tour-20506",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "See Waikīkī from a bicycle on a four-hour Hawaiian food-themed outing that combines neighborhood sightseeing with an introduction to local flavors. Riding through Honolulu makes it possible to connect the beach, parks and food stops at a relaxed street-level pace.",
      "The route described by the operator includes Kapiʻolani Park, Waikīkī Beach and the Kūhiō Beach Banyan Tree, alongside its Taste Hawaii food component. The park sits below Diamond Head, while the beachfront provides a lively contrast of surf culture, historic public spaces and busy visitor streets.",
      "Bike rental and equipment are listed in the operator's highlights. Food stops and tastings can change, so confirm exactly what is included in the ticket and any dietary needs in advance. The meeting details identify Bike Tour Hawaii in Honolulu."
],
    "schemaDescription": "A four-hour bicycle outing with Bike Tour Hawaii in Honolulu. The outing passes Kapiolani Park.",
    "highlights": [
      "four-hour bicycle outing in Honolulu",
      "Kapiolani Park",
      "Bike rental + equipment"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/Q8dJ5ddqRh2e3FWVKfYv"
    ],
    "productImage": "https://cdn.filestackcontent.com/6MLKVoXvQXumgvhBYvk2",
    "wordCount": 126,
    "durationLabel": "4 Hours",
    "durationIso": "PT4H",
    "meetingLocation": "Bike Tour Hawaii • 2421 Ala Wai Blvd 1402 Honolulu, HI 96815",
    "visiblePriceLabel": "From $189",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18-60",
        "amountLabel": "$189"
      },
      {
        "label": "Child",
        "note": "Ages 12-17",
        "amountLabel": "$169"
      },
      {
        "label": "Kama'aina",
        "note": "",
        "amountLabel": "$169"
      },
      {
        "label": "Military Member",
        "note": "Must show military ID",
        "amountLabel": "$169"
      },
      {
        "label": "Senior",
        "note": "Ages 61 and up",
        "amountLabel": "$179"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "189.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/biketourhawaii/items/20506/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "395815",
    "company": "biketourhawaii",
    "title": "Open House Real Estate Bike Tour",
    "publicPath": "/destinations/hawaii/honolulu/tours/open-house-real-estate-bike-tour-395815",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a 4.5-hour bicycle outing with Bike Tour Hawaii. Local Meal, Cold Water, Snacks, and Sunscreen are included.",
      "Groups are capped at 6.",
      "Guests must be at least 12 years old. A full refund is available with at least 24 hours' notice."
    ],
    "schemaDescription": "A 4.5-hour bicycle outing with Bike Tour Hawaii.",
    "highlights": [
      "4.5-hour bicycle outing",
      "Local Meal"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/juhRW3dxROGgZjiwEW1Q"
    ],
    "productImage": "https://cdn.filestackcontent.com/23D1v516TeOEf0RwM5jY",
    "wordCount": 45,
    "durationLabel": "4.5 Hours",
    "durationIso": "PT4H30M",
    "meetingLocation": "Waikiki's Kuhio Beach Hula Mound",
    "visiblePriceLabel": "From $169",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 18-60",
        "amountLabel": "$169"
      },
      {
        "label": "Child",
        "note": "Ages 12-17",
        "amountLabel": "$139"
      },
      {
        "label": "Senior",
        "note": "Ages 61 and up",
        "amountLabel": "$149"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "169.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/biketourhawaii/items/395815/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "58782",
    "company": "biketourhawaii",
    "title": "Manoa Falls Electric Bike to Hike",
    "publicPath": "/destinations/hawaii/honolulu/tours/manoa-falls-electric-bike-to-hike-58782",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Combine an electric-bike outing with the green landscape of Mānoa Valley on a four-and-a-half-hour excursion from Honolulu. The route heads away from the beachfront toward the wetter mountain foothills associated with Mānoa Falls.",
      "The valley is known for lush vegetation and a dramatically different atmosphere from the sunlit Waikīkī coast. The operator's source references Mānoa Falls and the valley, along with film-location themes associated with tropical scenery. An electric bicycle provides assistance on the riding portions of the outing.",
      "Bike rental and equipment are listed among the highlights, with a meeting point near the Kūhiō Beach Banyan Tree. Confirm the current route, the length and difficulty of any walking segment, and whether access to the waterfall trail is included. Trail conditions can change after rain."
],
    "schemaDescription": "A 4.5-hour bicycle outing with Bike Tour Hawaii in Honolulu.",
    "highlights": [
      "4.5-hour bicycle outing in Honolulu",
      "Bike rental + equipment"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/MIYLsbzFQbmltlYopW5J"
    ],
    "productImage": "https://cdn.filestackcontent.com/dJAD16J0RfOqpF8cnJhh",
    "wordCount": 125,
    "durationLabel": "4.5 Hours",
    "durationIso": "PT4H30M",
    "meetingLocation": "Kuhio Beach Banyan Tree • 2453 Kalakaua Ave Honolulu, HI 96815",
    "visiblePriceLabel": "From $179",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 15-64",
        "amountLabel": "$179"
      },
      {
        "label": "Senior",
        "note": "Ages 65 and up",
        "amountLabel": "$169"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "179.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/biketourhawaii/items/58782/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "663537",
    "company": "divealohascuba",
    "title": "Divemaster",
    "publicPath": "/destinations/hawaii/honolulu/tours/divemaster-663537",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Divemaster is a guided outing lasting 1-6 Weeks with Aloha Scuba Diving Co. The outing starts at Ocean training days. The route then visits Workshops and Skill-circuit video review.",
      "Later stops include Workshop, Map & EAP finalize, and Knowledge reviews & final exams. Groups are capped at 4.",
      "Guests must be at least 18 years old. A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "A guided outing lasting 1-6 Weeks with Aloha Scuba Diving Co. The outing passes Ocean training days, Workshops, and Skill-circuit video review.",
    "highlights": [
      "1-6 Weeks guided outing",
      "Ocean training days and Workshops",
      "Groups are capped at 4"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/zcHg8mmET1GuRwO90hyS"
    ],
    "productImage": "https://cdn.filestackcontent.com/yZhWAnlmTmqPbEsCAjz2",
    "wordCount": 67,
    "durationLabel": "1-6 Weeks",
    "durationIso": null,
    "meetingLocation": "410 Atkinson Dr. Honolulu, Hawai'i",
    "visiblePriceLabel": "From $1,999",
    "priceRows": [
      {
        "label": "Divemaster",
        "note": "",
        "amountLabel": "$1,999"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1999.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.7,
      "reviewCount": 271,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.7 from 271 reviews on GET https://fareharbor.com/api/v1/companies/divealohascuba/items/663537/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "3108",
    "company": "diveoahu",
    "title": "Night Dives",
    "publicPath": "/destinations/hawaii/honolulu/tours/night-dives-3108",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Night Dives is a 3- to 4-hour guided outing with Dive Oahu. PADI Professional Guide, All premium gear, and Dive light (if needed) are included. The outing reaches Twilight dive at a local dive spot."
    ],
    "schemaDescription": "Night Dives is a 3- to 4-hour guided outing with Dive Oahu.",
    "highlights": [
      "3- to 4-hour guided outing",
      "Twilight dive at a local dive spot",
      "PADI Professional Guide"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/ZoxBh2eBS9WUqP4GBIsR"
    ],
    "productImage": "https://cdn.filestackcontent.com/LnAYJniuRkq7i5aQsKKu",
    "wordCount": 36,
    "durationLabel": "3-4 Hours",
    "durationIso": null,
    "meetingLocation": "Honolulu Harbor",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Certified Diver",
        "note": "Ages 15+",
        "amountLabel": "$231"
      },
      {
        "label": "Rider",
        "note": "Ages 16+",
        "amountLabel": "$99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 2385,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.8 from 2385 reviews on GET https://fareharbor.com/api/v1/companies/diveoahu/items/3108/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "8984",
    "company": "diveoahu",
    "title": "Shallow Reefs Tour",
    "publicPath": "/destinations/hawaii/honolulu/tours/shallow-reefs-tour-8984",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Shallow Reefs Tour is a 3- to 4-hour snorkel outing with Dive Oahu.",
      "In-Water Guide, All premium gear, and Light snack with refreshments are included."
    ],
    "schemaDescription": "Shallow Reefs Tour is a 3- to 4-hour snorkel outing with Dive Oahu.",
    "highlights": [
      "3- to 4-hour snorkel outing",
      "In-Water Guide"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/sk7XcA2QSq2S5gKBp5Ut"
    ],
    "productImage": "https://cdn.filestackcontent.com/vzudqlKpQOyuuV8myDDX",
    "wordCount": 27,
    "durationLabel": "3-4 Hours",
    "durationIso": null,
    "meetingLocation": "Honolulu Harbor",
    "visiblePriceLabel": "From $79",
    "priceRows": [
      {
        "label": "Certified Diver",
        "note": "Ages 15+",
        "amountLabel": "$231"
      },
      {
        "label": "Discovery Scuba Diver/Intro Diver",
        "note": "Ages 10+",
        "amountLabel": "$251"
      },
      {
        "label": "Snorkeler",
        "note": "Ages 13+",
        "amountLabel": "$131"
      },
      {
        "label": "Rider",
        "note": "Ages 16+",
        "amountLabel": "$99"
      },
      {
        "label": "Snorkeler, (Child)",
        "note": "8-12 years old. Must swim and be accompanied by an adult at all times",
        "amountLabel": "$101"
      },
      {
        "label": "Rider Youth",
        "note": "8-12 years old. Must be accompanied by an adult at all times",
        "amountLabel": "$79"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "79.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 2385,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.8 from 2385 reviews on GET https://fareharbor.com/api/v1/companies/diveoahu/items/8984/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "9120",
    "company": "diveoahu",
    "title": "Wreck & Reef Tour",
    "publicPath": "/destinations/hawaii/honolulu/tours/wreck-and-reef-tour-9120",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Wreck & Reef Tour is a 3- to 4-hour guided outing with Dive Oahu. In-Water Guide, All premium gear, and Light snack with refreshments are included. The outing reaches Dive 2.",
      "Guests must be at least 8 years old."
    ],
    "schemaDescription": "A 3- to 4-hour guided outing with Dive Oahu. The outing passes Dive 2.",
    "highlights": [
      "3- to 4-hour guided outing",
      "Dive 2",
      "In-Water Guide"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/M0pObavRV20Kcf9aqS2f"
    ],
    "productImage": "https://cdn.filestackcontent.com/QGb2pjpCT6CeIKoFIGZO",
    "wordCount": 40,
    "durationLabel": "3-4 Hours",
    "durationIso": null,
    "meetingLocation": "Honolulu Harbor",
    "visiblePriceLabel": "From $99",
    "priceRows": [
      {
        "label": "Certified Diver",
        "note": "Ages 15+",
        "amountLabel": "$231"
      },
      {
        "label": "Rider",
        "note": "Ages 16+",
        "amountLabel": "$99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "99.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 2385,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.8 from 2385 reviews on GET https://fareharbor.com/api/v1/companies/diveoahu/items/9120/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "42966",
    "company": "enoatours",
    "title": "Pearl Harbor City - from Waikiki",
    "publicPath": "/destinations/hawaii/honolulu/tours/pearl-harbor-city---from-waikiki-42966",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The commentary takes up Pearl Harbor Visitor Center and King Kamehameha Statue. That same account stays with Iolani Palace and Downtown Honolulu."
    ],
    "schemaDescription": "The commentary takes up Pearl Harbor Visitor Center and King Kamehameha Statue.",
    "highlights": [
      "5-hour guided outing",
      "Pearl Harbor Visitor Center and USS Arizona Memorial"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/DEJhgBw9QPKeP0DnZRdi"
    ],
    "productImage": "https://cdn.filestackcontent.com/Hty9kxAhQsGJfObtftZy",
    "wordCount": 22,
    "durationLabel": "5 Hours",
    "durationIso": "PT5H",
    "meetingLocation": "Pick-up from Waikiki",
    "visiblePriceLabel": "From $69",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+",
        "amountLabel": "$69"
      },
      {
        "label": "Child",
        "note": "Ages 3 - 11",
        "amountLabel": "$39"
      },
      {
        "label": "Lap Child",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "69.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 38886,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.9 from 38886 reviews on GET https://fareharbor.com/api/v1/companies/enoatours/items/42966/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "9620",
    "company": "enoatours",
    "title": "Pearl Harbor Remembered A - from Waikiki",
    "publicPath": "/destinations/hawaii/honolulu/tours/pearl-harbor-remembered-a---from-waikiki-9620",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Visit the historic sites of Pearl Harbor on a seven-hour guided excursion with pickup from Waikīkī. The day centers on the events of December 7, 1941, and the memorials that preserve the stories of those who served and died.",
      "The operator lists the Pearl Harbor Visitor Center, the USS Arizona Memorial and a tour of the Battleship Missouri, alongside travel through downtown Honolulu. The Arizona Memorial marks the resting place of sailors and Marines killed aboard the ship, while the Missouri is associated with Japan's formal surrender in 1945.",
      "Admission to the visitor center, USS Arizona Memorial entry and the Missouri tour are described as included. Memorial access and transport arrangements can be affected by operational conditions, so confirm the current itinerary and security restrictions before departure."
],
    "schemaDescription": "A 7-hour guided outing with E Noa Corporation. The outing passes Pearl Harbor Visitor Center, USS Arizona Memorial, and Downtown Honolulu.",
    "highlights": [
      "7-hour guided outing",
      "Pearl Harbor Visitor Center and USS Arizona Memorial"
    ],
    "galleryImages": [
      "https://www.filepicker.io/api/file/XhoaKFZ9TTS0UnyWQsUY"
    ],
    "productImage": "https://www.filepicker.io/api/file/pe89KdazQrOg7flieMPJ",
    "wordCount": 127,
    "durationLabel": "7 Hours",
    "durationIso": "PT7H",
    "meetingLocation": "Pick-up from Waikiki",
    "visiblePriceLabel": "From $143",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+",
        "amountLabel": "$143"
      },
      {
        "label": "Child",
        "note": "Ages 3 - 11",
        "amountLabel": "$115"
      },
      {
        "label": "Lap Child",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "143.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 38886,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.9 from 38886 reviews on GET https://fareharbor.com/api/v1/companies/enoatours/items/9620/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "476798",
    "company": "gohawaii-watersports",
    "title": "Parasailing",
    "publicPath": "/destinations/hawaii/honolulu/tours/parasailing-476798",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Parasailing is a 4- to 10-minute harbor outing with Go Hawaii Watersports on Honolulu Harbor. Parasailing equipment and harness and Life vests are included.",
      "Guests must be at least 6 years old. A full refund is available with at least 24 hours' notice."
    ],
    "schemaDescription": "A 4- to 10-minute harbor outing with Go Hawaii Watersports on Honolulu Harbor.",
    "highlights": [
      "4- to 10-minute harbor outing in Honolulu",
      "Parasailing equipment and harness"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/SXOUPA1HT5KuUuXkweWk"
    ],
    "productImage": "https://cdn.filestackcontent.com/3gm6nhiTDCOuIWifrwGz",
    "wordCount": 44,
    "durationLabel": "4-10 minutes",
    "durationIso": null,
    "meetingLocation": "1025 Ala Moana Blvd, (Slip F6) Honolulu, HI 96814",
    "visiblePriceLabel": "From $45",
    "priceRows": [
      {
        "label": "Parasailing Experience (600ft)",
        "note": "5 years or older",
        "amountLabel": "$80"
      },
      {
        "label": "Standard Ride (800ft)",
        "note": "5 years or older",
        "amountLabel": "$90"
      },
      {
        "label": "Ultimate Ride (1000ft)",
        "note": "5 years or older",
        "amountLabel": "$115"
      },
      {
        "label": "Observer",
        "note": "Adults or Supervised Children from 2 years and up",
        "amountLabel": "$45"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "45.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 879,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.8 from 879 reviews on GET https://fareharbor.com/api/v1/companies/gohawaii-watersports/items/476798/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "991",
    "company": "hhsurf",
    "title": "Surf Lessons",
    "publicPath": "/destinations/hawaii/honolulu/tours/surf-lessons-991",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. A surfboard is provided for the time in the water. The booking is private, so the instructor works with that party alone.",
      "The lesson is aimed at first-time and beginner surfers. People are in the water on surfboards for the lesson. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "A two-hour guided outing with Hans Hedemann South Shore (Queen Kapiolani) in Honolulu.",
    "highlights": [
      "two-hour guided outing in Honolulu",
      "Rashguard, reef shoes, and surfboard rental"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/2MvjxwSRS6aOK5QbYMzb"
    ],
    "productImage": "https://cdn.filestackcontent.com/0OHV1XRSzi5sgVmBOdJg",
    "wordCount": 89,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": "Hans Hedemann Surf Waikiki,150 Kapahulu Avenue Honolulu, HI 96815",
    "visiblePriceLabel": "From $100",
    "priceRows": [
      {
        "label": "Group Lesson",
        "note": "Participant must be ages 14 & older and must be able to swim. If children age 13 and below, must book private lesson.",
        "amountLabel": "$100"
      },
      {
        "label": "Semi Private Lesson",
        "note": "Must be booked for 2 or more, ideal for pairs, friends, or family learning together, and must be age 14 & older to participate.",
        "amountLabel": "$140"
      },
      {
        "label": "Private Lesson",
        "note": "Private surf lessons are available for individuals aged 5 and up, with one-on-one instruction provided by a dedicated surf coach",
        "amountLabel": "$175"
      },
      {
        "label": "Surf with a Pro",
        "note": "Experience the thrill of surfing with a pro-catch waves alongside pro surfer Hans Hedemann or one of our pro surfers",
        "amountLabel": "$400"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "100.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 1816,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.9 from 1816 reviews on GET https://fareharbor.com/api/v1/companies/hhsurf/items/991/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "284519",
    "company": "livingoceanscuba",
    "title": "Turtle Canyons Snorkel Excursion",
    "publicPath": "/destinations/hawaii/honolulu/tours/turtle-canyons-snorkel-excursion-284519",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests snorkel from the boat over a patch reef. The stop is over coral, with tropical fish in the same water. Floats are aboard for the break between time in the water. The landmarks are seen from the harbor, with the boat doing the traveling.",
      "The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A two-hour snorkel outing with Living Ocean Tours in Honolulu.",
    "highlights": [
      "two-hour snorkel outing in Honolulu",
      "High Quality Snorkeling Equipment"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/kpRWprfrQgWqcrfencSY"
    ],
    "productImage": "https://cdn.filestackcontent.com/I0sGDrfjQKmfZKhduuxP",
    "wordCount": 85,
    "durationLabel": "2 Hour",
    "durationIso": "PT2H",
    "meetingLocation": "1125 Ala Moana Blvd Slip B1 Honolulu, HI 96814",
    "visiblePriceLabel": "From $89",
    "priceRows": [
      {
        "label": "Person Age 3+: Refundable • Up To 48 Hours Before Trip",
        "note": "Free Cancellation up to 48 hours Before the Start of the Trip • Ages 3+",
        "amountLabel": "$99"
      },
      {
        "label": "Person Ages 3+: Non-Refundable • All Sales are Final",
        "note": "Ages 3+ • This Rate is NON-REFUNDABLE • All Sales are Final",
        "amountLabel": "$89"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "89.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 8891,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 8891 reviews on GET https://fareharbor.com/api/v1/companies/livingoceanscuba/items/284519/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "323935",
    "company": "livingoceanscuba",
    "title": "Waikiki Sunset Cruise BYOB",
    "publicPath": "/destinations/hawaii/honolulu/tours/waikiki-sunset-cruise-byob-323935",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "From the water, guests see Kewalo Basin and Waikiki Coast. The cruise also passes Diamond Head. The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by.",
      "The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A one-hour harbor outing with Living Ocean Tours on Honolulu Harbor.",
    "highlights": [
      "one-hour harbor outing in Honolulu"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/nZ3T8JidRoGmSCFX56y6"
    ],
    "productImage": "https://cdn.filestackcontent.com/AxyZS9ASP2dRkSjqPiQl",
    "wordCount": 69,
    "durationLabel": "1 Hour",
    "durationIso": "PT1H",
    "meetingLocation": "1125 Ala Moana Blvd Slip B1 Honolulu, HI 96814",
    "visiblePriceLabel": "From $59",
    "priceRows": [
      {
        "label": "Person Age 3+: Refundable • Up To 48 Hours Before Trip",
        "note": "Free Cancellation up to 48 hours Before the Start of the Trip • Ages 3+",
        "amountLabel": "$69"
      },
      {
        "label": "Person Ages 3+: Non-Refundable • All Sales are Final",
        "note": "Ages 3+ • This Rate is NON-REFUNDABLE • All Sales are Final",
        "amountLabel": "$59"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "59.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 8891,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 8891 reviews on GET https://fareharbor.com/api/v1/companies/livingoceanscuba/items/323935/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "494462",
    "company": "livingoceanscuba",
    "title": "Deluxe Snorkel and Wildlife Cruise",
    "publicPath": "/destinations/hawaii/honolulu/tours/deluxe-snorkel-and-wildlife-cruise-494462",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests snorkel from the boat over a patch reef. The stop is over coral, with tropical fish in the same water. A bar on the boat sells drinks while the cruise is underway. From the water, guests see Diamond Head and Rainbow Reef. The cruise also passes Ocean Playground.",
      "The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A 2.5-hour snorkel outing with Living Ocean Tours in Honolulu.",
    "highlights": [
      "2.5-hour snorkel outing in Honolulu"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/Su0IdBHYSWCoXRxoBmSy"
    ],
    "productImage": "https://cdn.filestackcontent.com/Pbf5qvLTQXWn0DN5PWGT",
    "wordCount": 102,
    "durationLabel": "2.5 Hour",
    "durationIso": "PT2H30M",
    "meetingLocation": "1125 Ala Moana Blvd Slip B1 Honolulu, HI 96814",
    "visiblePriceLabel": "From $89",
    "priceRows": [
      {
        "label": "Person Age 3+: Refundable • Up To 48 Hours Before Trip",
        "note": "Free Cancellation up to 48 hours Before the Start of the Trip • Ages 3+",
        "amountLabel": "$99"
      },
      {
        "label": "Person Ages 3+: Non-Refundable • All Sales are Final",
        "note": "Ages 3+ • This Rate is NON-REFUNDABLE • All Sales are Final",
        "amountLabel": "$89"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "89.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 8891,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 8891 reviews on GET https://fareharbor.com/api/v1/companies/livingoceanscuba/items/494462/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "7571",
    "company": "ohanasurfproject",
    "title": "Surf Lessons!",
    "publicPath": "/destinations/hawaii/honolulu/tours/surf-lessons-7571",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "All surfers share a common sensation that can't be explained in words. The mission is to help guests meet that sensation and to reach next level of performance. The goal is to enhance the total surfing meet through smart instruction in a personal environment. The surfing lessons in Waikiki are also customized to fit any meet level and learning style.",
      "Guests hear how to connect with ocean environment, understand line up and actions of surfers around guests, and surf to express the personality. The lessons are customized to the skill level. All prices cover a surfboard and all the equipment guests need to get out and riding waves.",
      "All guests have to bring is the swimwear, towel, sunscreen and change of clothes. Transportation to and from designated meeting spots in Waikiki."
    ],
    "schemaDescription": "A two-hour guided outing with Ohana Surf Project in Honolulu.",
    "highlights": [
      "two-hour guided outing in Honolulu",
      "Surfboard"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/pk6fpMWmSBmrRcmcw6y3"
    ],
    "productImage": "https://cdn.filestackcontent.com/fsH5S7yyTKeYMH7MPCxq",
    "wordCount": 131,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "The Ohana Surf Center, in the Waikiki Beach Marriott Hotel. 2552 Kalākaua Ave p159/p160, Honolulu, HI 96815",
    "visiblePriceLabel": "From $120",
    "priceRows": [
      {
        "label": "Private Lesson (2HR)",
        "note": "All ages & abilities (1 on 1 instruction, tandem lessons available)",
        "amountLabel": "$205"
      },
      {
        "label": "Open Group Lesson (2HR)",
        "note": "Ages 13+ with the ability to swim may join our Open Group lesson (shared experience with other NOVICE students)",
        "amountLabel": "$120"
      },
      {
        "label": "Semi-Private Lesson (2HR)",
        "note": "Price is per person and requires 2 students over the age of 13 with their own instructor",
        "amountLabel": "$160"
      },
      {
        "label": "Exclusive Group (2HR)",
        "note": "Price is per person for 3 or more students over the age of 13 who can swim with their own instructor.",
        "amountLabel": "$150"
      },
      {
        "label": "Family Lesson (2HR)",
        "note": "Price is per person (not per pair). Select total participants. Min: 1 parent & 1 child (12 & under). All must be able to swim.",
        "amountLabel": "$145"
      },
      {
        "label": "Private Professional Coaching Level 3 (2HR)",
        "note": "Private Lesson with our Experienced Senior Instructors",
        "amountLabel": "$300"
      },
      {
        "label": "Semi-Private Professional Coaching Level 3 (2HR)",
        "note": "Price is per person. Two students to one instructor. Lesson with a highly experienced senior instructor.",
        "amountLabel": "$200"
      },
      {
        "label": "Private Professional Coaching Level 4 (2.5 Hours)",
        "note": "Private Lesson with a Pro Surfer, Includes Video Analysis",
        "amountLabel": "$450"
      },
      {
        "label": "Semi-Private Professional Coaching Level 4 (2.5HR)",
        "note": "Price is per person. Two students to one instructor. Lesson with a Pro Surfer, Includes Video Analysis.",
        "amountLabel": "$290"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "120.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/ohanasurfproject/items/7571/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "110203",
    "company": "pinksailswaikiki",
    "title": "Turtle Snorkeling Adventure + Guaranteed Sightings",
    "publicPath": "/destinations/hawaii/honolulu/tours/turtle-snorkeling-adventure-guaranteed-sightings-110203",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests sail on a catamaran for this cruise. From the water, guests see Turtle Canyon and Waikiki Beach. The cruise also passes Pacific Ocean. The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint.",
      "People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A two-hour snorkel outing with Pink Sails Waikiki in Honolulu. The outing passes Return to the harbor.",
    "highlights": [
      "two-hour snorkel outing in Honolulu",
      "Return to the harbor",
      "Snorkel gear"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/12QHdJOjT06FNtWV8XkU"
    ],
    "productImage": "https://cdn.filestackcontent.com/2lMPMvH1QyyZpu1HxjeR",
    "wordCount": 77,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "1 Holomoana St Honolulu, HI 96815",
    "visiblePriceLabel": "From $79",
    "priceRows": [
      {
        "label": "Guest",
        "note": "4 years and older",
        "amountLabel": "$79"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "79.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 5559,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.8 from 5559 reviews on GET https://fareharbor.com/api/v1/companies/pinksailswaikiki/items/110203/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "80660",
    "company": "pinksailswaikiki",
    "title": "Sunset Splash Adventure",
    "publicPath": "/destinations/hawaii/honolulu/tours/sunset-splash-adventure-80660",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests sail at sunset aboard a 55-foot sailboat. The water is usually calmer once the afternoon wind drops. Guests sail on a catamaran for this cruise. From the water, guests see Waikiki Coastline and Pacific Ocean. The landmarks are seen from the harbor, with the boat doing the traveling.",
      "The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A two-hour guided outing with Pink Sails Waikiki in Honolulu. The outing passes Sunset views.",
    "highlights": [
      "two-hour guided outing in Honolulu",
      "Sunset views",
      "Scenic sunset sail"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/BKnnnjiOSVCrQVuhMlKS"
    ],
    "productImage": "https://cdn.filestackcontent.com/WaPrmA5bQ6fmobBauFww",
    "wordCount": 90,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "1 Holomoana St Honolulu, HI 96815",
    "visiblePriceLabel": "From $56",
    "priceRows": [
      {
        "label": "Guest",
        "note": "4 years and older",
        "amountLabel": "$56"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "56.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 5559,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.8 from 5559 reviews on GET https://fareharbor.com/api/v1/companies/pinksailswaikiki/items/80660/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "280763",
    "company": "polyad-activities",
    "title": "Oahu Grand Circle Island Tour – Waimea Valley & Dole Plantation (7B)",
    "publicPath": "/destinations/hawaii/honolulu/tours/oahu-grand-circle-island-tour-waimea-valley-and-dole-plantation-7b-280763",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "The commentary takes up Diamond Head and Makapu'u Beaches. That same account stays with Halona Blowhole and Nu'uanu Pali Lookout. Byodo-In Japanese Temple and Waimea Bay Beaches are part of the same story. The route keeps Haleiwa Town and Kahala's Gold Coast Sandy in view."
    ],
    "schemaDescription": "The commentary takes up Diamond Head and Makapu'u Beaches. That same account stays with Halona Blowhole and Nu'uanu Pali Lookout. Byodo-In Japanese Temple and Waimea Bay Beaches are part of the same story. The route keeps Haleiwa Town and Kahala's Gold Coast Sandy in view.",
    "highlights": [
      "10-hour guided outing",
      "Diamond Head and Kahala's Gold Coast and Sandy's and Makapu'u Beaches",
      "Hotel pickup and drop-off"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/XoK0IogHTkKj2t7wdQ2m"
    ],
    "productImage": "https://cdn.filestackcontent.com/Uh021S5QiqfjT6eO6rXC",
    "wordCount": 46,
    "durationLabel": "10 Hours",
    "durationIso": "PT10H",
    "meetingLocation": "Oahu | Hotel Pickups From Select Waikiki Locations",
    "visiblePriceLabel": "From $139",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 12+ (12-17 must bk w/ 18+)",
        "amountLabel": "$139"
      },
      {
        "label": "Child 3-11 yrs",
        "note": "Must book Adult ticket first",
        "amountLabel": "$106"
      },
      {
        "label": "Infant 2 yrs and under",
        "note": "",
        "amountLabel": "Free"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "139.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/polyad-activities/items/280763/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "68062",
    "company": "waikikibeachservices",
    "title": "One-on-One Individual Surf Lesson",
    "publicPath": "/destinations/hawaii/honolulu/tours/one-on-one-individual-surf-lesson-68062",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. A surfboard is provided for the time in the water. A rash guard, fins, a leash, and reef shoes are also set out with the gear.",
      "A private booking keeps one instructor with one guest. The lesson is aimed at first-time and beginner surfers. People are in the water on surfboards for the lesson. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. A surfboard is provided for the time in the water. A rash guard, fins, a leash, and reef shoes are also set out with the gear.",
    "highlights": [
      "one-hour guided outing in Honolulu",
      "Surfboard"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/78Jbux2JT3OAgyqJ1Kxx"
    ],
    "productImage": "https://cdn.filestackcontent.com/dY7px8gVRjGYfeV1ZSuq",
    "wordCount": 102,
    "durationLabel": "1 Hour",
    "durationIso": "PT1H",
    "meetingLocation": "Royal Hawaiian Hotel, 2259 Kalākaua Ave., Honolulu, HI 96815",
    "visiblePriceLabel": "From $150",
    "priceRows": [
      {
        "label": "One-on-One Individual",
        "note": "1 Student per Instructor",
        "amountLabel": "$150"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "150.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/waikikibeachservices/items/68062/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "68064",
    "company": "waikikibeachservices",
    "title": "One-on-One Individual Stand-Up Paddle Lesson",
    "publicPath": "/destinations/hawaii/honolulu/tours/one-on-one-individual-stand-up-paddle-lesson-68064",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a one-hour paddle outing with Waikiki Beach Services in Honolulu. The group includes a stand-up paddle session. Stand-up paddleboard, Rash guard, and 15-minute safety briefing are included. The group passes 15 minutes of safety instruction on the sand. Guests must be at least 13 years old.",
      "A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "A one-hour paddle outing with Waikiki Beach Services in Honolulu. The outing passes 15 minutes of safety instruction on the sand.",
    "highlights": [
      "one-hour paddle outing in Honolulu",
      "15 minutes of safety instruction on the sand",
      "Stand-up paddleboard"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/lBWP4qw2TZSNVPQenPyj"
    ],
    "productImage": "https://cdn.filestackcontent.com/oNCjCkRZSMEi2YciwhsT",
    "wordCount": 63,
    "durationLabel": "1 Hour",
    "durationIso": "PT1H",
    "meetingLocation": "Royal Hawaiian Hotel, 2259 Kalākaua Ave., Honolulu, HI 96815",
    "visiblePriceLabel": "From $150",
    "priceRows": [
      {
        "label": "One-on-One Individual",
        "note": "1 Student per Instructor",
        "amountLabel": "$150"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "150.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/waikikibeachservices/items/68064/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "68066",
    "company": "waikikibeachservices",
    "title": "Beachboy Valet",
    "publicPath": "/destinations/hawaii/honolulu/tours/beachboy-valet-68066",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. A surfboard is provided for the time in the water. A rash guard, fins, a leash, and reef shoes are also set out with the gear.",
      "The lesson is aimed at first-time and beginner surfers. People are in the water on surfboards for the lesson. The instructor stays in the surf with the group for the length of the lesson. The paddle passes Personal Beachboy Valet."
    ],
    "schemaDescription": "A 3.5-hour paddle outing with Waikiki Beach Services in Honolulu.",
    "highlights": [
      "3.5-hour paddle outing in Honolulu",
      "Use of a rash guard"
    ],
    "galleryImages": [],
    "productImage": "https://cdn.filestackcontent.com/fLENO2bvRCiJF6ljtwNf",
    "wordCount": 99,
    "durationLabel": "3.5 Hours",
    "durationIso": "PT3H30M",
    "meetingLocation": "Royal Hawaiian Hotel, 2259 Kalākaua Ave., Honolulu, HI 96815",
    "visiblePriceLabel": "From $450",
    "priceRows": [
      {
        "label": "Beachboy Valet (1 beachboy per person)",
        "note": "",
        "amountLabel": "$450"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "450.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/waikikibeachservices/items/68066/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "94733",
    "company": "waikikibeachservices",
    "title": "Canoe Charter",
    "publicPath": "/destinations/hawaii/honolulu/tours/canoe-charter-94733",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. The booking is private, so the instructor works with that party alone. Family or friends share the lesson and take the same waves together.",
      "People are in the water on surfboards for the lesson. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "A one-hour paddle outing with Waikiki Beach Services in Honolulu.",
    "highlights": [
      "one-hour paddle outing in Honolulu",
      "Canoe and paddles"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/FHJ7PMTbSIqzBbkkuUNC"
    ],
    "productImage": "https://cdn.filestackcontent.com/OEu5Ic5BSRuJ0BbDNDUW",
    "wordCount": 81,
    "durationLabel": "1 Hour",
    "durationIso": "PT1H",
    "meetingLocation": "Royal Hawaiian Hotel, 2259 Kalākaua Ave., Honolulu, HI 96815",
    "visiblePriceLabel": "From $400",
    "priceRows": [
      {
        "label": "One Hour Private Canoe Charter",
        "note": "For up to 6 people",
        "amountLabel": "$400"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "400.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/waikikibeachservices/items/94733/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "314433",
    "company": "wildlifehawaii",
    "title": "Round Trip North Shore Haleiwa Shuttle",
    "publicPath": "/destinations/hawaii/honolulu/tours/round-trip-north-shore-haleiwa-shuttle-314433",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests meet the Best of Oahu's North Shore with the Convenient Shuttle. Escape hustle and bustle of Waikiki and find laid-back charm of and the North Shore alongside Wildlife Hawaii's round-trip shuttle service. Hotel pick up is also available for additional fee. Direct Transportation: Relax and the scenic ride to Town.",
      "Comfortable Share Ride: a friendly and reliable shared transportation experience. After that, round Trip Service: guests provide comfortable and easy transportation back toward Waikiki at the end of the adventure. Guests explore Town, Boat Harbor, and optional stops at Waimea Valley & Sunset Beach. Hotel pickup is also available for an additional fee.",
      "Stops at Town/North Shore Marketplace and Boat Harbor. Optional stops at Waimea Valley and Ted's Bakery (Sunset Beach) for an additional fee."
    ],
    "schemaDescription": "An 8-hour guided outing with Wildlife Hawaii. The outing passes North Shore Shuttle Itinerary, Option 1, and Gyu-Kaku Japanese BBQ on (7.",
    "highlights": [
      "8-hour guided outing",
      "North Shore Haleiwa Shuttle Itinerary and Option 1",
      "Sheraton Princess Kaiulani"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/fbXyq9xuTOK1cONlwtkg"
    ],
    "productImage": "https://cdn.filestackcontent.com/AgzJHWfDToaWDD0dDSG9",
    "wordCount": 128,
    "durationLabel": "8 hours",
    "durationIso": "PT8H",
    "meetingLocation": "Haleiwa",
    "visiblePriceLabel": "From $70",
    "priceRows": [
      {
        "label": "Passenger",
        "note": "Up to 12 Passengers",
        "amountLabel": "$70"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "70.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/wildlifehawaii/items/314433/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "247",
    "company": "xtreme",
    "title": "Parasail",
    "publicPath": "/destinations/hawaii/honolulu/tours/parasail-247",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Parasail is a one-hour harbor outing with X-Treme Parasail & Diamond Head Parasail. Life jackets and Boat ride are included.",
      "Guests must be at least 5 years old. A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "A one-hour harbor outing with X-Treme Parasail & Diamond Head Parasail.",
    "highlights": [
      "one-hour harbor outing",
      "Life jackets"
    ],
    "galleryImages": [
      "https://www.filepicker.io/api/file/LNVhTlAwSQ6CcsESLggj"
    ],
    "productImage": "https://cdn.filestackcontent.com/c5xgjQkGSKoZ72DYQKhN",
    "wordCount": 40,
    "durationLabel": "1 Hour",
    "durationIso": "PT1H",
    "meetingLocation": "1085 Alamoana Blvd Slip F-1, 96815",
    "visiblePriceLabel": "From $50",
    "priceRows": [
      {
        "label": "Xtreme Parasailer",
        "note": "1,000 ft",
        "amountLabel": "$105"
      },
      {
        "label": "Deluxe Parasailer",
        "note": "850 ft,",
        "amountLabel": "$90"
      },
      {
        "label": "Standard Parasailer",
        "note": "700 ft,",
        "amountLabel": "$75"
      },
      {
        "label": "Observer",
        "note": "",
        "amountLabel": "$50"
      },
      {
        "label": "Ultimate Xtreme Parasail",
        "note": "1,200 ft",
        "amountLabel": "$120"
      },
      {
        "label": "Ultimate Xtreme Parasail Private Charter",
        "note": "",
        "amountLabel": "$1,500"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "50.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.9,
      "reviewCount": 8172,
      "provider": "TripAdvisor"
    },
    "ratingProvenance": "TripAdvisor rating 4.9 from 8172 reviews on GET https://fareharbor.com/api/v1/companies/xtreme/items/247/ratings/ fields ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used to infer the score. Google reviews were not substituted. Catalog quality_score and availability_count were not used."
  }
];
