// Generated by scripts/fareharbor-lead-to-gold/build_stage_b_proof.py
// Stored FareHarbor harvest only. Do not edit by hand.
export type FareHarborProofOffer = {
  type: "Offer";
  price: string;
  priceCurrency: string;
  availability: string;
};

export type FareHarborProofProduct = {
  itemId: string;
  company: string;
  title: string;
  publicPath: string;
  engine2Path: string | null;
  exceptionStatus:
    | "OK"
    | "SOURCE_NOT_FOUND"
    | "PRICE_NOT_FOUND"
    | "INSUFFICIENT_SOURCE";
  paragraphs: string[];
  highlights: string[];
  durationLabel: string | null;
  durationIso: string | null;
  visiblePriceLabel: string | null;
  offer: FareHarborProofOffer | null;
  aggregateRating: null;
  ratingProvenance: string;
};

export const fareHarborLeadToGoldProofProducts: FareHarborProofProduct[] = [
  {
    "itemId": "145208",
    "company": "countryboymine",
    "title": "Country Boy Gold Mine Tour",
    "publicPath": "/destinations/colorado/breckenridge/tours/country-boy-gold-mine-tour-145208",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Country Boy Gold Mine Tour is booked with Country Boy Mine. The operator lists the duration as 1 hour. The listed meeting address is 0542 French Gulch Rd Breckenridge, CO US 80424.",
      "Included items listed by the operator: Country Boy Gold Mine Tour.",
      "Additional facts stated by the operator: over 1,000 feet into the mountain, and gold pan in Eureka Creek.",
      "The operator description states: Venture over 1,000 feet into the mountain.",
      "The stored price preview lists Adult (13+) at $59.95 USD on the stored departure starting 2026-09-30T09:00:00. Other listed prices: Child at $39.95. Listed at $0 on that departure: Mine Tour Child (3-years old and under) - FREE."
    ],
    "highlights": [
      "Country Boy Gold Mine Tour"
    ],
    "durationLabel": "1 hour",
    "durationIso": "PT1H",
    "visiblePriceLabel": "Prices starting at $59.95",
    "offer": {
      "type": "Offer",
      "price": "59.95",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "181765",
    "company": "mauisunriders",
    "title": "Haleakala Downhill Self-Guided Bike Tour",
    "publicPath": "/destinations/hawaii/paia/tours/haleakala-downhill-self-guided-bike-tour-181765",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Haleakala Downhill Self-Guided Bike Tour is booked with Maui Sunriders Bike Company. The operator lists the duration as 4-5 hours. The listed meeting address is 71 Baldwin Ave. Suite D3 Paia, HI US 96779.",
      "The operator lists minimum age 15.",
      "Included items listed by the operator: Front-suspension mountain bike with disc brakes, Downhill Bike full-face helmet (or lightweight helmet option), Rain and wind gear, Bike Gloves, Backpack with lock and map, Narrated van tour to the starting point, and Roadside assistance during the ride.",
      "Items listed as not included: Meals and beverages (available for purchase along the route), Personal expenses or shopping, and Tips for guides (optional).",
      "Listed itinerary: Check-In at Paia Shop (8:45 AM), Scenic Van Tour to 6,500 Feet, Begin Self-Guided Bike Ride, Van Shuttle Through Kula (Highway Bypass), For safety, Maui County law requires all bike tours to bypass a short stretch of Kula Highway. Riders will be transported in the van past this section before continuing their ride, and Continue Riding Through Makawao.",
      "Listed restrictions: Minimum age: 15 years - Maximum weight: 280 lbs - Not suitable for beginner riders - Not suitable for pregnant women - Not suitable for individuals with impaired mobility.",
      "Listed items to bring: Light layers (cooler temperatures at higher elevation), Closed-toe shoes, Sunglasses, Sunscreen, and Cash or card for food and shopping.",
      "The stored price preview lists Adult (18+) at $119 USD on the stored departure starting 2026-09-29T08:45:00. Other listed prices: Youth at $119."
    ],
    "highlights": [
      "Front-suspension mountain bike with disc brakes",
      "Downhill Bike full-face helmet (or lightweight helmet option)",
      "Rain and wind gear",
      "Bike Gloves",
      "Backpack with lock and map",
      "Narrated van tour to the starting point"
    ],
    "durationLabel": "4-5 hours",
    "durationIso": null,
    "visiblePriceLabel": "Prices starting at $119",
    "offer": {
      "type": "Offer",
      "price": "119.00",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "322210",
    "company": "untappednewyork",
    "title": "NYC's Underground Subway Tour - Private Tour",
    "publicPath": "/destinations/new-york/new-york/tours/nycs-underground-subway-tour---private-tour-322210",
    "engine2Path": null,
    "exceptionStatus": "PRICE_NOT_FOUND",
    "paragraphs": [
      "NYC's Underground Subway Tour - Private Tour is booked with Untapped New York. The operator lists the duration as 2 hours. The listed meeting address is 200 Broadway New York, NY US 10038.",
      "The operator lists group size Any group size - 12 guests per guide recommended, as many guides as needed.",
      "Included items listed by the operator: Walking tour in English, led by a local New Yorker, and Ear pieces provided to each guests, ensuring everyone hears the guide perfectly, even from a distance.",
      "Items listed as not included: Guests will need one MetroCard swipe, or OMNY tap, to enter the subway.",
      "Listed itinerary: City Hall Park, The Municipal Building, Astor Place, and 14th St. Union Square.",
      "Listed restrictions: This tour is easy and most people can participate.",
      "Listed items to bring: Please bring comfortable shoes.",
      "Cancellation terms listed by the operator: Free cancellation up to 72 hours before the tour starts.",
      "The stored price-preview response did not include a bookable price for this item. No from-price is shown."
    ],
    "highlights": [
      "Walking tour in English, led by a local New Yorker",
      "Ear pieces provided to each guests, ensuring everyone hears the guide perfectly, even from a distance"
    ],
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "visiblePriceLabel": null,
    "offer": null,
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "595701",
    "company": "wilsonfishingguides",
    "title": "Scenic Float Tour",
    "publicPath": "/destinations/wyoming/wilson/tours/scenic-float-tour-595701",
    "engine2Path": null,
    "exceptionStatus": "SOURCE_NOT_FOUND",
    "paragraphs": [
      "Authoritative FareHarbor content and price data were not available for Scenic Float Tour. The stored harvest returned content HTTP 403, structured-description HTTP 404, item HTTP 404, and price-preview HTTP 400. This page does not state a price, review count, duration, meeting point, or inclusions."
    ],
    "highlights": [],
    "durationLabel": null,
    "durationIso": null,
    "visiblePriceLabel": null,
    "offer": null,
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "694384",
    "company": "yellowstoneadvmoto",
    "title": "Self-Guided ADV Motorcycle Rental – KLR 650",
    "publicPath": "/destinations/wyoming/cody/tours/self-guided-adv-motorcycle-rental-klr-650-694384",
    "engine2Path": null,
    "exceptionStatus": "PRICE_NOT_FOUND",
    "paragraphs": [
      "Self-Guided ADV Motorcycle Rental – KLR 650 is booked with Yellowstone Adventure Moto. The operator lists the duration as 1 day. The listed meeting address is 1108 14th Street Cody, WY US 82414.",
      "The operator lists minimum age 25, maximum age 75, group size Maximum 2 riders per motorcycle rental.",
      "Included items listed by the operator: Premium adventure motorcycle rental (Kawasaki KLR 650 / 650S or Yamaha Ténéré 700), Complimentary delivery and pickup within the greater Cody, WY area, Most riding gear included (helmet, jacket, gloves) - limited sizes and quantities available, Riding or hiking boots (ankle-covering footwear required; no street shoes or sneakers), Pre-ride inspection and setup, Local area orientation and riding recommendations, Soft Pannier side bags, and Tools, first aid kit and extra tubes.",
      "Items listed as not included: Optional supplemental insurance: $15 per day (through MBA), and Motorcycle boots: limited sizes and quantities available; guests are strongly encouraged to bring their own ankle-covering riding or hiking boots if proper fit cannot be provided.",
      "Listed itinerary: Pickup & Orientation - Cody, WY, Meet in Cody for motorcycle delivery, paperwork, and a safety briefing. Bike setup, fit check, and local riding overview included, Recommended Loop Selection, Ride independently with flexibility for stops, photos, meals, and fuel. Routes are designed for experienced riders who want freedom without a rigid schedule, Return & Pickup, and Motorcycle pickup at the agreed location in Cody or surrounding area. Post-ride check and wrap-up.",
      "Listed restrictions: This experience is not suitable for beginners or first-time motorcycle riders, Riders must have prior on-road motorcycle experience, Participants must be physically able to safely mount, dismount, balance, and control a mid-to-large displacement adventure motorcycle for extended periods, and Riders must be comfortable riding in changing weather conditions, including cold mornings, wind, rain, and varying road surfaces.",
      "Listed items to bring: Full water bottle or hydration pack, Sunglasses, Light jacket or extra layer (weather and elevation can change quickly) Rain Gear is in each Rental Bike, Snacks (energy bars, trail snacks, etc.), and Camera or phone for photos.",
      "The stored price-preview response did not include a bookable price for this item. No from-price is shown."
    ],
    "highlights": [
      "Premium adventure motorcycle rental (Kawasaki KLR 650 / 650S or Yamaha Ténéré 700)",
      "Complimentary delivery and pickup within the greater Cody, WY area",
      "Most riding gear included (helmet, jacket, gloves) - limited sizes and quantities available",
      "Riding or hiking boots (ankle-covering footwear required; no street shoes or sneakers)",
      "Pre-ride inspection and setup",
      "Local area orientation and riding recommendations"
    ],
    "durationLabel": "1 day",
    "durationIso": "P1D",
    "visiblePriceLabel": null,
    "offer": null,
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "646999",
    "company": "solitudefloattrips",
    "title": "Grand Teton Scenic Float - Private Tour",
    "publicPath": "/destinations/wyoming/moose/tours/grand-teton-scenic-float---private-tour-646999",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Grand Teton Scenic Float - Private Tour is booked with Solitude Float Trips. The operator lists the duration as 2.5 hours. The listed meeting address is 1 Teton Park Road, Moose, WY 83012.",
      "The operator lists minimum age 5, maximum age 99.",
      "Included items listed by the operator: central meeting point, transportation to river put-in, life jacket for each person (USCG certified), professional guide, and small group tour: 12 guests per boat, maximum.",
      "Items listed as not included: layered clothing (for warmth), refillable water bottle, soft-soled shoes, sunglasses / hat, sunscreen, and personal items (lip balm, medications like epi, inhaler, etc.).",
      "Listed restrictions: This will ensure that they are properly fitted for a personal flotation device (PFD or life jacket), While a scenic float is not necessarily an athletic activity per se, some agility and mobility is required, Please note there is no cover on the raft for shade or solid back support, and The landing area changes depending on the time of year, with there being little room to maneuver when the water is high (typically May - July).",
      "The stored price preview lists Private Raft (Select the number of rafts) at $1,200 USD on the stored departure starting 2027-05-15T09:30:00. Listed at $0 on that departure: Adult, Child."
    ],
    "highlights": [
      "central meeting point",
      "transportation to river put-in",
      "life jacket for each person (USCG certified)",
      "professional guide",
      "small group tour: 12 guests per boat, maximum"
    ],
    "durationLabel": "2.5 hours",
    "durationIso": "PT2H30M",
    "visiblePriceLabel": "Prices starting at $1,200",
    "offer": {
      "type": "Offer",
      "price": "1200.00",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "612500",
    "company": "hotelebikerentals",
    "title": "(Guided) 4-Hr E-Bike Tour of Vancouver Seawall - JW Marriott",
    "publicPath": "/destinations/british-columbia/vancouver/tours/guided-4-hr-e-bike-tour-of-vancouver-seawall---jw-marriott-612500",
    "engine2Path": "/destinations/world/canada/british-columbia/vancouver/tours/guided-4-hr-e-bike-tour-of-vancouver-seawall---jw-marriott-612500",
    "exceptionStatus": "SOURCE_NOT_FOUND",
    "paragraphs": [
      "Authoritative FareHarbor content and price data were not available for (Guided) 4-Hr E-Bike Tour of Vancouver Seawall - JW Marriott. The stored harvest returned content HTTP 403, structured-description HTTP 404, item HTTP 404, and price-preview HTTP 400. This page does not state a price, review count, duration, meeting point, or inclusions."
    ],
    "highlights": [],
    "durationLabel": null,
    "durationIso": null,
    "visiblePriceLabel": null,
    "offer": null,
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "34849",
    "company": "red-jeep",
    "title": "Shared San Andreas Fault Jeep Tour",
    "publicPath": "/destinations/california/palm-springs/tours/shared-san-andreas-fault-jeep-tour-34849",
    "engine2Path": "/destinations/california/palm-springs/tours/shared-san-andreas-fault-jeep-tour-34849",
    "exceptionStatus": "OK",
    "paragraphs": [
      "Shared San Andreas Fault Jeep Tour is booked with Desert Adventures Red Jeep Tours. The operator lists the duration as 3 hours. The listed meeting address is Metate Ranch - 38635 Monroe St, Indio, CA 92203.",
      "The operator lists minimum age 5, group size Minimum 2 / Maximum 7 guests per Jeep (Single riders, please call to book).",
      "Cancellation terms listed by the operator: Cancel up to 48 hours before departure without penalty. No refund or credit for cancellation within 48 hours.",
      "Additional facts stated by the operator: Jeep Scrambler (CJ-8), up to 7 guests per Jeep, admission fees and taxes included, bottled water, granola snacks, and one mile deep into the heart of the San Andreas Fault zone.",
      "The stored price preview lists Adult (18 years and up) (Aged 18 and up) at $183.75 USD on the stored departure starting 2026-09-30T08:00:00. Other listed prices: Child (Aged 17 and under) at $149.62."
    ],
    "highlights": [],
    "durationLabel": "3 hours",
    "durationIso": "PT3H",
    "visiblePriceLabel": "Prices starting at $183.75",
    "offer": {
      "type": "Offer",
      "price": "183.75",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "333279",
    "company": "epicpaddleadventures",
    "title": "Date Night Neon Glow Clear Kayak or Paddleboard & Champagne Orlando",
    "publicPath": "/destinations/florida/orlando/tours/date-night-neon-glow-clear-kayak-or-paddleboard-and-champagne-orlando-333279",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Date Night Neon Glow Clear Kayak or Paddleboard & Champagne Orlando is booked with Epic Paddle Adventures. The operator lists the duration as 2 hour experience. The listed meeting address is 1600 North Orange Avenue Orlando, FL US 32804.",
      "The operator lists group size 40.",
      "Included items listed by the operator: Clear kayak or paddleboard (selected at booking), Neon under-glow lighting setup, Complimentary champagne (21+), USCG-approved life vests, Paddle and safety equipment, Guided experience, and Complimentary photos provided after the tour.",
      "Items listed as not included: Additional food or beverages.",
      "Listed itinerary: Sunset Launch - Enter the water as evening light fades, Neon Glow Paddle - Relaxed guided paddle with champagne and photo moments, and Return to Shore - Easy paddle back under the city lights.",
      "Listed items to bring: Athletic wear, shorts, or light layers, Closed-toe water shoes or sandals with straps, A valid ID (21+ for champagne), and Phone or camera (dry storage recommended).",
      "Cancellation terms listed by the operator: Refund or credit available with 24 hour notice.",
      "The stored price preview lists Adult Paddle Board (15 years and over, Requires Valid Drivers License or Permit) at $80 USD on the stored departure starting 2026-09-29T20:00:00. Other listed prices: Clear 2-Person Kayak at $160; Clear Single Kayak at $80."
    ],
    "highlights": [
      "Clear kayak or paddleboard (selected at booking)",
      "Neon under-glow lighting setup",
      "Complimentary champagne (21+)",
      "USCG-approved life vests",
      "Paddle and safety equipment",
      "Guided experience"
    ],
    "durationLabel": "2 hour experience",
    "durationIso": "PT2H",
    "visiblePriceLabel": "Prices starting at $80",
    "offer": {
      "type": "Offer",
      "price": "80.00",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "193220",
    "company": "wineroutebaja",
    "title": "La Bufadora Tour in Baja California",
    "publicPath": "/destinations/california/ensenada/tours/la-bufadora-tour-in-baja-california-193220",
    "engine2Path": "/destinations/california/ensenada/tours/la-bufadora-tour-in-baja-california-193220",
    "exceptionStatus": "OK",
    "paragraphs": [
      "La Bufadora Tour in Baja California is booked with The Wine Route. The operator lists the duration as 4 hours. The listed meeting address is Miguel Aleman Ave | 512 Colonia Ampliacion Moderna Ensenada, Ensenada Municipality MX 22879.",
      "The operator lists maximum age 99, group size 50.",
      "Included items listed by the operator: Hotel pickup and drop-off, Transport, Local expert English/Spanish guide, Bottled water, and Snacks.",
      "Items listed as not included: Food and drinks, and Gratuities.",
      "Listed itinerary: Midmorning pickup in Ensenada and scenic 24-mile (39 km) drive to Punta Banda peninsula, Observe La Bufadora as waves force water up through the sea cave every 1-2 minutes, Free time to browse the sidewalk crafts market and visit nearby restaurants (own expense), and Meet the guide at 1:00 pm to return to hotels by 2:00 pm.",
      "Listed restrictions: Minimum drinking age is 18 years, Children must be accompanied by an adult, and Tour recommended for all ages.",
      "Listed items to bring: Cash (U.S. dollars widely accepted; few ATMs available), Hat or cap, Comfortable walking shoes, Sunscreen in summer, and Sunglasses.",
      "Additional facts stated by the operator: Bottled water.",
      "The stored price preview lists Adult (Ages 5+) at $40 USD on the stored departure starting 2026-10-01T10:00:00. Other listed prices: Private Tour at $55. Listed at $0 on that departure: Infant."
    ],
    "highlights": [
      "Hotel pickup and drop-off",
      "Transport",
      "Local expert English/Spanish guide",
      "Bottled water",
      "Snacks"
    ],
    "durationLabel": "4 hours",
    "durationIso": "PT4H",
    "visiblePriceLabel": "Prices starting at $40",
    "offer": {
      "type": "Offer",
      "price": "40.00",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock"
    },
    "aggregateRating": null,
    "ratingProvenance": "No numeric rating or review count is present in the stored FareHarbor content, structured-description, item, or price-preview payloads. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
