// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborCoronadoLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "454816",
    "company": "jobsurfexperience-sd",
    "title": "Private Surf Lesson",
    "publicPath": "/destinations/california/coronado/tours/private-surf-lesson-454816",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. Ocean safety is covered before anyone takes a board into the water. Choosing which wave to catch is part of the same instruction.",
      "A wetsuit and a surfboard are provided for the time in the water. A rash guard, fins, a leash, and reef shoes are also set out with the gear. A private booking keeps one instructor with one guest. The lesson is aimed at first-time and beginner surfers.",
      "People are in the water on surfboards rather than walking a neighborhood route. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "A 1.5-hour guided outing with Jamie O'Brien Surf Experience - San Diego in Coronado.",
    "highlights": [
      "1.5-hour guided outing in Coronado",
      "Wetsuit"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/QAfxoxEdS5GzAkWnDKFr"
    ],
    "wordCount": 131,
    "durationLabel": "1.5 Hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "“The Views” courtyard on the southern end of the Hotel Del Coronado at our surf trailer - 1500 Orange Ave, Coronado, CA, 92118",
    "visiblePriceLabel": "From $295.74",
    "priceRows": [
      {
        "label": "Person",
        "note": "",
        "amountLabel": "$316.94"
      },
      {
        "label": "Children",
        "note": "",
        "amountLabel": "$295.74"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "295.74",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/jobsurfexperience-sd/items/454816/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "454824",
    "company": "jobsurfexperience-sd",
    "title": "Ohana Surf Lesson",
    "publicPath": "/destinations/california/coronado/tours/ohana-surf-lesson-454824",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. Ocean safety is covered before anyone takes a board into the water. Choosing which wave to catch is part of the same instruction.",
      "A wetsuit and a surfboard are provided for the time in the water. A rash guard, fins, a leash, and reef shoes are also set out with the gear. Instructors stay with the group at about 4 guests per instructor. The booking is private, so the instructor works with that party alone.",
      "Family or friends share the lesson and take the same waves together. People are in the water on surfboards rather than walking a neighborhood route. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "A 1.5-hour guided outing with Jamie O'Brien Surf Experience - San Diego in Coronado.",
    "highlights": [
      "1.5-hour guided outing in Coronado",
      "Wetsuit"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/1p8VFaKrQJes66ImcxqI"
    ],
    "wordCount": 147,
    "durationLabel": "1.5 Hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "“The Views” courtyard on the southern end of the Hotel Del Coronado at our surf trailer - 1500 Orange Ave, Coronado, CA, 92118",
    "visiblePriceLabel": "From $189.74",
    "priceRows": [
      {
        "label": "Person",
        "note": "Minimum of 2 people per booking • All Ages • Ages 10 and under will be charged an additional $100 for personal instructor",
        "amountLabel": "$189.74"
      },
      {
        "label": "Children",
        "note": "Ages 10 and under will be with a personal instructor.",
        "amountLabel": "$295.74"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "189.74",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/jobsurfexperience-sd/items/454824/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "454829",
    "company": "jobsurfexperience-sd",
    "title": "Group Surf Lesson",
    "publicPath": "/destinations/california/coronado/tours/group-surf-lesson-454829",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. A wetsuit and a surfboard are provided for the time in the water.",
      "A rash guard, fins, a leash, and reef shoes are also set out with the gear. Instructors stay with the group at about 4 guests per instructor. Family or friends share the lesson and take the same waves together. The lesson takes groups of up to 16 guests.",
      "People are in the water on surfboards rather than walking a neighborhood route. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "A 1.5-hour guided outing with Jamie O'Brien Surf Experience - San Diego in Coronado.",
    "highlights": [
      "1.5-hour guided outing in Coronado",
      "Groups are capped at 16"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/SF4LKtBJSd27B19BFWAe"
    ],
    "wordCount": 121,
    "durationLabel": "1.5 Hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "1500 Orange Ave Coronado, CA 92118",
    "visiblePriceLabel": "From $157.94",
    "priceRows": [
      {
        "label": "Person",
        "note": "",
        "amountLabel": "$157.94"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "157.94",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/jobsurfexperience-sd/items/454829/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "644836",
    "company": "jobsurfexperience-sd",
    "title": "Group Coronado Island E-Bike Tour",
    "publicPath": "/destinations/california/coronado/tours/group-coronado-island-e-bike-tour-644836",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests set out on a modern adventure with the exclusive guided e-bike outing of Coronado Island, departing daily. After that, coronado Bike and Surf is only tour operator conveniently located at the Hotel del Coronado, offering guests a and exhilarating way to explore. The cutting-edge electric bikes amplify the pedaling power, allowing guests to effortlessly cover more ground, guests discover hidden coves, and soak in coastal views.",
      "That fun and dynamic ride is for anyone looking to meet Coronado's rich history, architecture, and community in an exciting new way. Fun for Everyone: An exciting and accessible e-bike adventure suitable for a wide range of ages and fitness levels."
    ],
    "schemaDescription": "A 1.5-hour bicycle outing with Jamie O'Brien Surf Experience - San Diego in Coronado. The outing passes Coronado Island.",
    "highlights": [
      "1.5-hour bicycle outing in Coronado",
      "Coronado Island",
      "Premium electric bicycle rental"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/Ql0ffiTOQlOy0GNLK5kN"
    ],
    "wordCount": 111,
    "durationLabel": "1.5 Hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "1500 Orange Ave Coronado, CA 92118",
    "visiblePriceLabel": "From $126.14",
    "priceRows": [
      {
        "label": "Person",
        "note": "",
        "amountLabel": "$126.14"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "126.14",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/jobsurfexperience-sd/items/644836/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "648512",
    "company": "jobsurfexperience-sd",
    "title": "Del Club Members Daily Group Surf Lesson",
    "publicPath": "/destinations/california/coronado/tours/del-club-members-daily-group-surf-lesson-648512",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests start on the sand with a lesson in paddling, stance, and how to stand up on the board. After that land lesson, the group goes into the ocean to catch waves. A wetsuit and a surfboard are provided for the time in the water.",
      "A rash guard, fins, a leash, and reef shoes are also set out with the gear. The lesson itself is given in English. Instructors stay with the group at about 4 guests per instructor. The lesson is aimed at first-time and beginner surfers. The operator aims to have beginners standing on the board within about 30 minutes.",
      "People are in the water on surfboards rather than walking a neighborhood route. The instructor stays in the surf with the group for the length of the lesson."
    ],
    "schemaDescription": "A 1.5-hour guided outing with Jamie O'Brien Surf Experience - San Diego in Coronado.",
    "highlights": [
      "1.5-hour guided outing in Coronado",
      "Wetsuit"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/PD17XlwrRTOcffMzq1Os"
    ],
    "wordCount": 131,
    "durationLabel": "1.5 Hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "Del Beach Club 1500 Orange Avenue Coronado, CA 92118",
    "visiblePriceLabel": "From $132.50",
    "priceRows": [
      {
        "label": "Person",
        "note": "",
        "amountLabel": "$132.50"
      },
      {
        "label": "Children",
        "note": "",
        "amountLabel": "$238.50"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "132.50",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/jobsurfexperience-sd/items/648512/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "654219",
    "company": "jobsurfexperience-sd",
    "title": "Private Coronado Island E-Bike Tour",
    "publicPath": "/destinations/california/coronado/tours/private-coronado-island-e-bike-tour-654219",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests set out on a personalized modern adventure with the exclusive guided private e-bike outing of Coronado Island. Coronado Bike and Surf is only tour operator conveniently located directly at Hotel del Coronado, offering guests a and exhilarating way to find the island at the own pace.",
      "The cutting-edge electric bikes amplify the pedaling power, allowing the group to effortlessly cover more ground, guests discover hidden coves, and soak in coastal views. That fun and dynamic private ride is for anyone looking to meet Coronado's rich history, architecture, and community in an exciting new way, designed for guests.",
      "Guided private e-bike outing of Coronado Island."
    ],
    "schemaDescription": "A 1.5-hour bicycle outing with Jamie O'Brien Surf Experience - San Diego in Coronado. The outing passes Coronado Island.",
    "highlights": [
      "1.5-hour bicycle outing in Coronado",
      "Coronado Island",
      "Helmet (mandatory for all riders)"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/FngF3uI1SpaUjYpw2NpA"
    ],
    "wordCount": 108,
    "durationLabel": "1.5 Hours",
    "durationIso": "PT1H30M",
    "meetingLocation": "1500 Orange Ave Coronado, CA 92118",
    "visiblePriceLabel": "From $179.14",
    "priceRows": [
      {
        "label": "Person",
        "note": "",
        "amountLabel": "$179.14"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "179.14",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/jobsurfexperience-sd/items/654219/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
