// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborNaplesLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "44245",
    "company": "floridaadventuresandrentals",
    "title": "Rookery Bay Kayak Tours",
    "publicPath": "/destinations/florida/naples/tours/rookery-bay-kayak-tours-44245",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a two-hour kayak tour in the Rookery Bay Estuarine Research Reserve.",
      "Groups are capped at 10.",
      "Guests must be at least 4 years old. A full refund is available with at least 48 hours' notice."
    ],
    "schemaDescription": "Two-hour kayak tour in Rookery Bay with Florida Adventures and Rentals, for groups of up to 10.",
    "highlights": [
      "two-hour paddle outing in Naples",
      "Rookery Bay Estuarine Research Reserve",
      "Groups are capped at 10"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/P7hY6A7Q96dHVAKHbWR5"
    ],
    "productImage": "https://cdn.filestackcontent.com/1gcLiu63TkigI9M3sf1F",
    "wordCount": 38,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": "Capri Paddlecraft Park, 1295 Capri Blvd, Naples, FL 34113",
    "visiblePriceLabel": "From $65",
    "priceRows": [
      {
        "label": "Kid",
        "note": "Ages 10 & Under",
        "amountLabel": "$45"
      },
      {
        "label": "Adult",
        "note": "Ages 11+",
        "amountLabel": "$65"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "65.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1525,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1525 reviews on GET https://fareharbor.com/api/v1/companies/floridaadventuresandrentals/items/44245/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "464256",
    "company": "marcoecotours",
    "title": "Deluxe Pedal Kayak Tour | Marco Island and Naples, Florida",
    "publicPath": "/destinations/florida/naples/tours/deluxe-pedal-kayak-tour-marco-island-and-naples-florida-464256",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a two-hour paddle outing with La vita é bella - Marco Eco Tours. The group passes Marco Island. The group stays on the water in Naples."
    ],
    "schemaDescription": "Two-hour pedal-kayak tour with Marco Eco Tours, passing Marco Island.",
    "highlights": [
      "two-hour paddle outing in Naples",
      "Marco Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/zxpP1xVrTmZdTJlTw4QF"
    ],
    "productImage": "https://cdn.filestackcontent.com/WpeZkDZZRiC8Bg4kDZzJ",
    "wordCount": 27,
    "durationLabel": "2 Hours",
    "durationIso": "PT2H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $74.99",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 16+",
        "amountLabel": "$74.99"
      },
      {
        "label": "Child",
        "note": "Ages 5 - 15",
        "amountLabel": "$74.99"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "74.99",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 5,
      "reviewCount": 1142,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 5 from 1142 reviews on GET https://fareharbor.com/api/v1/companies/marcoecotours/items/464256/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  },
  {
    "itemId": "416773",
    "company": "threebrothersboards",
    "title": "Dolphin and Manatee Adventure Tour of Naples with Olde Florida History",
    "publicPath": "/destinations/florida/naples/tours/dolphin-and-manatee-adventure-tour-of-naples-with-olde-florida-history-416773",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests paddle on the water for the whole outing. Time on the water is about 2 hours. A guide stays with the group and chooses the water from recent sightings. The watch includes dolphins, manatees, sea turtles, and conchs. Birds along the same water include bald eagles, pelicans, and osprey.",
      "The West Indian manatee is the animal this water is known for. The water around the city is the setting, picked for the animals that live there. The group moves at an easy pace, with time to watch rather than cover a set distance. Sea life and birds are both part of what the guide is looking for.",
      "Manatees, when they are present, are why many guests book this water. Which animals appear depends on the day, and a sighting is not promised."
    ],
    "schemaDescription": "Two-hour guided paddle in Naples watching for dolphins, manatees, sea turtles, and coastal birds. A sighting is not promised.",
    "highlights": [
      "two-hour walking tour in Naples"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/RH6VUmgQJ6BCLay3Eewz"
    ],
    "productImage": "https://cdn.filestackcontent.com/hNSHADkGRdGafqN6pELJ",
    "wordCount": 133,
    "durationLabel": "2 hours",
    "durationIso": "PT2H",
    "meetingLocation": null,
    "visiblePriceLabel": "From $65",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 9+",
        "amountLabel": "$65"
      },
      {
        "label": "Child",
        "note": "Under 9 years old",
        "amountLabel": "$55"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "65.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": {
      "ratingValue": 4.8,
      "reviewCount": 343,
      "provider": "Google"
    },
    "ratingProvenance": "Google rating 4.8 from 343 reviews on GET https://fareharbor.com/api/v1/companies/threebrothersboards/items/416773/ratings/ fields ratings.google_reviews.rating and ratings.google_reviews.user_ratings_total. TripAdvisor was absent, so this pair stays attributed to Google. rating_image_url was not used. Catalog quality_score and availability_count were not used."
  }
];
