// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborStockIslandLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "532140",
    "company": "sixfinscharter",
    "title": "Private Custom Activities Combo Charter",
    "publicPath": "/destinations/florida/stock-island/tours/private-custom-activities-combo-charter-532140",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Combine sandbars, snorkeling, dolphin viewing, sightseeing, evening light, and other activities in one private day. The outing does not provide preparation, fishing time, effort, or focus of dedicated fishing charter. If guests want a true Key West fishing meet, reserve the Private Patch Reef Fishing charter.",
      "The USCG-licensed captain builds the route around the priorities and current conditions aboard 30' Jeanneau yacht. Meet at The Perry Hotel & Marina, Dock A, Slip 32; brief safety overview and flexible departure time. Dolphin search and scenic harbor cruise with local commentary. Snorkeling over reefs or backcountry patch reefs; snorkel gear provided.",
      "Fishing gear for casual, family-friendly fishing (request in advance; conditions permitting)."
    ],
    "schemaDescription": "A 10-hour snorkel outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "10-hour snorkel outing in Stock Island",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/OfeqdTQAShyXRHgu1eXI"
    ],
    "productImage": "https://cdn.filestackcontent.com/dVPju7rSo279Z1WyNqlC",
    "wordCount": 111,
    "durationLabel": "10 hours",
    "durationIso": "PT10H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $1,395",
    "priceRows": [
      {
        "label": "6 Hour Private Charter",
        "note": "",
        "amountLabel": "$1,395"
      },
      {
        "label": "8 Hour Private Charter",
        "note": "",
        "amountLabel": "$1,795"
      },
      {
        "label": "10 Hour Private Charter",
        "note": "",
        "amountLabel": "$2,195"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1395.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/532140/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "532157",
    "company": "sixfinscharter",
    "title": "Private Romantic Sunset Cruise",
    "publicPath": "/destinations/florida/stock-island/tours/private-romantic-sunset-cruise-532157",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "A few optional stops leave time to step out for photographs and a closer look. Music plays on board, and some departures add a live set. Bean bags on the bow are there for sitting out in the air. From the water, guests see Key West and Marina Scenic Harbor.",
      "The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint. People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A three-hour harbor outing with Six Fins Charter on Stock Island Harbor. The sail passes Mallory Square Harbor, Tank Island, and Wisteria Island.",
    "highlights": [
      "three-hour harbor outing in Stock Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/XqwQ1QzQQqeMi1AGxnjl"
    ],
    "productImage": "https://cdn.filestackcontent.com/dUz5aAyR9CR0PeWgW3Jj",
    "wordCount": 103,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $995",
    "priceRows": [
      {
        "label": "Private Charter",
        "note": "Up to 8 People.",
        "amountLabel": "$995"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "995.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/532157/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "532224",
    "company": "sixfinscharter",
    "title": "Private Snorkel Adventure",
    "publicPath": "/destinations/florida/stock-island/tours/private-snorkel-adventure-532224",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests snorkel from the boat over a patch reef. The reef is several miles offshore from Key West. Sergeant majors and parrotfish are the fish this reef is known for. A southern stingray is possible, though not on every trip. Masks, fins, and snorkels are on the boat.",
      "There is no fixed reef on a printed schedule. The stop is over coral, with tropical fish in the same water. On the way out, the boat watches for dolphins, sea birds, and flying fish. The charter runs about 4 hours. Fuel and the safety gear are included.",
      "Atlantic patch reefs are the water this charter is booked for. The boat is private for the group that booked it. Floats are aboard for the break between time in the water. Gear is set for as many as six guests."
    ],
    "schemaDescription": "A four-hour snorkel outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "four-hour snorkel outing in Stock Island",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/UifQzOXyQ8q4MWmormiA"
    ],
    "productImage": "https://cdn.filestackcontent.com/nZOAr70bR8yPM5lbbwiq",
    "wordCount": 137,
    "durationLabel": "4 Hours",
    "durationIso": "PT4H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $1,195",
    "priceRows": [
      {
        "label": "Private Charter",
        "note": "Up to 8 People.",
        "amountLabel": "$1,195"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1195.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/532224/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "532226",
    "company": "sixfinscharter",
    "title": "Private Secret Local Sandbars Escape",
    "publicPath": "/destinations/florida/stock-island/tours/private-secret-local-sandbars-escape-532226",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a four-hour guided outing with Six Fins Charter in Stock Island. The outing includes a stand-up paddle session.",
      "Groups are capped at 8.",
      "Guests must be at least 1 year old. A full refund is available with at least 24 hours' notice."
    ],
    "schemaDescription": "A four-hour guided outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "four-hour guided outing in Stock Island",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/1c1QPJFSniXIJFrelZa9"
    ],
    "productImage": "https://cdn.filestackcontent.com/lfTU36coSeCs6VvlYDkg",
    "wordCount": 46,
    "durationLabel": "4 Hours",
    "durationIso": "PT4H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $1,195",
    "priceRows": [
      {
        "label": "Private Charter",
        "note": "Up to 8 People.",
        "amountLabel": "$1,195"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1195.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/532226/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "532228",
    "company": "sixfinscharter",
    "title": "Private National Wildlife Refuge Eco Tour",
    "publicPath": "/destinations/florida/stock-island/tours/private-national-wildlife-refuge-eco-tour-532228",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This private charter looks for wild dolphins in the backcountry channels. The charter runs about 3 hours. The boat is private for the group that booked it. Whether a pod is close that day is not promised. This is a private sandbar charter on the water.",
      "The booking is about 3 hours. The stop is a Key West sandbar, away from a crowd of other boats. A Coast Guard licensed captain runs the boat. Fuel and the safety gear are included. From the water, guests see Great White Heron and Lower Keys."
    ],
    "schemaDescription": "A three-hour guided outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "three-hour guided outing in Stock Island",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/0Di2BwgDTfSsWuwW6ruB"
    ],
    "productImage": "https://cdn.filestackcontent.com/zhsgTdGSLqqeEFI08wIQ",
    "wordCount": 92,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $995",
    "priceRows": [
      {
        "label": "Private Charter",
        "note": "Up to 8 People.",
        "amountLabel": "$995"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "995.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/532228/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "532233",
    "company": "sixfinscharter",
    "title": "Private Dolphin Playground Safari",
    "publicPath": "/destinations/florida/stock-island/tours/private-dolphin-playground-safari-532233",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Private Dolphin Playground Safari is a three-hour guided outing with Six Fins Charter in Stock Island.",
      "Groups are capped at 8.",
      "Guests must be at least 1 year old. A full refund is available with at least 24 hours' notice."
    ],
    "schemaDescription": "A three-hour guided outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "three-hour guided outing in Stock Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/kIAz9SGbQsalnlGlNbd7"
    ],
    "productImage": "https://cdn.filestackcontent.com/6auNpiXIQrCxnQM9DV1R",
    "wordCount": 41,
    "durationLabel": "3 Hours",
    "durationIso": "PT3H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $995",
    "priceRows": [
      {
        "label": "Private Charter",
        "note": "Up to 8 People.",
        "amountLabel": "$995"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "995.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/532233/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "541394",
    "company": "sixfinscharter",
    "title": "Private Patch Reef Fishing",
    "publicPath": "/destinations/florida/stock-island/tours/private-patch-reef-fishing-541394",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "From the water, guests see Lower Keys and Key West. The landmarks are seen from the harbor, with the boat doing the traveling. The boat is how guests move, and the harbor is the viewpoint.",
      "People stay aboard, watching the shore go by. The course is on the water for the whole outing, and the shore is what guests are there to see."
    ],
    "schemaDescription": "A four-hour guided outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "four-hour guided outing in Stock Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/u5m14eZHT5ivjVeNnQnM"
    ],
    "productImage": "https://cdn.filestackcontent.com/trC4enRduUsMUKHLjJrA",
    "wordCount": 63,
    "durationLabel": "4 hours",
    "durationIso": "PT4H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $1,395",
    "priceRows": [
      {
        "label": "Half-Day Charter",
        "note": "4 hours | Max of 6 Passenger",
        "amountLabel": "$1,395"
      },
      {
        "label": "3/4 - Day Charter",
        "note": "6 hours | Max of 6 Passenger",
        "amountLabel": "$1,595"
      },
      {
        "label": "Full-Day Charter",
        "note": "8 hours | Max of 6 Passenger",
        "amountLabel": "$1,795"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1395.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/541394/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "550475",
    "company": "sixfinscharter",
    "title": "Discover the Marquesas Keys",
    "publicPath": "/destinations/florida/stock-island/tours/discover-the-marquesas-keys-550475",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This private charter looks for wild dolphins in the backcountry channels. The charter runs about 10 hours. The boat is private for the group that booked it. Whether a pod is close that day is not promised. This is a private sandbar charter on the water.",
      "The booking is about 10 hours. The stop is a Key West sandbar, away from a crowd of other boats. A Coast Guard licensed captain runs the boat. Fuel and the safety gear are included. From the water, guests see Key West."
    ],
    "schemaDescription": "A 10-hour snorkel outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "10-hour snorkel outing in Stock Island",
      "Groups are capped at 8"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/ngEhdLRR5Ow4w367Z1D7"
    ],
    "productImage": "https://cdn.filestackcontent.com/gzyl1XbhRBivoYpb9Dzd",
    "wordCount": 88,
    "durationLabel": "10 hour",
    "durationIso": "PT10H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $2,605",
    "priceRows": [
      {
        "label": "8 Hour Private Charter",
        "note": "",
        "amountLabel": "$2,605"
      },
      {
        "label": "10 Hour Private Charter",
        "note": "",
        "amountLabel": "$3,065"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "2605.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/550475/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  },
  {
    "itemId": "563185",
    "company": "sixfinscharter",
    "title": "Private Clothing optional Charter",
    "publicPath": "/destinations/florida/stock-island/tours/private-clothing-optional-charter-563185",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "This is a private sandbar charter on the water. The booking is about 10 hours. The stop is a Key West sandbar, away from a crowd of other boats. A Coast Guard licensed captain runs the boat. Fuel and the safety gear are included. Bean bags on the bow are there for sitting out in the air.",
      "Time on the water is about 10 hours. From the water, guests see Key West Harbor. The landmarks are seen from the harbor, with the boat doing the traveling."
    ],
    "schemaDescription": "A 6-hour snorkel outing with Six Fins Charter in Stock Island.",
    "highlights": [
      "6-hour harbor outing in Stock Island"
    ],
    "galleryImages": [
      "https://cdn.filestackcontent.com/tE52xOOZQQqrCfOhij4U"
    ],
    "productImage": "https://cdn.filestackcontent.com/C7jKlgoLRJ2nwI3Hrctb",
    "wordCount": 86,
    "durationLabel": "6 Hour",
    "durationIso": "PT6H",
    "meetingLocation": "7001 Shrimp Rd Dock A Slip 32 Stock Island, FL 33040",
    "visiblePriceLabel": "From $1,295",
    "priceRows": [
      {
        "label": "6 Hour Private Charter",
        "note": "",
        "amountLabel": "$1,295"
      },
      {
        "label": "8 Hour Private Charter",
        "note": "",
        "amountLabel": "$1,445"
      },
      {
        "label": "10 Hour Private Charter",
        "note": "",
        "amountLabel": "$1,670"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "1295.00",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/sixfinscharter/items/563185/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
