// Generated by scripts/fareharbor-lead-to-gold/build_boston_legacy.py
// Stored FareHarbor harvest only. Do not edit by hand.
import type { FareHarborProofProduct } from "./fareharborLeadToGoldProof.generated";

export const fareHarborHealdsburgLegacyProducts: FareHarborProofProduct[] = [
  {
    "itemId": "29264",
    "company": "getawayadventures",
    "title": "Healdsburg Sip 'N Cycle",
    "publicPath": "/destinations/california/healdsburg/tours/healdsburg-sip-n-cycle-29264",
    "engine2Path": null,
    "exceptionStatus": "OK",
    "paragraphs": [
      "Guests ride bikes from one winery to the next. A bike and a helmet are set out when the group checks in. Lunch can be a picnic at a winery or a meal at a restaurant on the route. An electric-assist bike is offered as an upgrade for the ride.",
      "The bikes do the traveling, and the winery stops are where guests get off to taste. The ride passes Wine Country Bikes and Hudson St. Cyclists also come to Truett Hurst and Mill Creek. Guests cover the sights by bike, stopping where the guide has something to say.",
      "Among the places guests actually encounter are Wine Country Bikes, Hudson St, and Truett Hurst."
    ],
    "schemaDescription": "A guided outing with Getaway Adventures in Healdsburg.",
    "highlights": [],
    "galleryImages": [
      "https://cdn.filestackcontent.com/6QtlqGStTi683k9VDt9O"
    ],
    "productImage": "https://cdn.filestackcontent.com/CtHNMZJWQ7CYQmPbaoM5",
    "wordCount": 114,
    "durationLabel": null,
    "durationIso": null,
    "meetingLocation": "Dry Creek Wine Region: Healdsburg, CA",
    "visiblePriceLabel": "From $221.54",
    "priceRows": [
      {
        "label": "Adult",
        "note": "Ages 16 and up",
        "amountLabel": "$221.54"
      }
    ],
    "pricingNotes": [],
    "offer": {
      "type": "Offer",
      "price": "221.54",
      "priceCurrency": "USD"
    },
    "aggregateRating": null,
    "ratingProvenance": "The FareHarbor ratings endpoint https://fareharbor.com/api/v1/companies/getawayadventures/items/29264/ratings/ did not include a TripAdvisor rating and review count in ratings.tripadvisor.rating and ratings.tripadvisor.num_reviews. rating_image_url was not used. Google reviews were not substituted. Catalog quality_score and availability_count were not used. AggregateRating is omitted."
  }
];
